/* XPM */
/* This file is a part of the NsCDE - Not so Common Desktop Environment */
static char *Buckles_pm[] = {
/* columns rows colors chars-per-pixel */
"64 64 2 1 ",
".      s selectColor    m black c #949494949494",
"X      s bottomShadowColor        m black c #bdbdbdbdbdbd",
/* pixels */
"................................................................",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
"................................................................",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
"................................................................",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
"................................................................",
".X.X.X...................................................X.X.X.X",
"........................................................XX......",
".X.X.X.................................................XXX.X.X.X",
"......................................................XXXX......",
".X.X.X.....X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.XXXXX.X.X.X",
"......................................................XXXX......",
".X.X.X.....X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.XXXXX.X.X.X",
"......................................................XXXX......",
".X.X.X.....X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.XXXXX.X.X.X",
"......................................................XXXX......",
".X.X.X.....X.X.X...............................X.X.X.XXXXX.X.X.X",
"..............................................XX......XXXX......",
".X.X.X.....X.X.X.............................XXX.X.X.XXXXX.X.X.X",
"............................................XXXX......XXXX......",
".X.X.X.....X.X.X.....X.X.X.X.X.X.X.X.X.X.X.XXXXX.X.X.XXXXX.X.X.X",
"............................................XXXX......XXXX......",
".X.X.X.....X.X.X.....X.X.X.X.X.X.X.X.X.X.X.XXXXX.X.X.XXXXX.X.X.X",
"............................................XXXX......XXXX......",
".X.X.X.....X.X.X.....X.X.X.X.X.X.X.X.X.X.X.XXXXX.X.X.XXXXX.X.X.X",
"............................................XXXX......XXXX......",
".X.X.X.....X.X.X.....X.X.X...........X.X.X.XXXXX.X.X.XXXXX.X.X.X",
"....................................XX......XXXX......XXXX......",
".X.X.X.....X.X.X.....X.X.X.........XXX.X.X.XXXXX.X.X.XXXXX.X.X.X",
"..................................XXXX......XXXX......XXXX......",
".X.X.X.....X.X.X.....X.X.X.......XXXXX.X.X.XXXXX.X.X.XXXXX.X.X.X",
"................................XXXXXX......XXXX......XXXX......",
".X.X.X.....X.X.X.....X.X.X.....XXXXXXX.X.X.XXXXX.X.X.XXXXX.X.X.X",
"..............................XXXXXXXX......XXXX......XXXX......",
".X.X.X.....X.X.X.....X.X.X...XXXXXXXXX.X.X.XXXXX.X.X.XXXXX.X.X.X",
"............................XXXXXXXXXX......XXXX......XXXX......",
".X.X.X.....X.X.X.....X.X.X.XXXXXXXXXXX.X.X.XXXXX.X.X.XXXXX.X.X.X",
"............................................XXXX......XXXX......",
".X.X.X.....X.X.X.....X.X.X.X.X.X.X.X.X.X.X.XXXXX.X.X.XXXXX.X.X.X",
"............................................XXXX......XXXX......",
".X.X.X.....X.X.X.....X.X.X.X.X.X.X.X.X.X.X.XXXXX.X.X.XXXXX.X.X.X",
"............................................XXXX......XXXX......",
".X.X.X.....X.X.X.....X.X.X.X.X.X.X.X.X.X.X.XXXXX.X.X.XXXXX.X.X.X",
"....................XXXXXXXXXXXXXXXXXXXXXXXXXXXX......XXXX......",
".X.X.X.....X.X.X...XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.X.X.XXXXX.X.X.X",
"..................XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX......XXXX......",
".X.X.X.....X.X.X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.X.X.XXXXX.X.X.X",
"......................................................XXXX......",
".X.X.X.....X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.XXXXX.X.X.X",
"......................................................XXXX......",
".X.X.X.....X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.XXXXX.X.X.X",
"......................................................XXXX......",
".X.X.X.....X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.XXXXX.X.X.X",
"..........XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX......",
".X.X.X...XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.X.X.X",
"........XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX......",
".X.X.X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.X.X.X",
"................................................................",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
"................................................................",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
"................................................................",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X"
};
