/* XPM */
/* $XConsortium: Pebbles.pm /main/3 1995/07/18 17:19:35 drk $ */
/*********************************************************************
*  (c) Copyright 1992, 1993, 1994 Hewlett-Packard Company	
*  (c) Copyright 1993, 1994 International Business Machines Corp.
*  (c) Copyright 1993, 1994 Sun Microsystems, Inc.
*  (c) Copyright 1993, 1994 Unix System Labs, Inc., a subsidiary of
*      Novell, Inc.
**********************************************************************/
static char * Pebbles [] = {
/* width height ncolors cpp [x_hot y_hot] */
"162 95 12 1 0 0",
/* colors */
"     s iconGray7     m black c #424242424242",
".    s iconGray5     m black c #737373737373",
"X    s iconGray4     m white c #949494949494",
"o    s selectColor m white c #737373737373",
"O    s bottomShadowColor m black c #636363636363",
"+    s background    m black c #949494949494",
"@    s iconGray2     m white c #bdbdbdbdbdbd",
"#    s iconGray6     m black c #636363636363",
"$    s iconGray3     m white c #adadadadadad",
"%    s topShadowColor m white c #bdbdbdbdbdbd",
"&    s iconGray1     m white c #dededededede",
"*	s iconColor2	m white	c white",
/* pixels */
" .. XXX   oO+o@OO#++ #. +++.++O+$..XO#@$$$XO OO#Ooo X++  .O#. # #%++OO#% O#...##O$@ + .+ #.X$$X$$   ..XX.# OO#O++X+O .+  O X.O #..#X.  OOO.O###..#..#. O  OO#    .",
"   O o+#.XXOooO #...O. +#++++.X## ##++X%+X$@O#+++ O + #O # @X X ++.XX##.+ #.###  O@X+Oo# O#..X. O .O#...$.@$ . O +..O#++.$ X$X#O###.O# .O.X #.###X#O.#OO#@$$$XO . ",
"#  O#O#..+%@OO O@&X$#. ##++#O#X+OX+# XX@@XX@ +.+XO#    #.@O.+$ #+++#.. ..#### O#.$ ##O X%oX##O  .  .# ###++ O.O&.OXX  #+#$.#X#X#  #   .. ..   ..##. #. ++X%+X$@O.&",
"$O# OXX.#.XXXOOOOX& X$  ### O ++O  +  .X%@XX .+@# ++$+ #$#OO.# # .+X%+O. OX  #..#X$O .X+% +X #X+X%O@X OOO+%.O .#+O# #   #O  #.#.O  .XX@#OX# X.O.. X.    XX@@XX@ #$",
"+# XXX+X.X+#@X+X#O X.#O. o  .O #X@.O.#O#.o.+O+X% X+X++#O# #@*$O#. ...+O  X%* X.. O O X++%#o+++++X#.+$@O#.+X..X@+&+.#o@ .. X  ##O +.. $# #OO+++.$$@O## #  .X%@XX @@",
"X ##.X+#X+$X+%# .#$$X.X.O &.# O.@+X.#..@ +OX O + O++%%#  X@.@.@O#..#$++ ##$ XX$ #.O#$X#%+  O..+X#X+O. O .X.++@X@ # ###...OO# O O.X+X+XO..X%O # .$@.O# ..#O#.o.+O.$",
"#+#.X%++X.++.$#.# .+. .@O$+XOO+X X+.%%@%.$O #   .XOX+O$. @@ +X@O ..XXOO..O #XX ...O.XX+%XO## ##X++# .% .+.+O&.XX ###...$$.O . O O X.$#.  OX@*O  $$X.. .#..@ +OX #X",
" # O#o..XXX.Xo$ . X .X.O.%  O#O.X.X...@@O.$@*o+O.#+ .#O  ##*#&@  .X+X# .X.O  O O##.X+.++ +.+ + +.O.# ...O#O O.X#X+ ###.XX.O.O.XO## .O..#..O # .. ..# ..%%@%.$O #.#",
"  O  # +++ +#..###.#+ +# .X #oXO.##X##$. X$%%#.$O+XX@.#OO#..#@X .##X+ OO .#O ...OOX..++.+... O XXO. .o@O.O # O .+#O##.#.@.#.## . O    # #.oO.XO#.$&####..@@O.$@.#@",
" ..###.OO  OX+X###X.O.#XO++++# .O#o+X.XX#..X#o&%@ XX..X#  #$@XX  ++ #.#+  @OOOO#&.O.#+ O++.X #O. X O#X.X #.X#@OX.$ O #...XX#O .+X  ..X o#O .X$O.#.$.o..##$. X$%%O$",
"X###+X+##XX #. ###+XO@O X. O. .OXOXO...OO .%OO@+&O++%+..OO#.##.+##o..#.O+XO$$X$.@%.O   . X.O.O@$+O .oO#%###.#$..O.@ . ...@##O#. X  #$XX #.O .X#XXX#O##.X.XX#..X# X",
" . O#O*X  # #O  .X $$O.o@.#O  #.@@X% O#XX$   . . O#X.%#.+# O O@$O. ...#   X$X$&.$X.###XX& O. O&@ OX. X.OO#. O##X  $$O.###$#$O#X.O#OXX$###.$O$.#$XX#O $o...OO .%OOo",
".O.@O+O+X%%$%+  #O@.$@#O@@oO$&+$X.+@#O..$@XO.##.#+O#+.# #$X.OoOX.#XO o#XOO.X.&$X## XoOX$$X  X  #OOX+XX+XO #.O.@XXO#&.###.#XXOOO### $.XO O.@ .# X.O@@O.# O#XX$   O+",
"OX&X@O#+##o+++++# ..O $$O###OO. $+&.@#X$O@. o##  $@OOo  o#X$X.X+$X@@.  #X @X$&. XX.O.X..$O# %$%.OX+.+++. . O@%%+$X .O ##.X##X$@O.OO.###+@O.&O+XO.X# XO$#O..$@XO.. ",
"#.X$@ #+#X##+O..XX$$##..O### #$. .$@.# XX .+O #  X@+o+ . #X$.#O@$&X.X##O#O.XXOX.@@X.+.%.O #o$X.@.++ %+#.o O%%%+.$%#@.. # #.#$$ ##.##++++%.OX @$.X$@O#.X@#X$O@. o #",
"O.@XX @+++ +%OX$.$X@. .  ###  .#.&X@X.OO++. X ...@+##O #O .# +.OX&X O ##O# + %X+$@ X.+++O## X@@@ +++X+#O O%%%+$+X$+.@&.O..$X. OXOOXO +X%X%OX..X+..#.#X..# XX .+O#X",
" #$$. ++#+#% #@..$$$..##O###O.X. #%XO.&&O#.XO##$$O.XO## $.O .X@+#O.#XO ..O.XO.+ OO+.+++. o  . .X# ..$  # +.$XX+X$XOO@@...$$$$OO.@@O OO +++O +O.#O#... .X.OO++. X.X",
" oOoOX+++oX O XX.. $O%XO ##  .@X.X+OO $*# X$XO.X.. #.O #%@O#..$#..OX.    ..+#O.@$#O+#+o##o O#+#. ..+ ..+O.+#+#+o+++#.# #.$$$$. @X@.+ .O..   O@@.O.#X. .O.&&O#.XO#.",
"@O.. X.#.++ OO#  .O.  +OO  O.X%XX#$X.OOo #OX.X X+# .o#$$ %# ...#@$.#@X#X + +OO@@X@+ #+.O##  #  O O#   @.+O+.o+ O#+++O+ #.$..X +XX@X+X. @$O.O+@+OO OO.O O $ # X$XOO",
"OOo Oo+##oX$O.O+X$..#X X#O #+O#.X#O #@&. $X$XO.. .oX+ #XX . ## .X%.#$X $ +O @ .&.*O#++O  ##oOXX. oX# #.X++O+ # ++.%+O  .#..#X+$ oO &o XO@# #.O  .$X  X#.OOo #OX.O.",
"#$.+.O#++O@X+X %*.O +++#% XXXXOoX%XO$@@@ X#.X#X.## OXXOO.  ##X....@+X#.O++o.+@OO.. O# XO.#  #o##+X+.XO#X#%.  O+++X+ ##.O# $+o+X%OO.$XXX#. ##.XO.XXX@# .Xo+$$O oOX@",
"%X%+XXOOOXX@#O@@@ .#O+++++OO+ #+@@+$X@&@@.OOXX@ #OoX+o+#X.O#.X...+$+ +# .o #@XOX&@&XXXO ## oXO .XXX.+ X&.@@ ##O#X%+O.X   .@X$#XX@#@X.#.. #...X #.XX..#@@OO#.@ ..#X",
"X@X%%# .#.XO+#$@+...XO +X .+ o.X$ X$X@@$@@OO+@%OX##O#X##@@X.X.X.#XXO.@.X#X ooO@$@X$@. $ # #o  OX@XX$. .X#@@XO.#  #  O# O#X $.*O  .+ #$$$#+#+#$OO.X$X X$+%##O## .XO",
"Oo+X%O$X#+.O  OO  X..$O  XX#@#+X%X#$@$@&&OO#.Xo+O.O&O . .X@o X.#X+ O#&##. OoO.$.&$@&* .$O  O.+ #.X#X$.O.X&@X  #+O.O. . XO$#X @+++O#X$ $....X @ XO..#X.+X+ ..@@@.@.",
"#OO+X .##X+#+X # ##...Xo.@ X#$  X+O.X@@&oOO&$oX+#X $.%XXX#O&@OXXX#Xo.XO.#.+ OX$@*X$$& ..#.O+ X #OXX @OO .$@# O#O.#.  .OXX#@$$.XO O$$.X$OOX#.@.OX@#. +.+.X# @&XX@.@",
"# .  O$ %O.@$+X@ oO#..#++.+.*X@XO @ .XOOO##@@#+.o$#+O#X+%+X@ XOoO # .O O#.##o.##  ##+..+%+#.+O O$$X.OO#      ..O#@###+. OOX$.@ $ .XX.$.#+ .o# #.#  X$+.+. o.@X$X@+",
"&#$#O.$#++O#O#.@XO.O##+$o..+@+%X XO. . #..OX # +.XOX OoOO$+$###.#.##.#.OOOO@#+@ . X@+XX.%X +#oOX.X$@&O ##  +   #O++.   ##.#.#   O#OX.#+& . .o#X + X +.+XX O..$X++@",
"XO@  X$X# .$  #&XoO OX++#OX+#@@.@O###O@$O +  X.+@+++O O #X O$  ##.#.++##..XO o  .X%.XXO o  ##+O.XX+@XO#  # OOO. OOXX .@  O O. +X@X  O@X#O++..#X#X+ +#X.X$ Xo..@X&X",
"  . X#X$.#XX+ O @%o Oo o O.@+.X+@& #+X## ++@ OoOOo  O+ O#OXO.###..#.O XX+X%%. o# +X#o +%   O++ X+.$. #Oo...  +O OX&@OOO+..  # .XX&o@  $.# X..#OXO$ XX$@ O# OoX$X+O",
"O $O..X. X%O..X O..o.@@O.XO+$++X+&%O  XX+++%+%  Oo.oX +.oXo oO #.##. X.%XX&Xo.OOX+$#X +@X+  o.#.X++O+ # O+%# .$+$ @@@+XO.#@@O @.XX#$X .##.OO #.OXX.O OO##+XXOoO@ O",
"$.OOo#.# #O.@ *@X#  X&*+X##OX+X@$.*o#X#@@O+%  #O%..OOO#@O@ +X  o....XX$X++X+O#.O..$.+O%@X+##O#O#X#%.  O#O.+O X@+#&&@@X+O# X O $#@..$@O $ OOX . O#.O.X.+O X+@O.OO  ",
"X@X     .O$@$*X&X%.#.&@@ ..OO#X@+X%*OX#$.##    .OO.$@ #$ O+++++O.... +X+X%O #$ oX..XO +X+@@+ X X&.@@ ##O%OOX@%@&+$$$@*## . ++OO. #XX@OXO #$# O#+++## O#%OOo .oOooX",
"&@Xoo++#. $$&#@X.%X oO.#&.  #o$X+X$+.O#..+#$X$ #o#X.+XO@OO+$#++.O.#.  +%X+X@XX$O+.+. O.@.#.@   .X#@@XO.$%O$$$$X@##.*X@*O+OX+X OO# O # O OOoO.o+++$  .+O $.oO#@XXO#",
"@$$+X% O ..@@.&X%%XO $XoO..#++#X+##.$  O # .$X.# ##.#.O#XO o+o+%Oo#.  O# #&%.@X # OO   X++X%O .O.X&@X  + $.X.$$$OOO##@@#+.o$#+O#X+  @#O ..$@O ++.oO . +O## ..O&&X+",
"X@O#++Oo O$XX%X@X++ O$X.O  OO%% XOo#. # O ##.X#$O +++O@O&   ++++ O OO +#O##.$@XOO+    #+XXXX.#OO .$@# O $X.$.$@. #..OX # +.XOX OoO  .X.#&#X   OoOO##  +.# .@X@X@&@",
"@$O# .+#+$O$.+X.@%O..X@XO#. ##.o.+ +. .X$$. o@@@# &@X.O.$X+o ++  O XX #+OO##.@+ &@%%   X.X.X@.O#       +  X@X$$+@$O +  X.+@+++O O   +@@#@X#.@O#OOO##O O % O.$$$XX@",
"+O.#.X.X $.O $$@%#O++O@.. O#%%% # ++ OX%X%O.$&$@*#X$&XO  $.Oo+OOO@$@+X$OX O .@O@@$@+oOO+X$+X&OO ##  +# OOO $@@ o## ++@ OoOOo  O+ O + + #+.@$XOX&@O@O+ OX@@   X$X$ ",
" XX.X.$$XOo +O #  OX+ O#+O+X$@%X+. O#+O.#O&@&$$$@.X@.$XOoo+.OO%X+oX%X .#XX++O oO@@%X# o XXX@OOO#  # OO## OO..#O XX+++%+%  Oo.oX +..$$O@@XO @ +X$@$O.XXO$.X@O.O.$X.",
"oo...XX@O@$ # %%X @  #O#o#+$+X%+O O#.$X.o#&&&$$&&+  O#X##OO#. %+ ##o..OX+++ XO#oOoX+#XXOX+.%O.O##.O##.oo .O#.OX##@@O+%  #O%..OOO#@&&&+#.@#+##X.XXX###.+X.$. #XO.XX",
"..###.X+$%++OOO++++ X.XOOX+XXoX++ ..XXX.#@@@&&.$ +++XX+Oo # #O+OoO OX# +.+.+% ##+ OXX@  o+@ # +$X@@.o+  O oOO   #$.##    .OO.$@ #$@@+&O.XOOX O#.o .+#% .$@O+  # # ",
"XO#.#+XOXX%oO+++o+O#oO.@.+$X+++@O.X XXX. X$*@@@+ ++++o%XO#.#O.XX.O O# #O+XO+O ###O@X#$ # # . +@$&X.X @@.# O# %X.#..+#$X$ #o#X.+XO@X$$@ @@@##.+   #+#XXOo.. #++. o#",
"O#O #  #+.+#++#+X+OO$X%o#OO$$XXo.#XOXXX.. X++XOO +o#+++X #.$ + +%@*+O#...O#  O # O#X.o##.X#Xo$ +$X@@.X.X#.# +.@+ O # .$X.# ##.#.O##$$$XXXXX$O@&& #+#%#O   ++$O #X+",
"o$. O.$..##+##o.o+O#+%XX+++O###+oOO OXXXX.oO O. ##X#++.+ +$OXOX#OX.%#X.X@#Xo+#O X%OoO#..XX.X  +@$&X.X#.# +o .. ## O ##.X#$O +++O@OX@@*#$X$+%#++@+#+$.O.. X..@O#.#X",
".. % #$X$. ooo+++o ++ ++%X#OO#XX+#+oO X.X+XO#&@@ O##+X#%O#.& oX+XX#o#...$$# . .@X@XO#.#.X#O##+OOX&X O#.X O+ X #X$#O O # XOXX.OOX&XX$@&O .+#OXX$@#+X.OX#+ OOXXO ###",
"#oX%+O.$$$o++ X++O O X++X%%+OOX+..O.XOXX.X#X.@&+O.   #+XO$##X+ X+%%X .X..$ ### o+   #..XX+. +..+#O.#XO   X# .#.#X.o O #$ ..$.O.&@@ $$+.X###.O$@O++X   X++X. OO.O##",
" OX+.+O.$$O #+X+O #$  .+ X%XO #XXo..$OO$XX#XX+XO.X OXo OOOo+OO$O@++ + ..X Xo  o OXO## +$.O%O++X#..OX.##+  # ...X$X# O $$.$$ #O#@*XOX+O.##X$.O+#+.$#  O#XXO#+ OoXo#",
" oO+$ooO.O#OO#.O+ OOO##@@#+.o$#+O#X+OXO X# XO+X@ #O.#  OXo.+##+@+.  %# .#$$O ...+  ###+.#OX#+++#@$.#@#..XX O  ##$X.X@O *.$$++oOXoO#OO+ O###X #..$+ ... ++#O +$ .+ ",
" o  ++oX. o++ @O++ #..OX # +.XOX OoOo+++O+ O@+$+oo#O  #+.o oO#O O##+@+XO#$##..X$ # ##.+X O    +X$@O# ##.#+%O.# ###O@$ $ *$$$+O OX. # .@@O#.$X.X@##O O O++#O#$@#+O#",
"# $@o+#O@+O++o##OO@$O +  X.+@+++O O oXX% # #%+ OO#XX .+  OO# .$OO.+O..O.XO#.#+#+O&@.O +O  @@O $.@O  O#.Oo#.Oo.+.+.#@.O$**#%+%O #.X. OO.O.X.O +X+  +O..OO#  .$.$#X ",
"o#+#O+.#O##++O*&.### ++@ OoOOo  O+ OO+++ X#o+OX+$O+XO#  . .O+& X@$ oO$X#XoO   +#XO&$X+ #O  #&#. O # $$$$XOO.XO.. $.O#. $$*X%O .#XO .$$O .$X...  XO#O O$@O OXXX#&%O",
" O .X@@@O@.##&&&$OXX+++%+%  Oo.oX +..+++.OX#O#+%+o++# o+O@ o@$OX$%O  .X  O.  +#++.oO@#..OOO@@X.@.O#XX$%@@XO#&.#.+.+### $$$*$# #+O o#$.$ .$$.X$+#O# o O$@XO##X$$# %",
"..$##o O#+X.O*@@ X#@@O+%  #O%..OOO#@+OXX##+## .+#+O*XOOX.####O X+o##++O ++ .#. # .$ $@ #$@&+X #+% #X$$#$@.+OX#O#@XO. O.#X$$X+ .o+  #XX#.#.XOX$OO..$@O# O@#+ #.# X%",
"XXoO##  # .+#+@+%&#$.##    .OO.$@ #$ . X. O..++.OO. @ +#@+O#+++O #  X%XOO X.+#  + X#O# #$&XX. X$@# ..$@&@X* OO O  .OXX O## .O++#+O##$.  O .+ OXoXX..O#O.+X.O   O+#",
"$.X  ##oOXXX+OO%$+#..+#$X$ #o#X.+XO@.$OO.#..$.%#.X&.#+#XOO++.X++#O . %X+#O+   X$O+.X$.##@%@&++@+#o#X@$#X *+X$.# Oo###X$ OX O  +%+# X#   ++#++OXX #..O$ Oo#  oOO# +",
"#X.O.#  #o%XO+X$+  O # .$X.# ##.#.O#.@  ##.   O& .&@.@   O+X++%+O+O+o%$Xo+ O###+#+XXX. +@$@+@ O+XX OOo... X$%@OO$@#OX..X  .$XOO #$.##.+#.+#OX #.@O. O.XOXO#.  # . ",
"#$X ## oXO+X+ +%o@# O ##.X#$O +++O@O.#+ oXX ..#O.$$$+@ XX#O+.++++.. @X+. +.$o#. +++oO# +O .XOoO +.XX O# O .$. $**@&+O# + ##.# ..$.@ .### Oo# .#. .oX oO#$XO##. #+ ",
"#.X # #o  O+.X  @#X##O$X@O+%. +@...+.XX+o$$O.####$XX ++O+@#Oo++O. O.o OO.OXX @$% # oXX##.#O@O #++X%$### ..  OX&$@@@#o# #.# +++ .X.. X$O+## O   # . #. Oo@$O#..@.OO",
"##.$O  O.+#O#+.@@&+o#o @ X$ # #o.XXXXXX  ++O.##o  X X  +X*%..O .X +#OX+#.OXX $+.X. XX+...+XX.O+++X%@ ##.$  O @%%%@*+O..O# +X+ .@.@#O#@@O X$@# OOX++#    $XO . ++OO",
"##..#.O+ XX+OO$%X@@#O XOX.@+#$X .o+###.##+ O#  #o##..O@OO@@%@o X+#+#o +....## XX#@+ + @XOO++XO+.+ $+o+.  #.+.$$*@@&O#o.   #O%#$..OO  .X.@XX+$.+ +%.+X+Oo@XO+OO.#XX",
"+X++#$X%$X#X$#$X+X%+OOX$OX #..$  #   o#Xo+#.X# O   .X. Xo @*+ ##  O+   #XXO+$+&@%O#..##.+# ++##.+XX#++X .#.+#$$@.@ @ O.X.O..O ..#O..&#O &$XX@X#@ +%+% OO#o O O+X$$",
".++..X.@+OO XX#+XX o++O OOO...@ OX. $# O#OOO$ ##++XO#oOX+O oO# #.#.O#.O#.X#@.$&@@ .O# + ++&O# O+.X+++++O+.X+X#&@@O.@%@+.X##.  oXOX.@X+  X@X$++X@#O+X+ .  ++O#+#++$",
"OX+  +@%++X.@$XO+$++++++++ X#$oo X&%#O*X$#O++ ++.+X+OoO ++O@@#  X.XX $. ..O#O$+@*+O  O.%X.  +.. OO#++ @O$@X@$X+Oo#++@ *XO$ O@$OO.#X++O   #X.$+..&X#+O#X$X.O   + XX",
"#  $ooXX+.XX+##+#++.#+++$ O#.+O++#+#XX#&oOOOO +.+X  O #o++OX@. #X.XX .@  o.##O#$XO##X X%OO.XO .O+.  #X@#OX%X# O#O@.+$%@XO#  ..OX OO#.X o  XX.X *X.o #O.$$$O #OO#OO",
"OX$.o o#.X.@.O+o+o.+.+X #O. .+$ +# XX++&O#@@@O+ +O# #OoOO XO&.O#...XX #.O##@@#O X+ ## +oo .. XX+.+  X+*+  #O#oO++O.$..@#.O## OX&X  ++$X   X.+.X+$     #X@@#.@X@+XO",
"+ #o+@oO...X. .##o+#+oX@ .X X$@ X+#X+@+OO@%@%%O+ OX@%%%O$XO O   .XX.O. .  .O@X+%O+ o oO OO.+o #.OOO +.%@  O oOo++ O .. .O##.##OO@ OX$+O+  X.@.+ OX  #OO#  %+ OO@ .",
".XO#.+#$..#$.O#.+#o+ ..% +.O.o#O#O +++O#oX$X%*#+ O+%@&@+&@X$+#.O#.# #&+#.$O++@O @  #.#..O# O+ +oOooO.$X*O.  O . # O %$#O.####..%OX@ O @ O$ X. OO#%oO#$+O#XX%%+XX& ",
"..%Oo+.+X .$#OOX+o+o#+XXOoO +.O#@ .OOO. O+X$@%+ .#O@X@%.%@.+O@@#.@X@+X XX#@+@@O.@@O.XO..#.OO..%  O OXX@XO#&%O#.+.XX#O #O  ##..O#X@$X OX#OO O   #+++OX@ +XX+@%@O@%+",
"#.+O. OO ##O  #O+  # # X##.#%&#+. #.XX+#O +X@@OO .O %XX X+Oo   %+ OO@ # O.OX+. .O+o#oOO$+O@@.X$%O.+O.X%@OO$*  ... o+#O .#   #+#O@.$*XOO+#O OXOo+#X#XOO++X$XX%+XO@#",
"X.XX.+.  # +##XOO  #  +% O.+Xo+. .@X$XX%XOo++%   ..# OO.$&OO #XX%%+XX&# O+O@X& .X.  X*O+@O+XX$+X X% o#.o. O.O*.@#@  ... o+#OOX$##$&@..OOXOO@ O+.#X+%.#+. .X$% &++#",
"X$$$XX@# ##..o .+ ++ Oo+O@.X# .+#XXXXXXX*+ O ##. #$$X+OO@+oX.XX+@%@O@%$# #O&X@o....O$@XOXOO.$XXoXOO..X#O @$O++%X%XO@.@#@X#O#@ OXO # #@& OX @+ .#.%+OX@O+&OO.#.&++ ",
".$XX$O$  oX+XO@o oO++ +@$XX.@# + X+X+$+%@+ &O#XOoO.$@X#+ .o oX$XX%+XO@XO@.OXX.#X...XO@o#O@X +$@OOO...X % X#@O.#$. ++%X%XX@O.$X .o OX%@X%.&O#XO.#.+#X++#OX#+O# #+%X",
".$X$o#@ O+ +O+XX@#OO +#+o+#oXo#OO$XXX+@X@+ OOO+.O@OX&&# .XO$+ .X$% &++.+ .XO  .......O....Oo@@O.X#...$ X##@@ O...@O.#$. #+ #$#X#O @..+$.@OXOO +..+.@@&% %+@ . .O%&",
"XX.$ +O.O+%%+X.&++#X  O#X+. +  #o$+$+X+@%#X#+#XOX@@OO #+o +&%&OO.#.&++X+#X..+#.... $+O..#..O+O#XX. .#$O.OOoX  OOOO O...@.OOo&@..#..@X.%X.+ +O ..X .%X@#+%#+X@@O#O$",
"$.$o++X++.+%+O+O.#+ #+##+OX  +@ +O.+$#@@X##++XO XX&O$* + XX#$X#+O# #+%% ........##X.XXO#.  oO OXXO#.# XOX.+#. .o XXX%$ ++OO # #OX$X..$$@+X ##OoX+o+##+O XO#$X&X X+",
"..+.##++OX++O$ .o..X####.o.$ X+ ++#XX$$@+OX+X+  .@*++Oo+X$&.$%+@ . .O%O....$O..X o.O#@.#  +##O#    .##X. O#XO..X++++X%O.#XX XO OXX. $$.O #O#.. +XO o#OO## oo&%+.##",
"# #X+X+##OoOX+.@#O.$#..##.  #@  + #O+X@%+O+++.+O.Xo  o#o X.#X%#+X@@O#O O..XO@##XO.*+#@$.XX+. ##### # $X@#. OO% @O +$XXO+X$$$.#XOO$$*XOOO#.O##@&.OO%#@o .#+ +X$+@.#",
" + ++++XO.#   X.@ #XO.#....Oo.++$@O#.oOoOX. @O + +#@# o++OOX&XO#$X&X X+@#OX+@XOX@OXO$X$XO@#.  +O   O..$++.%#O.+oOOO OO+#++$X$$ ..O$ O  O  O..@&XO..X# OXo#.++# XXO",
"#O.#+%X+ Oo #$XX@#OOXo#o#.O + %X@@#$$ X##..XX+ @X+. #o+ ++.#O# oo&%+.#$*&$#o# &X**+ .X&++#O##@OO$@#O..O#X#.%. X%%XX++  + XXOXX#O@OO# ## .XXOX@XO. X.. ##+O$XXX. @+",
"+#o+X+  @@O@.O...OOXXXXXOO# ++ #$+@X@@XXO.X.XO.#+*%@%O +%Ooo+#+ +X$+@.$XX%+O .@$$@* O o#X%++# $X#@&+XX+ ...+. *@@.@ X OO#OO$O.#O*+  . O.$XXO$XO#o XOO.+ # ##$$O+#.",
"++  OX% @X+  @O..OoOX..Xo..o#+. O.X$#@$X$ .#OXX@@@XX$X# O#  #o#.++# XX@@@$+# @+$X$X###O++.# #X&$@@@#.%. O#.X..O$X$.# oX#&+OOO+XXo+XO# o$#.#@$%o ##XX#+.O   +OO.OXX",
"#O.X$#X#$X  $#+#.@@#+.X.O.X  #O  $.#.XX&*XO#  $$+%X@@ X%%# o +O$XXX. @X@.X+#O+$@XX@o# . +#.#+@%%%@.+%.   OOo#  .X+@#O .@&#.+O@++.+.X  O#.++@X+ #..+.X    $X XXOXO+",
"  .X$..+.XX @$OO$X#XO o#@ ..X#+@+#$#@X&@oO.X+#O#.@@@+%X%+O$ +# ##$$O+#+$@%@  O.$$@XO.#.XX#OO $$+@@&O.++  O#O.#oXXX..O  XXO   # XXO $+ $+#+.$o  .#X#.# #. .@O.+##++",
".@#$$$o@OX@$O#X+ oOO ..OX$O$.XX  OO.#.oOO$X#+#  .XX%+X#@O++.    +OO.OX #@&X ##O  @$o# ##$ +@O$$@.@ @+ OO  #+O.O #OX.@ + o+++#O #o. X#O##.+@o+#O ## XXO###X#. #.#+O",
"#@OX$$O&#+X@@#$@OO#O#.X. O X#+X#Oo O..O.$..+. o Oo OX+@#++X++ $X XXOXO++X@#OXo X@O+ $#OO$#$X##&@@O.@O# O ++++O oO@@X+X$++o++++Oo#.+  $$O.$+X.oO.OO..XO+ +%OO #.XO+",
"#%OO#XXoOO@XO.$X# @.O O#. o O#++OX .#O.X####Xo.#O+oO . ++++++ .@O.+##+ .#O O@@O$XO@$$XO#.OOX X+Oo#++O+. X+++.+##@XX.&.O+++%++X. X O#$@@OO .@$O@&& @@#  +++  $@ O O",
"O#*%#O# .X XOX. o XX&++#Xo#X$.O.+X@ .+    ##O XXX O.  #+.%%%+#X#. #.#+.O OXO++ X+O.*$#.#O #O  O#O@.+# XO++#+#+%#OXX@+O.O X+%+O+ #O.O@*O# O*@%#++@+XoO   O$. OO#+O+",
"#&@O + O##@@+.  . #$$+#  X@O. #@..$#o+#.#X%o OX%+X.@#.O##+++++%OO #.XO.XO. &@ @.#+O#+ ...++X +OO # #. O +++.+ ++.+#.#+O oO++O+%O+&+ O$+Xo+#@OXX$@#+O++OO .X.+.#. o",
".OoO#@$@O #$+X+X O+.&  XX@$+# #@@.+#X oO +.#XOXX+%O.#@XO #++.++  $@ O X .&@ O.@@Oo##. .#+X+++ +OO#..XO$.O#o#   $XXOo#X #  + O. #$+@%oO+.+O#X.O$@O++O .X+X+#$OO..o#",
"X  X@X%@%O##O   o. .@@.@@@X%.X $%.  $.O+ OoooO$X@% X @&O  # ++o. .@X% O.@$OX.. OX #...  +X#X#%O#OO#.#.X@XO#.##O+.O+ O##+++    OXo+%+@+#@$+ #X OO#+o .X.X..##o.##$ ",
"oO$X%+%&@+o +++   OOX.#@@@$XX.##+ O#X.. o#o#+O.@XO.+XOO+OOO##.O. $$&O% X$OO@#$& #X ...# +X##+X+X.O##OO.X@ O.. X # . %.@ OX$o O+++++X@+#@. ##X o+%O #.$X..#...$+#+O",
"#.@%X%$X@X+#++o+OX@+O.OX$$+ O .XO.. #$oOX.# +##Xo.#++  #$$..oOXX.*X&O@%#O#X...X++# ...#+O o #O o%+OoO.O X#XO.O&*..+ +.OX@ O.# . ++#.+@++#  X  O +###...+X#...$X#@ ",
"O$X&$%%@%%O+o+# ..X$@O.O#$. Xo##.+X@X . #XXXOOO#.+ X +#.@$@$O %%o @## ++++X%.#@+X$O  XOO#.OO#++#O#  OO X #$+O *@&#@O OX@$X  O#+$X#++XX#X% ..O   O##.# ..##..#$. X ",
"  @X@%@X&+#O+#+o.XX.%+o#O@&%#O.++.X  $   #.o #+.@@O+o #OO #Oo #+O#.X..O#+#+.+%X@OO+Oo# ...$OO.X.   o.O.#$OX.. .&$O#+.#@.$.XoO #XX+#%. .$@O ##o+O  ## o..##. #..o.#",
".O+X.+%X#+%+ o  O#.X@%OX O@@# .$XoO##.++#O  o+$@.@ #  +  %+% .#O...X+  OO+++#+%+.O.X  X...$.#O + . .+#.$ +##.X$%  OX++#$&@.#O+.@X+#@O  +O@+OX ++ ##  .###.+  O.+O.",
"..OO#.OO++++O #o Oo ..# $@OOX##OO#.###+oX $@O.$$XX#o + ++%%++O.XX.#O+  .## #+ #o#  #+..XX..++O.X##   o.#+++#.@+.@##+. O # #   +$XX+oO  O$@@ #O#..   # ##.#X#OO...."};
