/* XPM */
/* $XConsortium: RicePaper.pm /main/3 1995/07/18 17:19:50 drk $ */
/*********************************************************************
*  (c) Copyright 1992, 1993, 1994 Hewlett-Packard Company	
*  (c) Copyright 1993, 1994 International Business Machines Corp.
*  (c) Copyright 1993, 1994 Sun Microsystems, Inc.
*  (c) Copyright 1993, 1994 Unix System Labs, Inc., a subsidiary of
*      Novell, Inc.
**********************************************************************/
static char * Riceppr [] = {
/* width height ncolors cpp [x_hot y_hot] */
"164 168 8 1 0 0",
/* colors */
"     s iconGray3     m white c #adadadadadad",
".    s iconGray4     m white c #949494949494",
"X    s iconGray2     m white c #bdbdbdbdbdbd",
"o    s iconGray5     m black c #737373737373",
"O    s background    m black c #949494949494",
"+    s topShadowColor m white c #bdbdbdbdbdbd",
"@	s iconColor2	m white	c white",
"#    s selectColor m white c #737373737373",
/* pixels */
"  .    X.o  oO. .o..OOo  .. o ..O..O... X XO. Xo O.o .  .  . . XXO  .. . ..+.   .O     . . ..O.O .... XOO.. X . .X...O  O..oXX   .  .... . . ..  .   o  .OoXX X .O  ",
" ... ..  .OOOoOo. ..o.Oo..  o.+...  .o   .  X  . . .    ..o .  .oo. ....X .  O  ... .X + .O ++o+  .o . . ...    .    ..  ....     .   .OXO   oO.   +..... .  X XX   ",
"O . +O  X.o O.o..OO O....oX+  . O XOO  .OX    X Oo . . . . O + .. o ..o  O...+X..O Oo. .. .oo..   .  . .O.  .. ..  . .+. . +. X oO... .   .   .oO.XXO.    .X..X+X   ",
"OOo  X.o. oOoOo.o...+Oo.o.. X+O.. .OOoO  .    XO..  . O   . X . . O .O....O.O .O .o.... .  +.O   o+ .....o  ...o.  +OO  + X.X.. +....  +  +  Ooo+..X+ Xo.  .oX+.X+. ",
"O.O..  + o  Oo.oOO .OO.... .o O. ...O.o .  O X+...OX+ ..  O..o X  ...Oo..o.Oo. ..    .    ... O X+o X...... .....XO +O. X+.+ .O   .    . ...  O . .+..O. .  . XXX..X",
".o ..X  +.O.o..Oo   ..oO   ..O...   ....O.X+X +O.+ .  .  . O+ .. O.o..Oo  O.X . .X....  ..X....O.+O.  .  o +  ...+. ...  .. . .. ...  .   .... XO.+X.....  +.X.XXo. ",
"O   +  .  ...oOoo.oX OOO.. . Oo .... .o+. +  o .  .. ..  O.XX+.. Oo.O. . ..  . .   .. .+. ...... X.o. o.o    .O.o+o. O.X+  ...O .  +o..  .....  O X O + . .. ++ +..O",
" .. .   .. .O. .oo.. . .oO .o.. .+O.+ . +.X   ..o. X  O . O  O .X..O..o .Oo. . o..OO..  . + ... .... .  ... .O...+.  .X.+ +..+  +o    .. .. . .  o.  ..O . O  XXX+. ",
"  X   XX o..o.o.  . .    O.ooo .  X   oX . .. ..+.  + .  .   .X.o.. ....Oo .oo O. . . .  .X.. +.o.......O..  O O X..O.O.  . . .o  ... . +   X  X . o. . .  ++ X+ + .",
" X.   .  . .. o .  X..O  +.oO .O.O .. .++ . O. ..  O..o. +O.X o. . ..o.X.O..o..OoO.. O..o+.  .++ . .O. .o . ....X +. .....o  . o ..oX O  ...      +..  oO.. + X +  .",
" XX+ +..O  . .. +   ....   ..O.. O.     X  OX ...X.o.. . .   OoX+o . .   .....O +O o..O  X . .X   +..o  O.  +O.oX+X.... .o..  .  .   .. ...+   .. XXo   ..    . +.+ ",
". .  ... o ...+.   +. +.  +.o . .... .+  ..+.....  o.  O  . . . .....  X+ .....o.. +..+. .+..... ..o.. . O....+..XX+ oX.Oo.  . .  O  o. .. . ...X  +.+.X+ .X. X X  X",
"XX.. ..  O.  .o  X X  +  .  O +O.o..O  .  .. .... O     o.O  .O .. . ... .XOo..Oo.+  O X..+.++.X+ o    .o.. X  .. .  . o X O.X.  +oo .....O+ o .X+. ... ..  +.+X++ +",
".  .. .     X  . + X ..  +  . ++...O .       ..o  .   Xo.o..oo. .......    . .... ..+. .o.. ..  X. + ..O+.O X+.Xo    o...+ XXO.. ..O...+...o..  +.X .  . .   X  +.X.",
".   XX.    +XO..+ XX o  .. +O o O X ..O O. oO.. o. ..X.O.OOoOoo .Oo o.. . ..... o+o+.   ..o+O ....  ..   oo . X  +X+X .O .   . o . O .  ... . O .X.   +   .+..X   ..",
"O ++ .  X+.XX.. X  .O+     .  +o ..  ..O ....ooO.Oo.....O...oOO. o .O. O OoOOOo +.. ..  X.. + . ..O.  . OOoX+  .X ++    ... X+ +..o. . .... OO....oX.X +O ..X  +X   ",
"+.XXX .o  +X  .. XX . XX O. ..     +. .... o..O.. O + O..o..OoO.  .OO...  O.oO..X+ oO..  O  . . . .  .  ..oX  X   XX+ Oo.  O X .  . o+.o .O.O  . Oo  .. +.  .. X.X .",
"  O.XO.O      .     ..    .. . .   +.XX. Oo.o  . . O . . .O.OOo.. OXOX.    O.. o. .. o.o+.O......O.....o.Oo.+  .+XXXX  ....   +O ..O  .oO. .... ....X.. X  o ..+.  .",
".o O   . .  + X X..X     +.   . o X+   O.. .. . .     O.o OO..Oo.O...  .. .o Oo.+ ..  .....X.. . ......X..o +.XX XX....  .O  ..o.  .    o  O......  .  . . .    +   ",
" O O. +..+.. .  X +.X O .. .XX  .  +  ..o  .. .+OoO.  o.... .O..Oo.... . ..o.O O.+...XoO...  o..o.XO. .+.Oo ..o. XX+ ...    o..o O O..o. .. .O..Oo. .O oo   OX.X+   ",
"  OoXXo.+o X..  + X.o OX+ ...X  OXXX X+oo O...X. o.O .. .O..OooO..oO + ....O. oO.  ..o.. ......o. +.O. .oo.. . . X .X X..XOO X.o...+ . .O. ..Oo.Oo+.O  . X ... X.o+O",
"    ..O o... X. . ...  . OO.  .   X   ...o.O. OOo .... o ..O ...O   .X. o.Oo.   .Oo.O.oo ...XO. +O  ....OoO +.o o X.+ ..+O ..O   ..O...O...o.. Oo.  X .   .OO.X....X",
" X+++. . O.   . .  .X +   .O      O.. XO..   oOoO. .O ...  . .O. O.  .O.O. O.o+.o.O....o...oOX.  +..o ....o+.O.....XX O   o OO.. .. O O .  o...oO.o.X X. .  ......  ",
"   X+ ...O.   . + +      .X.o  +. o.. O.O.   Oo  .oO.o..O.  o O..   X. .+.O.O  ... ...O   o.o.X . ... .O... OOO.  .  X+  O... .o .... ..  .OO oOo ..o.X+ .XO+o.X .  ",
"    ......O...   .X  . +...+....XOo..O.oOo..O. ...o ..Oo. +oooO..  .X. .. O....o....o   ..O..oo.+..O+Oo...   Oo.  o ..  . .O... .OO.  . . .  oO O.  X  +.XX... o.oO ",
"X..X .. O .  + .O  O.+oX. . .... X...XOo.+OOo..+  O.oOO ..O.. ..oO . . .o. O  . ... O.o. O ..+.. ..+..   o .+XO.   X. ..  . ... o. .. O  . . O ... .X    ...o ...  .",
"X . +.o ..OO.oo   .  o.o.oX+O...   o.. Oo OoO    OO...  XOO   .o. .  o.  .O...+ ......O.O O O...XX.o    ..O  +oo .X. . OO. +  XOo.X.O.O  .O. +Oo..O. .XX    ..   .. ",
"XX+ .O.+  .  OO. ..+ oO .O   o  O.O...O.o..  o. . O.o  ....o .o.. o.  .oX. . .  o o...... Xo.+OX X. . ... o   ..o+OXoO.. . ...OO...X.. X + . o ....X  . +o. +. O .. ",
"    .o... .O..   .+o... ... +O...O... O.O.oO O.+ X..O..OO. O..O. o.Oo. . ..O... . .OoO.o. .... o..oO.o+..+ . +.  ..... .o.. O O..+...X+ . . ..X+.. .....X.   .      ",
"..  . .o o   . . . O..  . ... . O.. ooO. O.. .. X  ooX+.. ...o . Oo  o ..o .... ...  OoOo.. O +Oo. O. . . +.O  . .X..  ..  . o+. ++ . .   X     .O. .X   ...   . ...",
"XX   .OOo  .       .. O  . .. +o+o ... .o.o.O... Xo..... o...oO OOO.X+. .. . .  +.  .o..Oo .o. O.Oo.    o.. X...   O.+.......X.  X.X  .. X+. + o.O.. oX.....o O.+. .",
"..... .o.     .o. .+.    O o + .oO. .O Oo...O ... .. O..XOO ....oO.. O Oo.O.. .o ... ..  .OOO...o+O. .o..o.. X . .. .. . O... .   X..     . . .  ..X..  ....+..O X+.",
" O .   . .  . . O. X . . O..  +OOOo.O O. ..o.o .O . o.Oo O.oO. O .  O . +.+oO..  o+ + +.X...O..O...X +     +o o  .. .. O . .  .Oo ..X   . O..... +..+ . +...  ....XX",
" X o.O..... + .+ +...o X  X .. X.oO. O....Oo.  O . O.. ..    . +. .X.. ...ooO O.. O X+XX Oo . ....    ++..+O. +.. .. .. .+. OO X  ...Xo.+  .X.  ..  .. .X.Oo+.  +oX ",
"..  .. Xo .X.   X .. o.   X. .+. ...oo.o..O. ..o. .oO ...  o.. X . .X  O ..oOoO..  .  .   ....oO....X+ +   +....  +..o . o+.+   ......+  .. X.. O.O   ... .. +  .+ .",
"..    ..+O..o  .   . X. +X     +.   .. ...O. o.o  .Oo. .  OO.. +X+   O. . oOoo.o. .O.  .. o. .O. .X. X+X+ .+. ..X+     OO. +  +.X. . O    . .+.O   ..X. X... ... .O.",
". + o+ .  .... X.X XXo   + ++ . O o.O.+.X..oo +. O .OO.. O.oX. X + .. .  ..Oo. O..  . . . O  .. .X ...X.+.. ....  O  X...      .... +. + +.XX.O       .. + . .O. O.+",
"o.o... .o    . X  .. .XO. +X+..OO +   . X..O.o oo.. .O +.. O.. . X+XO +ooo oo.. O O.  .o X+  . ...  oX  X ..+ .X ..O o..X  .  ...X  . .  .. XO. . O +..X X   . .+.. ",
"oo ..+..O .  .   O  X . XX .X+.  X . .. X+... .o....+... +o+o O.. +   O.....Oooo.. X. Oo .X .O.+X+ .+ XX  +  . .... .... . .+. ..XX....+..XX ..   .O .+ .  +O.  OO  ",
". . o O. . ..Xo.   .+O+.     +.   . + +.. .+O ..Oo....  O... .. .. X ..+  o.OO....o   .  . X..X.. ... ... .....O . .X...Oo..+O.oo . .  X  ...+o . ..  . .X.o+     + ",
" .. o O..o      .  . X  X.  . +. ..o   . +  .oO O..+. + .. o. ...  X.  . .OoO . O.+.+o.O.X .     X.  O. .....O..X+ .  ....O   . .X + .  .O . +  .Oo .X  .X  ..oX+.XX",
"o..X.O.o .  +.  ..o.. o   ..   oO+.. XO.+ + +  o..o .    ... .o. .o..X  +    .... . XO.O.X.XXX+ .+.+ +  OO . .o+ . X O .O.... .....X.... +.+..X  X..+ XX. XX .. ... ",
" . .ooO. .o++.  .O....X..+.  +. X..  X .XXX   .OO .... .... ..O.OoO . X X  o .OOO .X.oO . .  X+.o  .  .    .  +X X. ... ... O .o X.   .   +  X+o.X .+.X X  . +  . O.",
" o..O .. X .  . O.O .   .+XX +   .     ++X  +  +  O .+   . . +....O.. XX.    O o .. ..O . X     +. .... +.  + . XXX.XX     .. ...oX O.oXo .X    .....+...XX+..+  .  ",
".o.oo. .  ...  O o.o  .X Xo .. .o  . X+XXXXO X  .O . XO.   O    .O .OX .+ .  O.O.o..  .   . .X +. ...o    .XX  O  XOX.X ..OO.. .  o. o. O .++    .   .X .  O..X+  ..",
".. ...o... X . .. .X. .      ..O.  .+ X   X+ X O.  ... + X .X  O ..O XX+ O..o+.o.Oo.o .O . Oo+ . +XO  +.O .  X  .  +.XX O . O .. X .O    . O .  + ..X+ .+.X....+.  O",
".O .o. . +... .o... .. ..O.. X. +..  .  + XX+ .   . o X +..   O  Oo .X  ...O  .o.OO.... O   O +  X ...    ....X.. + X ... .  ...+  ..O. . .  . . ..XX.. + +  .  X..+",
".  o . +  ...O...Oo . .O.    . .oX ... XXX X O.. . . .   X .X . ...+.+X+. .O. Oo o..o .o.X+O X  O.......   X. ++. + ..... .   .  ..  O. . .X...oO..  ..+ +. .    X +",
"X.o .O   .o+..  .Oo O. X .     +.... +  .XX  . .X+ .          +....+ X   X ..Oo.OO.O. X. X..   ...oO.      . . X+     OOO. ..OXX     +.. ..oX..X   O.+ +.X .   ...  ",
" .o....  +. .o. . O...    .. +.. . O.X XX  +  O ..  . .oo   o   +o ... .X+ .o .O.oo. ..    .    ..... o  X.X...XX. X X.o. . .X  X . .   .... .X .O   oOO.. +  X..+ .",
"o.o... . ..O   O... O . . XOo O.O.. o  .  +  ooo.X.X   ..   X+O O .. ..    Oo ..o ...    ..    . X.o      o   .XX .+. ..o  .X  X ..X+....... .XXO  o.. ..XX .X +  OO",
"......o..X .o.o  ..    O.  X .Oo.O.O.O.X . . ... O.      .o    + ..++o. o o .Ooo.+ +.... o . XXO... +  X  .o+  X X  ..Ooo.. +O.   .. .o    +. . X    ..+ +  . X ... ",
"o ...O... ... o.. O  + +..   Oo.O.o.. o . oO .  . ++  .. O ....+ +  o X.   .o .. . +.OO   +    + .oX  X. ..... X   o   . . o .X X ... +.X. .O. ...  .  +.X+ o X.. .O",
"o .  o . .o   o     . ..O + ...Oo...  X  X+ Oo     . . .O   . X X  O   .....O  .  . O... X+.X .  .X++ X    ... +.  ..   +.  ...   ....  X X ...   X OO. .XX.       .",
" ...oO.oO O.O.+Oo  o       O.O.oOo..   XXX  Xo... . ..o .  . X.  O X+o  .  O .o.O.       . X..  . X    O...O   X....    X. .O  . .. .+.   .O o   X. ...  .   ...X+  ",
"..oo .O.O .    Oo  . .X..  o.ooooXO      XX.... XOX    . O..    . O + oo. o.o  .+O..  . .X  .   ++   +. O o o  O X +. X+     +   . .    .X. . O..  XX.+.   .X  X X  ",
". oO ...oo .O.oO. XO.... ..ooO..  o o  +X .+o.  o   .oO .oX..oo  .. X.. .. . X. XO.. . . .+   . .  oX .. ....X X oX+   X.     . X.+.OX+ X   O.OX  X XX. +X .o  XX  X",
". Oo  X .O.. .O..+O. . +.OOo..  .  +.  .X.X +X ..Oo.o. ..  XO  .O .o.. . OX o    .  Oo..  XX   ..O   X + . +.+O.oX   O   .+....X. .X X +.O..  .  . .   +oX+X  . . X ",
".. .O .XO..O..o. .O..Xo .OoO. X  .. X..  +..  o...... O.. . + +O  .. o. O.oX..   . OO .. o O  O..   .. XXO....X.. .  oX .  +.X+  .XXX+.++... .o X.  +. . X   +  X .+",
"  +...O..OOO . . . +O.....ooo ..o+.  O . . o....O.O. .   .  XO ...o O .oO   .oX..O +.....   +   . ..X   .. +  +    ..   O..  +   .     ++... .  ..XXXX..X.  .  X .+ ",
".  .  ...o.  o O  O . O..oO.X.OO.o X.. . . O .o + . O .. .+   o .+X.  ..o.  .. .. X +. .O    X +++o+ + .X  X. X.X++OO + ++. +X  oX+ X. .  .O.. . X .  .. +.  X.X  .X",
" +o. . .o. . X .o..o..Oo ..  .+..+.X .... . .  .     .. .X. o o+OXX  .O..  +.+  ..+  O. X. X   . o+..X.  .+.   + . + OX+o  oX+.  X  .   .o.  .o.o XX  .o . .  ..X.  ",
"...+.  .O. .XX .+oOO. O o .o. X+ +XX.XX +.O .  .  X..OOo. .. .    X +.Oo.       .XX.+   ..   ...  +O X.   ..... +.X+.+  O  o  .Oo .  +  +..   .X    +. .. ..   .X+.X",
". . .o.  o.X   X.  .o .+OO .O . XX. .. . . X   @+X+.Oo..  o .....XX  ..O .  .  . ...  . o  O+  .  +X X. ..O . X.XX + X.    .+.+OoX o.. .O . XO..oX+X X+X  o .o.X O..",
"X.   .Ooo. .  X.X.Oo.   o  o . X.   . XOoo   XXo+.X.Oooo ....  +.. o O..o. .        . . O. + .  .. .X +.+. O o . X    O   . +X.O. + .X .  .+..o.   .  X.   .  .X.X. ",
" ..   . ... o. o+ +o    ..O+ .   + .  ...o.X    .  o.O.   .o . X  .X.Ooo.... .. X. o   .o     +. X.XX X.. X+  .. .X..  X. + +X..O  .X...OO .  +X. .   . X.. o + X+  ",
" .o  ..... .O.O.  O .   .O  .   X....  . ...  ..X.  ..   ...OX   . .O.O..  .. oX+  .  .ooX  Xo. ..XXX+.OOO. .. .....+O   O  .XO..O.. .. .   + +..  +  X+ O.+  . XXX ",
"  O ...oOXX  ..Oo. o..   o.. ....... ...o.O+ X . X +o .X.. . .     o .O  .+    ..    X ..  .  +...XX X  . .O.  ... +oO..+O  . O   ..    .O. XX...X ..+.X.. .. +X   .",
"o .o.oX O. +.oo .. Oo.X.Oo.o....+o.  X  . . X . . +X X  + + +...  .O.O .+  XX..o..o    . ..    +    X  #... ..o+.o  . .++O O  .oX.O   .. ... O    .X+. . .  O.  X.. ",
"  . O .+  . +O.O. O.O  OOOO.+oo .O  o . .  X .    X  .   . X.. . .o.. .     . X ...Oo +o.O  .o .  OXO    ... o..+... O  . .. +  +O O.. O. .  ..   .   XXX..+O.+ ...O",
". o.  .  .XO .  O. . .o.O...+. oo. +.  +    +. X+ X X     o  X.X+oO... X.XX. .o X. O... o o. .. X.. X .  ... ..o.. .    OX+. . +.O .Oo + O O.  .oX. .  .    o..X.  O",
"..   O   O.  .  o.O O.oOo... ..O. ..  . .. ..X.oO       Xo   ...  ...o  .+  .o   ... X .. .  XOo.o..  .. .  . .o +  + ..  ...  ..  ..+.+OX..O +..+. X.. .+.O o+X.  +",
"o..   ..  OX..  ..oo.+...Oo..... o.+ ....  .. .    +  O  .ooOo   o.+.X +. X X..X.O + o   . .      O  .....X .   . +o   X+X O  ..O ...OX. ...O.O .X .+  . X. .o..o  .",
". + ..    o .   .o..  ..O  +.. .O+. ..X +..   O.   .  XO ....o  o. ..    OX .o. .o o. . .+XO..   O. .  O O. +.. . +   XX  .. ...  o.  . .o. Oo.o X .X ..  .. .O.  o.",
"..X.O.  X..      . .  oo.+. oo . X.  ..XX+...X.  XX .o  X...Xo   . . .X.  X +.+   OOo.+.o o ....  X.. ...X+X.  o.  .. X..X+.....O. oo...o.oo  O.o .o. . ....o..X ..+",
" .o.    o ..    o . X o. .o. XO..OO...    o.. .   X.. O  Oo.++ . O    . .        .X+OX o+  ++OOO.  ..   o+ XX . .X. +...+X+.Xo.O. +.+  .oO .O.X.o.  o.+. o...... . .",
"o  .+. .  X..X +oXo   oo X..  ....o....X ...... . XX O +O.o..XO .... o.  .  X     .  X+X  +   . .. .+ ..O +.X . o   X  X   ..O.O. ....OX..Ooo. +. O..   O. ..+...O o",
"+.O     o. O.  . oo  ... .  +O. ..O  .   oX.O.      ..  ..Oo o   +.+.O .   X X  X.     X ..X. .  ..XXX.+..   . ....X ..X .O o. +.. O. .  ...O X+...    .oO.OO.  . ..",
". .  ..o.+ o.   +O.o O o..   ..o. o.. ...  ..O XX.. . .oOO.  oX  X . ...XX X. . +X.oX.  .X..X.Oo  .X +   O. O. ...X  ...o. O....O...  O .. O..  .....  O. ...o ...Oo",
"..  ..O . O + ..o ..OX .   .... .. o. ... o.O..  . .X.++oO .X    X   +   X  X   XXX.   ..X.X .o + XX+XX  +.o+  O.      .O .  o..O . O .  .  ..X+ ... . +O . ..o ..OO",
".O +.O  +... .  ... XX...X . .  O .. .o..o.Oo. .   . X  O.O.  XX.. X  . + XX .X .   .   .oX  +o .X.X  X+  ..... ... O . +.. ..  ......  . .. . +O .  oO .OOo .o .O..",
". +    . .O.   oO. .X.O. o o.o..o o   oX.. .o .X.o   .  O. o.X   .  .XX.X X   .    .X XXXO.XX.... XX    +Oo  o..  .O .  + O . o. .o   .X+O ..     X.O.O ..    .  ...",
"O X    . . o . .ooo  . .O.O.o  ...O  o .. ..O   X...   O. .o +....oXO   X X+o .   . X  o X.o  ..X .     XOo o X+.X. . O  ...  .  . . . +.o...   . .o   +...    .O.O.",
"+..+ X  ...  X .OoOo o ... . .. o. .   ....... .  .oX. o ..    .  ..+.     XXX..o  +   X.  .X ..XX+.  . o.o .XoX.. . o. . oO  .   O. ..  O... . ...O o  +O.. .. ..oO",
" .   +XX. .oX o...O. . O...O.o..o.  . .X.. .. ..   o. ..oOo  o     .X + XXX       .X  XX.X ++Oo .. . O.o....X.o o....O . .. ..  o  X....o  .... . .. ..  ...+   +.OO",
" .o..X   ooo .  .O.O Xo...O ooooX . o  +  +oX. oX+ .  o.o. . +   .. .XX    +.    X       X X  . O.   .. o ..X  .  ..O .Oo . X.o .  X.OoX+O  .+ ..    . +. X ..O .Oo.",
". o X.      .X...  .X... ....ooo   .Oo .o.X.o .   oOOX oO  .O       + X  .  X . +.   X X   o  . . . .. ....  .....X.o. o o.+   O X . ...   o  X. .  X  .   . .   . O",
"...  o...  . X+ .  ..   X. ..O.X oo.X o  .  .o.. oo.oo O  O    Xo   .O .X++    X+ .O +   X   .. X. . Oo.o o O XO OOoo...... o+ Xo..+X. . .. .   .   X. X..   X  +. .",
"o O .O  o  ..XX. . ... .O. O    Xo    + O . . . O. ..Oo o..  . . o  +  . X .  .X  o  X. X+ X.    ..X   O.o X.o   .OOo...OoOo.. ..     X+    OX  .. X .. . .. . + +. ",
" .XO.o Oo ..   Oo+ . .  .. ..   ..... .ooX . o .  +o ...o..  o.X.....  +..+.o    . ...  X +. .  .  X. ...  .o....O.O .   OoO oXX.. .+.   o  XOo ...+      ++     .  ",
" . O. ...o. ..X.. .o. ..   o . . o + ... o O ..  ... Ooo...XX.   .  oX   + .Ooo     . Xo X.. .O..  .  . o..o.. ..   .. o..o.o  XO    .  . ..Xo.+... +. X .   +...X+ ",
"X  o  .o oO.OXX.. X...... .     .X   + o..o. .O Oo. ..o.Oo X   . ..    X.  o. oO.  X.X O. . o  ... ..   .Ooo.  ... ...O  . O..XO    X+. oo+.+ XXO . X.+X ..  +O .   ",
".o..ooo.oo.o..+  . .. . Oo    . . +.  ..o .. . .O .. .oO..o . o   +o..  +o......oX   ..   Oo.  O.+o. .O      o.   ..o  OoO OO +  X. o   .....   .+ O   +  XX... +++.",
"X..  ...OOoooOo o ..o.o.o.Xo.  .X X    oXO  oo.o O..O.O.. o. . o . O  o O.O..O OoXXo X . .o  .   O. ..  O .     .  ..Oo.O .  O ..  .OO .  O. .X   . .XX.  . .. ..o. ",
".o... oo+OOoOoO... .oo...o .. . X .X .. .o.O..o..o..o. .oo.+ .o ..   .X ...OO.ooo .   X. ..oo. ...o.. ...  .XXX  ..O..o. ..... O.. ..+. O... + X.  .X      ... .   X",
" ..X. .....oOoo.OO..+OO.   o.. XX   X+ O. o.oo...... oXO..  +X .oX  .X. O  ooOoO.  X ....o.Oo... Oo.o  . .O .X X .O.o ..o. XX .. . ...X  O ...X  + .   X.oX. O .oX  ",
".     . .oooo..Oo.  ..OoX oX.X XXXX X.   ...o...+  .O. o.O     ....  o . .o.o..oXoX.  o .O..O. .. .   . .X    XX   .o.  .o .o... O  o     .o ..   O.X+ .XO  X+.O..XO",
".  .X.. o ..ooo.oo. o .Oo..    +XXX.X      ..   .o. .oo X.. X.o.. O..O.. ......o. .. . o ..O     .. o.X. o+ XXX    o     O.X+O.XO. .. O  X. .o.  O. . .  OoX...o. X.",
".    ... O.o.. .o.o.   OO  .  .X X+  .   ....o O. oo . ..+...   .  OO....O.... +O. oO.  ... ..+ . .   OX . .X+ XX..o. . X.. .X.X+.   . X. X.. + O X+   X....+.o+.  .",
"  . .. .o.o..OoOooo...o.... .oX XX  ...O X . +XXX.  . O + Oo   .O.  ..oo  . .    . . .o.O +O.X   .   ..X .  .   XOO. . ... X+o    +  ..   O ..X..   .O.O Oo .. . ..X",
" O.o.+..OoooO .Oooo.o .O .o X ... + .o O . .OoX   ...  o X. . ....  O . o. . .. .O. . ...o. O .. .  ...X  OO .X   ..X   +. X oo  .X.X. .o .X..  O..oO..O  ...O .o   ",
". O . .oo  .O.o.O.o... . o+XX       .o...   ...X .... o X. .   ...  ...  o..o    .  ..ooOo.. . ..  o    .X...     O.. X   .  ..    XX  X O  ..O..oo..O. O....  Oo. .",
".o    ....o.o..O.Ooo o.o... . X.XX....    o....X.  O.. +... + . O  .o .. . .O ..    .OOoo  .. X+  X O X  o Oo. . .o. .    .X.   .      X. +.  o..o  o .  o..  O ....",
".o .o   . O...oO.  . ..o... .+.XXX . ...+X+o.. .. ..O.  X. .     . ...+ .O  ..XX ...o..Ooo  o . . .  ... .+ .  ..++o . O ...+ .. . .o  .. X  oo.Oo .. X  O.  .+X.  O",
"o. o. O o .o   .  . .. .o .   . X.   ..oXX+  O  .oOoOoO..+ .. .O.. . ..  XO.  o .... o.ooo  O.+ .o   .+.o+ .O..  X  .   +o   .o..o.Oo     . .o..Ooo. ..  ...  X.+  +",
" .....  . O. OX..o.o. ... .  ..o.   . .+   Xoo  ..o.o.O..  .... ..o .o  oXOoo  .O.oo..OOo..o . .o .X.....o Ooo...  ...    OooO   ..   XooO  . ooo.  . .... ...... ..",
"   . o .  X   o .O o...O.... .o..   . XXX..X..  o.OoOOoo..o O......  Xo..X.o oX O..   ooOoo o.    +X+   ..ooOO.. O.....o   ... O  oX.  ..  . .O..o o  +...o. .o.O o ",
"   .        . . . . . .  ..  ..o   +. X   ..O+. . OO..o.o... ..o.... . ....O  o.. O. .+oOoo.oo.. .     . . o.o..ooo.... .o....XX  +. .X oOo ...Oo..OO...  ... OO..O ",
" .  .  ..   o  O.+  .X .o.. o O..     . .  ... o O .o. .oo.ooO.OOoo    Oo.o.O. ..O. oo.ooo.oOo.. . +   . .OoO..o.oo .  .O ooO....  ..OX...... ..   o  ooX O....  ...",
"X.. ..o  . OoOo. .. . .X. ....o .... X   o. ..O..  .. ..  +..o...O..o oo o.O o..+ .. oOoOOo. o.O.   o .X.O O  o. .o...  . OoX        ....O. O..   .XO OO +o..o. OX..",
" ..o... ..O..oOo .  .oX ..  o.o. O   .. .. ..oO. .     o o oo.o     .o.o..o  .. .....oo Ooo. Ooo.  o o.XX.. .o  +.o .. .  ..  .  . .o .O.  oOo  Xo..+o .  .. .. X  .",
".Ooo.o.o oo o . .ooO.  .......  .. ..o  ..ooO  oo. .  .X..oX.O....   .o.. .o......o .. +.OO.oX..O  . . X   .X .+... ...   O ..O  .  . +.o.. .o .  XO   oOX+...XXOo..",
"...o.o .XO. . .. ..o.+. O.O . O.. +oOo..oo O ..o   .  . ..o .Oo  .  o .o.O.Xo.. .o    oooOo  O+Oo...X+.X     oX+...  . X   . + .   .  .o..  .o. .     .. ..   X +  .",
" . .o  .   O...  .... . .Ooo...... o.o  o..X.. O.X O.XO. .  . ..o ....o.O.O  o .oXO   O .o..o ... . . X    .+X. .o... ... .  X X  XO ooOoo ..  o  + . . oO  ..  .   ",
"O    O . X  o. X  o.....O. .o. +O .. .  oO ..  .  ..Oo  ...o o.o.Oo. .ooo. o .Oo .  .o .O.o o....o.  X    . ...XO.. .  ..   +.. .+. . oO.. . .     .    .. .o O...X.",
".  .X.  .  .. o  X O. .+oOXO. .  ..o  +.+.+oO+oo   oo..o+.o O. ..  oOo OoOo.. O.o.. .+ . +O . ...O o.  o  O . .X .   ..... X X.o ... oO.o.X..O.....  . .. .OO .  .Xo",
"   . o.X.    .O XX. .o   o. .oo ..oo.   XXo.  .ooo. o . o.Ooo o..  ..+..... . . o..+X  .. .  ..  o.X .  X X+..X X. . o .  .   OOo+o XOo Ooo . o.o   o.   . .  . ..  ",
"...  Oo     + +Oo X+ +Ooo X.o    ...o X o . . .O..  oOOoooo .O .o.OOO .o  o . ..+.X ... ..oX+ . .+..O  O.   .o.O... o. .X . . oX  Oo......   O. X. ...X   O .. . +.o",
". O .   o O. . .o   XXO.o. .o .  +oo... .....oo.oo .Ooo....o...o .......  oX+ O   .O. oX+..  . .O ...o.OO. .. o...o. .O X .  o. . . . X ..  +O. .. .   . .  oo. . +o",
" +o..  .   . X.  X   X..o ....    ..o.....o....O.    o . ..O  Oo .oO . .. .  ..   . .o  +      .    oo .. X..o ....o.. .  .  ...o ...    . .   . o.. .  X.. o.. +.. ",
" X  o. ...O..    X.X .o    . .   ...o  O.o ..oo ..XO.O.  ..  o....o ...  . O. o    o. X. ..   o . o   .o.oo.o. o.+ .oO.    .. .. O.o ..   .X  ... . .  X+  Xo XO.   ",
"  X ..  O.o.o.X   X. ..X   o. X +o ...o o .Ooo..o X.O .. oo ...o..  o  . ..   . o+O oXOX.. oX    o..  .. OoOoO O.+. .. ... XX.o.. o .... .X .+. o....     X..+o  .  ",
" X . .  ..ooO     X. O. X...    X.oo .ooo. ..oOO ...... .o. ......oO . O. .  .Oo o  . o X      . ..XOo .o.O. oo.X     .. ..XX..  oo +.. +. .o  O   O..XX   XX . X.o.",
". X X. .oo .o.    o o.. X .Xo . . Ooo .   ...o.o..O  .. . O   .O..o..Oo +.  O.... .... o.  . ..   oX+.  ...XOoO    o .Oo.. Ooo.o... .   o  O. .  +oX   . X   X  Xo O",
" X.  ..OoO ..      .O.X+.O.  .  ....O. O Ooo.Oo+. .. .  ... X .oo O o.  . o..o  .   .. .X+. ...      .  . X Oo...o... .o. O ++oo. .. O... X    +.X  . .   ..X+o XX. ",
" o .... .o   o   . . ..o.X .    .o. .. o..  .oX... O...X.. . o..Xo .. .  O.  . O. ...O .O. +o  .XX o . .+. O.O.  oo ..o.O .    .. O X.Ooo. +    + X .X X X. .X..  X ",
" .  ..  .... .o.X .. ....  . .  O . .    .. o  .  O . . X.  X O..Oo XOX..+        .  .  . . .. X. . . . . . oo.o o..oo ..ooo  .  O.. .      . oXXX . X.X..  .O.o . .",
"X+XO  O.      X  +o. .X .  Oo...Oo.. o+   oOO oo o  o.. O......+  . . X.   .o + .   ...  X  . .  ..  . Oo.oo..O o . ..o. .X...  ...     X+ +.o ..+.X  .o+ ...  .o...",
"X. X  .     .X.o     .XX  .oO O. . . .X  .  Oo.oO .O O...O... X. . o. X   o O  .ooX O.X    +O +. .+O....o oo .o.  .  oOOOoooO.o. O.. . X.X+  . .X.X  ... .X.   .+o  ",
" .  X..ooOo X. O   .    .   .. .o. . X  o.Xo OOOo..  O . + .Oo..O.   .o.   X.oX...o   O  XO . +O  X.  o. .   oo.O. oO ..o.O. OOoO .  .  o   X  .. .X. .oo . X +oo  .",
"..oo. o   X .. . . ..  X+  . . . O+   ...   OoooooOO X+O...  ...  . + ...   XX.  oO.o. OX   .      .. .O.  o+o  +.O  ..O .Oo.o.OooOo+. X. o.  ..X . .....+. +.o O  X",
".o.. .. X X   o.   .    . +. o  ..Xo..   . ooo.oOoOoo.. . ..X..  . o.  .     o O ...   .oo  ..o.oX    . . .  .O..  .      o..  .o.oOOOo   + . .X   X   ..  o  .  . .",
"   X    X   ....o. .  .. o Xo oO X...   ..ooOOoo.ooo...O .... o .. O.. .  .+. . o . .  ... .. oo+.   .  . Oo..X. ...   .  O .o.o  ..Ooo  .+ .   +.X++ .o +. O.  Xoo+",
" .. . .o o.. .  oO..  oo. . ... o  .o  .oo. oO..o..OO Oo oX ..   .o .   o. o .    .. . O O. . O... +.. . . ...X.o .  OXXX. + . .oX..oo.Ooo .. . XX @. .  X .   . .. ",
" o..O  .      O . ......o  oo.o .  .o .OO. OO ....o.o..oO .. . X O. .o.....o .. . .  .   . .o ...X. ....X  . ..          ..  ..O   O.ooo.Oo..o .  XX+.o. .XO XoO.. +",
" .  . . .. . ... o ... ...o  ..  .oo  Xo ..OooO.. ..o..X.oO  . oX .O.XO..  .oo.oO. . ..+.O.o.    . .oo. o.   ...o. .X .+oXX+O ... O..o ..o.Oo#oX         .   o.O.   ",
"  O +o. O.    . .o  .. O     . Xo Oo  ... o o.o.... .... Oo   .    X    o..Oo .oo  .  ..o.+.o. .. ..Oo  .....+.O  .+o  X.X . ..O .  .o  .   OOoo   .  X.  . O OOooX ",
"X+..   . ..    . ..  .O.. .. .. .oX.   o  ooO. oo..ooo. o.o XO .. .X .o.oO ... ..X..o .o.. ooX+..o.o . + .O. o  ..  .XX .  O  O.  . .. +.X. oOOo.X X X.+. oo O.ooO O",
"   X  . ..o.  .    .O. O    .o.. o...X. .O..... .o....ooXO. o o .  X. .O.+.o. . .. .o    o.o . O.o. X..   ..+   .... X X +O  . .....o XoX. . .oOoO .oo O Oo.oO o.oO.",
"  .. .... .     .  .o..  + ..  o....o ...oo. oO.o.X.O.   X o .  o   .. ...  .Oo.....Oo .......O+OO X .. .o  .XX .X.X+XX+++.. O  ......O.++.      .OOo...o....... ooX",
". . o.      .o .  . O.o .. O..+O.... .O Oo.. ...o. O..  X .   .  ..X  . .. o   o ..  .. . o..  . .  .. .o o  XXO..X.XX+XX.. o O.o o O .X o. Xo.  ..o.X ..   .  o....",
" ...       .o.  XO.O .. .o.X X...  o. oOo .oo      ..o  .  . . o  ..   ...O O  o . ..o   o OooX.X...  . .O XoX+ .   XX.    .  o  o...  .o+ .... .X  X + X . .X.  X. ",
"o o    X .ooo..    oO  O.  .. .O. o .. . .o  .. .  .. ..   X XOoo. oX o.o..o  . .. ... ...  ..o ..o   . +oO .   +... X XXoX   .....    .O oX             .   XX   X ",
"  o .oO . ..o O  .Xoo    .   ..oo ..o o ..o....... . o ..  o ....O   o.o.oO . ..o    .. oX..o....X. X. o  .O.X..   oX  +.  +  ..o      . .. .   oX.    XX o   X +.  ",
"...X o ..o..  ...O o.    .  .... Xo ..    o..o     o .o.o..o o.o.o   oo. +.o  O X +. ..OoXo .O..  . X......  .+ . +    ..  XX Oo.....O.O  X ... o    X   X XXX  . X.",
"o   .... O....O.. .O. .O  o oo.Oo.. ....  o..o.... O.  +  ..o+..O.+. O.  .O.oO     oo.o.....O . .X  ..  .O ..o  ...  . . .X X. .o.oo .o   +. . .   X X.  X+  XX  .  ",
". ... .oo . ..O.o O .O   .OOO. ...O.o o. .O.. ....oo o. ..OO .OoO... ..o. + .. ...o. ooo.. Oo.oO. ...o ..O o.O .o.O..X  o    ...o.  +o.o   X   ...XX X Xo o    XO.X ",
"..XO  ... ....O......oO.. ..o. Ooo o...O..o....... oo.XX+   O...o..o.. . .. .... O.  Oo    ..o   O . O  O .Oo+ oo..  . oXX... .O..X. o.      O O XXXX+ XXXX.  .. .o ",
"o X  . O..o...o..O  Xoo..    o.. .oo...o oOo..O.  +....  ..oooo   o.. ..OoXo. o..o..  o.XX .. X .. O Xo  ..+.. ..  O..   .  ......o     o.  . +oX X  .X.X  ... .+. X",
"O.X..  X. .   . .o   oo..O  ..O. .Oo.   . Xoo +.  .oo  .  ...O o o.ooo.. .X..o..Oo.o .+.  . ..   ..      . ....X.   o . O . OXXOo.  oX++. . +X  . O XX.  . + .   .  ",
"  . O  ooo   .  ..  . .....X .   ooo..     O .   ..o O. X.Oo....oo ..o.oO   ooo.Oo....   .+      .o..  o .O . .  +.oo... X. o..O X.. X.XO .X    .   X  Xo   . ...   ",
"X ...o .ooo X.X  . .   .  ..  o O .o..+. o.o. ......o OXoo.....o..X o  Oo o ooooo...oOo  .   . X.+oo .OO   .  . .  .. .  oo.. O. XX  .+ oX X++. .XXXX  oO .  +o.X o ",
".o.o.. o  o .  X.o   .     .o...XO . .     .  X.  oo . +...o.. O  o .o o..ooo.o. o .   ... O .  +Oo.oo ..    .. ..   o  oO....o .o   .X . X X X..XX  + .X..O . + +. ",
" ...O.. .o o +.  .o  . .... o . ..  ..o.X+  Xo.. X.. O ...   oX... . ..  . . ..o. O oo . . Xo O.o .Oo.O     ... .+o ....    o ..X X.O  X.. . ..     XX XOX        X+",
"..o....          O .X .O.  O.oX.     .    . .. X   ..O.oo   ..  +.  O  oo  .  O.Xo .o.  . . O .   .O+. +  ... .  +.o..o. . .. ..  O. X ...X+X   X.XX . o   .+. X+   ",
"oO.O..  o. O X  O . X .  . .o.X   .. .  X.    .o.  O.X..o..o... .... .....oX o..   . ...O. o .... O. o XO X+o X   .....  .OX.  . +.O.o .  XXX     . O.X  XX  +.XXX +",
"o.  o.. .     X   ..O+.    .. XX..  .     ..  .o. .o   ......ooo...... X . . o . .  ......oO .   . o...  .o. +    +. .. .+.. . +  .ooOo.   o..X.X  o  XXX..  X XX  X",
".+oo  +  ..    +... . +.X... XX ..   +o   .. .    O.. . o ....o  o. . oXO  o ..+.   .  o...+o..    .   .. X  X.  X..       .  XX .oOooOo.X . .  . .   .  X XO  XX++ ",
"o..O    .....     .+.   ..oX  .X...    o   X  .X  .   O....+... oo o.   . . o.  X. ..   .o ..o o...        . . .  ++.X.+ ..X XX  .o....O  .O..X  O   ..XX ..  XXXX. ",
"o o X..   . oX  .    ..  OX.....o. X . . +oo        .  . OXO...+... .o  X  . X. . .   XO+O. .oo   o  X.   OX+ . ....... o o+. + X.+O.  . .O oOo. o.X .XX@.XXXXXXXX X",
"oo   .  ..  X ..o   .  X X...O oO    .. X .    . .. +o  X XOo..X oo .XX XXoOX ++... .      ..O.....XX.X....XX.  o.    .+  .  XX .X.    .X.+ Ooo    X. XX  XXXXXXXX+ ",
"O. Xo..   .+  .   .  .   X  Oo.O..     . +   XX X..o. o    +o.  .o. .X XX . . XX.. ..  X+.+  ..O.O    .+ .   .  . . .. ..o   .  Xo     .    . .  .   .  .XXXXXXXXXX.",
"o   o .  .XX   o   o.O .  . .   o  .X        X X.  .... oo. O. .. + .  .X  X  oX X .OX.XX. . . o .X XoX.. .   X. ...o.  +  . oO.X X  X .. X  +..   .. .X.. X X XXXX ",
".  ..Oo..o .+. .  ....  + oO.oo.     . . X.X X X   O .  +   X ...  X XXX .o   . X X. o  ...O. .  .. X X .   .o. O.  O. . ..+Oo..  X  XXoO..X+    . ..  X .XX XX. XX+",
" ..o .   . o  .o   .. ..   o.o.o .+.    .+.     ..  .    . . .X.oXX     ....XO  . XX.. .  ....  ... o X ...    . .X O O....o oo.O    X+. O O.+ X.  o+.   XXXXXXX  . ",
"   . +..  .oXo.....O.o.   ...o.. . X.  XX ooX .X   .o ..o..X    .XX.XX   .OOoX.XX.  X  X      . + O. XX o . .  .+. +.. ... . . oo.+X  X.O   .X.   .X..o  .XXXXXX+.XX",
" O.o X .    ..o..o.oo..  O. .o    XX+ X  o  XX    X+.   .++XX  Xo XX XX ..... . .     . .o..X. XX X    +.O.O   . +.  .. o.X. oO. .X.  . .o . X.X .X  ..   . XX.  .  ",
"   ..  .. .ooo....o .  oo .o  + X .XX.X+..   +  X  X  X .     X...o XX  . X .o..X.  X.  .   ..X  .    XX+ . ..O.X O ..  ..o o.o.  + .     .OO  .  . +.. .X  X XX    "};
