/* XPM */
/* $XConsortium: DtABcnt.pm /main/3 1995/07/18 17:08:32 drk $ */
static char * DtABcnt_x_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 32 10 1 0 0",
/* colors */
"     s iconGray4     m white c #949494949494",
".    s iconGray8     m black c #212121212121",
"X    s iconGray5     m black c #737373737373",
"o    s iconGray1     m white c #dededededede",
"O	s iconColor2	m white	c white",
"+	s iconColor1	m black	c black",
"@    s iconGray2     m white c #bdbdbdbdbdbd",
"#    s iconGray4     m white c #949494949494",
"$    s iconGray3     m white c #adadadadadad",
"%    s iconGray6     m black c #636363636363",
/* pixels */
"                                                ",
"                                                ",
"   ..........                                   ",
"   .XXXXXXXXoOO     ...                         ",
"   .XOXXXXXXOO+      .                          ",
"   .OOOXXXXOO+       .      .  .                ",
"   OOOOOXXOO+        . . .  .                   ",
"   .OOOOOOO+@        . .  . .  . .............  ",
"   .XOOOOO+X@                                   ",
"   .XXOOO+XX@                                   ",
"   .XXXO+XXX@                                   ",
"   .@@@@@@@@@                                   ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"  ............................................  ",
"  .############@@@@@@@@@@@@@#################@  ",
"  .############@$$$$ %@$$$$%#################@  ",
"  .############@$$$$ %@$$$$%#################@  ",
"  .############@$$$$ %@$$$$%#################@  ",
"  .############@%%%%%%%%%%%%#################@  ",
"  .@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  ",
"                                                ",
"                                                "};
