/* XPM */
/* $XConsortium: Dtadskt.m.pm /main/3 1995/07/18 16:26:59 drk $ */
static char * Dtadskt_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 14 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X	s iconColor1	m black	c black",
"o    s iconGray5     m black c #737373737373",
"O	s iconColor5	m black	c blue",
"+    s iconGray4     m white c #949494949494",
"@    s iconGray1     m white c #dededededede",
"#    s iconGray8     m black c #212121212121",
"$	s iconColor3	m black	c red",
"%    s iconGray7     m black c #424242424242",
"&    s iconGray6     m black c #636363636363",
"*	s iconColor6	m white	c yellow",
"=    s iconGray2     m white c #bdbdbdbdbdbd",
"-    s iconGray4     m white c #949494949494",
/* pixels */
" .............................X ",
" .oOoOoOoOoOoOoOoOoOoOoOoOoOoOX ",
" .OoOoOoOoOoOoOoOoOoOoOoOoOoOoX ",
"......oOoOoOoOoOoOoOoOoOo......X",
".+++++.oOoOoOoOoOoOoOoOo.++++++X",
".++++++.oOoOoOoOoOoOoOo.+++++++X",
".+++++++...............++++++++X",
".++++++++++++++++++++++++++++++X",
".++++++++++++++++++++++++++++++X",
".++++++.............+++++++@+++X",
".+++++.ooooooooooooo#+++++@$@++X",
".+++++.o%%%%%%%%%%%o#&+++*$$$@+X",
".+++++.o%+++++++++@o#&++**&$#++X",
".+++++.o#.+...+...+o#&+**@=#+++X",
".+++++.ooooooooooooo#o***=#--++X",
".+++++.ooooooooooooo#**@=#--+++X",
".+++++.o..#o..#o..#o***=#--++++X",
".+++++.o###o###o##o**@=#--+++++X",
".+++++.ooooooooooo***=#--++++++X",
".+++++.o..#o..#oo**@=#--+++++++X",
".+++++.o###o###o***=#&-++++++++X",
".+++++.oooooooo**@=#&&+++++++++X",
".+++++.o..#o.&***=#&#&+++++++++X",
".+++++.o###o%**@=#&o#&+++++++++X",
".+++++.ooooo***=#&oo#&+++++++++X",
".+++++.o..%**@=#&.#o#&+++++++++X",
".+++++.o#%#%*=#&###o#&+++++++++X",
".+++++.oo#..-#&ooooo#&+++++++++X",
".++++++##..##&######&-+++++++++X",
".+++++++###&&&&&&&&&-++++++++++X",
".++++++++++++++++++++++++++++++X",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"};
