/* XPM */
/*********************************************************************
*  (c) Copyright 1999 Sun Microsystems, Inc.
**********************************************************************/
static char * Bkdrp_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 7 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray6	m black	c #636363636363",
"X	s iconGray1	m white	c #dededededede",
"o	s iconGray2	m white	c #bdbdbdbdbdbd",
"O	s iconGray3	m white	c #adadadadadad",
"+	s iconGray8	m black	c #212121212121",
"@	s iconGray5	m black	c #737373737373",
/* pixels */
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"................................................",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo",
".XOOOOOOOOOOOOOOOOOOOOOOO+@@@XXXOOOO+++@@@@XXX+o",
".XXXXXXXXXXXXXXXXXXXXXOOO+@@XXXOOOO+++@@@@XXXO+o",
".XOOOOOOOOOOOOOOOOOOO+OOO+@XXXOOOO+++@@@@XXXOO+o",
".XOOOOOOOOOOOOOOOOOOO+OOO+XXXOOOO+++@@@@XXXOOO+o",
".XOOOOOOOOOOOOOOOOOOO+OOO+XXOOOO+++@@@@XXXOOOO+o",
".XXXXXXXXXXXXXXXXXOOO+OOO+XOOOO+++@@@@XXXOOOO++o",
".XOOOOOOOOOOOOOOO+OOO+OOO+OOOO+++@@@@XXXOOOO+++o",
".XOOOOOOOOOOOOOOO+OOO+OOO+OOO+++@@@@XXXOOOO++++o",
".XOOOOOOOOOOOOOOO+OOO+OOO+OO+++@@@@XXXOOOO+++@+o",
".XXXXXXXXXXXXXOOO+OOO+OOO+O+++@@@@XXXOOOO+++@@+o",
".XOOOOOOOOOOO+OOO+OOO+OOO++++@@@@XXXOOOO+++@@@+o",
".XOOOOOOOOOOO+OOO+OOO+OOO+++@@@@XXXOOOO+++@@@@+o",
".XOOOOOOOOOOO+OOO+OOO+OOO++@@@@XXXOOOO+++@@@@X+o",
".XXXXXXXXXOOO+OOO+OOO+OOO+@@@@XXXOOOO+++@@@@XX+o",
".XOOOOOOO+OOO+OOO+OOO+OOO+@@@XXXOOOO+++@@@@XXX+o",
".XOOOOOOO+OOO+OOO+OOO+OOO+@@XXXOOOO+++@@@@XXXO+o",
".X+++++++++++++++++++++++++++++++++++++++++++++o",
".XOOOOOOOOOOOOOOOOOOOOOOO+XXX+++XXX+++XXX+++XX+o",
".XXXXXXXOOXXXXXXOOXXXXXXO+OXOO+OOXOO+OOXOO+OOX+o",
".XX+++++OOX+++++OOX+++++O+XXX+++XXX+++XXX+++XX+o",
".XX+OOOOOOX+OOOOOOX+OOOOO+OXOO+OOXOO+OOXOO+OOX+o",
".XX+OOOOOOX+OOOOOOX+OOOOO+XXX+++XXX+++XXX+++XX+o",
".XX+OOOOOOX+OOOOOOX+OOOOO+OXOO+OOXOO+OOXOO+OOX+o",
".XX+OOOOOOX+OOOOOOX+OOOOO+XXX+++XXX+++XXX+++XX+o",
".XOOOOOOOOOOOOOOOOOOOOOOO+OXOO+OOXOO+OOXOO+OOX+o",
".XOOOOOOOOOOOOOOOOOOOOOOO+XXX+++XXX+++XXX+++XX+o",
".XXXXXXXOOXXXXXXOOXXXXXXO+OXOO+OOXOO+OOXOO+OOX+o",
".XX+++++OOX+++++OOX+++++O+XXX+++XXX+++XXX+++XX+o",
".XX+OOOOOOX+OOOOOOX+OOOOO+OXOO+OOXOO+OOXOO+OOX+o",
".XX+OOOOOOX+OOOOOOX+OOOOO+XXX+++XXX+++XXX+++XX+o",
".XX+OOOOOOX+OOOOOOX+OOOOO+OXOO+OOXOO+OOXOO+OOX+o",
".XX+OOOOOOX+OOOOOOX+OOOOO+XXX+++XXX+++XXX+++XX+o",
".XOOOOOOOOOOOOOOOOOOOOOOO+OXOO+OOXOO+OOXOO+OOX+o",
".X+++++++++++++++++++++++++++++++++++++++++++++o",
".ooooooooooooooooooooooooooooooooooooooooooooooo"};
