/* XPM */
/* $XConsortium: DtBldr.l.pm /main/3 1995/07/18 16:17:30 drk $ */
static char * DtBldr_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 13 1 0 0",
/* colors */
" 	s none	m none	c none",
".    s bottomShadowColor m black c #636363636363",
"X    s iconGray1     m white c #dededededede",
"o    s topShadowColor m white c #bdbdbdbdbdbd",
"O    s iconGray4     m white c #949494949494",
"+    s iconGray5     m black c #737373737373",
"@    s iconGray6     m black c #636363636363",
"#	s iconColor4	m white	c green",
"$    s iconGray3     m white c #adadadadadad",
"%	s iconColor2	m white	c white",
"&    s iconGray2     m white c #bdbdbdbdbdbd",
"*    s iconGray7     m black c #424242424242",
"=    s iconGray8     m black c #212121212121",
/* pixels */
" ............................................   ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo   ",
" .XOOOOOOOOOOO+XOOOOOOOOOOOOOOOOOOOOOOOOOOOOo   ",
" .XOXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo   ",
" .XOXOOOOOOOOO@XOOOOOOOOOOOOOOOOOOOOOOOOOOOOo   ",
" .XOXOOOOOOOOO@XOOOOOOOOOOOOOOOOOOOOOOOOOOOOo   ",
" .XOXOOOOOOOOO@#OO$$@OO%%%%%&&OO%%@OOOOOOOOOo   ",
" .XOXOXXXXXXXO@##$%%X@@%%%%XX+@O%X@OOOOOOOOOo   ",
" .XOXOX$$$$$@O@##&%XX@@%%XXXX+@@%X@OOOOOOOOOo   ",
" .XOXOX@@@@@@O@##*XX@@@%%XXX$+@@&&@OOOOOOOOOo   ",
" .XOXOOOOOOOOO@#%#@@@O@%$$$$$+@+&$@OOOOOOOOOo   ",
" .XOXOOOOOOOOO@##%#%#OO@@@@@@@++@@@OOOOOOOOOo   ",
" .X+X@@@@@@@@@@#%#%#%#@@&&+*+@@@@@@@@@@@@@@@o   ",
" .XXX&&&&&&&&&&##%#%#%#&&&O*+*OO&&&&&&&&&&&&o   ",
" .XOX&+++++++++#%#%#%#%#&X&*+*@+++++++++++++o   ",
" .XOX&+++++++++##%#%#%#%&XX*+*@+++++++++++++o   ",
" .XOX&+++++++++#%#%#%#%#&X%*O*@+++++++++++++o   ",
" .XOX&+++++++++##%#%#%#%&X%*O*@+++++++++++++o   ",
" .XOX&+++++++++#%#%###%#&X%*O@@+++++++++++++o   ",
" .XOX&+++++++++##%#%#+#%&X%*O@@+++++++++++++o   ",
" .XOX&+++++++++#%#%##+O#&X%*O@@+++++++++++++o   ",
" .XOX&+++++++++##%#%#+OO&X%*O#@+++++++++++++o   ",
" .XOX&+++++++++#%#%##+OO&X%*OO#@++++++++++++o   ",
" .XOX&+++++++++##%#%#+OO@@@**#O#@+++++++++++o   ",
" .XOX&@@@@@@@@@#%#%##@@@@@@***#+#@@@@@@@@@@@o   ",
" .XOX@@@@@@@@@@##%#%#@@@O++**=O#%#@@@@@@@@@@o   ",
" .XOX&&&&&&&&&&#%#%##O&@++***=#+#%#@&&&&&&&&o   ",
" .XOX$$$$$$$$$$##%#%#O$@O++*+=+#%#%#@$$$$$$$o   ",
" .XOX$$$$$$$$$$#%#%##O$@++***=++#%#%#@$$$$$$o   ",
" .XOX$$$$$$$$$$##%#%#O$@O++*+=++##%#%#@$$$$$o   ",
" .XOX$$$$$$$$$$#%#%##O$@++***=++$##%#%#@$$$$o   ",
" .XOX$$++++++++##%#%#++@O++*+=**++##%#%#@+++o   ",
" .XOX$$+$O$O$O$#%#%##+O@++***=+O$O$##%#%#@O$o   ",
" .XOX$$+O$O$O$O##%#%#+$@O++*+=++O$OO##%#%#@Oo   ",
" .XOX$$+$O$O$O$#%#%###X@++***=+#X#XX###%#%#@o   ",
" .XOX$$+O$O$O$O##%#%#%#@O++*+=#+#%##%#%#%#%#o   ",
" .XOX$$+$O$O$O$#%#%#%#%@++***=+#%#%%#%#%#%#%#   ",
" .XOX$$+O$O$O$O##%#%#%#@O++*+=#+#%##%#%#%#%#%#  ",
" .XOX$$+$O$O$O$########@++***=################# ",
" .XOX$$+O$O$O$O$+++++++@O++*+=++++++++++++++o.  ",
" .XOX$$+$O$O$O$O$O$O$O$@++***=+O$O$$O$O$O$O$o.. ",
" .XOX$$+O$O$O$O$O$O$O$O@O++*+=O+O$OO$O$O$O$Oo   ",
" .ooooooooooooooooooooo@++***=ooooooooooooooo   ",
"                       @O++*+=..                ",
"                       @++***=.                 ",
"                       @======..                ",
"                        .......                 ",
"                         . . . .                "};
