/* XPM */
/* $XConsortium: DtBldr.m.pm /main/3 1995/07/18 16:17:39 drk $ */
static char * DtBldr_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 13 1 0 0",
/* colors */
" 	s none	m none	c none",
".    s iconGray1     m white c #dededededede",
"X    s iconGray2     m white c #bdbdbdbdbdbd",
"o    s iconGray4     m white c #949494949494",
"O    s iconGray7     m black c #424242424242",
"+    s iconGray3     m white c #adadadadadad",
"@	s iconColor2	m white	c white",
"#    s iconGray6     m black c #636363636363",
"$    s bottomShadowColor m black c #636363636363",
"%    s iconGray8     m black c #212121212121",
"&    s iconGray5     m black c #737373737373",
"*	s iconColor4	m white	c green",
"=	s iconColor1	m black	c black",
/* pixels */
"                                ",
"  .........X.................   ",
"  .ooooooooOX++oo@@@Xoo@#oooo$  ",
"  .ooooooooOX@@##@@..#o.%oooo$  ",
"  .o.....#oOX..##@..+##X%&ooo$  ",
"  .o.#####*Oo##o#+++#%%+%&ooo$  ",
"  .ooooooo.*#o#oo####&&%%&ooo$  ",
"  .OOOOOOO*.*#OOOX@#OOOOOOOOO$  ",
"  .XXXXXXX.*.*#XXX@#oXXXXXXXX$  ",
"  .&&&&&&&*.*.*#&X@##&&&&&&&&$  ",
"  .&&&&&&&.*.*.*#X@##&&&&&&&&$  ",
"  .&&&&&&&*.*.*.*X@##&&&&&&&&$  ",
"  .&&&&&&&.*.&.*.X@##&&&&&&&&$  ",
"  .&&&&&&&*.*&&.*X@##&&&&&&&&$  ",
"  .&&&&&&&.*.&&&&###=&&&&&&&&$  ",
"  .#######*.*###&&O==########$  ",
"  .XXXXXXX.*.oXX&&&==*#&XXXXX$  ",
"  .+++++++*.*o++&&O==+*#+++++$  ",
"  .+++++++.*.o++&&&==*+*#++++$  ",
"  .+++++++*.*o++&&O==+*.*#+++$  ",
"  .+++++++.*.o++&&&==o+*.*#++$  ",
"  .++&&&&&*.*&&&&&O==OO.*.*#&$  ",
"  .++&o+o+.*.o+o&&&==oo+.*.*#$  ",
"  .++&+o+o*.*.*.&&O==+*.*.*.*$  ",
"  .++&o+o+.*.*.*&&&==X+*.*.*.*  ",
"  .++&+o+o*.*.*.&&O==+*.*.*.*.* ",
"  .++&o+o+o&&&&&&&&==&&&&&&&&$$ ",
"  .++&+o+o+o&&&&&&O==&&&&&&&&$$$",
"  .++&o+o+o+o+o+&&&==&oo+oo+o$  ",
"   $$$$$$$$$$$$$&&O==$$$$$$$$$  ",
"                =====$$         ",
"                  $$$$$         "};
