/* XPM */
/* $XConsortium: DtBldrA.pm /main/3 1995/07/18 16:17:54 drk $ */
/*********************************************************************
*  (c) Copyright 1993, 1994 Hewlett-Packard Company	
*  (c) Copyright 1993, 1994 International Business Machines Corp.
*  (c) Copyright 1993, 1994 Sun Microsystems, Inc.
*  (c) Copyright 1993, 1994 Unix System Labs, Inc., a subsidiary of
*      Novell, Inc.
**********************************************************************/
static char * DtBldrA_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"98 98 11 1 0 0",
/* colors */
"     s background    m black c #949494949494",
".    s iconGray1     m white c #dededededede",
"X    s iconGray4     m white c #949494949494",
"o    s iconGray5     m black c #737373737373",
"O    s iconGray6     m black c #636363636363",
"+	s iconColor2	m white	c white",
"@    s iconGray3     m white c #adadadadadad",
"#    s iconGray2     m white c #bdbdbdbdbdbd",
"$	s iconColor4	m white	c green",
"%	s iconColor1	m black	c black",
"&    s iconGray7     m black c #424242424242",
/* pixels */
"                                                                                                  ",
"                                                                                                  ",
"                                                                                                  ",
"   .....................................................................................          ",
"   .....................................................................................          ",
"   ..XXXXXXXXXXXXXXXXXXXXXXoo..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX          ",
"   ..XXXXXXXXXXXXXXXXXXXXXXoo..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX          ",
"   ..XX.................................................................................          ",
"   ..XX.................................................................................          ",
"   ..XX..XXXXXXXXXXXXXXXXXXOO..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX          ",
"   ..XX..XXXXXXXXXXXXXXXXXXOO..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX          ",
"   ..XX..XXXXXXXXXXXXXXXXXXOO..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX          ",
"   ..XX..XXXXXXXXXXXXXXXXXXOO+.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX          ",
"   ..XX..XXXXXXXXXXXXXXXXXXOO+OXXXX@@@@OXXXXX++++++++++++#+#XXXX++++OOXXXXXXXXXXXXXXXXXX          ",
"   ..XX..XXXXXXXXXXXXXXXXXXOO+$OXX@#####OXXXX+++++++++++#+##XXXX++++OOXXXXXXXXXXXXXXXXXX          ",
"   ..XX..XX..............XXOO+.$O@#++++..OOOO+++++++++.+.+ooOOXX++.+OOXXXXXXXXXXXXXXXXXX          ",
"   ..XX..XX.############%XXOO+$.$@#++++..#OOO++++++++.+.+.+oOOXX+++.OOXXXXXXXXXXXXXXXXXX          ",
"   ..XX..XX.#@@@@@@@@@@O%XXOO+.$.@#+++...#OOO+++++.+.+.+.+ooOOOO++.+OOXXXXXXXXXXXXXXXXXX          ",
"   ..XX..XX.#@@@@@@@@@@O%XXOO+$.$@#++....#OOO++++.+.+.+.+.+oOOOO+++.OOXXXXXXXXXXXXXXXXXX          ",
"   ..XX..XX.#OOOOOOOOOOO%XXOO+.$.@#.....##OOO+++++.+.+.+@+ooOOOO#+#+OOXXXXXXXXXXXXXXXXXX          ",
"   ..XX..XX.%%%%%%%%%%%%%XXOO+$.$@#....##XOOO++++.+.+.+.+@+oOOOO+#+#OOXXXXXXXXXXXXXXXXXX          ",
"   ..XX..XXXXXXXXXXXXXXXXXXOO+.$.$@#####XOXOO+++@+@+@+@+@+ooOOoo#+@+OOXXXXXXXXXXXXXXXXXX          ",
"   ..XX..XXXXXXXXXXXXXXXXXXOO+$.$.$OOOOOOXXOO++@+@+@+@+@+@ooOOoo+#+@OOXXXXXXXXXXXXXXXXXX          ",
"   ..XX..XXXXXXXXXXXXXXXXXXOO+.$.$.$.$.$.OXXXOOOOOOOOOOOOOOOooooOOOOOOXXXXXXXXXXXXXXXXXX          ",
"   ..XX..XXXXXXXXXXXXXXXXXXOO+$.$.$.$.$.$.OXXOOOOOOOOOOOOOOOooooOOOOOOXXXXXXXXXXXXXXXXXX          ",
"   ..oo..OOOOOOOOOOOOOOOOOOOO+.$.$.$.$.$.$.OOOO##XXXooooooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO          ",
"   ..oo..OOOOOOOOOOOOOOOOOOOO+$.$.$.$.$.$.$.OOO###XXXXooooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO          ",
"   ......####################+.$.$.$.$.$.$.$.O###+#XXXXXooOOXXXX########################          ",
"   ......####################+$.$.$.$.$.$.$.$.O#.#+#XXXXooOOXXXX########################          ",
"   ..XX..##oooooooooooooooooo+.$.$.$.$.$.$.$.$.##+.+#XXXXoOOOOoooooooooooooooooooooooooo          ",
"   ..XX..##oooooooooooooooooo+$.$.$.$.$.$.$.$.$#..+.+#XXXoOOOOoooooooooooooooooooooooooo          ",
"   ..XX..##oooooooooooooooooo+.$.$.$.$.$.$.$.$.##+.+.+@XXoOOOOoooooooooooooooooooooooooo          ",
"   ..XX..##oooooooooooooooooo+$.$.$.$.$.$.$.$.$#..+.+.+@XoOOOOoooooooooooooooooooooooooo          ",
"   ..XX..##oooooooooooooooooo+.$.$.$.$.$.$.$.$.##+.+++@+XXOOOOoooooooooooooooooooooooooo          ",
"   ..XX..##oooooooooooooooooo+$.$.$.$.$.$.$.$.$#..+.+++@XXOOOOoooooooooooooooooooooooooo          ",
"   ..XX..##oooooooooooooooooo+.$.$.$.$.$.$.$.$.##+.+++@+XXOOOOoooooooooooooooooooooooooo          ",
"   ..XX..##oooooooooooooooooo+$.$.$.$.$.$.$.$.$#..+.+++@XXOOOOoooooooooooooooooooooooooo          ",
"   ..XX..##oooooooooooooooooo+.$.$.$.$.$O$.$.$.##+.+++@+XXOOOOoooooooooooooooooooooooooo          ",
"   ..XX..##oooooooooooooooooo+$.$.$.$.$.OO$.$.$#..+.+++@XXOOOOoooooooooooooooooooooooooo          ",
"   ..XX..##oooooooooooooooooo+.$.$.$.$.$OoO$.$.##+.+++@+XXOOOOoooooooooooooooooooooooooo          ",
"   ..XX..##oooooooooooooooooo+$.$.$.$.$.OooO$.$#..+.+++@XXOOOOoooooooooooooooooooooooooo          ",
"   ..XX..##oooooooooooooooooo+.$.$.$.$.$OooXO$.##+.+++@+XXOOOOoooooooooooooooooooooooooo          ",
"   ..XX..##oooooooooooooooooo+$.$.$.$.$.OooXXO$#..+.+++@XXOOOOoooooooooooooooooooooooooo          ",
"   ..XX..##oooooooooooooooooo+.$.$.$.$.$OooXXXO##+.+++@+XX$OOOoooooooooooooooooooooooooo          ",
"   ..XX..##oooooooooooooooooo+$.$.$.$.$.OooXXXX#..+.+++@XX.$OOoooooooooooooooooooooooooo          ",
"   ..XX..##oooooooooooooooooo+.$.$.$.$.$OooXXXX##+.+++@+XX$.$Ooooooooooooooooooooooooooo          ",
"   ..XX..##oooooooooooooooooo+$.$.$.$.$.OooXXXX#..+.+++@XX.$.$Oooooooooooooooooooooooooo          ",
"   ..XX..##oooooooooooooooooo+.$.$.$.$.$OooXXXXOOOOOOO&&&&$.$.$Ooooooooooooooooooooooooo          ",
"   ..XX..##oooooooooooooooooo+$.$.$.$.$.OooXXXXOOOOOOO&&&&.$.$.$Oooooooooooooooooooooooo          ",
"   ..XX..##oooooooooooooooooo+.$.$.$.$.$OoooooOOOOOOOO&&&&&.$.$.$Ooooooooooooooooooooooo          ",
"   ..XX..##oooooooooooooooooo+$.$.$.$.$.OooooOOOOoooooOo&&&$.$.$.$Oooooooooooooooooooooo          ",
"   ..XX..##OOOOOOOOOOOOOOOOOO+.$.$.$.$.$OOOOOOOOoOoooooO&&&&$.$.$.$OOOOOOOOOOOOOOOOOOOOO          ",
"   ..XX..#OOOOOOOOOOOOOOOOOOO+$.$.$.$.$.OOOOOOOoOoooooOoO&&&.$.$.$.$OOOOOOOOOOOOOOOOOOOO          ",
"   ..XX..OOOOOOOOOOOOOOOOOOOO+.$.$.$.$.$OOOOOOOOoooooooO&&&&$.$.$.$.$OOOOOOOOOOOOOOOOOOO          ",
"   ..XX..####################+$.$.$.$.$.O####OOoOoooooOoO&&&.$.$.$.$.$OO################          ",
"   ..XX..####################+.$.$.$.$.$O####OOOoooooooO&&&&$.$.$.$.$.$O################          ",
"   ..XX..@@@@@@@@@@@@@@@@@@@@+$.$.$.$.$.OXX@@OOoOoooooOoO&&&.$.$.$.$.$.$OXX@@@@@@@@@@@@@          ",
"   ..XX..@@@@@@@@@@@@@@@@@@@@+.$.$.$.$.$OXX@@OOOoooooooO&&&&O.$.$.$.$.$.$OXX@@@@@@@@@@@@          ",
"   ..XX..@@@@@@@@@@@@@@@@@@@@+$.$.$.$.$.OXX@@OOoOoooooOoO&&&oO.$.$.$.$.$.$OXX@@@@@@@@@@@          ",
"   ..XX..@@@@@@@@@@@@@@@@@@@@+.$.$.$.$.$OXX@@OOOoooooooO&&&&ooO.$.$.$.$.$.$OXX@@@@@@@@@@          ",
"   ..XX..@@@@@@@@@@@@@@@@@@@@+$.$.$.$.$.OXX@@OOoOoooooOoO&&&oooO.$.$.$.$.$.$OXX@@@@@@@@@          ",
"   ..XX..@@@@@@@@@@@@@@@@@@@@+.$.$.$.$.$OXX@@OOOoooooooO&&&&ooooO.$.$.$.$.$.$OXX@@@@@@@@          ",
"   ..XX..@@@@@@@@@@@@@@@@@@@@+$.$.$.$.$.OXX@@OOoOoooooOoO&&&oooo@O.$.$.$.$.$.$OXX@@@@@@@          ",
"   ..XX..@@@@@@@@@@@@@@@@@@@@+.$.$.$.$.$OXX@@OOOoooooooO&&&&oooo@@O.$.$.$.$.$.$OXX@@@@@@          ",
"   ..XX..@@@@oooooooooooooooo+$.$.$.$.$.OooooOOoOoooooOoO&&&&&&&oooO.$.$.$.$.$.$OOoooooo          ",
"   ..XX..@@@@oooooooooooooooo+.$.$.$.$.$OooooOOOoooooooO&&&&&&&&ooooO.$.$.$.$.$.$Ooooooo          ",
"   ..XX..@@@@oo@@@@@@@@@@@@@@+$.$.$.$.$.OXX@@OOoOoooooOoO&&&XX@@@@@@@O.$.$.$.$.$.$OXX@@@          ",
"   ..XX..@@@@oo@@@@@@@@@@@@@@+.$.$.$.$.$OXX@@OOOoooooooO&&&&XX@@@@@@@@O.$.$.$.$.$.$OXX@@          ",
"   ..XX..@@@@oo@@@@@@@@@@@@@@+$.$.$.$.$.OXX@@OOoOoooooOoO&&&XX@@@@@@@@@O.$.$.$.$.$.$OXX@          ",
"   ..XX..@@@@oo@@@@@@@@@@@@@@+.$.$.$.$.$OXX@@OOOoooooooO&&&&XX@@@@@@@@@@O.$.$.$.$.$.$OXX          ",
"   ..XX..@@@@oo@@@@@@@@@@@@@@+$.$.$.$.$.O++++OOoOoooooOoO&&&++++++++++++++.$.$.$.$.$.$OX          ",
"   ..XX..@@@@oo@@@@@@@@@@@@@@+.$.$.$.$.$.$...OOOoooooooO&&&&..$.$.$.$.$.$.$.$.$.$.$.$.$O          ",
"   ..XX..@@@@oo@@@@@@@@@@@@@@+$.$.$.$.$.$.$.$OOoOoooooOoO&&&.$.$.$.$.$.$.$.$.$.$.$.$.$.$O         ",
"   ..XX..@@@@oo@@@@@@@@@@@@@@+.$.$.$.$.$.$.$.OOOoooooooO&&&&$.$.$.$.$.$.$.$.$.$.$.$.$.$.$O        ",
"   ..XX..@@@@oo@@@@@@@@@@@@@@+$.$.$.$.$.$.$.$OOoOoooooOoO&&&.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$O       ",
"   ..XX..@@@@oo@@@@@@@@@@@@@@+.$.$.$.$.$.$.$.OOOoooooooO&&&&$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$O      ",
"   ..XX..@@@@oo@@@@@@@@@@@@@@+$.$.$.$.$.$.$.$OOoOoooooOoO&&&.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$O     ",
"   ..XX..@@@@oo@@@@@@@@@@@@@@+.$.$.$.$.$.$.$.OOOoooooooO&&&&$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$O    ",
"   ..XX..@@@@oo@@@@@@@@@@@@@@+$.$.$.$.$.$.$.$OOoOoooooOoO&&&.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$O   ",
"   ..XX..@@@@oo@@@@@@@@@@@@@@#OOOOOOOOOOOOOOOOOOoooooooO&&&&OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO  ",
"   ..XX..@@@@oo@@@@@@@@@@@@@@@@XXXXXXXXXXXXXXOOoOoooooOoO&&&XXXXXXXXXXXXXXXXXXXXXXXXXXXX          ",
"   ..XX..@@@@oo@@@@@@@@@@@@@@@@XXXXXXXXXXXXXXOOOoooooooO&&&&XXXXXXXXXXXXXXXXXXXXXXXXXXXX          ",
"   ..XX..@@@@oo@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@OOoOoooooOoO&&&@@@@@@@@@@@@@@@@@@@@@@@@@@@@          ",
"   ..XX..@@@@oo@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@OOOoooooooO&&&&@@@@@@@@@@@@@@@@@@@@@@@@@@@@          ",
"   ..XX..@@@@oo@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@OOoOoooooOoO&&&@@@@@@@@@@@@@@@@@@@@@@@@@@@@          ",
"   ..XX..@@@@oo@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@OOOoooooooO&&&&@@@@@@@@@@@@@@@@@@@@@@@@@@@@          ",
"                                             OOoOoooooOoO&&&                                      ",
"                                             OOOoooooooO&&&&                                      ",
"                                             OOoOoooooOoO&&&                                      ",
"                                             OOOoooooooO&&&&                                      ",
"                                             OOoOoooooOoO&&&                                      ",
"                                             OOOoooooooO&&&&                                      ",
"                                             OO&&&&&&&&&&&&&                                      ",
"                                             OO&&&&&&&&&&&&&                                      ",
"                                                                                                  ",
"                                                                                                  ",
"                                                                                                  ",
"                                                                                                  "};
