/* XPM */
/*********************************************************************
*  (c) Copyright 1999 Sun Microsystems, Inc.
**********************************************************************/
static char * Color_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 14 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray6	m black	c #636363636363",
"X	s iconColor2	m white	c white",
"o	s iconGray2	m white	c #bdbdbdbdbdbd",
"O	s iconGray3	m white	c #adadadadadad",
"+	s iconColor6	m white	c yellow",
"@	s iconColor8	m black	c magenta",
"#	s iconColor3	m black	c red",
"$	s iconGray5	m black	c #737373737373",
"%	s iconGray8	m black	c #212121212121",
"&	s iconGray1	m white	c #dededededede",
"*	s iconColor5	m black	c blue",
"=	s iconColor4	m white	c green",
"-	s iconColor1	m black	c black",
/* pixels */
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"            ..........          ",
"         ...XXXXXXXXXX...       ",
"       ..XXXooOOOOOOooXXX..     ",
"     ..XXooOOOOOOOOOOOOooXX..   ",
"    .XXoOOO+O+OOOOOOOOOOOOoXX.  ",
"   .XoOOOO+O++O+OOOOO@@@@OOOoX. ",
"  .XoOOOO++++++OOOOO@@@@@.OOOo. ",
" .XoOOOOO+++++#OOOOO@@@@.OOOO$% ",
" .XOOOOOOO+++#OOOOOOO...OOOO%%o ",
".XoOOO#OOOOOOOOOOOOOOOOOOO$%%o  ",
".XoO####OOOOOO%%%%%$OOOOO%%oo   ",
".XOO###O##OOO%%    &OOOO%oo     ",
".XoOO#####OOO%     &OOO%o    ...",
".XoO#####.OOO%     &OOO%o  ..&oo",
" .XOO###.OOOO$&&&&&OOOO&...o&o.o",
" .XoO...OOOOOOOOOOOOOOOo&&&&OO%o",
"  .oOOOOOOOO*O*OOOOOOOO==OOOO%o ",
"   o$OOOOOO******OOOO*=*==OOO%o ",
"    o%OOOOOO****-OOOO=*=*=OO%o  ",
"     o%%OOO****-OOOOO***OOO%oo  ",
"      oo%%OOOOOOOOOOOOOOO%%oo   ",
"        oo%%%OOOOOOOOOO%%ooo    ",
"          ooo%%%%%%%%%%ooo      ",
"            oooooooooooo        ",
"                                ",
"                                ",
"                                "};
