/* XPM */
/* $XConsortium: Dthistnexti.m.pm /main/2 1996/07/23 12:11:43 drk $ */
static char * Dthistnexti_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 5 1 0 0",
/* colors */
" 	s background	m black	c #949494949494",
".	s iconGray6	m black	c #636363636363",
"X	s iconGray5	m black	c #737373737373",
"o	s iconGray2	m white	c #bdbdbdbdbdbd",
"O	s iconGray4	m white	c #949494949494",
/* pixels */
"                                ",
"                                ",
"                ..              ",
"               .XXX             ",
"              .XXXo             ",
"             .XXXXo             ",
"            .XXXXo              ",
"           .ooXXo               ",
"          .X.ooo                ",
"          oXXo                  ",
"           oo                   ",
"                 ..             ",
"       ...      .XXX            ",
"      .XXXo    .XXXo            ",
"     .XXXXo   .XXXXo  oo        ",
"    ..XXXo   .XXXXo   .Oo       ",
"    .XXXo   .o.XXo    ..Oo      ",
"   .o.Xo   .X.ooo     .O.Oo     ",
"  .X.oo    oXXo       ..O.Oo    ",
"  .XXo      oo        .O.O.Oo   ",
"   oo   ..            ..O.O.Oo  ",
"       .XXX           .O.O.O.Oo ",
"      .XXXo           ..O.O.O.Oo",
"     .XXXXo           .O.O.O.O. ",
"    .XXXXo            ..O.O.O.  ",
"   .o.XXo             .O.O.O.   ",
"  .X.ooo              ..O.O.    ",
"  oXXo                .O.O.     ",
"   oo                 ..O.      ",
"                      .O.       ",
"                      ..        ",
"                                "};
