/* XPM */
/* $XConsortium: Dthover.m.pm /main/3 1995/07/18 17:10:44 drk $ */
static char * Dthover_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 11 1 0 0",
/* colors */
" 	s none	m none	c none",
".    s iconGray2     m white c #bdbdbdbdbdbd",
"X    s iconGray5     m black c #737373737373",
"o	s iconColor1	m black	c black",
"O    s iconGray1     m white c #dededededede",
"+    s iconGray3     m white c #adadadadadad",
"@    s iconGray4     m white c #949494949494",
"#    s iconGray7     m black c #424242424242",
"$	s iconColor5	m black	c blue",
"%	s iconColor6	m white	c yellow",
"&	s iconColor3	m black	c red",
/* pixels */
"                                ",
"    ........................    ",
"    XXXXXXXXXXXXXXXXXXXXXXXo    ",
"    XXOOXOOOXOOXXXXXXXXXXXXo    ",
"    XXXXXXXXXXXXXXXXXXXXXXXo    ",
"    +ooooooooooooooooooooo@o    ",
"    +o####################@o    ",
"    +o####################@o    ",
"    +o###OO#OO#O##########@o    ",
"    +o####################@o    ",
"    +o####################@o    ",
"    +o....................@o    ",
"    +o..........$$$.oXo#o.@o    ",
"    +o..........$.$.XoXoX.@o    ",
"    +o....................@o    ",
"    +o...%%%%%%%..........@o    ",
"    +o....................@o    ",
"    +o...oXoXo............@o    ",
"    +o...XoXoX............@o    ",
"    +o....................@o    ",
"    +o...o.o.oo...........@o    ",
"    +o....................@o    ",
"    +o&&.oXo.#..X#.oX.o...@o    ",
"    +o&&.#.o.Xo.o..Xoo....@o    ",
"    +o....................@o    ",
"    +o....#.####.#.##.##..@o    ",
"    +o....................@o    ",
"    +o..........$$$$$$$$$.@o    ",
"    +o....................@o    ",
"    +@@@@@@@@@@@@@@@@@@@@@@o    ",
"    oooooooooooooooooooooooo    ",
"                                "};
