/* XPM */
/*********************************************************************
*  (c) Copyright 1997 Sun Microsystems, Inc.
*  All Rights Reserved
**********************************************************************/
static char * Dtkey_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 7 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X	s iconGray2	m white	c #bdbdbdbdbdbd",
"o	s iconGray8	m black	c #212121212121",
"O	s iconGray7	m black	c #424242424242",
"+	s iconGray1	m white	c #dededededede",
"@	s iconGray6	m black	c #636363636363",
/* pixels */
"                                                ",
" ....................................           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXXoooXoOOOXXXOOOXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXX++++++XXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXX++@@@@@@++XXXXo           ",
" .XXXXXXXXXXXXXXXXXXX+@@@@++@@@@+XXXo           ",
" .XXXXXoooXXoooOOoXX+@@@@++++@@@@+XXo           ",
" .XXXXXXXXXXXXXXXXXX+@@@@++++@@@@+XXo           ",
" .XXXXXXXXXXXXXXXXXX+@@@@@++@@@@@+XXo           ",
" .XXXoooXXoOOOXooOXX+@@@@@@@@@@@@+XXo           ",
" .XXXXXXXXXXXXXXXXXX+@@@@@@@@@@@@+XXo           ",
" .XXXXXXXXXXXXXXXXXX+@@@@@@@@@@@@+XXo           ",
" .XXXoooooXoooOXXXXX+@@@@@@@@@@@@+XXo           ",
" .XXXXXXXXXXXXXXXXXX+@@@@@@@@@@@@+XXo           ",
" .XXXXXXXXXXXXXXXXXX+@@@@@@@@@@@@+XXo           ",
" .XXXooOOOXOoooXXoXXX+@@@@@@@@@@+XXXo           ",
" .XXXXXXXXXXXXXXXXXXX+@@@@@@@@@@+XXXo           ",
" .XXXXXXXXXXXXXXXXXXXX++@@@@@@++XXXXo           ",
" .XXXooOOOooOOoXXOooXXX+@@@@@@+XXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXX++@@@@++XXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXX+@@@@+XXXXXXo           ",
" .XXXoooXXoOXXOOOoooXXXX+@@@@+XXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXX+@@@++XXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXX+@@@++XXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXX+@@@@+XXXXXXo           ",
" .XXXXXoooXOOOXoooXXXXXX+@@@@+XXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXX+@@@@+XXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXX+@@@++XXXXXXo           ",
" .XXXooOOOOXooOOOXoooXXX+@@@@+XXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXX+@@@@+XXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXX+@@@@+XXXXXXo           ",
" .XXXOOXOOOoOOOXXOOOXXXX+@@@++XXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXX++@@+XXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXX+@@+XXXXXXXo           ",
" .XXXoooXXOoXXoooXXXXXXXX++++XXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXX++XXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .ooooooooooooooooooooooooooooooooooo           ",
"                                                "};
