/* XPM */
/* $XConsortium: DtMail.l.pm /main/3 1995/07/18 16:21:38 drk $ */
static char * DtMailAW_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 14 1 0 0",
/* colors */
" 	s none	m none	c none",
".    s iconGray1     m white c #dededededede",
"X    s iconGray2     m white c #bdbdbdbdbdbd",
"o    s iconGray3     m white c #adadadadadad",
"O    s iconGray4     m white c #949494949494",
"+    s iconGray5     m black c #737373737373",
"@    s iconGray6     m black c #636363636363",
"#	s iconColor2	m white	c white",
"$    s bottomShadowColor m black c #636363636363",
"%	s iconColor3	m black	c red",
"&	s iconColor4	m white	c green",
"*	s iconColor1	m black	c black",
"=    s topShadowColor m white c #bdbdbdbdbdbd",
"-    s iconGray7     m black c #424242424242",
/* pixels */
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"       .....................X.X.XXXXXXXXX       ",
"       .ooooOOOOOOOOOOOOOO+++++++++@+@+@+       ",
"      ....................X.X.XXXXXXXXXXXX      ",
"      .oOOOOOOOOOOOOOO+++++++++++++@+@+@+@      ",
"     #####################################$     ",
"     #...............................X.X..$     ",
"     #.++.+....................%+..%+&o&X.$     ",
"     #...........................%+.X+&+..$     ",
"     #.+++.....................%+..%++&+X.$     ",
"     #...........................%+.X&o&..$     ",
"     #....................................$     ",
"     #....................................$     ",
"    $#..................................X.+$    ",
"   $O#...................................X@X$   ",
"  $#+#................................X.X.@OX$  ",
" $#+@#.................................XXX@*OX$ ",
"$#.oooOOOOOOXXX.....................X+++++++++X=",
"$#.o........OooX...++.++++.++.......+.........-=",
"$#..oOOOOOOO+@oXX.................X+.OOOOOO+@@-=",
"$#.oooOOOOOO+@ooX..+++++.++++......+.OOOOO+++@-=",
"$#..oOOOOOOO+@oXo...............X.X+.OOOOOO+@@-=",
"$#.oooOOOOOO+@ooXoXXXXXXXXXXXXXXXXX+.OOOOO+++@-=",
"$#..oOOOOOOOO+@ooooooooooooooooooo+.OOOOOOO+@@-=",
"$#.oooOOOOOOOOO@@@@@@@@@@@@@@@@@@@.OOOOOOO+++@-=",
"$#..oOOOOOOOOOO...................OOOOOOOOO+@@-=",
"$#.oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+++@-=",
"$#..oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+@@-=",
"$#.oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+++@-=",
"$Xoo++++++++++++++++++++++++++++++++++++++++@@-=",
"$o@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@=",
" ============================================== ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                "};
