/* XPM */
/*********************************************************************
*  (c) Copyright 1997 Sun Microsystems, Inc.
*  All Rights Reserved
**********************************************************************/
static char * SDtNoteEditor_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 14 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor3	m black	c red",
"X	s iconGray4	m white	c #949494949494",
"o	s iconColor2	m white	c white",
"O	s iconGray6	m black	c #636363636363",
"+	s iconGray2	m white	c #bdbdbdbdbdbd",
"@	s iconGray3	m white	c #adadadadadad",
"#	s iconGray8	m black	c #212121212121",
"$	s iconGray7	m black	c #424242424242",
"%	s iconColor1	m black	c black",
"&	s iconGray5	m black	c #737373737373",
"*	s iconGray1	m white	c #dededededede",
"=	s iconColor6	m white	c yellow",
"-	s iconColor8	m black	c magenta",
/* pixels */
"                          .X    ",
"                         o..X   ",
"                        .....   ",
"                         ...O   ",
"ooooooooooooooooooooooooOo.O    ",
"o++++++++++++++++++++++O++@#    ",
"o+++++++++++++++++++++O++++#    ",
"o++$%O%+%%++%+%%+++++#O++++#    ",
"o++++++++++++++++++++++&+++#    ",
"o+++++++++++++++++++++++X++#    ",
"o++$%%+%%%+%+%%+%%+++++++@+#    ",
"o++++++++++++++++++++++++++#    ",
"o++++++++++++++++++++++++++#    ",
"o++$%+%%X+%%@%&++++++++++++#    ",
"o++++++++++++%$O@++++++++++#    ",
"o++++++++++++O%ooX+++++++++#    ",
"o++++++++++++@O*o*X++++++++#    ",
"o++++++++++++@&$@=*X+++++++#    ",
"o+++++++++++++XO$@=*X++++++#    ",
"o++++++++++++++XO$@=*X+++++#    ",
"o+++++++++++++++XO$@=*X++++#    ",
"o++++++++++++++++XO$@=*X+++#    ",
"o#################&O$@=*&###    ",
"                   OO$@=*X      ",
"                    OO$@=*X     ",
"                     OO$@=*X    ",
"                      OO$@=+$   ",
"                       OO$XO*$  ",
"                        OO$O&*& ",
"                         OO$*--&",
"                          OO$-$&",
"                           OO$$ "};
