/* XPM */
/*********************************************************************
*  (c) Copyright 1997 Sun Microsystems, Inc.
*  All Rights Reserved
**********************************************************************/
static char * proc_mgr_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 14 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray6	m black	c #636363636363",
"X	s iconColor2	m white	c white",
"o	s iconGray2	m white	c #bdbdbdbdbdbd",
"O	s iconGray1	m white	c #dededededede",
"+	s iconGray7	m black	c #424242424242",
"@	s iconColor6	m white	c yellow",
"#	s iconColor1	m black	c black",
"$	s iconColor4	m white	c green",
"%	s iconGray4	m white	c #949494949494",
"&	s iconGray8	m black	c #212121212121",
"*	s iconGray3	m white	c #adadadadadad",
"=	s iconColor3	m black	c red",
"-	s iconGray5	m black	c #737373737373",
/* pixels */
"                                                ",
"                                                ",
"  .........................................     ",
"  .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo     ",
"  .XOoOoOoOoOooOooOooooOooooooooooooooooo+o     ",
"  .XoOoOoOoOooOooOooOoooooooooooooooooooo+o     ",
"  .XOo+++++++++++++++++++++++++++++++++oo+o     ",
"  .XoO+...............................Xoo+o     ",
"  .XOo+...................@........@..Xoo+o     ",
"  .XoO+..................@#.......@#..Xoo+o     ",
"  .XOo+...$$$........@..@#....@..@#...Xoo+o     ",
"  .XoO+..$O$%$&.....@@.@#....@@.@#....Xoo+o     ",
"  .XOo+..$$$$%&....@@@@#....@@@@#.....X*o+o     ",
"  .Xoo+..$%$%$&...@#@@#....@#@@#......Xoo+o     ",
"  .XoO+...$%$&...@#.@#....@#.@#.......Xo*+o     ",
"  .XOo+...&&&...@#..#....@#..#........Xoo+o     ",
"  .Xoo+........@#.......@#............X*o+o     ",
"  .XoO+...............................Xo*+o     ",
"  .XOo+..***************************..Xoo+o     ",
"  .Xoo+...............................X*o+o     ",
"  .XoO+...................*........*..Xo*+o     ",
"  .Xoo+..................*........*...Xoo+o     ",
"  .XOo+...===........*..*.....*..*....X*o+o     ",
"  .Xoo+..=o=-=&.....**.*.....**.*.....Xo*+o     ",
"  .Xoo+..====-&....****.....****......Xoo+o     ",
"  .Xoo+..=-=-=&...*.**.....*.**.......X*o+o     ",
"  .Xoo+...=-=&...*..*.....*..*........Xo*+o     ",
"  .Xoo+...&&&...*........*............X*o+o     ",
"  .Xoo+........*........*.............Xo*+o     ",
"  .Xoo+...............................X*o+o     ",
"  .Xoo+XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo*+o     ",
"  .Xoooooooooooooooo*ooo*oo*oo*oo*o*o*o*o+o     ",
"  .Xoooooooooooooo*ooo*oo*oo*oo*oo*o*o*o*+o     ",
"  .X++++++++++++++++++++++++++++++++++++++o     ",
"  .oooooooooooooooooooooooooooooooooooooooo     ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                "};
