/* XPM */
/*********************************************************************
*  (c) Copyright 1997 Sun Microsystems, Inc.
**********************************************************************/
static char * proc_mgr_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 10 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X	s iconGray8	m black	c #212121212121",
"o	s iconGray2	m white	c #bdbdbdbdbdbd",
"O	s iconGray5	m black	c #737373737373",
"+	s iconGray7	m black	c #424242424242",
"@	s iconColor6	m white	c yellow",
"#	s iconColor4	m white	c green",
"$	s iconColor3	m black	c red",
"%	s iconGray4	m white	c #949494949494",
/* pixels */
"                                ",
"                                ",
"                                ",
" ..............................X",
".ooooooooooooooooooooooooooooooX",
".oOOOOOOOOOOOOOOOOOOOOOOOOOOOOoX",
".oOXXXXXXXXXXXXXXXXXXXXXXXXXX.oX",
".oOX++++++++++++++++++++++++X.oX",
".oOX+++++++++++++++@++++++@+X.oX",
".oOX++##+++++++@++@+++@++@++X.oX",
".oOX+####X++++@@+@+++@@+@+++X.oX",
".oOX+####X+++@@@@+++@@@@++++X.oX",
".oOX++##X+++@+@@+++@+@@+++++X.oX",
".oOX++XX+++@++@+++@++@++++++X.oX",
".oOX++++++@++++++@++++++++++X.oX",
".oOX++++++++++++++++++++++++X.oX",
".oOX+oooooooooooooooooooooo+X.oX",
".oOX++++++++++++++++++++++++X.oX",
".oOX+++++++++++++++o++++++o+X.oX",
".oOX++$$+++++++o++o+++o++o++X.oX",
".oOX+$$$$X++++oo+o+++oo+o+++X.oX",
".oOX+$$$$X+++oooo+++oooo++++X.oX",
".oOX++$$X+++o+oo+++o+oo+++++X.oX",
".oOX++XX+++o++o+++o++o++++++X.oX",
".oOX++++++o++++++o++++++++++X.oX",
".oOXXXXXXXXXXXXXXXXXXXXXXXXXX.oX",
".oO...........................oX",
"%ooooooooooooooooooooooooooooooX",
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ",
"                                ",
"                                ",
"                                "};
