/* XPM */
/* $XConsortium: DtPrtjb.m.pm /main/3 1995/07/18 16:23:42 drk $ */
static char * DtPrtjb_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 12 1 0 0",
/* colors */
" 	s none	m none	c none",
".    s bottomShadowColor m black c #636363636363",
"X    s iconGray8     m black c #212121212121",
"o    s topShadowColor m white c #bdbdbdbdbdbd",
"O    s iconGray4     m white c #949494949494",
"+    s iconGray1     m white c #dededededede",
"@	s iconColor2	m white	c white",
"#    s iconGray2     m white c #bdbdbdbdbdbd",
"$    s iconGray5     m black c #737373737373",
"%	s iconColor1	m black	c black",
"&    s iconGray7     m black c #424242424242",
"*    s iconGray6     m black c #636363636363",
/* pixels */
"  ............................Xo",
"  .O+@@@@@@@@@@@@@@@@@@@@@@@+Xoo",
"  .#@@@@@@@@@@@@@@@@@@@@@@@@OXo ",
" .O+@@@@@@@@@@@@@@@@@@@@@@@+Xoo ",
" .#@@@@@@@@@@@@@@@@@@@@@@@@#$o  ",
" .@@@@@XX%@%&&@@&&&&@%%X@@@OOo  ",
".O@@@@@@@@@@@@@@@@@@@@@@@@@*oo  ",
".#@@@@@@@@@@@@@@@@@@@@@@@@@Xoo  ",
".+@@@@XX%%@@%%%%%%%%@%%X@@@Xoo  ",
".@@@@@@@@@@@@@@@@@@@@@@@@@@Xoo  ",
".+@@@XX%%@%%%@%%@%%%%%%X@@@Xoo  ",
".#@@@@@@@@@@@@@@@@@@@@@@@@@Xoo  ",
".O@@@@XX%%@%%%@@%%%%@%%X@@@Xoo  ",
" .+@@@@@@@@@@@@@@@@@@@@@@@@O#o  ",
" .#@@@@XX&@&%%@%&&@@&&XX@@@#Xo  ",
" .O@@@@@@@@@@@@@@@@@@@@@@@@+Xoo ",
"  .+@@@@XX%%&%@&%%%%&&%%X@@@OOo ",
"  .#@@@@@@@@@@@@@@@@@@@@@@@@#Xo ",
"  .O@@@@XX%&@&&%%@&&&@%%X@@@+Xoo",
"   .@@@@@@@@@@@@@@@@@@@@@@@@@OXo",
"  .O@@@@@@@@@@@@@@@@@@@@@@@@@X+o",
"   .@@@@XX%&&@%%%@@@&@&%XX@@@OXo",
"  .O@@@@@@@@@@@@@@@@@@@@@@@@@X+o",
"  .#@@@@XX&@&&&@%%@@&&&%XX@@+X+o",
"  .+@@@@@@@@@@@@@@@@@@@@@@@@#$oo",
"  .@@@@@XX&%&&@&&@&&%@%@X@@@O$o ",
" .O@@@@@@@@@@@@@@@@@@@@@@@@+$oo ",
" .#@@@@XXX&%@%%@@@@@@@@@@@@#Xoo ",
" .+@@@@@@@@@@@@@@@@@@@@@@@@O$o  ",
".O@@@@@@@@@@@@@@@@@@@@@@@@#X+o  ",
"%%%%%%%%%%%%%%%%%%%%%%%%%%%%o   ",
"ooooooooooooooooooooooooooooo   "};
