/* XPM */
/* $XConsortium: Dtrunpn.l.pm /main/3 1995/07/18 16:48:22 drk $ */
static char * Dtrunpn_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 16 1 0 0",
/* colors */
" 	s none	m none	c none",
".    s iconGray1     m white c #dededededede",
"X    s iconGray4     m white c #949494949494",
"o    s iconGray7     m black c #424242424242",
"O    s iconGray2     m white c #bdbdbdbdbdbd",
"+    s iconGray3     m white c #adadadadadad",
"@	s iconColor7	m white	c cyan",
"#    s iconGray6     m black c #636363636363",
"$	s iconColor2	m white	c white",
"%    s iconGray5     m black c #737373737373",
"&	s iconColor1	m black	c black",
"*    s iconGray8     m black c #212121212121",
"=	s iconColor6	m white	c yellow",
"-	s iconColor5	m black	c blue",
";	s iconColor3	m black	c red",
":	s iconColor8	m black	c magenta",
/* pixels */
"   ................................XXoXOO....   ",
"  .+O+ + + + + + + + + + + + + + +oXoXXoOo+ +.  ",
" .+ + + + @@@@@@@@@ + + + + + + .###Xo$##X##+ . ",
".+ X O + @@+++++++@@ + + + + + .###X%$$$$oo+ + o",
". + X O+&&+ + + + +@+ + + + + ..###X...$$++++ +o",
".+ + X +&&&+++ + + @@+ + + + $$*#**.$$o%%%++ + o",
". + + O +&&&& + + + @@+ + + +****%X$..$$$*+ + +o",
".+ + + O+&&$$&&+ + + @@@ + + ****XX$..$$$*++ + o",
". + + + ++&$$$$&& + + +@@@@ +o**+OO...%%**+ + +o",
".+ + + + +&&$$$*$& + + + +@@@+ o$.%XOOO**+ + + o",
". + + + ++&&$$*+=$& +++++++@@ oo ..XXXO*+ + + +o",
".+ + + + O+&X*+o==$&$$$$$$$XX$--#XX#***+ + + + o",
". + + + + +&&=o=o==$&OOOOOOOOO--.##*+++ + + + +o",
".+ + + + + +&*=o=o==$&OOOOOOOO--.##*++ + + + + o",
". + + + + + +&*=o=o==$&++++O+.o-.OO##++ + + + +o",
".+ + + + + + +&*=o=o==$&%%%%*-o-$-o-#+ + + + + o",
". + + + + + + +&*=o=o==$&****o--$--#o++ + + + +o",
".+ + + + + + +$$&*=o=o==$&#-o-##-#o*#+ + + + + o",
". + + + + + +$.X+&*=o=o==$&o-#--#*o###+ + + + +o",
".+ + + + + +$O.+Xo&*=o=o==$&-#--#*o####+ + + + o",
". + + + + +$O.+oo +&*=o=o==$&###***XXX#+++++.OO.",
".+ + + + +*..+o+ + +&*=o=o==$&** **#XXX.....XXX.",
". + + + +*%..o+ + +o$&*=o=o==$& + *#XX......#XX%",
".+ + + +*$$$o+ + +$$;O&*=o=o==$& + *##X+++XXooo#",
". + + + *%OO+ + + $;#;;&*=o=o==$& + *%%%%%%o+ +o",
".+ + + + *** + + +$%;%#O&*=o=o==$& + ****oo+ + o",
". + + + + + + + +$#;O;#;;&*=o=o==$& + + + + + +o",
".+ + + + + + + + $##o+;##O&*=o=o==$& + + + + + o",
". + + + + + + + +$#oo;+#OOO&*=o=o==$& + + + + +o",
".+ + + + + + + +..##oo%O.+.O&*=o=o==$& + + + + o",
". + + + + + + +..%XX*o*%%++..&*=o=o==$& + + + +o",
".+ + + + + + + ..OXX*oo**%++.O&*=o=o==$& + + + o",
". + + + + + + $OOO##o + o**+#O.&*=o=o==$& + + +o",
".+ + + + + + $.OOX%o + + +*o$OO+&*=o=o==$& + + o",
". + + + + + $$.OOXo + + + +$$OX%o&*=o=o==$& + +o",
".+ + + + + X..OXXo + + + +$OO+%o +&*=o=o==$& + o",
". + + + + $.XX*oo + + + +$.OO%o + +&*=o=o==:& +o",
".+ + + + $$.X+*% + + + +$$.O%o + + +&*=o=o:$:& o",
". + + + $..O+*+ + + + O.+.%oo + + + +&*=o:$:$:&o",
".+ + + $.O+%*+ + + +$.OO+%o+ + + + + +&*#;:$:$:o",
". + + $..+%*+ + + + $++X%o+ + + + + + +&#o;:$:Oo",
".+ +.X..+%*+ + + + +#%+.$$ + + + + + + +&#o;::#o",
". %..X+.#*+ + + + + +##.... + + + + + + +&#o:#+o",
".+%+++X.#+ + + + + + +#%...% + + + + + + +&##+ o",
". *++$.++ + + + + + + +**** + + + + + + + + + +o",
" *o%+.$$.+ + + + + + + + + + + + + + + + + + + *",
"  oo%%$$..+ + + + + + + + + + + + + + + + + + o ",
"   oo%%%ooooooooooooooooooooooooooooooooooooo*  "};
