/* XPM */
/* $XConsortium: Dtsectnext.m.pm /main/2 1996/07/23 12:21:07 drk $ */
static char * Dtsectnext1_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 7 1 0 0",
/* colors */
" 	s background	m black	c #949494949494",
".	s iconColor2	m white	c white",
"X	s iconGray2	m white	c #bdbdbdbdbdbd",
"o	s iconGray7	m black	c #424242424242",
"O	s iconGray6	m black	c #636363636363",
"+	s bottomShadowColor	m black	c #636363636363",
"@	s iconGray3	m white	c #adadadadadad",
/* pixels */
"    ..................          ",
"    .XXXXXXXXXXXXXXXX.o         ",
"    .XXXXXXXXXXXXXXXX.Xo        ",
"    .XXXXXXXXXXXXXXXX.XXo       ",
"    .XXXXXXXXXXXXXXXX.XXXo      ",
"    .XXXXXXXXXXXXXXXX.XXXXo     ",
"    .XXXXXXXXXXXXXXXX.XXXXXo    ",
"    .XXXXXXXXXXXXXXXXoooooooo   ",
"    .XXXXXXXXXXXXXXXXXOOOOOOo   ",
"    .XXXXXXXXXXXXXXXXXXXXXXXo+  ",
"    .XXXXXXXXXXXXXXXXXXXXXXXo+  ",
"    .XXXXXXX.........XXXXXXXo+  ",
"    .XXXXXXX+@@@@@@@.XXXXXXXo+  ",
"    .XXXXXXX+@@@@@@@.XXXXXXXo+  ",
"    .XXXXXXX+@@@@@@@.XXXXXXXo+  ",
"    .XXXXXXX+@@@@@@@.XXXXXXXo+  ",
"    .XXXXXXX+@@@@@@@.XXXXXXXo+  ",
"    .XXXXXXX+@@@@@@@.XXXXXXXo+  ",
"    .XXXXXXX+@@@@@@@.XXXXXXXo+  ",
"    .XXX+++++@@@@@@@.....XXXo+  ",
"    .XXXX+@@@@@@@@@@@@@.XXXXo+  ",
"    .XXXXX+@@@@@@@@@@@.XXXXXo+  ",
"    .XXXXXX+@@@@@@@@@.XXXXXXo+  ",
"    .XXXXXXX+@@@@@@@.XXXXXXXo+  ",
"    .XXXXXXXX+@@@@@.XXXXXXXXo+  ",
"    .XXXXXXXXX+@@@.XXXXXXXXXo+  ",
"    .XXXXXXXXXX+@.XXXXXXXXXXo+  ",
"    .XXXXXXXXXXX+XXXXXXXXXXXo+  ",
"    .XXXXXXXXXXXXXXXXXXXXXXXo+  ",
"    .XXXXXXXXXXXXXXXXXXXXXXXo+  ",
"    .oooooooooooooooooooooooo+  ",
"      ++++++++++++++++++++++++  "};
