/* XPM */
/* $XConsortium: Dtsrchprevi.m.pm /main/2 1996/07/23 12:24:08 drk $ */
static char * Dtsrchprevi_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 7 1 0 0",
/* colors */
" 	s background	m black	c #949494949494",
".	s iconGray6	m black	c #636363636363",
"X	s iconGray2	m white	c #bdbdbdbdbdbd",
"o	c #CCCCCCCCCCCC",
"O	s iconGray5	m black	c #737373737373",
"+	c #000080808080",
"@	s iconGray4	m white	c #949494949494",
/* pixels */
"                                ",
"                         ..     ",
"                        .Xo.    ",
"                       .XoOO.   ",
"                      .XoOO+.   ",
"                     .XoOO+.    ",
"                    .XoOO+.     ",
"                   .XoOO+.      ",
"                ...XoOO+.       ",
"               .XXX+OOO.        ",
"              .XoooO.+.         ",
"              ..ooOOO.          ",
"            @ @X.OOO+.          ",
"           @X@X@X.O++.          ",
"          @X@X@X@X.+.       XX  ",
"         @X@X@X@X@..       X@.  ",
"       @@@@@@X@X@         X@@.  ",
"      @@X@X@X@X@X@       X@@@.  ",
"     @@@@@@@@@@X@       X@@@@.  ",
"   @@@X@X@X@X@X@       X@@@@@.  ",
"  @@X@@@@@@@@@@       X@@@@@@.  ",
" @@@@@X@X@X@X@       X@@@@@@@.  ",
"@XXX@@@@@@@@@@      X@@@@@@@@.  ",
"@XXXXX@@X@X@@        .@@@@@@@.  ",
"@XXXXXX@@@@@          .@@@@@@.  ",
" @XXXXX@@X@            .@@@@@.  ",
" @XXXXXX@@@             .@@@@.  ",
"  @XXXXX@@               .@@@.  ",
"   @@XXX@                 .@@.  ",
"     @@@                   .@.  ",
"                            ..  ",
"                                "};
