/* XPM */
/* $XConsortium: Dtsrchnext.m.pm /main/2 1996/07/23 12:22:48 drk $ */
static char * Dtsrchnext1_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 9 1 0 0",
/* colors */
" 	s background	m black	c #949494949494",
".	s iconColor1	m black	c black",
"X	s iconColor2	m white	c white",
"o	c #CCCCCCCCCCCC",
"O	s iconGray5	m black	c #737373737373",
"+	c #000080808080",
"@	s iconColor6	m white	c yellow",
"#	s iconGray4	m white	c #949494949494",
"$	s iconGray8	m black	c #212121212121",
/* pixels */
"                                ",
"                         ..     ",
"                        .Xo.    ",
"                       .XoOO.   ",
"                      .XoOO+.   ",
"                     .XoOO+.    ",
"                    .XoOO+.     ",
"                   .XoOO+.      ",
"                ...XoOO+.       ",
"               .XXX+OOO.        ",
"              .XoooO.+.         ",
"              ..ooOOO.          ",
"            @ @X.OOO+.          ",
"           @X@X@X.O++.          ",
"          @X@X@X@X.+. XX        ",
"         @X@X@X@X@..  .#X       ",
"       @@@@@@X@X@     .##X      ",
"      @@X@X@X@X@X@    .###X     ",
"     @@@@@@@@@@X@     .####X    ",
"   @@@X@X@X@X@X@      .#####X   ",
"  @@X@@@@@@@@@@       .######X  ",
" @@@@@X@X@X@X@        .#######X ",
"@XXX@@@@@@@@@@        .########X",
"@XXXXX@@X@X@@         .#######$ ",
"@XXXXXX@@@@@          .######$  ",
" @XXXXX@@X@           .#####$   ",
" @XXXXXX@@@           .####$    ",
"  @XXXXX@@            .###$     ",
"   @@XXX@             .##$      ",
"     @@@              .#$       ",
"                      $$        ",
"                                "};
