/* XPM */
/*********************************************************************
*  (c) Copyright 2000 Sun Microsystems, Inc.
**********************************************************************/
static char * SDtTypeEditor_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 13 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray7	m black	c #424242424242",
"X	s iconGray2	m white	c #bdbdbdbdbdbd",
"o	s iconGray1	m white	c #dededededede",
"O	s iconColor2	m white	c white",
"+	s iconGray4	m white	c #949494949494",
"@	s iconColor1	m black	c black",
"#	s iconGray8	m black	c #212121212121",
"$	s iconGray5	m black	c #737373737373",
"%	s iconGray3	m white	c #adadadadadad",
"&	s iconColor7	m white	c cyan",
"*	s iconColor4	m white	c green",
"=	s iconColor5	m black	c blue",
/* pixels */
"                                                ",
"                                                ",
"                     ......................     ",
"                     .XXXXXXXXXXXXXXXXXXXX..    ",
"                     .XXXXXXXXXXXXXXXXXXXX.o.   ",
"                     .XXXXXXXXXXXXXXXXXXXX.oo.  ",
"                     .XXXXXXXXXXXXXXXXXXXX..... ",
"        ..........................XXXXXXXXXXXX. ",
"        .OOOOOOOOOOOOOOOOOOOOOOOO..+XXXXXXXXXX. ",
"        .OOOOOOOOOOOOOOOOOOOOOOOO.O.+XXXXXXXXX. ",
"        .OOOOOOOOOOOOOOOOOOOOOOOO.OO.+XXXXXXXX. ",
"        .OOOOOOOOOOOOOOOOOOOOOOOO.OOO.+XXXXXXX. ",
"        .OOOOOOOOOOOOOOOOOOOOOOOO......+XXXXXX. ",
"@   ####################OOOOOOOOOOOOOO.+XXXXXX. ",
"@@  #$$$$$$$$$$$$$$$$$$#%OOOOOOOOOOOOO.+XXXXXX. ",
"@@@ #$$%%$$$$$%$$$$%$$$#%OOOO..OOOOOOO.+XXXXXX. ",
"@@@@#$$%$$%$$$%$$$%$$$$#%OOOO.&.OO..OO.+XXXXXX. ",
"@@@ #$$%%$%$%%$%%$$%%$$#%OOOO.&&.O.X.O.+XXXXXX. ",
"@@  #$$$$$$$$$$$$$$$$$$#%OO...&&&..&X..+XXXXXX. ",
"@   #..................#%OO.&&&&&&.X&X.+XXXXXX. ",
"    #OOOOOOOOOOOOOOOOOO#%OO.&&&&&&&.X&X.XXXXXX. ",
"    #OO$OOOO$$OOO$$OOOO#%OO.&&&&&&&&.X&X.XXXXX. ",
"    #OO%O%OO$OO$O$O$%OO#%OO.&&&&&&&&&.X&X.XXXX. ",
"    #OO$$%$O%$%$O$$O$OO#%OO.&&&&&&&&.X&X.XXXXX. ",
"    #OOOOOOOOOOOOOOOOOO#%OO.&&&&&&&.X&X.XXXXXX. ",
"    #..................#%OO.&&&&&&.X&X.+XXXXXX. ",
"    #OOOOOOOOOOOOOOOOOO#%OO.&&&&&..&X.#.........",
"    #OO$$OOO$OOOO%OOOOO#%OO...&&.$.X.%.*+*+*+*+.",
"    #OO%O%OO$O$%O%$$%OO#%OOOO.&.$%..%O.+*+*+*+*.",
"    #OO$$%%O%$%$$$$O$OO#%OOOO..$%OOOOO.*+*+*+*+.",
"    #OOOOOOOOOOOOOOOOOO#%OOOOO$%OOOOOO.+*+*+*+*.",
"    ####################%OOOOOOOOOOOOO.*+*+*+*+.",
"        .%%%%%%%%%%%%%%%%OOOOOOOOOOOOO.+*+*+*+*.",
"        .OOOOOOOOOOOOOOOOOOOOOOOOOOOOO..........",
"        .OOOOOOOOOOOOOOOOOOOOOOOOOOOOO.+XXXXXX. ",
"        .OOOOOOOOOOOOO%%%%%%%%%%%%%%%%%%$...... ",
"        .OOOOOOOOOOOOO%=================.       ",
"        .OOOOOOOOOOOOO%=================.       ",
"        .OOOOOOOOOOOOO%=================.       ",
"        .OOOOOOOOOOOOO%=================.       ",
"        .OOOOOOOOOOOOO%=================.       ",
"        .OOOOOOOOOOOOO%=================.       ",
"        .OOOOOOOOOOOOO%=================.       ",
"        .OOOOOOOOOOOOO%=================.       ",
"        .OOOOOOOOOOOOO%..................       ",
"        .OOOOOOOOOOOOOOOOOOOOOOOOOOOOO.         ",
"        .OOOOOOOOOOOOOOOOOOOOOOOOOOOOO.         ",
"        ...............................         "};
