/* XPM */
/*********************************************************************
*  (c) Copyright 2000 Sun Microsystems, Inc.
**********************************************************************/
static char * SDtTypeEditor_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 13 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray7	m black	c #424242424242",
"X	s iconGray2	m white	c #bdbdbdbdbdbd",
"o	s iconGray1	m white	c #dededededede",
"O	s iconColor2	m white	c white",
"+	s iconGray4	m white	c #949494949494",
"@	s iconColor1	m black	c black",
"#	s iconGray8	m black	c #212121212121",
"$	s iconGray5	m black	c #737373737373",
"%	s iconGray3	m white	c #adadadadadad",
"&	s iconColor7	m white	c cyan",
"*	s iconColor4	m white	c green",
"=	s iconColor5	m black	c blue",
/* pixels */
"            ...............     ",
"            .XXXXXXXXXXXXX..    ",
"            .XXXXXXXXXXXXX.o.   ",
"            .XXXXXXXXXXXXX.oo.  ",
"     ..................XXX..... ",
"     .OOOOOOOOOOOOOOOO..+XXXXX. ",
"     .OOOOOOOOOOOOOOOO.O.+XXXX. ",
"     .OOOOOOOOOOOOOOOO.OO.+XXX. ",
"@  ###########OOOOOOOO.....+XX. ",
"@@ #$$$$$$$$$#%OOOOOOOOOOO.+XX. ",
"@@@#$$%%$%%$$#%OOO..OOOOOO.+XX. ",
"@@ #$$$$$$$$$#%OOO.&.O..OO.+XX. ",
"@  #.........#%O...&&..&.O.+XX. ",
"   #OOOOOOOOO#%O.&&&&&.%&..+XX. ",
"   #OO$O$$$OO#%O.&&&&&&.%&.+XX. ",
"   #OOOOOOOOO#%O.&&&&&&&.%&.XX. ",
"   #.........#%O.&&&&&&.%&.+XX. ",
"   #OOOOOOOOO#%O.&&&&&.%&.#.....",
"   #OO$$O$$OO#%O...&&..&.%.*+*+.",
"   #OOOOOOOOO#%OOO.&.$..%O.+*+*.",
"   ###########%OOO..$%OOOO.*+*+.",
"     .%%%%%%%%%OOOO$%OOOOO.+*+*.",
"     .OOOOOOOOOOOOOOOOOOOO......",
"     .OOOOOOOOOO%%%%%%%%%%%%$X. ",
"     .OOOOOOOOOO%===========... ",
"     .OOOOOOOOOO%===========.   ",
"     .OOOOOOOOOO%===========.   ",
"     .OOOOOOOOOO%===========.   ",
"     .OOOOOOOOOO%===========.   ",
"     .OOOOOOOOOO%............   ",
"     .OOOOOOOOOOOOOOOOOOOO.     ",
"     ......................     "};
