/* XPM */
/* $XConsortium: IcCMinv.m.pm /main/3 1995/07/18 17:13:10 drk $ */
static char * IcCMinv_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 12 1 0 0",
/* colors */
" 	s none	m none	c none",
".    s iconGray1     m white c #dededededede",
"X    s iconGray3     m white c #adadadadadad",
"o    s iconGray4     m white c #949494949494",
"O	s iconColor2	m white	c white",
"+    s iconGray5     m black c #737373737373",
"@    s iconGray7     m black c #424242424242",
"#    s selectColor m white c #737373737373",
"$    s iconGray8     m black c #212121212121",
"%	s iconColor1	m black	c black",
"&    s iconGray6     m black c #636363636363",
"*    s iconGray2     m white c #bdbdbdbdbdbd",
/* pixels */
"      .                 .       ",
"  XXXoOX+XXXXXXXXXXXXXXoOX+XX   ",
"  XoooOXooooooooooooooooOXoo@#  ",
"  Xo@XOo$@@@@@@@@@@@@@@XOo$+@#  ",
"  Xo@XOo$@@@@@@@@@@@@@@X.o$+@#  ",
"  Xo@%o%@@@@@@@@@@@@@@@%o%@+@#  ",
"  Xo@@%@@@@@@@@@@@@@@@@@%@@+@#  ",
"  Xo@@@@@@@@@@@@@@@@@@@@@@@+@#  ",
"  Xo@@@@@@@@@@@@@@@@@@@@@@@+@#  ",
"  Xo@@@@@@@@@@@@@@@@@@@@@@@+@#  ",
"  Xo@@@@@@@@@@@@@@@@@@@@@@@+@#  ",
"  Xo@@@@@@@@@@@@@@@@@@@@@@@+@#  ",
"  Xo@@@@@@@@@@@@@@@@@@@@@@@+@#  ",
"  Xo@@@@@@@@@@@@@@@@@@@@@@@+@#  ",
"  Xo@@@@@@@@@@@@@@@@@@@@@@@+@#  ",
"  Xo@@@@@@@@@@@@@@@@@@@@@@@+@#  ",
"  Xo@@@@@@@@@@@@@@@@@@@@@@@+@#  ",
"  Xo@@@@@@@@@@@@@@@@@@@@@@@+@#  ",
"  Xo@@@@@@@@@@@@@@@@@@@@@@@+@#  ",
"  Xo@@@@@@@@@@@@@@@@@@@@@@@+@#  ",
"  Xo@@@@@@@@@@@@@@@@@@@@@@@+@#  ",
"  Xo@@@@@@@@@@@@@@@@@@@@@@@+@#  ",
"  Xo@@@@@@@@@@@@@@@@@@@@@@@+@#  ",
"  Xo@@@@@@@@@@@@@@@@@@@@@@@+@#  ",
"  Xo@@@@@@@@@@@@@@@@@@OO..++@#  ",
"  Xo@@@@@@@@@@@@@@@@@@O.X+&+@#  ",
"  Xo@@@@@@@@@@@@@@@@@@.X+&*+@#  ",
"  Xo@@@@@@@@@@@@@@@@@@.+&**+@#  ",
"  Xo@@@@@@@@@@@@@@@@@@+&***+@#  ",
"  Xo+++++++++++++++++++++++@@#  ",
"  X@@@@@@@@@@@@@@@@@@@@@@@@@@#  ",
"   ###########################  "};
