#!/bin/sh
echo "Image courtesy of Tilman Pietzsch <sundevil.arts@t-online.de>"
echo

cmd='../src/pclock -B../XPM/moonphase.xpm -H black --hands-width 0 --minute-hand-len 13 --hour-hand-len 10 --second-hand-len 16'

echo $cmd
$cmd
