#!/bin/sh
echo "Image courtesy of Clemens Krammer <drk@pollux.ikn.tuwien.ac.at>"
echo

cmd='../src/pclock -B../XPM/rolex2.xpm -H grey80 --hands-width=2 --hour-hand-length=12 --second-hand-length=18'

echo $cmd
$cmd
