#!/bin/sh

data_home=${XDG_DATA_HOME:-"$HOME/.local/share"}
nscde_data=${NSCDE_WAYLAND_DATA:-"$data_home/nscde-wayland"}
wallpaper="$nscde_data/photos/Flower.png"

command -v fnott >/dev/null 2>&1 && fnott &
command -v kanshi >/dev/null 2>&1 && kanshi &
command -v sfwbar >/dev/null 2>&1 && sfwbar &
command -v lavalauncher >/dev/null 2>&1 && lavalauncher &

if [ -f "$wallpaper" ]; then
	if command -v swaybg >/dev/null 2>&1; then
		swaybg -i "$wallpaper" -m fill &
	elif command -v wbg >/dev/null 2>&1; then
		wbg "$wallpaper" &
	fi
fi
