#!/bin/ksh

# Called from f_FrontPanelAction to populate Front Panel Action Icons

Button="$1"

SysActionFile="$NSCDE_ROOT/config/FrontPanel.actions"
if [ -r "$FVWM_USERDIR/FrontPanel.actions" ]; then
   UserActionFile="$FVWM_USERDIR/FrontPanel.actions"
else
   UserActionFile="/dev/null"
fi

ActionLine=$(egrep "^${Button},.*,.*,.*,.*" $UserActionFile $SysActionFile | head -1)
if [ "x${ActionLine}" != "x" ]; then
   echo $ActionLine | while IFS="," read button icon mousebutton check cmd
   do
      if [ "$mousebutton" == "M1" ] && [ "$icon" != "" ]; then
         echo "SendToModule FrontPanel ChangeButton $Button Icon $icon"
      fi
   done
else
   echo "Nop"
fi
