/* XPM */
static char *basket_weave_xpm[] = {
/* width height ncolors chars_per_pixel */
"49 48 5 1",
/* colors */
"` c gray60",
"a c black",
"b s bottomShadowColor   m black   c #636363636363",
"c s background   m black   c #949494949494",
"d c s topShadowColor   m white   c #bdbdbdbdbdbd",
/* pixels */
"cccccccccccccc`cccccccccccccccccccc`ddccccccccccc",
"cccccccccccccc`cccccccccccccccccccc`ddccccccccccc",
"cccccccccccccc`cccccccccccccccccccc`ddccccccccccc",
"cccccccccccccc`cccccccccccccccccccc`ddccccccccccc",
"cccccccccccccc`cccccccccccccccccccc`ddccccccccccc",
"cccccccccccccc`cccccccccccccccccccc`ddccccccccccc",
"cccccccccccccc`cccccccccccccccccccc`ddccccccccccc",
"cccccccccccccc`cccccccccccccccccccc`ddccccccccccc",
"cccccccccccccc`cccccccccccccccccccc`ddccccccccccc",
"```````````````cccccccccccccccccccc``````````````",
"dddddddddd`bbb`cccccccccccccccccccc`bbb`ddddddddd",
"dddddddddd`bdd`cccccccccccccccccccc`bdd`ddddddddd",
"cccccccccc`bda`cccccccccccccccccccc`bda`ccccccccc",
"cccccccccc``````````````````````````````ccccccccc",
"cccccccccc`ddcccccccccccccccccccccccccc`ccccccccc",
"cccccccccc`ddcccccccccccccccccccccccccc`ccccccccc",
"cccccccccc`ddcccccccccccccccccccccccccc`ccccccccc",
"cccccccccc`ddcccccccccccccccccccccccccc`ccccccccc",
"cccccccccc`ddcccccccccccccccccccccccccc`ccccccccc",
"cccccccccc`ddcccccccccccccccccccccccccc`ccccccccc",
"cccccccccc`ddcccccccccccccccccccccccccc`ccccccccc",
"cccccccccc`ddcccccccccccccccccccccccccc`ccccccccc",
"cccccccccc`ddcccccccccccccccccccccccccc`ccccccccc",
"cccccccccc`ddcccccccccccccccccccccccccc`ccccccccc",
"cccccccccc`ddcccccccccccccccccccccccccc`ccccccccc",
"cccccccccc`ddcccccccccccccccccccccccccc`ccccccccc",
"cccccccccc`ddcccccccccccccccccccccccccc`ccccccccc",
"cccccccccc`ddcccccccccccccccccccccccccc`ccccccccc",
"cccccccccc`ddcccccccccccccccccccccccccc`ccccccccc",
"cccccccccc`ddcccccccccccccccccccccccccc`ccccccccc",
"cccccccccc`ddcccccccccccccccccccccccccc`ccccccccc",
"cccccccccc`ddcccccccccccccccccccccccccc`ccccccccc",
"cccccccccc`ddcccccccccccccccccccccccccc`ccccccccc",
"cccccccccc``````````````````````````````ccccccccc",
"cccccccccc`bbb`dddddddddddddddddddd`bbb`ccccccccc",
"cccccccccc`bdd`dddddddddddddddddddd`bdd`ccccccccc",
"cccccccccc`bda`cccccccccccccccccccc`bda`ccccccccc",
"```````````````cccccccccccccccccccc``````````````",
"cccccccccccccc`cccccccccccccccccccc`ddccccccccccc",
"cccccccccccccc`cccccccccccccccccccc`ddccccccccccc",
"cccccccccccccc`cccccccccccccccccccc`ddccccccccccc",
"cccccccccccccc`cccccccccccccccccccc`ddccccccccccc",
"cccccccccccccc`cccccccccccccccccccc`ddccccccccccc",
"cccccccccccccc`cccccccccccccccccccc`ddccccccccccc",
"cccccccccccccc`cccccccccccccccccccc`ddccccccccccc",
"cccccccccccccc`cccccccccccccccccccc`ddccccccccccc",
"cccccccccccccc`cccccccccccccccccccc`ddccccccccccc",
"cccccccccccccc`cccccccccccccccccccc`ddccccccccccc"
};
