/* XPM */
/* This file is a part of the NsCDE - Not so Common Desktop Environment */
static char *CircleWeave_pm[] = {
"64 64 4 1",
/* colors */
"` c gray25",
"a   s bottomShadowColor   m black   c #636363636363",
"b   s background      m black   c #949494949494",
"c   s selectColor      m white   c #737373737373",
/* pixels */
"``````aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa``bbb`",
"bbbaa```````````````````````````````````````````````````````bbb`",
"bbbbaaaaaa```````````````````aaa`aaa````````````````bbbbbba`bbb`",
"bbbbbbaaaaaaa``````````ccca``cba`cba``accc`````````bbbaaaaa`bba`",
"``````bbbaaaaaaaa```cccbbba``cba`cba``abbbccc````bbaaaaaaa``baa`",
"aaaaa````bbbaaaa``ccbbbbaaa`cbba`cbba`aaabbbbc```aaaaaa`````baa`",
"ba`aab``````bb``ccbbaaaa````cba```cba````aabbbcc``aa```````baa`c",
"ba`aab`````````cbbaaaa``````cba```cba``````aaabbc``````````baa`c",
"ba`aab````````cbbaaa```````cbba```cba````````aabbc`````````baa`c",
"ba`aaab``````cbbaa```a`````cbba```cbba````bbb`aabbc```````bbaa`c",
"ba``aab`````cbbaa``aaaa````bba`````cba```bbaaa`aabbc``````baa``c",
"ba``aab````cbbaa```baaaa``cbba`````cba``baaaa```aabbc`````baa``c",
"ba``aaab``cbbaa`````baaaa`cbba`````cba`baaaa`````aabbc```baaa``c",
"ba```aab``bbaa```````baaaa`ba```````c`baaaa```````aabbc``baa```c",
"ba```aaab`baa`````````baaa`ba```````c`baaa`````````aabb`baaa```c",
"ba````aab`aa```````````baaa``````````baaa```````````aab`baa````c",
"ba````aaab`a```````````baaa``````````baa`````````````a`baaa````c",
"ba`````aaab```````````a`baaa````````baaa`a````````````baaa`````c",
"ba``````aaab`````````cba`baa````````baa`abc``````````baaa``````c",
"ba````a`aaaab```````cbbb`b``cccccc`baa``abbc````````baaaaaa````c",
"ba````caaaaaab`````cbbba``ccbbbbbb`baa``aabbc``````baaaa`aa````c",
"ba````caa`aaaab```cbbba``cbaa``````baa`a``abbc````baaaa`aaa````c",
"ba````caa``aaaa``cbbba`ccba``a````baaa`aa``aabc``baaaa``cba````c",
"ba```cba````aa`ccbbaa``cba`baa````baaa`aba`aaabc``aaa````cba```c",
"ba```cba``````cbbba```cba``baa````baa```cba``aabcc```````cba```c",
"ba```cba````ccbbba`b```````baa````baa````cba``aabbcc`````cba```c",
"ba```ca``cccbbbaa`aabbb`````aaa``baaa`````cb`b`aaaabccc```cb```c",
"ba``cba`ccbbbaa```aaaaabbbb`bab```````bbb`cb`aa``aaabbbcc`cba``c",
"````cba`bbaaa```````aaaaaaa`bbb`bbbbbbaaaa`cba`````aaabbb`cba```",
"ccc`cba`aa`````````````aaaa`bbb`bbbbbbaaaa`cb`````````aaa`cba`cc",
"bbb`cba`````````````aa``````bbb`bbbbaa`````cb`````````````cba`bb",
"aaa`cba`````````````cb``````bbb````````````cb`````````````cba`aa",
"````cba`````````````cb````````````bbb``````cb`````````````cba```",
"ccc`cba`````````````cb``````bbbba`bbb``````cb`````````````cba`cc",
"bbb`cba`ccc`````````cb`bbbbbbbbba`bbb`bbbb````````````ccc`cba`bb",
"aaa`cba`bbbcc```````cba`aaaaabbba`bbb`aaaabb```````cccbbb`cba`aa",
"````cba`aaabbcc```bbcba`aaa```````bbb`aaaaaaabb``ccbbbbaa`cba```",
"aa``cba``aaaabbcc`aa`abc```baa````baa`````aaaa`ccbbaaaa```cba``a",
"ba```cba````aaabbcca`abbc``baa````baa```c````ccbbaa``````cba```c",
"ba```cba``````aaabbc``abbc`baa````baa``cbb``cbbaaa```````cba```c",
"ba```cba````bb`aaabbc``abb`baa````aa``cbba`cbbaaa`aaa````cba```c",
"ba```cbba``baaa``aabbc``aa`baa``````ccba``cbbaa``aaaaa``cbaa```c",
"ba````cba`baaaa```aabbc```baa`ccccccbba``cbbaa````aaaaa`cba````c",
"ba````cb`baaaa`````aabbc`baaa`bbbbbb````cbbaa``````baaaa`ba````c",
"ba``````baaaa```````aabb`baa````````aab`bbaa````````baaaa``````c",
"ba`````baaaa`````````aa`baaa````````aaab`aaa`````````baaaa`````c",
"ba`````baaa```````````a`baa``````````aab`aa```````````baaa`````c",
"ba````baaa`a```````````baaa``````````aaab````````````a`baaa````c",
"ba````baa`aaa`````````baaa```````````aaaab``````````caa`baa````c",
"ba```baaa`aac````````baaa``a````````a``aaab`````````cba``baa```c",
"ba```baa``abbc``````baaaa`aaa```````aa`aaaab```````cbba``baa```c",
"ba``baaa```abbc````baaaa`acbaa`````cbaa`aaaab`````cbba```baaa``c",
"ba``baa`````abbcc`baaaa```ccba`````cba```aaaab``ccbba`````baa``c",
"ba`bbaa``````abbbc`aaa`````cba`````cba````aaa``cbbba``````baa``c",
"ba`baaa```````abbbc````````cbaa```cca``````a`ccbbba```````baaa`c",
"ba`baa`````````aabbcc```````cba```cba```````cbbbaa`````````baa`c",
"ba`baa``````bbb``abbbcc`````cba```cba````cccbbba``bb```````baa`c",
"ba`baa```bbbaaaaa`aabbbccca`cba```cba`cccbbbbaa`aaaabbb````baa`c",
"``baa`bbbaaaaaa`````aaabbbba`cba`ccba`abbbaaa````aaaaaabbb``````",
"b`bba`aaaaaaa``````````aaaaa`cba`cba`aaaaa`````````aaaaaaabbbbbb",
"a`bbb`aaaa```````````````````cba`cba``````````````````aaaaaabbbb",
"a`bbb````````````````````````bba`bba``````````````````````aaabbb",
"``bbb`bccccccccccccccccccccccccccccccccccccccccccccccccccb``````",
"b`bbb`aaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaaaa`baa`"
};
