/* XPM */
/* $XConsortium: Crochet.pm /main/3 1995/07/18 17:18:13 drk $ */
/*********************************************************************
*  (c) Copyright 1992, 1993, 1994 Hewlett-Packard Company	
*  (c) Copyright 1993, 1994 International Business Machines Corp.
*  (c) Copyright 1993, 1994 Sun Microsystems, Inc.
*  (c) Copyright 1993, 1994 Unix System Labs, Inc., a subsidiary of
*      Novell, Inc.
**********************************************************************/
static char * Crochet [] = {
/* width height ncolors cpp [x_hot y_hot] */
"198 264 10 1 0 0",
/* colors */
"     s iconGray3     m white c #adadadadadad",
".    s iconGray5     m black c #737373737373",
"X    s iconGray7     m black c #424242424242",
"o    s bottomShadowColor m black c #636363636363",
"O    s iconGray4     m white c #949494949494",
"+    s iconGray6     m black c #636363636363",
"@	s iconColor1	m black	c black",
"#    s iconGray2     m white c #bdbdbdbdbdbd",
"$    s iconGray1     m white c #dededededede",
"%    s iconGray8     m black c #212121212121",
/* pixels */
" .XXXooo.oOO+...++o.+oXXoooooOoo+.o O.+X o..++.OO ++.++++.O+o@@o+o.+ooo++++Oo+.o@@o@X...++o++++++OooX..+.+oX++oo+o+..+@@o+.ooo++OOOoo+++ooo@oo.O+ .oo+++oo.Xoo.+oX++oo+++++O+oo@o@oo+ooX++o.+XX++.OXX ",
"X+oooooo.oOO Ooo.+...+oo@@@X.o..o++O.o+o.o..+o.ooo+.++ooo. +@oo+.+o ...+o+.O++oooo@o+.o++Xo++++Xo++XX+.+.+.o+oooooo.++@o.oo....+..o++o.oooo@o+X.ooooXooo+.+o.++o+o+oo .... OX+ooo++oX+oo.oo+..oo.oOO.X",
"X @oo@@+.OOO.+Ooo...o+ooo@oo.o+o.oo+++.Xo+++.o+...oo+oooo.oo@o+ooO Oo++oo..+o++ooo@@oooX+ooo@+.o++oXo+oO+O+ooooooo++++o.+.ooXX++.++++O.ooXo@o+oooooo+oooooo+++.+@++O#o..o.o++oo+O++ooo.o++o+oOOoo.XO..",
" +@oo@o++ooo+oo+.++++Oo.oooooo+.oooooX..++o..++.+oooooooo.+oo++.O OO.OOO+..o.+oooo@oo+oXooo@ooooo+ooo+.o+ooooo+o@o+.++XXoo..+oooo++oo+.+X+oooooo+oo+XXXooo++ooo.ooOO....o+O.ooo+.o+o++ooO .o.#+oXo..+o",
"ooo@@oX+..oo+......O..o.+Xoooo++XooooX+o+oX+++oXooooooooo+o@o++O .oo+..++++++oo.ooo+++o+..oooX+ooXo++o++++X++++ooX+ooooo+.+++++.++.o+Xo+o++ooX++oo+oooooo++ooo+.. o+..+oo  +ooooX+++o+.O .o.  X++ooooo",
"o@@@@o+O  o+++++.oooOo+++++o++++++ooo++oooo@ooo@@++oo@oooXooooXoooo+oo++oooooooO++++++++.++oXooo@oooooX++o+oo+.+ooo.o@o..++o++++ooooo+Xoo+oo......oo@o++oooo+Oo+++o.+.++  .oooXooo+o+oO+o.OOO.+.oO.+++",
"o@oOo+.OO+.oOo.+++..++++..+++oooX++oXo..@ooooooo@X+++oooooooooo+.ooOO.+++oooo..o+....+.o.oOo.oo@oooo@oooo+.+o+..X@oX@o+++oo++++++o+.++Xo+++.+++++o++o+O.X.oo+oXoo+o++ooOo++oXXoXo+o+.+o+oO.+++oo....++",
"+oooXo+oo+OO  O.+o+++++.oo++++++...oXo+OXooooooX+++.+.ooooooo@o..+..o+oO..O.+o.oOo+O  ooo+++ooXooo@@o@@@@+++++++oooooo++Xo++o++++.+++.ooOoXo..++oo+O.+.oooooXoXXooooo+ooo.Xooooo+oo+++..++ooooooo@o+.o",
"o...++OOo.+oO.+++++...O.o+...o.+...o+oo++@ooX@o.OO.++..O+oo+++ooo+. +.ooOO.++++++oo.OOO@ooooo+oooooooooooo++++o+.oo++++X@oooo+X.+oo+oO..o+.OO+o++XO.ooooo+ooooooXo@o@o+X.+ooooo+Oo+++++X++o.o.++oXo@@o",
"..+.+O   OOoo@o+OOOoOo+++o+o++.+o+.++oooo@oXXXo++.OoXo.+o+++++++oo+.oooo+++oo+++ooo+.ooo++++OOo@ooooooo@oXooXo+.+. Ooo+++oXooXo+++OOo+..o+.+oo+o+o++oXooo+++o@oX+ooooooX+o@@oXXOo.++o+oo...ooo.++oooo@",
".XXXo++.....+XoooOoo+o++o+.+++oo.o..++Xoo@oooo++oXo++++o++.o.+oXoXooXoo.oOo++.o+o.o.oooOOo. O+oo@@oo@oo@ooooX++o++.O+o..oO.++oooXo+o+...++o++++++.+o+ooooo++++oo++++.++ooo@o@Xo+.+++o.o.ooO++ooX+XoooX",
"+oo+oo++++.++.+o++oo++o+.oo+oo+.+.o++oo@o@@oo++Xoo++++..+oX+.oo.+o..+o+oo+o..oo...++++oOO.o+Xo@ooooo@@o@oXooo+Xo++..++oO..o..XXoo++...+.++++++....oo++oooooo+.o.+++++o+++o@@+O.o+o++o+O.+++OOoo++++.+o",
"+++.o oO..++oOXo+o+O++..+oO.++ooo.++oooooXooo+o.+++...++.+++oX++oo++X++oo.+.o.o.ooOoOOo.+...o@o@@@@o@o@@oooo++.++..o.oo++.++.oXoo.oOo++o++.o+o+oo++OO++ooo@oXo++++++++.++.+o.  Ooo+XX+O+oO  O...++o+.X",
"oo.++ooooo.....o+ooOOO.+oOo..O..++oo+o+ooooooo++++.++o+oooo+++++ooOoX.Ooooo+++o++oOo+++++++Ooooooooo@@Xo++o+oo+..+o+.+++  o..oo@+oo++o.+++o+ooX+o+O++..+XooooX++ooo++..+..+X++.O.o+oo+oO oo+.ooO.OO.+o",
".ooo++...+.+..+oo.o+.+.o...++++++o+.++.o+++oX+.+++++oo...++...++oo.+oO.@ooooo.+++ooX@o++oo.+++++++ooo+++.+Xo++oooO.++....+++ooo+oo+o++ooo+oooXXo++OO..++ooXoooXoXo+.+++++....+.o+o+++o.++++.o.+.++OO+o",
"@++.++++++o++oo@..++o++..+o+++.+X+oo++++o+oo++oo+...oO O.+.+++.+++++Xo@+OOooo.oo+++oooX+o+O..X+ooO+o.++..o+.+ooo+oO Oo@oo++Xooo+..ooXX++..++X+XXo+oOO...+ooooooooooO+.o.+...O.oooo+o.+o+.++OXoOoo.. O+",
"+....++oo++ oo+++++ooo++.++....+oo+oO+..oo@o++o+.O.ooooooooo++++ooXooX.  OOO.oo++..+++oo.o+..+o+. .o.+oOo+..++o.  Oo.+...+++oXoooooXoOoo.o++oo+ooo. OoO..+XoXo++..++++oO+++++oX+o++.++++o+o.o. Oo...Oo",
"+++.o++o+++.ooooo+o+++++++++++ooooo+Oooo.o@o++o+++O+ooo+++ooo+.o.o+oo+OoOOO+o++..O.+++ooX++o+o.+O+OOoOOooo.++ooooooooOO.+.O..o+oXoo..oo..+...O+oo++o# OO.+oXXoo++oo..oooXOooooOOo++...+X+X+o+o.OooOO.o",
"+o++++oo O.XooXo+oo+++++....++Xo.oo++o++.+ooooo+o.o.+X@o.++o+Xo.O O.@+.++.ooooo.Oo+oXoX+.X+OOXo..+..OOo.O..+oo.o@o+oOo++oOOOOo.+o@+.+o+++oOooo+oX..XO#O+..+Xo+o+X++oOOoo.o.Xo.O.@o...+ooooXXo+.+.+ooo+",
".++++...O O.o.Oo...++++++++++o+++ooo+. O+.Xooo. ..++X@@oooXXoo++++ooX@Xo+ooOO.+.#.+.++ooooo+ O..+o+OOooO.++o+oo@oOO.++++.+++oX+O+o++OO+oo+++.ooX+.ooo.o++oooo.+oX++.oo++oo++o+o.o++.+oooo+oo+++.+..o.+",
"o++++++o+....++oo+++.+oo++.o.+++oXooo.  .+oX.+Oo+o+X@@ooooo+o.oXoo.OO+oo+oooXXoX..+oooo@oo.o.OO+@.+Oo+o..+o.+@@o++XXXooo+++o+o.++o+.oOO ...OoOo+.+oo++oO.+Xo+ooo++oOO+oooo+++oO.+++o++ooo++oo++o++.+o+",
"o+++++o+++o@o+++++++++++++++++ooooX+o.oOo+o++o++.+Xoooo+X+.+++++.+++++++...+ooo+o++.o++oooOo..OOoO++o+...++.o@+++oXo+o+++o+.+oooooo+++oOOooOOOoo++o..oO  .o.. ++o+O o@@@X+++++Ooooo+++.o++.+o+++++o+Xo",
"+++oooooXooX++++++..+.....++++oO.+o++.ooO.o....o.+Xooo+o+o.++.OOO.+.o+++++..+++.O o.OOo.o@o.O..Oo.o.ooo+O+o+o@o+Xo++++ooo+..+++oX+.o++++...++oo++.oooX.  ... ++Oo+ Oo@@oo++....ooo+.+.o+.oo..o...oOo+o",
"++ooo++XoooX+o++.o...OOo+++++. O.+++.+....+.ooO.ooooXoo+..+oO....++ooooo++++.o+.o #O++ooXo.O++o+O+.O..+o...+oooXoOOoo++....o.o+ooo. Oo++++ooooo...++++.O.o+ooOoO+OOo@@o++..+oo++o.ooo.+OO.+o++.o...Oo+",
"+o+o++++ooXoo+...oOOo+.+XO o+oooo++++o++++OO+..+oooX+o+.o+oo+++++.++++++++.o.oOOOOOo+.++o++O.oX+.+..+++...+.ooo+.o+oo.o..oOOO.oX+oo.OOo+o+++o+Oo+o+o..+ooo++.O+OOO.o@o.o..ooo+oo.Oo++oOOo+@..++OO++.++",
"+ooo++++++Xo+ooo++.++o++oo.o.+o+.++.+.++o.O.++.o+++.++o++++++.o+++.O.+....oo.o++oO.+o..+o+++.+ooo+.+o.+.+o..oo+.++++..+.oOOO++ooo++++X++.+o+oo+ooo.ooO+@oXo.O+.ooX.+o..+oO.+++o+.oo+++.+o+ooo.+.oOo..+",
"oXXo+.++++o+..oo++++++++..++++oX..o++o+oooo++.X+..oo+o+.oo.oo+.+o.+++ooOo+ooOo.+oO++ooo+oo.oooXo...oOoo+o+o+oXO..o..ooO  OooO...++.....++oo+++ooooO+.ooooX+oo..ooo+OXOo+Oooo.o+.o++.+++++.OOoo++ooo.++",
".oooo+.+++.+oO.Xo+o++..oooooooooo.oX++O.@++++oo+...oXoOOooO+o+.o++..o..++o+ Ooo.+.O.Xoo++++ooXo@o.+O XooooO+ooOO+o++o+OO+o#+oO++XXX++oOO..O.+ooo+.o.o+.+o++..o+o+oooOOo+o.+o..o.+..O++++o  X+...Oo+++X",
"+o++o+.o.++++.+o+++.++ooo+oo++o+o+ooo.oOoo.oXo.+Oo..o+ .o+o+oo..oXo+++.++o. +@o.o+oo+oXooo++++@@o+. O+o+++o++o.oOo++o+o..ooOo++X++.ooo.oOoo++oooo..+ +..oX+++o+o++.XOO..oooo.Oo.++++++ooO.oo+...O++Xo+",
"X+.o++o++++oX+X+++.o+++Xoooo++X..Xo+oo+oOo.Xoo+oO+o..ooo+.o+oXX++.....o.+XoOoo.+oo.++O+o++oo++o@+..O.Xo+.+.++.@o+O +X.+++o+O +XXo.oXoo.o+.++XXooo.+o Oo+Xoo++Oo...O+oo+.o.X.ooo+oo++..++o++o+.oo+XooXo",
"+OOo+.O ooOOOooo++o++++oooXXXoXo+oXX+Oo.++XX..oo..O.+@o+...+oX+..oooO..o++++XX.+Xoooooo++++oo++Xoooo++oo++oo..ooo+  o..o+X++++oo.O+++o.++XooX+oo+o.X  .+oo..o++O+...+o.o.++.oXoooooooooo++.oooo++oooo@",
"oO+X+o.O O.+.oX+++o.+.oooooX.ooooooo+O o.ooXo..o+.Oo+ooo.++Xoo+oo@o++.O.++++oo++Xoooo@o+o.o.+o+ooO.Xo O+o..+++o+oo++o..o+ooXXoooOO+oOoO+oooo++oXoo+o+OOoXoO+@o+O++.oo..++Xo++++.ooooXoo.+Xo+oOO+oooooX",
".+o++...o+ooooooo+Oo+ooo+ooo+ooo++++X+ o..o+o.oo OO.+oo++Xoo+X++o.oX++.++o++o.o++o+ooooo++.ooo+XXoooo. o.o+.+Xo.O.+.oo.+ooooX.O+O++oOoOooooXooooo++oX.oO+oooooooo..oo.oo++.+ooo+.XXXooX+o.O++OO++XooXo",
"++...++Oo+.+o+oo++o++.oX.+oooo++++o++ooO+.o+oo.O OooooX+oo+.++.oOO++++.++X++o.+O.oo.oooX.+.++++++o..oXO+..o.+o+.+++o++..ooo+.O  o++oOOoooooooXo@@o.oo.oo+oooo.O.+O+@@Xo+.o.++Oo+O+ooo+++++O++OoX.+oo+o",
"++++.++ +oO+oo+++..+o.+X+++o.o.++.+o+..o+++ooO.oooOoXo+oo.o.+++XO +++.o++o.o+.+oooo.+ooX+.+..+o+.oooo+Oo+O+.+XooX+oO+o+.oo++.+.O.+ooOo+.o@ooXXo@@+Ooo++++ooXX..++OoooX+ooo.++Oo. .o++..+Xoo+.O.oo++..+",
"oo@oo++Oo++o.++.o.+.X+.ooo+o++O+o..oX.OO++++oO.ooO ooXXo++ o++++X.+.o.X+.++o+++oo+X+.X@o++o+.o+o+o.o@oO++O..+Xoo.oOoo++.+oXo+o.+o++Oooo+Xo+XXXoo@o.XooooX@ooX++++oooo+++ooX+.Oo. oo..++....oo +o+++..+",
"o@@oO++++++.+.+o++o.++ooX..++oO.oo++o+. oo+o.O..o  .ooo.o+ o+.++++o.OoX+o++X++.o++.o.X@@o+.o+.o+o++X@oO+.O..X@oo+O.++...+oo++++++...+Xo.oo.oooooo@ooo+.+++++++o++.o+++o+.++ooO .OO++.+X.o+.oOO.Oo+++o+",
"o@.O.+.++O.O+++o.+oOooo+o++++OOo++X++oo.O+oo.oo.o Oo@.o..++++oooO.o.oo++O+XoX.+o.++.oo@@oo..o++ooooooo+o. .+oooo+Oo++.Oo++ooo++.o+oo++++XXO+X@o@@@o++o+++.OOOoO.++o++XoX++XXooO.+.++oo.+O+OOoO. +..++.",
"ooO.o.+.+O#O o+o.+oOOXO.o+++...o+.o++ooo..X.ooooooooX.+++Ooo+XX+ o+O+.+.O.++o+++++o+o.o@@oo.o.+o+ooXoo+o. OoX@o+OOo.+.O.++ooX+++O.o+oOoXo.O+ooooo@oooo++++.o.++ooooooo++++oo+Oo.+.++O+ooOoOO+o+.+O+ooo",
"@++oO.....# O.o+oooO .O+oo.o++o+O+oXoooXX+o+o+o+.+.oo+X+OO.oooXo#++O.+....+.+++.+++++o+o@@oooo+ooooooo+o+oO+oooOO++o+oOoo+ooooX.o+O+.O.+oOoooooo@@oo++o+..+oOO.+..oXXoo++++O+oo+.o++oooOOOO#+.oo+.+Ooo",
"oo+Oo++o+oo +..+XO.OO+.+OO.++oooOoXoooooooooooo++o.o+o+.O.o+++oO o..o++O++ooo+O.X.+o++++@@@@+Xoooooooooo+.o.oo..+++X+.O ++oXoooo..O+oOo.Xo+o@oo@@+.oo+.oo.+.ooOO..oo++++oo+o..o..+.+.OO#OoO#.oo.o+OO++",
"oX+O.+o+OOooOo.+o++.O..+OOXoo+o+OoXooo@ooo++++oooo.ooo.oo@o+XoXOO+O..++ o+Ooo+O.X+.o++++oo@o@oo@@o@oo@@@o.++oooX+.+o++oo+o+oX++.OOo+O o++oooooo@o+oo+.o.+oo+.ooOOO+oo+Xo@++.oooo+.++.Oo.OooOO@+.+XO.o+",
"ooX+.o@o+OO.oO.+ooo.o+o+.OooXo++Oooo@@oXoooXX+..o+o@oo++o@XXXoo++++++oO oO.+++O+o+oo+o.+@@@@@@o+ooo@@o++ooooo++o+ooX++o.oo++o+oOoO.+O +++++.@o@+o+++++oooo+++..+oo+oo@o@o.++oo+O++o+o..+OO. .oo+ooOoO+",
"ooooo@o.o..o.O.+o+o++o@Xooooooo+ .oooooo+++..+o+o.o@o++oooo++oXXo+o++Xo.  o.+.Ooo..oo+ooo@o+.++++oooo.OO+ooo+.+++ooo++oo.++ooXoo..ooO++++.+oo@@++o..+++oo++++o+o.o+X@@o@oo++o+oO..O #O+.O.+.o++oo++o+o",
"oooX....ooo+++XoXoooo@@oooooo.o+O+o..++o++++++oXo+oooXXo+.+.+++++oooX.+o oXoo.O+o+++++.ooo++.+oo+o+o+.oOo+o+.+++o.oooooO.+oooo.+.o+.o.o++o.Xo@@++.o+ooo+..+oooo.O+++@@@oo.++oO+.o.+oO.++.+oo.oooo++oo.",
"Xo+.++o+o++o+++ooXooo+.oooo+X++o+o.oo+...+o.++++oXoo@ooo..oo+.o++ooo+++.+ooo+o+oo+oooo+ooooooOOo..++..++oo+++Xoooo+ooXX++++.++++o.O+o.+++.oXo@o+.+++o+..+oo++++oo+o+o@@oo+oX+oo+.O.+..+o++++.+XXoo+o++",
"++.+++..+o+oXooXoo+o+++oooooo+.ooooo+.oO.+o..++ooooXoo++oo+o.oo.+oXooXo+++.+oo@oo@oXoXo+oO.++.OOo.+.O....+oooooo+oXo+oXooo++o+o+. OoOooo.+.+@o++++++.+++o+.++++oXoooooo@@ooooooX+o.+++++.ooXoXXooooXoo",
"+++o++XX++ooooXXoo++Oo.+++Xoooo+o+oO++.OOoo+++.+XoX++o++++OOo@.ooXXXoooXo++Xo+ooo@ooooo..+o+.+oo+++o+.Oo+++o+ooooo+..+oooo+o+o+.o +OooooX+++oo+o+++o++o.oOOooo.+++ooo++++oXXXoooo+o.XX+O+Xoooooo@ooXo@",
"++++o.o.+oooooooooX++.O O.+ooooXo.oOooX.O+ooXoo++o++XXo+OOooo+ .oooooooo@oXoX..++o@@oo++oooO.o++++o+oo++...+++++++o+oXoXoooo++..Ooooo+XoXooooXo+.+.++.ooO+++o+oooo+++o+o.+o+++oooo+oXoX..o@ooooooo@oo@",
".++oo.+ooo+oo@oooooX+++O..oo+o+oooo+++.o+oo++++OO++o++o O+o++oo++Xoo@@oo@oooo+O.Oo+ooooXX.++oo.o..+.++ooo++++oo+++o++++ooo@o+..o.o+o+..++oXoooo++ooo+..+++ooXo++.O.++o+++.++++Xooo+Xoooo++oooooXoX+o@o",
"o+o+oo.+.O+oooooo@@o++oOOoo.++++ooooo+o.oOo+oX++o+.+oO.oXooO..o.Xooooooooooo+o+o..oO.oooXoo+..X.O++++oo+o+++++++oooOo++Xo@@o.OooXo++ooo+++oXooooXX.oo..o+.o+o.++.+oo++++++.++Xoo+.ooo@@o+o+o+X++oo+O.o",
"o.o.Oo+O .ooo@oo@oo@o+.+oO  o+o+++XoooO o.+o+..++OO.O.oo+OO+++++oo@oooooooo++oX+.o.oo.+++XoXo@oO.o.+o++..+++.+++++..+.+Xo@o@@o++o+X..o+Xo+++++oooooooO+.+X++.+o++++++.oOooo.+.+o++o@@@@@o+oo++.++.++++",
"++++.+oO+ooo@@o@o@@oo.+++.O Oo.oo+++.O.o+o+..+oOOo.+X@+.o.X+.++oooooo@o@o@X+..+o+.oooo..++o+o@.O+oo.oOOOOoOo...+oOoO.+ooXo@@@@@@o.++.+oXo+oooo+....OO.++oX+OOo..+o+ooo+o++.o.o+...+o@@@@oo.o.+++oooo+o",
".++..o.+.+oXooo@@o+++.+.+o++.ooooo+++.O.o+++oOOO.o++o+.+++...+X+oooooooo@o+.++.Xo.+o.+++ooo+o@+..o Oo++ooo.o+oooX.+OO+oO+ooooooo@oO+OO+++ooo++....++.+ooo+o+..OOOO.++o OO..+o+O +.Xoo++o.+o++ooo++o+.+",
"++oX++.O+O+oXXooooo.O+OO.++++o+++.++oo++o+o.OOooOo.++.++.+o+oo+o+oXXooo@+...X+.O+++++++oo.o.+oX.oo.+Xo o+o+ooo++.+.oOOoO +ooXoo@+OOo.o++++..oo+...+o+oooXo+o+++....O### Oo.+ooo.+oo++++Xoooo+.o+++++++",
".+ooX++.+..ooooooOoO.o++.Oo....+o.+.+..++ooo++.oo..ooo.++oo+OOO.+++oXoo+OO+o+++..++.+++.....+oo+o+..oO.+.o+ooo+o+o..oO.+ Ooooooo+.Oo.+oo++++o.+++.+..o.o+o..++o+.ooOOOo.+oOOOOO.+o+++XXXoooXo+ooo.....",
"++XooX+.o++X+Xo+o..o+.+oo.oXo++++o+++++.o@+.o.o++.o..++oo+Xo+   oX+ooo.OO+o.Oo.++++++ooXoooooXo+.o..o+O..+.OX+oXo+oO.oOo.O.ooo+.oooo..++...+ooo.+oo+.++.+o++XX++o+.....+++.ooO O+++.Xo++++o+oXXo++++X+",
".Oo+oXo.oOooXoo..o+.o+.Oo+oooooo+++++++oo@o++oooo+oo++.+o+Xo+.OOO+Xo@XOO.++Xoo....oo...ooo+.+++.oOoO+...O. o+oooo++XO.o+O+.o@o++o.+++oXo+ooo+..+ooooo++o.+.oo++oooo+.+.o+X+o+   +.+X@++.Xo+oXXoo@ooooo",
".+oooo++..o+oo.o...O+..OoXXo+++++oo.+++X@ooooXooooooo+o++.+@o+.OOOooooO++++OO.+o++oOo.o++ooo++o OOO+ooo+oOO++XXoo++o.oO..o+ooo.oo+.oooo@oo+Oo+oo++o++.+++o+Xoo+++++o++oo+o...o  oo+@o++o+.+oooXo++o+oX",
"+o++oo+o.++.+Xoo.+o+oOXoXXX+++++++oooo+oooX++++++ooo.O.+o+Ooo+o+.+.oo.+o++O .+ooooo++X+OO.o+ooOoooX.OOOOooo+oooo..++.+O +O+o+OO.++++oXooo++++..+++....ooo+oo+o+++.+++o++Xo+o.Oooo.oo.+++.+XXo+Xo++++oX",
".o+.oX+++...+oo.+.+oO+ooooX++++++++oooX+Xo.O.+o+o...++.+o+o+o.+++o+oo++o.Oo.+ooXo@@oo+oO+oOO o....ooooooOo.o.oO  o++Oo. o.X+o..Oo+++Xo@++++++o++.o.ooooO+Xo++..++..+++oXo+.+Xoo+ooo++o+.+o..+oo+++Oo++",
"+++ooXoo..oO++o++.+.+.oo+.o+++ooo.o++ooo++o+oo++++...o+++..oo+..O+X+ooOOoO...o+oooXXo++o.  O....+.oo+oXoX+++O # .o.oO+o.o+X++.Oo..++o+o+++oo++oo+o+.++OO.O++.oo...oo..+oX..+ooo.o+X+o+oo+..oooo+o+.o++",
"+oXooo+oooo++++o+oo+oo++@o.+++.oOoOo+ooo++oX+.o.++OOOo.+o+.oXo+.  +o@oO.OOoo+oX++++o+oXoOO+ooo++oo+++++++oX+..+oXoX+.Ooo.oooo +o.+oooXo+++++.++++++...O   oo...+oo.O O.+Xo.+Oo++o++oo+X+o.o+oo+++.oo+.",
"++++++o+o...Xo++..+o+.oXo+oo+.+...o.+++oo+oo..+oo+++.O  .o+o++o+O Oo+ooOO.o.oXo++oo+++++Xoooo.++..ooo....+o+ooooXXo+.+.o+Xo+ .o.o+++oo.++.+.o..++.O+.O+..o.. O  O.++++o+ooO.OooXooXXOo+Oo++++++o.o++++",
"ooOo+o+.o++.++O.o...o+@+o.+++oXoo++++oooXX+..+oXo++++o..+.o.+o++.Oo+.O+o.o.oX.o+O.++.ooo+o@.o+++...+++++++o.+oooXo+.oo.oooX+o++++.++o+O+o+++++...O+o+ ++o..+...ooo.++.OOoo +O+ooooXo o.o.o++oooo.OX+++",
".+.+o++ooXo.+oo.Oo.oOooo+oX+Xo++++.oO.oo......+ooO.o.o+++.++o.+o++o+o+++o.+oo.++Oooo++.o.XoOo++++.++++.+++o+oo+oX+o.Ooo+ooo+++.o..++.+o+Xooo.ooo++o.o.oooooo+.+++.oo++O+++ +O+Xo@oo+OOOo++oooX+o ooX+o",
".+oo+++.oX.++o+o.+oO+o@o+++o+.o.oooX+oooo.++.+++oO ooOO.o.++o++ooo++++.+o+o++.++.o.+o+++.o.o.oOo..+.o...++oooo.oo+++O Ooo@o+.OX+o++.o+X++XX+ooXooX..OOO o.+++oo+OO  .+oo.+ .o.X@oooOooo+++ooo++o +ooo+",
".+oo+++X+ooo+oo.o.+oo+oo.OoooO.++o.ooOOo+..+o.ooX. Oo+o++o++++.++oo++++OO++.+..+.oo.++++o+OooOOo..o+....++++...o+..+.O OO@oo++o.o+.O oXooo++oooo++oo+OOO++oo++o++.  Ooooo...oO.@o@o+oo+o+XXoo+o .o+X+.",
"o+ooo+++o+oo+O++o..o+o+o+++Oo .o+++.oO+X++o.oo.o.o+OO+++o+o+o.o. o@o.++O +o.oo++..Ooo.ooo..OOoo.+oO OooOOOo++++oo+.++o OO+@ooo.ooooo .o@o+.o++ooo.++..oo+oooO..ooo+o+oooO.++.. +@ooo+oo++Xo++ooo.O+o++",
"ooo+X.o.o..oo..+++o.++++ooooOO+oo.++.++++oo+++oO+oX+ .ooo+o++.o. O+ooo+++.O.oo++.+o+.o.X@oo++o.++oo.oooo.o O.++oo+..+..oo.o@o++OoooO .@oXo+o o+XoX+...oo+o+Ooo+@oo@@oooo.o++..O +o.+oo+o++X.+O++OOoXo+",
"oo++o.O++o+oo.+++.o+.+++o+.oOOoooo+.oo..+++Xo.++oo++o+++X+oo++oOoO+o+ooX+oOO+o..o.o++...ooOo+.+o.ooX+.o..++.++X@X+oOo+..+++oo+o..oOO +o+.+o. O+o.+o++.+XX+oOOo+oooooooo@+.o+..o O@o+ooooo++OoooO .oXo.",
"oooo.. oooOX@o+++o.oo++oo+.OO+oo@@..o..ooo+...oXo.oo.o++++oo++oO.o+++Xoo+.o.+ooo+o.o+.ooOOo.o+o.oo+oO..OO...ooo@X++o O+++.+ooOOOo .O oo++++o Oo+o+oo+o.Xo..# .o..X+oXXX@o.o++.OO +oX++O++.oOoo+OO.oo++",
".oo@+.  .+ooX@Xo+.oo+.+oo+OO+@ooo+oo.OOOOOOooo+o.+o.oO+ooooX++OoO..o+o++....oo.+.O.++oXX....+.+oo+oo OOo..+++oooo+++ #.Xo..o+Oo..O+oo+o.+ooo.o.+.+oo+o@+++.$Ooo++o++oooooOo.+oO. .oX.O.+o.OoX++OO+oo+X",
"..o@o.o OX+O+oooooO.+o.+XoO+oXXX.o.++oOo...o.+o.o+.OooOXXXoo++ooOo..o+o+++.ooX+OO ++O.o.o...o+++++oo.oO..o.+oooo+X+o.OOoXO.o+.o++o.oo+.+o+.+.++...+o+oo++oo +oo+Xoo+o+.+X..OoO.+ oo.Oo++.+O+X+oO+++o+o",
"+.o@o.+OOooOoooo+.O+OOo+o+o+.+++..ooo+.o.oo.+@o o.o.+o+oX+ooo+.Oo +O+.o+++oOXo+ ..oX+.ooOO Oo.o++@.O. .++ooo+XXooo+++OOo@OooO +...ooOooooo+...o++oooooOO+oO+ooo+oo.+o+.oo+.+oOOo.ooo .Xo+O.X+..o++oo. ",
"o++o@++.o.o+o+oo+... oOXoooooO...oo+++...O.+.o o..+o+.oo++@oXoo..o....+X.+OOX.o+ooo++oooOo.+oO.+ooO+.o.+X++++XXooo+++++oo++oOO+.ooO..@@+.o.o+.O.+.OO OO++..++oo+oo.++..+o.+o+oOO+X+o Ooo..oo.+Xo+oXX++",
"+ooo@o+o+.+o++oo+++.o.oo@Xo+++o.+oOo+oO.+o+..oO...++..+oXooooX.o+++o+.++++o+oXooo.++.o.+++oO ..oooo+...+oOO..oooooo+o+Xooooo.O+.o+ +o@+..+Oo++....O+.+X+o++o.oo+o.O++.+ooX++o+.+ooX.o.++.oooXoXooooo++",
".oXo@o+oXooo@oooooo+oo+@oo.+..o++o.+o. ...o.+OoOoo+++o.o@oooooX+ooX@o++O++ooo@@X++.OOOo+...ooo.+X+.o+..++ O+.o++XoX+oooooXooo.+++. o@ooO.ooo.+.+O. ++++O.+oO+ooo+Oo.+..X@@X+.oo++++oXX+oXXoooooXoXoo+o",
".+oooooooXooo@oXooo+Xoooo++++oo++++.o+ o.++.o OOo .++o.o@o@@oo@oXoo@oo+.ooooo@@++oo++o+oO..o.o+o++o++.o++  O.+++Xooooo@ooooXooXXo+.oo.OO+..+oo++OOO.++Ooo+Ooo++X+oO++o+.@@oX+o.o++..+oo+oo@@o@ooooo++.",
".oooo@@oooooo@oooo@ooooooooo++o+++OOX.O..++OOOooOO..ooO+oooo@o+ooooooooXoo@oooo+Xoooooo...+OO++X++. Ooo..  oooo++o@oXooo+++o++ooo+o@o.++..@X+oooOO ++.O+ooOo+..++..+oooO+@oooo++++.++++.oo+o@oo@@o+o+.",
"oooo@o+.+Xoooooooo+ooooXXoooo@o++oo.o.o..++OoooO +..OOo+Xooooo+o+.oo+Xo++.ooooX+++++oooo+++.o.oo++o  o+OooOO.Oo+ooo@X+++.oOO.+.+ooo@o+Xo+oooo..X+Oo+++.+. .++.O...+.oo.o+o@o+.+++oO...++.Oo.o@oo@oo+o.",
"ooooo+oXXXo+++...oo++++ooooooXoo.o..o.OO++oO+.OOo+.OO.+.oooo@ooooOOOo+XXXo++oooo+.++o++oXoo.o.++o++ O.oO.oOOoo.ooooX+.+ooooo+++.+o@oo+ooo+XooX.o+o.+++++..O+o+.++o+++O.++o@+oX++++++++XXXooooo@@oX..o+",
"X.oo++o++++....++.++.++++++OooooO+o.+.O .+oO+.O +++O.++.ooooooo+..o...+Xo+o++ooo+.++XooXooo.OOoOoo+ooo.++.O.+o++ooX++o..+++++oXoooooo+++++++oooXo..+o.+oXXo++ooooo+oo.o+oo@++o+ooooXXooo+..o+oo@Xoo.o+",
".o.+XooO+o....+++..++....o...++o+.+++.+O.+ooo.OO++.oo++.+o@X++oo++..+Xo++++++.O.OO.ooo++ooo+OoO O+++o.++o..+o+o.ooo+OoOOO+++++++XXooX...oO.oo+ooo++oo.++oX++X+OoX++OO.O..@oooooo+.o..oooo.+OOO.Xooo+oo",
"+oXo+o.oo+o .++++++o+oXo+...OO+ooo+o+..o.+++..oo.o++++++ooo++oo++oo+.+++o..++o.+++o+o+X+o@ooo+.Oo.. .+++oX+o+oo+o+.OO  O+o+oo.++ooXo++....+++oXXXoo+..+XXXooX. ooX+oo+ o+oooooo+++.+++.++.oO O.+oX..oo",
"XooX+..+OOO.+ooo+o++.oo++.o.+++++oooo+o+++++.+o+..@ooX.+ooo+o+oOOX+o+o.oo++ooo+XXo+.oo.+oo@oo++..+o..+++o+X+.++Xo.+++++X+oo+++o++...++..++.+++XoXoooXo+oXooXoooXoooooXOo.oo++oo+oX.oooo+.++.oO +@@O#Oo",
"@oooooOoo.++o+....+oOooOOooO.+++oo+..o+ooX+.o+.oo@@o@+..ooX+..o.Xo.oo.+.+o+++oo+++ooO +oX@oooXoOO++++++ooX@XOo+o+oX+.++++..+..++++...oo+oX+.+++oo++o+++oXooooXoooooooo..+oo.o.o++++..o..++oo.+Ooo@+o.o",
"XoXo+.+o.+o++++o..Xooo+oOO..+++Xooooo++oooooXooooooo@+o+Xoo++.OO.+oo.OO+oo+ooXooXooXOO++o@@@@@@o.ooo.oXoooo@.oooo+OO++.X+.+.o+.oo...+oo+X+.+..+oooooo+++oooooooo++oooo+++++..++o.oO   ..Ooo.oXo+X@ooo+",
"+oooX+X.++.+oooooooOo+oo@oooo+++X@Xooo+X.oooooooooo@oXoooo++..o.OOoOOoo+.o++.OoXo++++++o.+@oooo@@@oO+o+ooo@@oo@@.o.+.O+OO++X.OO.oOo.oX+++OOOO+o@oooo@@ooooXoo+XX.+o+o+oooooOoo+o.+..+ ..o.oOo.XX++.Xoo",
"+o++oooo++oo++ooo+..+ooooXooXo+o.X+o@@@o.ooooXoooo+++ooooo+.OOOoo.++oo.o+.O  OOooO++o+oo+Oo@o@@@ooo+.o+X..oooooo+oo+..O.ooo.O..o..+o+Oo+OoOO.o+.o@o@ooooooooo++@.oo+Xo+o@X+o+...+o...+.+..+++oo+o.+ooX",
"++o+.ooo+o++.oo+o+++oooX@o+oX+oo..ooo@@@o++ooXo++oX++..oooo+.o.oXo++oOo.OoOOOOOo+o.+o+oX++.+ooooooo++o++.+ooo+++..oooo@@@+..oo.++oo+oO.o.oO.o+o.+oo@oooooooXXooOO.o+XX+o++.+....o++.Oo+OO+oXo.  oXo+o+",
".O.+.oooo...+++++.+++oooX@oO.o+o.o.oo+oooo.oXo+.O.++++oooooo.o.+o+X+.+.o.+o+++oo@@X+.+++o+.++oXoooo+OOo+.++oXooo+++++++oX o+++..+++++...oo++oXo+++oo++oooooo.+O.oOoXoO.oXo++++++.+...oo+ooo+.Ooooo++o.",
"+.Oo+oo+.o++.oo+++o+++.++X@o Ooo+OOooo+oooo+o+++oOoOO++OOOOO...oo@ooo+++.ooooooo@oo++o.+oo+o.+ooXo@oO#+X++++++o.oO OOooo+o+o+O.o+++++Xooo.+XX++o+++o+++ooooooo.oXOO++oX++++oo+O  O.oo++..oOO+ooo..+ooX",
".o+Oo+oo..++.+..oooo+++ooo@oo#O+++oOooXXooo+oOoo....OooOOOOOo.+o+.o+++.+X++++oo++.oo+oo.+oXo.++oooo@o O++++Xo.oooOoO Oo++OoOo.o+oX+XooooX+.++o++o+.o+oXooXo@o..+.+oo.+oo+++++o+o+o.Xo+oOOO.ooo+++o++oo",
"++X. o+o..ooXooooo++..+++Xoo+. o+ooo +XXXoo.+++++o+.O.oo.OOO.+o.OOo..+oo+.++++++oo+oo++.++++.+oooXoo++.++o+..++.oOOo++oo@o O+oo+oo..+ooXo+o+oX.++Xo.oX+++++o@ooo.oX+.++o+++++ooooo+ooo+ooo++.+o+.o.++.",
".++oO+o+++oo+++++...++o++oooo++..+X. +oooo@oOo+ooo+++++.ooo+X+.+oOOo.+ooO++..oo+++ooXo++++..ooXo+oo..Xo+o+++++...+.oo.ooXo+o+.++o+oooo+Xooo++.o+.o++ooo++ooXoX+o.+o+O+X+++Ooo.++oXo.o+XXo+++O ..+..o+.",
"++++.+X++oo++++.+++o++X.+ooXooo++oo..+ooX@ooo+.o..++oOOOo+++..+oOOoO.o++O.++..oOoXXoXoo++.+++O.oXo+.+.+.o+.o..++.+++Xoo++oo++++++++oX+o++oo+o++o+O o+oXooo+o.++..+.O.oO..o++++oooo+++++X.o.++..o+oXoo+",
"o+o++oo.+++oo+oo+o++.++oooXo+oOOX+++ooo@oo++X+oOOOOO.oOOoo.O.+.oOOO.o+.+o+o+++++.+oooo+o+.+o+..X@ooo.++.O++oooooooooo..oo....ooO.OO++..+ooo.+o.+oooo..oo+.O..+XoOO++...oOOO.oooooo.o..+.OO++..++o+ooo+",
"+oo.ooo+++oXo+oo+oX++++Xo+o++XX ++++OOoo+oO++++++o.  O.+X+o.+.  OO.+.o.oo.o...+++.Xo++++o.o+o++oo+.+o+OO+.o@XooooXoo.O++..o  OO++.+.o.+o+X.o.+o.++++O+o.Oo+..++o.Oo+.o.o.+Xooo+++.oOO+o++oOOo..o+XXooo",
".o..+o+o+ooo+o oo+ooo+o@+o++++o+.oooo#O.o o..oooXXo+o+X++ooO  O+++o.o++++.+..Oo.++oo+++o+.+++oo@++++. O.o.@o++++++oo+++..o.o.o+.o.+++..Xo+oX+o+.+o.++Xoo.o+.ooOOO+...++..+oooooo+o  +Xooo+.....+oo.+++",
"+o.++XXX+o++ooo o.oXXXoo+...+++o.++o@XO  Oooooo+oXo@oo+OOooooOo+oo.oo+ooo..oOOOoo++oo+oO+o+o++Xoo+oo ooo+XX++o++..o.+++oo+o++....+.+.Oo.+oOo.+o.+o++ooX+o+o+oo O..+ooXoo+ooo@+O..OO+oXo+oo++...++..+++",
"..O.XooooX+o+.ooOoO+ooo+oOOo.+.X.o+.@ooO+o+.o..+oo@@+o.ooo.++++oooo.+++o.oo+. # .o++++o.o.o+o.oooo+oo.+ooXXo+++.oo.oooooOOo+++++++..ooOoO+.oo+X.+++.Xoo.o.++o+.+++X@ooooooo@ooo.+o++oo++oo+...+OOo+X++",
".oO.++++Xo+oo+oX..OOoo++.OOo+..+oo+o.+.oo+...o+Xo@@o++++.oOOo+o++ooX++o+XoOoo+o  .+.++.oo.oo++oooooo+Xo+ooXoo+o+.O.+.+oOo..oo......++oO.+XooO.o+oo+ oX.+.++o.O++.+@ooo+ooo+oX.o+oo+o.++ooXo+XoX++++++o",
"ooO .++o+++o++oo+o.OooX..OO.+..+.++oo+oo..+.o.ooooo++o+++oO.+oo++.Xoo.+o@+  oO+.ooO.o+o+o.oOOo+ooooX+o++ooX++.oO..+oooX++.ooo+oO.++++ O+Xoo+.O+.oooooo...++.O.++ooooo+..++ooo+++oO+.+++XooXo+++++o++++",
"O.oo+o+oo+oX+++@++X+XoooO...+oo.+oo+ooo.++OO.ooooo.o.+ooooo+++oX++oooooo++. O....O.+oooo++.OOOO+@ooo.++oooXo+++.+o++++ooO OOOOo++o+OO+XooXo+oO.+oo@@oX+Ooo+O.o.+oooooXoX+.+X++...o.++.ooo++++.+++o+++o",
"oO.+XoOOo++o+o+oXoXXoooo +.++o.+..oo++.++OO++oXoo...+o+oo+++oo+++o+o+ooX++Oo  ..+++oo+.o+++.Ooo.@oo+.oXo+o+XXooo+++.oo.oXo ++o+oo+o+O ..+X+ooOOoo@oo@oo+o....Ooooooo+o+++++O+++++.++.+oXo+X+o++o++++++",
"..+.++XOoooX.O@ooooooo@+O.+.+o .o+ooo++++.+++oo+oO..++++.+++++++o++o.o@+o+O.+OOo+++oX++O.+oo.+oo+oo+++oooo+Ooo++++++.+.+o+.+X..+ooo+.o.+Xo.+o+ +@o@@oX+oo+.+.oo@ooo.++.++o+.O.oO.++.++oO.Oo.++++..ooOO",
".o.+o+.+o+++oXoooooooooooOO+.O# ..ooX+o++o.++++o+o+o++...OOoo.+++++ooo+oooo+oo+..+ooo+o+..+oooo+.o++++++++++.+o++.+..+++.O+.o+.+ooXoooOO.oo++o.oo@@@ooooo+++.oooooo..o++oo+oo.++++o.++ooooo.++o...+.Oo",
"++o.o++++++.+oooo+oooooooOo+oO  Ooo@ooo++.O+.++oo.+o+.oO++o...o....+X++.oo. Oooo.oXooX+o.+++ oooooX+X++++.o  .+.o...+Xo...o+oo.+oo.O...ooooO++O.+@@@+O...++.+++O++X++oooXo+++o++++++oooo.OOo++o OooOo.",
"++o+oo++o..++oooo+ooooooX..o. Oo.O+XoooooOO+.++o+oo..OO++++++ooooo+oo+.+++oO++o+..oXoo++o+.+O.o+++Xooo+.+..+o+..o.+++++.oo+oo@..oX++oo@@ooXOoXoo+o@@X.+.o+Xo+o++++ooo+++ooo++o+o+..ooooo+.OOO..+....oo",
"o..o+O+.+.++XXooX+oo+oo@o.+o.O#o+OoX@ooooO.++++.ooo+oo.+oX++o+++..+o+o+X+..+o++oooooooX.+o+++.++.Oo@oo.o+oo...o OOo.+.+o.++o.o...o++.+.oooo..+XO.+o@oo+++ooooXoooXo++++..++++o o.o.Xo+.+++oooO..o.++Oo",
"oo+o+ ++.oOOoo+++o..+oo@X .+.+Oo++.+@o+o+.o..++Oo+++.O+oo..++X+ooooooo+o+ o+.++.+oXoo@o...oo+++oo..@Xoo.+oooO.OOOO   O+++..++X+.oX+oo+.Xooo+.oo+O+.XX+.+++oo+oooX+++ooO.+++++.ooo.ooX.oooooXo++o.o+oO+",
"oo.o+O++.OO.o..++oo++oo@o ooooo.oXXoo@o+o+.Oooooooo+O.Xo+o.++o.+oXo+o+.o. .+.oo..+oooooo+..@oXo++o+ooo.+oXooo+..o oo.+o++o.+ooo+o+o+.+.+XX@oOoo+ooo+ooO+++++o+ooo+o+...Oooo. OOoXo@@+.oX+o+Xooo+oo++++",
"+o++X.oo+OoX+O....O++ooo@OO.ooo+OOoO+@ooo+O.OOoo+.+O.X...o+X+o+XXo++++.ooo.OOOO+o.+o+oooXo++oooo+oooXXo++ooooo.+o+o+++oo+o.oo+o+++++.X+o+o@o.O+o+X+O++.+o+++..oo...+.+++ooO+@++ooXoooo+o+oo++oo@@X++++",
"..o.o+O .#oo.OoO+oO.+.+o@Xoo+o..o o.+oo++.o+Oooo+...oO .+O+o.++.o.o+++.+oOoooo o+++Oo+oo@@ooXooooXoooo+ooooooo.++oOooooX++ooo+.++++.o++..+@@+ooXoo+++++ooo++o++Xooo..o+++oo+ooooooX+o..O.+o+.oooX+++++",
"+++o++O o#.ooO. +o +++..o@@O+++O.OO.o@+++O+.O.oo+oo.OO +.O++.oo.o+.+Ooo.oOO.O+oOo++.O.ooo.oooooo+.oo...oXoo@@o.+o+o.XoXooo+oo+.o++ooo++oo+o@X.+.o+o.o+ooo++oo+.Xoo+o.oo+.+o+oXooXXo+++oO.o.+..ooo++++.",
"++.oOoo#oOoOoOo oo +o++..o@oo++OO.OO+oO++o..o+oooX...OO.+O+oo.o+oo+ O+OO.OO.oooo.oooO ooX+@@@X++++o++.o.+ooo@o.+o+o+++ooo++oX.oX+.+..o+o...oo++.+o+o++oo+ooO.++o@o+o+o++.+.o+oXoooX.+o+O++o+oooo@+++++",
"O++. o. +oOO.oO ooO+.O+oo@@XooooOooo++O+..Oo.ooo@+OOooOo+.oO..Oo +..++OO+Oo.+.++++oo+ O+oo@@X++oo.oOO.++oXXXo@+o+++oo+oXX++XXo..oo++.++oo+.+@o+o+oo+o+oo+.O.+++oX+.O+++o+.o..+X+o+o++++o.+o+ooo++oX+++",
"..++OO+O+O O.+OOo.o+.oO+oooooooo++++o+oo++OO+o@@Xo O.Ooooo...oo. O.X++O+.Ooo++.oXo++o+o+o@@oo+..++++.+.+o+.+oo++oo++o.+ooo..o++o+.+.+O++o+.+Xo+.+Xo+..oooOo+o++o++o.o+o.oo+o +.++o++.++.o+ .+.O+.oX+.+",
"+++.+ooo. Ooo+.o++o+o+o.oooooooXoooXXooooX...@o@oOO.o..+o+++.o +OOo+o+o+.o.O+o+Xoo+o.oXoo@oo+++...o++.+++.ooo@++Xoo+o++o+o.O+oX..+o.+O+o+.O.ooo.o+ooo+ooo+++O++oo+.++oX.O++o++ooO+oo+o+++oO.ooo+.+o+.+",
"+oo.o+o+.O.Oo++o+ooooO++ooooooooooXooo++oXXXooo@+o+.+oXo+.o++oOo.O+.oooX+o.+.+oooo+..ooXooo+.+.....oo++++++X+oo.o+X++++o+++O+o++Oo+.oO++.o+O.oXo+o.@oooo OX+o++o++.+.oo++o++X.oo.Oooo.+..+.Oooo+ +o+++",
"o+X.oo+o+o+oX+++oooooOoooooooooooo..++++oooo@ooo+o+oooo++++oXo Oo.+o+ooX+o++o+X@ooX++o@oo.++.oOOOo  .oooo.+ooo@oo+oo+++++OX.++o+o+.++O+o+.ooo+@oXo.X+oOOO O.o.+oXXoX.++o.oo.o+O.+Oo+Oo.+o.+oo+..OooX+.",
"o++OOoo.oo++o.+ooXoo.OO+ooooo@@o++++oX+o++oXX@ooooXo+.++ooo+ooOO+o.o+Xoo.o+oooooX.+o+OOoo+oXo+...++o+oooo+OO+@o@o.oo..oo+oo.o+o...O+. o@+O+o++@oooo++....+..o+ooooooXo.o.oo+.+oo+O+.Oo.oO+OO+oo..+Xoo.",
"oo@oooXoooXOO+ooooo@.OO+oooooo+.+++++...O.o.X+oo++...+oo+oooXooO+++++Xo++.ooXoX++oo+.OoO@@oooo+o++.....+++o.o+@@oo.+o.o.+++++++++..ooOo@oO.Xooooooo+++..oo.o+X@oX+Xoo.+.+++oooO.+++OOOOoOOOoo.O.o+o+Xo",
"oooXXooooooo+o+o+oo@..oo@o@@o+  o+++.+XX+o+++++...+..oX.+oooo@+++++o++XXo.ooooo..+O.+X+.ooooXooo+oXXoX.o+++ooXoo+o+.o.oOo++.o.+o++X+.o@ooOoXoooo@oooooXooo++X+o@oooo++.oo+oo.o.oOoo ooo OO.oo+o.O+@ooo",
"oXXXo@ooooo+++++Xoo@++.o@oooo+.o+oO+oooo.+oooo.oo.+O.o.o+ooXoo++++++.++oo.oXo+++o++o+ooX.oo+++++o++++.O Ooo+oo+o++.+. .O++Xooo.+++o.+o@ooOooo@@oo+.++++++.o+.+oooooo++.+Xo+ooo+o +ooX+O  O+.oO.oO+@XX.",
"oooXoo+Ooo.oo++o.oX@Xooo@o@o.  ++ooo.+oO.++X.Ooo...+.o...o+oo+ooo++..+o@+@@@+O.+OOO.++o++++++ooo..o.oo.oOo++oo+XXo o.O+OO.oX+..o.+O.ooooo.ooooooo.+oo++++++oo+ooo@@@+.+ooo+o+o.oo++.o+  O+.O o..O+@o+o",
"oooo++oooXoooXOO+ooo@oo@o@ooooXo+OOo.+.++.+.OoOOO.o+o..oo++.XoXo+.+++++@@oo+oOO++Oo++o++o++oX+.oooOO.Xo++.o+oo@oX  +. .+O++..+.++..o++X@o++oooo+oXXo++Xo++.o.ooXo@@oo+o+Xooooo+oo++++OOOo+.oo..+.+@@oo",
"X++++oXXooooooo+o+o+ooooo@@o.@o.  o +Xo.O.oO.oOOOoooo+.+X...oooooO+.o.+@X+Ooo. OO@o.++oo..+.oo+++o+oXXoo+.+Xooooo  +.O.+oo++.++ooo.XXoooo+o@oXooo++..o++++oOOO++oo@@o++ooo@oooooo+Xo+O .+oX+++.+.oooo+",
"+O+o.o.o@ooooo....+X+..o.@ooooXO+oooooooo+oo@OO.o+o+.+oO..+o. ..++++oO+++oo+ooO+o+@o@oooooXoooo++oo+ooo.+++o..OX.+.o+oO.o..o.oo+.+oo++.+ooooooo+oOO+oX+..+X+OOo..ooooo+o@oooXo++oo+oo+oo+oXX+.+.+@oo@o",
"..oo +.Oo.oooo+o.oXo++o+oooooX.o+++o+++o++o@o@@.+OOo+o....oX+ o+o++ooo.++..XooO.o.@o@@ooo+++++oo.+ooXoo+oo.O+OOoo+.o+oo+O+.+o++++ooX++++++oo+o+++oooo+.o..+oo+.+ooo+ooo.XXX..+ooooooo.oo++oo+oX.+@oooo",
"O.+X o..++.OO ++.++++.O+oo+o+o.+ooo++++Oo+.o@@o@X...++o++++o+OooX..+.+oX++oo+o+..+@@o+.ooo++OOOoo+++ooo@oo.O+ .oo+++oo.Xoo.+oX++oo+++++O+ooooXoo+ooX++o.+XX++.O+oooooooo+..O.++.oooXo+o@oo.oooooo@oooo",
".o+o.o..+o.ooo+.++ooo. +@oo+.+o ...+o+.O++oooo@o+..+ooo+.o.Xo++XX+.+.+.o+oooooo.++@o.oo....+..o++o.oooo@o+X.ooooXooo+.+o.++o+o+oo .... OX+ooo++oX+oo.oo+..oo.oOO.++++oo+..++o.o+oo+oXXoXo+O.+o+oooooo@",
"++.Xo+++.o+...oo+oooo.oo@o+ooO Oo++oo..+o++ooo@@oooX+ooo@+.o++oXo+oO+O+ooooooo++++o.+.ooXX++.++++O.ooXo@o+oooooo+oooooo+++.+@++O#o..o.o++oo+O++ooo.o++o+oOOoo.OO.+oooo@X+.ooooooooooooooo+oo@ooo+o.. o",
"oX..++o..++.+oooooooo.+oo++.O OO.OOO+..o.+oooo@oo+oXoo..ooooo+ooo+.o+ooooo+o@o+.++XXoo..+oooo++oo+.+X+oooooo+oo+XXXooo++ooo.ooOO....o+O.ooo+.o+o++ooO .o.#+oXo..+oooooooo+@oXoXo+oooooo@o+Xo@oo+.o.+O ",
"oX+o+oX+++oXooooooooo+o@o++O .oo+..++++++oo.ooo+++o+..oooX+ooXo++o++++X++++ooX+ooooo+.+++++.++.o+Xo+o++ooX++oo+oooooo++ooo+.. o+..+oo  +ooooX+++o+.O .o.  X++ooooooooo@ooooooo+...++o.+oXXoooooOoo+.o ",
"o++oooo@ooo@@++oo@oooXooooXoooo+oo++oooooooO++++++++.++oXooo@oooooX++o+oo+.+ooo.o@o..++o++++ooooo+Xoo+oo......oo@o++oooo+Oo+++o.+.++  .oooXooo+o+oO+o.OOO.+.oO.+++Xooooo@o.oOO Ooo.+...+oo@@@X.o..o++O",
"Xo..@ooooooo@X+++oooooooooo+.ooOO.+++oooo..o+....+.o.oOo.oo@oooo@oooo+.+o+..X@oX@o+++oo++++++o+.++Xo+++.+++++o++o+O.X.oo+oXoo+o++ooOo++oXXoXo+o+.+o+oO.+++oo....++oo@oo@@+.OOO.+Ooo...o+ooo@oo.o+o.oo+",
"Xo+OXooooooX+++.+.ooooooo@o..+..o+oO..O.+o.oOo+O  ooo+++ooXooo@@o@@@@+++++++oooooo++Xo++o++++.+++.ooOoXo..++oo+O.+.oooooXoXXooooo+ooo.Xooooo+oo+++..++ooooooo@o+.o++@oo@o++ooo+oo+.++++Oo.oooooo+.oooo",
"+oo++@ooX@o.OO.++..O+oo+++ooo+. +.ooOO.++++++oo.OOO@ooooo+oooooooooooo++++o+.oo++++X@oooo+X.+oo+oO..o+.OO+o++XO.ooooo+ooooooXo@o@o+X.+ooooo+Oo+++++X++o.o.++oXo@@oooo@@oX+..oo+......O..o.+Xoooo++Xooo",
"+oooo@oXXXo++.OoXo.+o+++++++oo+.oooo+++oo+++ooo+.ooo++++OOo@ooooooo@oXooXo+.+. Ooo+++oXooXo+++OOo+..o+.+oo+o+o++oXooo+++o@oX+ooooooX+o@@oXXOo.++o+oo...ooo.++oooo@o@@@@o+O  o+++++.oooOo+++++o++++++oo",
"++Xoo@oooo++oXo++++o++.o.+oXoXooXoo.oOo++.o+o.o.oooOOo. O+oo@@oo@oo@ooooX++o++.O+o..oO.++oooXo+o+...++o++++++.+o+ooooo++++oo++++.++ooo@o@Xo+.+++o.o.ooO++ooX+XoooXo@oOo+.OO+.oOo.+++..++++..+++oooX++o",
"+oo@o@@oo++Xoo++++..+oX+.oo.+o..+o+oo+o..oo...++++oOO.o+Xo@ooooo@@o@oXooo+Xo++..++oO..o..XXoo++...+.++++++....oo++oooooo+.o.+++++o+++o@@+O.o+o++o+O.+++OOoo++++.+o+oooXo+oo+OO  O.+o+++++.oo++++++...o",
"oooooXooo+o.+++...++.+++oX++oo++X++oo.+.o.o.ooOoOOo.+...o@o@@@@o@o@@oooo++.++..o.oo++.++.oXoo.oOo++o++.o+o+oo++OO++ooo@oXo++++++++.++.+o.  Ooo+XX+O+oO  O...++o+.Xo...++OOo.+oO.+++++...O.o+...o.+...o",
"+o+ooooooo++++.++o+oooo+++++ooOoX.Ooooo+++o++oOo+++++++Ooooooooo@@Xo++o+oo+..+o+.+++  o..oo@+oo++o.+++o+ooX+o+O++..+XooooX++ooo++..+..+X++.O.o+oo+oO oo+.ooO.OO.+o..+.+O   OOoo@o+OOOoOo+++o+o++.+o+.+",
"++.o+++oX+.+++++oo...++...++oo.+oO.@ooooo.+++ooX@o++oo.+++++++ooo+++.+Xo++oooO.++....+++ooo+oo+o++ooo+oooXXo++OO..++ooXoooXoXo+.+++++....+.o+o+++o.++++.o.+.++OO+o.XXXo++.....+XoooOoo+o++o+.+++oo.o..",
"++++o+oo++oo+...oO O.+.+++.+++++Xo@+OOooo.oo+++oooX+o+O..X+ooO+o.++..o+.+ooo+oO Oo@oo++Xooo+..ooXX++..++X+XXo+oOO...+ooooooooooO+.o.+...O.oooo+o.+o+.++OXoOoo.. O++oo+oo++++.++.+o++oo++o+.oo+oo+.+.o+",
"O+..oo@o++o+.O.ooooooooo++++ooXooX.  OOO.oo++..+++oo.o+..+o+. .o.+oOo+..++o.  Oo.+...+++oXoooooXoOoo.o++oo+ooo. OoO..+XoXo++..++++oO+++++oX+o++.++++o+o.o. Oo...Oo+++.o oO..++oOXo+o+O++..+oO.++ooo.++",
"Oooo.o@o++o+++O+ooo+++ooo+.o.o+oo+OoOOO+o++..O.+++ooX++o+o.+O+OOoOOooo.++ooooooooOO.+.O..o+oXoo..oo..+...O+oo++o# OO.+oXXoo++oo..oooXOooooOOo++...+X+X+o+o.OooOO.ooo.++ooooo.....o+ooOOO.+oOo..O..++oo",
"+o++.+ooooo+o.o.+X@o.++o+Xo.O O.@+.++.ooooo.Oo+oXoX+.X+OOXo..+..OOo.O..+oo.o@o+oOo++oOOOOo.+o@+.+o+++oOooo+oX..XO#O+..+Xo+o+X++oOOoo.o.Xo.O.@o...+ooooXXo+.+.+ooo+.ooo++...+.+..+oo.o+.+.o...++++++o+.",
"+. O+.Xooo. ..++X@@oooXXoo++++ooX@Xo+ooOO.+.#.+.++ooooo+ O..+o+OOooO.++o+oo@oOO.++++.+++oX+O+o++OO+oo+++.ooX+.ooo.o++oooo.+oX++.oo++oo++o+o.o++.+oooo+oo+++.+..o.+@++.++++++o++oo@..++o++..+o+++.+X+oo",
"o.  .+oX.+Oo+o+X@@ooooo+o.oXoo.OO+oo+oooXXoX..+oooo@oo.o.OO+@.+Oo+o..+o.+@@o++XXXooo+++o+o.++o+.oOO ...OoOo+.+oo++oO.+Xo+ooo++oOO+oooo+++oO.+++o++ooo++oo++o++.+o++....++oo++ oo+++++ooo++.++....+oo+o",
"o.oOo+o++o++.+Xoooo+X+.+++++.+++++++...+ooo+o++.o++oooOo..OOoO++o+...++.o@+++oXo+o+++o+.+oooooo+++oOOooOOOoo++o..oO  .o.. ++o+O o@@@X+++++Ooooo+++.o++.+o+++++o+Xo+++.o++o+++.ooooo+o+++++++++++ooooo+",
"+.ooO.o....o.+Xooo+o+o.++.OOO.+.o+++++..+++.O o.OOo.o@o.O..Oo.o.ooo+O+o+o@o+Xo++++ooo+..+++oX+.o++++...++oo++.oooX.  ... ++Oo+ Oo@@oo++....ooo+.+.o+.oo..o...oOo+o+o++++oo O.XooXo+oo+++++....++Xo.oo+",
".+....+.ooO.ooooXoo+..+oO....++ooooo++++.o+.o #O++ooXo.O++o+O+.O..+o...+oooXoOOoo++....o.o+ooo. Oo++++ooooo...++++.O.o+ooOoO+OOo@@o++..+oo++o.ooo.+OO.+o++.o...Oo+.++++...O O.o.Oo...++++++++++o+++ooo",
"+o++++OO+..+oooX+o+.o+oo+++++.++++++++.o.oOOOOOo+.++o++O.oX+.+..+++...+.ooo+.o+oo.o..oOOO.oX+oo.OOo+o+++o+Oo+o+o..+ooo++.O+OOO.o@o.o..ooo+oo.Oo++oOOo+@..++OO++.++o++++++o+....++oo+++.+oo++.o.+++oXoo",
"+.++o.O.++.o+++.++o++++++.o+++.O.+....oo.o++oO.+o..+o+++.+ooo+.+o.+.+o..oo+.++++..+.oOOO++ooo++++X++.+o+oo+ooo.ooO+@oXo.O+.ooX.+o..+oO.+++o+.oo+++.+o+ooo.+.oOo..+o+++++o+++o@o+++++++++++++++++ooooX+",
"+o+oooo++.X+..oo+o+.oo.oo+.+o.+++ooOo+ooOo.+oO++ooo+oo.oooXo...oOoo+o+o+oXO..o..ooO  OooO...++.....++oo+++ooooO+.ooooX+oo..ooo+OXOo+Oooo.o+.o++.+++++.OOoo++ooo.+++++oooooXooX++++++..+.....++++oO.+o+",
"++O.@++++oo+...oXoOOooO+o+.o++..o..++o+ Ooo.+.O.Xoo++++ooXo@o.+O XooooO+ooOO+o++o+OO+o#+oO++XXX++oOO..O.+ooo+.o.o+.+o++..o+o+oooOOo+o.+o..o.+..O++++o  X+...Oo+++X++ooo++XoooX+o++.o...OOo+++++. O.+++",
"o.oOoo.oXo.+Oo..o+ .o+o+oo..oXo+++.++o. +@o.o+oo+oXooo++++@@o+. O+o+++o++o.oOo++o+o..ooOo++X++.ooo.oOoo++oooo..+ +..oX+++o+o++.XOO..oooo.Oo.++++++ooO.oo+...O++Xo++o+o++++ooXoo+...oOOo+.+XO o+oooo+++",
"oo+oOo.Xoo+oO+o..ooo+.o+oXX++.....o.+XoOoo.+oo.++O+o++oo++o@+..O.Xo+.+.++.@o+O +X.+++o+O +XXo.oXoo.o+.++XXooo.+o Oo+Xoo++Oo...O+oo+.o.X.ooo+oo++..++o++o+.oo+XooXo+ooo++++++Xo+ooo++.++o++oo.o.+o+.++.",
"+Oo.++XX..oo..O.+@o+...+oX+..oooO..o++++XX.+Xoooooo++++oo++Xoooo++oo++oo..ooo+  o..o+X++++oo.O+++o.++XooX+oo+o.X  .+oo..o++O+...+o.o.++.oXoooooooooo++.oooo++oooo@oXXo+.++++o+..oo++++++++..++++oX..o+",
"+O o.ooXo..o+.Oo+ooo.++Xoo+oo@o++.O.++++oo++Xoooo@o+o.o.+o+ooO.Xo O+o..+++o+oo++o..o+ooXXoooOO+oOoO+oooo++oXoo+o+OOoXoO+@o+O++.oo..++Xo++++.ooooXoo.+Xo+oOO+oooooX.oooo+.+++.+oO.Xo+o++..oooooooooo.oX",
"X+ o..o+o.oo OO.+oo++Xoo+X++o.oX++.++o++o.o++o+ooooo++.ooo+XXoooo. o.o+.+Xo.O.+.oo.+ooooX.O+O++oOoOooooXooooo++oX.oO+oooooooo..oo.oo++.+ooo+.XXXooX+o.O++OO++XooXo+o++o+.o.++++.+o+++.++ooo+oo++o+o+oo",
"+ooO+.o+oo.O OooooX+oo+.++.oOO++++.++X++o.+O.oo.oooX.+.++++++o..oXO+..o.+o+.+++o++..ooo+.O  o++oOOoooooooXo@@o.oo.oo+oooo.O.+O+@@Xo+.o.++Oo+O+ooo+++++O++OoX.+oo+oX+.o++o++++oX+X+++.o+++Xoooo++X..Xo+",
"+..o+++ooO.oooOoXo+oo.o.+++XO +++.o++o.o+.+oooo.+ooX+.+..+o+.oooo+Oo+O+.+XooX+oO+o+.oo++.+.O.+ooOo+.o@ooXXo@@+Ooo++++ooXX..++OoooX+ooo.++Oo. .o++..+Xoo+.O.oo++..++OOo+.O ooOOOooo++o++++oooXXXoXo+oXX",
"X.OO++++oO.ooO ooXXo++ o++++X.+.o.X+.++o+++oo+X+.X@o++o+.o+o+o.o@oO++O..+Xoo.oOoo++.+oXo+o.+o++Oooo+Xo+XXXoo@o.XooooX@ooX++++oooo+++ooX+.Oo. oo..++....oo +o+++..+oO+X+o.O O.+.oX+++o.+.oooooX.ooooooo",
"o+. oo+o.O..o  .ooo.o+ o+.++++o.OoX+o++X++.o++.o.X@@o+.o+.o+o++X@oO+.O..X@oo+O.++...+oo++++++...+Xo.oo.oooooo@ooo+.+++++++o++.o+++o+.++ooO .OO++.+X.o+.oOO.Oo+++o+.+o++...o+ooooooo+Oo+ooo+ooo+ooo++++",
"+oo.O+oo.oo.o Oo@.o..++++oooO.o.oo++O+XoX.+o.++.oo@@oo..o++ooooooo+o. .+oooo+Oo++.Oo++ooo++.o+oo++++XXO+X@o@@@o++o+++.OOOoO.++o++XoX++XXooO.+.++oo.+O+OOoO. +..++.++...++Oo+.+o+oo++o++.oX.+oooo++++o+",
"+ooo..X.ooooooooX.+++Ooo+XX+ o+O+.+.O.++o+++++o+o.o@@oo.o.+o+ooXoo+o. OoX@o+OOo.+.O.++ooX+++O.o+oOoXo.O+ooooo@oooo++++.o.++ooooooo++++oo+Oo.+.++O+ooOoOO+o+.+O+ooo++++.++ +oO+oo+++..+o.+X+++o.o.++.+o",
"oooXX+o+o+o+.+.oo+X+OO.oooXo#++O.+....+.+++.+++++o+o@@oooo+ooooooo+o+oO+oooOO++o+oOoo+ooooX.o+O+.O.+oOoooooo@@oo++o+..+oOO.+..oXXoo++++O+oo+.o++oooOOOO#+.oo+.+Ooooo@oo++Oo++o.++.o.+.X+.ooo+o++O+o..o",
"ooooooooooo++o.o+o+.O.o+++oO o..o++O++ooo+O.X.+o++++@@@@+Xoooooooooo+.o.oo..+++X+.O ++oXoooo..O+oOo.Xo+o@oo@@+.oo+.oo.+.ooOO..oo++++oo+o..o..+.+.OO#OoO#.oo.o+OO++o@@oO++++++.+.+o++o.++ooX..++oO.oo++",
"oo@ooo++++oooo.ooo.oo@o+XoXOO+O..++ o+Ooo+O.X+.o++++oo@o@oo@@o@oo@@@o.++oooX+.+o++oo+o+oX++.OOo+O o++oooooo@o+oo+.o.+oo+.ooOOO+oo+Xo@++.oooo+.++.Oo.OooOO@+.+XO.o+o@.O.+.++O.O+++o.+oOooo+o++++OOo++X+",
"@@oXoooXX+..o+o@oo++o@XXXoo++++++oO oO.+++O+o+oo+o.+@@@@@@o+ooo@@o++ooooo++o+ooX++o.oo++o+oOoO.+O +++++.@o@+o+++++oooo+++..+oo+oo@o@o.++oo+O++o+o..+OO. .oo+ooOoO+ooO.o.+.+O#O o+o.+oOOXO.o+++...o+.o+",
"oooo+++..+o+o.o@o++oooo++oXXo+o++Xo.  o.+.Ooo..oo+ooo@o+.++++oooo.OO+ooo+.+++ooo++oo.++ooXoo..ooO++++.+oo@@++o..+++oo++++o+o.o+X@@o@oo++o+oO..O #O+.O.+.o++oo++o+o@++oO.....# O.o+oooO .O+oo.o++o+O+oX",
".++o++++++oXo+oooXXo+.+.+++++oooX.+o oXoo.O+o+++++.ooo++.+oo+o+o+.oOo+o+.+++o.oooooO.+oooo.+.o+.o.o++o.Xo@@++.o+ooo+..+oooo.O+++@@@oo.++oO+.o.+oO.++.+oo.oooo++oo.oo+Oo++o+oo +..+XO.OO+.+OO.++oooOoXo",
"o+...+o.++++oXoo@ooo..oo+.o++ooo+++.+ooo+o+oo+oooo+ooooooOOo..++..++oo+++Xoooo+ooXX++++.++++o.O+o.+++.oXo@o+.+++o+..+oo++++oo+o+o@@oo+oX+oo+.O.+..+o++++.+XXoo+o++oX+O.+o+OOooOo.+o++.O..+OOXoo+o+OoXo",
"+.oO.+o..++ooooXoo++oo+o.oo.+oXooXo+++.+oo@oo@oXoXo+oO.++.OOo.+.O....+oooooo+oXo+oXooo++o+o+. OoOooo.+.+@o++++++.+++o+.++++oXoooooo@@ooooooX+o.+++++.ooXoXXooooXooooX+.o@o+OO.oO.+ooo.o+o+.OooXo++Oooo",
"++.OOoo+++.+XoX++o++++OOo@.ooXXXoooXo++Xo+ooo@ooooo..+o+.+oo+++o+.Oo+++o+ooooo+..+oooo+o+o+.o +OooooX+++oo+o+++o++o.oOOooo.+++ooo++++oXXXoooo+o.XX+O+Xoooooo@ooXo@ooooo@o.o..o.O.+o+o++o@Xooooooo+ .oo",
"ooX.O+ooXoo++o++XXo+OOooo+ .oooooooo@oXoX..++o@@oo++oooO.o++++o+oo++...+++++++o+oXoXoooo++..Ooooo+XoXooooXo+.+.++.ooO+++o+oooo+++o+o.+o+++oooo+oXoX..o@ooooooo@oo@oooX....ooo+++XoXoooo@@oooooo.o+O+o.",
"++.o+oo++++OO++o++o O+o++oo++Xoo@@oo@oooo+O.Oo+ooooXX.++oo.o..+.++ooo++++oo+++o++++ooo@o+..o.o+o+..++oXoooo++ooo+..+++ooXo++.O.++o+++.++++Xooo+Xoooo++oooooXoX+o@oXo+.++o+o++o+++ooXooo+.oooo+X++o+o.o",
"o+o.oOo+oX++o+.+oO.oXooO..o.Xooooooooooo+o+o..oO.oooXoo+..X.O++++oo+o+++++++oooOo++Xo@@o.OooXo++ooo+++oXooooXX.oo..o+.o+o.++.+oo++++++.++Xoo+.ooo@@o+o+o+X++oo+O.o++.+++..+o+oXooXoo+o+++oooooo+.ooooo",
"ooO o.+o+..++OO.O.oo+OO+++++oo@oooooooo++oX+.o.oo.+++XoXo@oO.o.+o++..+++.+++++..+.+Xo@o@@o++o+X..o+Xo+++++oooooooO+.+X++.+o++++++.oOooo.+.+o++o@@@@@o+oo++.++.+++++++o++XX++ooooXXoo++Oo.+++Xoooo+o+oO",
".O.o+o+..+oOOo.+X@+.o.X+.++oooooo@o@o@X+..+o+.oooo..++o+o@.O+oo.oOOOOoOo...+oOoO.+ooXo@@@@@@o.++.+oXo+oooo+....OO.++oX+OOo..+o+ooo+o++.o.o+...+o@@@@oo.o.+++oooo+o++++o.o.+oooooooooX++.O O.+ooooXo.oO",
"+.O.o+++oOOO.o++o+.+++...+X+oooooooo@o+.++.Xo.+o.+++ooo+o@+..o Oo++ooo.o+oooX.+OO+oO+ooooooo@oO+OO+++ooo++....++.+ooo+o+..OOOO.++o OO..+o+O +.Xoo++o.+o++ooo++o+.+.++oo.+ooo+oo@oooooX+++O..oo+o+oooo+",
"oo++o+o.OOooOo.++.++.+o+oo+o+oXXooo@+...X+.O+++++++oo.o.+oX.oo.+Xo o+o+ooo++.+.oOOoO +ooXoo@+OOo.o++++..oo+...+o+oooXo+o+++....O### Oo.+ooo.+oo++++Xoooo+.o+++++++o+o+oo.+.O+oooooo@@o++oOOoo.++++oooo",
"+..++ooo++.oo..ooo.++oo+OOO.+++oXoo+OO+o+++..++.+++.....+oo+o+..oO.+.o+ooo+o+o..oO.+ Ooooooo+.Oo.+oo++++o.+++.+..o.o+o..++o+.ooOOOo.+oOOOOO.+o+++XXXoooXo+ooo.....o.o.Oo+O .ooo@oo@oo@o+.+oO  o+o+++Xo",
"+++.o@+.o.o++.o..++oo+Xo+   oX+ooo.OO+o.Oo.++++++ooXoooooXo+.o..o+O..+.OX+oXo+oO.oOo.O.ooo+.oooo..++...+ooo.+oo+.++.+o++XX++o+.....+++.ooO O+++.Xo++++o+oXXo++++X+++++.+oO+ooo@@o@o@@oo.+++.O Oo.oo+++",
"+++oo@o++oooo+oo++.+o+Xo+.OOO+Xo@XOO.++Xoo....oo...ooo+.+++.oOoO+...O. o+oooo++XO.o+O+.o@o++o.+++oXo+ooo+..+ooooo++o.+.oo++oooo+.+.o+X+o+   +.+X@++.Xo+oXXoo@ooooo.++..o.+.+oXooo@@o+++.+.+o++.ooooo++",
"+++X@ooooXooooooo+o++.+@o+.OOOooooO++++OO.+o++oOo.o++ooo++o OOO+ooo+oOO++XXoo++o.oO..o+ooo.oo+.oooo@oo+Oo+oo++o++.+++o+Xoo+++++o++oo+o...o  oo+@o++o+.+oooXo++o+oX++oX++.O+O+oXXooooo.O+OO.++++o+++.++",
"oo+oooX++++++ooo.O.+o+Ooo+o+.+.oo.+o++O .+ooooo++X+OO.o+ooOoooX.OOOOooo+oooo..++.+O +O+o+OO.++++oXooo++++..+++....ooo+oo+o+++.+++o++Xo+o.Oooo.oo.+++.+XXo+Xo++++oX.+ooX++.+..ooooooOoO.o++.Oo....+o.+.",
"ooX+Xo.O.+o+o...++.+o+o+o.+++o+oo++o.Oo.+ooXo@@oo+oO+oOO o....ooooooOo.o.oO  o++Oo. o.X+o..Oo+++Xo@++++++o++.o.ooooO+Xo++..++..+++oXo+.+Xoo+ooo++o+.+o..+oo+++Oo++++XooX+.o++X+Xo+o..o+.+oo.oXo++++o++",
"+ooo++o+oo++++...o+++..oo+..O+X+ooOOoO...o+oooXXo++o.  O....+.oo+oXoX+++O # .o.oO+o.o+X++.Oo..++o+o+++oo++oo+o+.++OO.O++.oo...oo..+oX..+ooo.o+X+o+oo+..oooo+o+.o++.Oo+oXo.oOooXoo..o+.o+.Oo+oooooo++++",
"+ooo++oX+.o.++OOOo.+o+.oXo+.  +o@oO.OOoo+oX++++o+oXoOO+ooo++oo+++++++oX+..+oXoX+.Ooo.oooo +o.+oooXo+++++.++++++...O   oo...+oo.O O.+Xo.+Oo++o++oo+X+o.o+oo+++.oo+..+oooo++..o+oo.o...O+..OoXXo+++++oo.",
"+++oo+oo..+oo+++.O  .o+o++o+O Oo+ooOO.o.oXo++oo+++++Xoooo.++..ooo....+o+ooooXXo+.+.o+Xo+ .o.o+++oo.++.+.o..++.O+.O+..o.. O  O.++++o+ooO.OooXooXXOo+Oo++++++o.o+++++o++oo+o.++.+Xoo.+o+oOXoXXX+++++++oo",
"+oooXX+..+oXo++++o..+.o.+o++.Oo+.O+o.o.oX.o+O.++.ooo+o@.o+++...+++++++o.+oooXo+.oo.oooX+o++++.++o+O+o+++++...O+o+ ++o..+...ooo.++.OOoo +O+ooooXo o.o.o++oooo.OX+++.o+.oX+++...+oo.+.+oO+ooooX++++++++o",
"O.oo......+ooO.o.o+++.++o.+o++o+o+++o.+oo.++Oooo++.o.XoOo++++.++++.+++o+oo+oX+o.Ooo+ooo+++.o..++.+o+Xooo.ooo++o.o.oooooo+.+++.oo++O+++ +O+Xo@oo+OOOo++oooX+o ooX+o+++ooXoo..oO++o++.+.+.oo+.o+++ooo.o+",
"+oooo.++.+++oO ooOO.o.++o++ooo++++.+o+o++.++.o.+o+++.o.o.oOo..+.o...++oooo.oo+++O Ooo@o+.OX+o++.o+X++XX+ooXooX..OOO o.+++oo+OO  .+oo.+ .o.X@oooOooo+++ooo++o +ooo++oXooo+oooo++++o+oo+oo++@o.+++.oOoOo",
"oOOo+..+o.ooX. Oo+o++o++++.++oo++++OO++.+..+.oo.++++o+OooOOo..o+....++++...o+..+.O OO@oo++o.o+.O oXooo++oooo++oo+OOO++oo++o++.  Ooooo...oO.@o@o+oo+o+XXoo+o .o+X+.++++++o+o...Xo++..+o+.oXo+oo+.+...o.",
"oO+X++o.oo.o.o+OO+++o+o+o.o. o@o.++O +o.oo++..Ooo.ooo..OOoo.+oO OooOOOo++++oo+.++o OO+@ooo.ooooo .o@o+.o++ooo.++..oo+oooO..ooo+o+oooO.++.. +@ooo+oo++Xo++ooo.O+o++ooOo+o+.o++.++O.o...o+@+o.+++oXoo+++",
".++++oo+++oO+oX+ .ooo+o++.o. O+ooo+++.O.oo++.+o+.o.X@oo++o.++oo.oooo.o O.++oo+..+..oo.o@o++OoooO .@oXo+o o+XoX+...oo+o+Ooo+@oo@@oooo.o++..O +o.+oo+o++X.+O++OOoXo+.+.+o++ooXo.+oo.Oo.oOooo+oX+Xo++++.o",
"oo..+++Xo.++oo++o+++X+oo++oOoO+o+ooX+oOO+o..o.o++...ooOo+.+o.ooX+.o..++.++X@X+oOo+..+++oo+o..oOO +o+.+o. O+o.+o++.+XX+oOOo+oooooooo@+.o+..o O@o+ooooo++OoooO .oXo..+oo+++.oX.++o+o.+oO+o@o+++o+.o.oooX",
"o..ooo+...oXo.oo.o++++oo++oO.o+++Xoo+.o.+ooo+o.o+.ooOOo.o+o.oo+oO..OO...ooo@X++o O+++.+ooOOOo .O oo++++o Oo+o+oo+o.Xo..# .o..X+oXXX@o.o++.OO +oX++O++.oOoo+OO.oo++.+oo+++X+ooo+oo.o.+oo+oo.OoooO.++o.o",
".OOOOOOooo+o.+o.oO+ooooX++OoO..o+o++....oo.+.O.++oXX....+.+oo+oo OOo..+++oooo+++ #.Xo..o+Oo..O+oo+o.+ooo.o.+.+oo+o@+++.$Ooo++o++oooooOo.+oO. .oX.O.+o.OoX++OO+oo+Xo+ooo+++o+oo+O++o..o+o+o+++Oo .o+++.",
"+oOo...o.+o.o+.OooOXXXoo++ooOo..o+o+++.ooX+OO ++O.o.o...o+++++oo.oO..o.+oooo+X+o.OOoXO.o+.o++o.oo+.+o+.+.++...+o+oo++oo +oo+Xoo+o+.+X..OoO.+ oo.Oo++.+O+X+oO+++o+oooo+X.o.o..oo..+++o.++++ooooOO+oo.++",
"o+.o.oo.+@o o.o.+o+oX+ooo+.Oo +O+.o+++oOXo+ ..oX+.ooOO Oo.o++@.O. .++ooo+XXooo+++OOo@OooO +...ooOooooo+...o++oooooOO+oO+ooo+oo.+o+.oo+.+oOOo.ooo .Xo+O.X+..o++oo. oo++o.O++o+oo.+++.o+.+++o+.oOOoooo+.",
"++...O.+.o o..+o+.oo++@oXoo..o....+X.+OOX.o+ooo++oooOo.+oO.+ooO+.o.+X++++XXooo+++++oo++oOO+.ooO..@@+.o.o+.O.+.OO OO++..++oo+oo.++..+o.+o+oOO+X+o Ooo..oo.+Xo+oXX++oooo.. oooOX@o+++o.oo++oo+.OO+oo@@..",
"+oO.+o+..oO...++..+oXooooX.o+++o+.++++o+oXooo.++.o.+++oO ..oooo+...+oOO..oooooo+o+Xooooo.O+.o+ +o@+..+Oo++....O+.+X+o++o.oo+o.O++.+ooX++o+.+ooX.o.++.oooXoXooooo++.oo@+.  .+ooX@Xo+.oo+.+oo+OO+@ooo+oo",
"o. ...o.+OoOoo+++o.o@oooooX+ooX@o++O++ooo@@X++.OOOo+...ooo.+X+.o+..++ O+.o++XoX+oooooXooo.+++. o@ooO.ooo.+.+O. ++++O.+oO+ooo+Oo.+..X@@X+.oo++++oXX+oXXoooooXoXoo+o..o@o.o OX+O+oooooO.+o.+XoO+oXXX.o.+",
"o+ o.++.o OOo .++o.o@o@@oo@oXoo@oo+.ooooo@@++oo++o+oO..o.o+o++o++.o++  O.+++Xooooo@ooooXooXXo+.oo.OO+..+oo++OOO.++Ooo+Ooo++X+oO++o+.@@oX+o.o++..+oo+oo@@o@ooooo++.+.o@o.+OOooOoooo+.O+OOo+o+o+.+++..oo",
"X.O..++OOOooOO..ooO+oooo@o+ooooooooXoo@oooo+Xoooooo...+OO++X++. Ooo..  oooo++o@oXooo+++o++ooo+o@o.++..@X+oooOO ++.O+ooOo+..++..+oooO+@oooo++++.++++.oo+o@oo@@o+o+.o++o@++.o.o+o+oo+... oOXoooooO...oo+",
"o.o..++OoooO +..OOo+Xooooo+o+.oo+Xo++.ooooX+++++oooo+++.o.oo++o  o+OooOO.Oo+ooo@X+++.oOO.+.+ooo@o+Xo+oooo..X+Oo+++.+. .++.O...+.oo.o+o@o+.+++oO...++.Oo.o@oo@oo+o.+ooo@o+o+.+o++oo+++.o.oo@Xo+++o.+oOo",
"o.OO++oO+.OOo+.OO.+.oooo@ooooOOOo+XXXo++oooo+.++o++oXoo.o.++o++ O.oO.oOOoo.ooooX+.+ooooo+++.+o@oo+ooo+XooX.o+o.+++++..O+o+.++o+++O.++o@+oX++++++++XXXooooo@@oX..o+.oXo@o+oXooo@oooooo+oo+@oo.+..o++o.+",
"+.O .+oO+.O +++O.++.ooooooo+..o...+Xo+o++ooo+.++XooXooo.OOoOoo+ooo.++.O.+o++ooX++o..+++++oXoooooo+++++++oooXo..+o.+oXXo++ooooo+oo.o+oo@++o+ooooXXooo+..o+oo@Xoo.o+.+oooooooXooo@oXooo+Xoooo++++oo++++.",
"+.+O.+ooo.OO++.oo++.+o@X++oo++..+Xo++++++.O.OO.ooo++ooo+OoO O+++o.++o..+o+o.ooo+OoOOO+++++++XXooX...oO.oo+ooo++oo.++oX++X+OoX++OO.O..@oooooo+.o..oooo.+OOO.Xooo+oo.oooo@@oooooo@oooo@ooooooooo++o+++OO",
"+..o.+++..oo.o++++++ooo++oo++oo+.+++o..++o.+++o+o+X+o@ooo+.Oo.. .+++oX+o+oo+o+.OO  O+o+oo.++ooXo++....+++oXXXoo+..+XXXooX. ooX+oo+ o+oooooo+++.+++.++.oO O.+oX..oooooo@o+.+Xoooooooo+ooooXXoooo@o++oo.",
"o+o+++++.+o+..@ooX.+ooo+o+oOOX+o+o.oo++ooo+XXo+.oo.+oo@oo++..+o..+++o+X+.++Xo.+++++X+oo+++o++...++..++.+++XoXoooXo+oXooXoooXoooooXOo.oo++oo+oX.oooo+.++.oO +@@O#Ooooooo+oXXXo+++...oo++++ooooooXoo.o..",
".o+ooX+.o+.oo@@o@+..ooX+..o.Xo.oo.+.+o+++oo+++ooO +oX@oooXoOO++++++ooX@XOo+o+oX+.++++..+..++++...oo+oX+.+++oo++o+++oXooooXoooooooo..+oo.o.o++++..o..++oo.+Ooo@+o.oX.oo++o++++....++.++.++++++OooooO+o.",
"o++oooooXooooooo@+o+Xoo++.OO.+oo.OO+oo+ooXooXooXOO++o@@@@@@o.ooo.oXoooo@.oooo+OO++.X+.+.o+.oo...+oo+X+.+..+oooooo+++oooooooo++oooo+++++..++o.oO   ..Ooo.oXo+X@ooo+.o.+XooO+o....+++..++....o...++o+.++",
"oo+X.oooooooooo@oXoooo++..o.OOoOOoo+.o++.OoXo++++++o.+@oooo@@@oO+o+ooo@@oo@@.o.+.O+OO++X.OO.oOo.oX+++OOOO+o@oooo@@ooooXoo+XX.+o+o+oooooOoo+o.+..+ ..o.oOo.XX++.Xoo+oXo+o.oo+o .++++++o+oXo+...OO+ooo+o",
"@@@o.ooooXoooo+++ooooo+.OOOoo.++oo.o+.O  OOooO++o+oo+Oo@o@@@ooo+.o+X..oooooo+oo+..O.ooo.O..o..+o+Oo+OoOO.o+.o@o@ooooooooo++@.oo+Xo+o@X+o+...+o...+.+..+++oo+o.+ooXXooX+..+OOO.+ooo+o++.oo++.o.+++++ooo",
"o@@@o++ooXo++oX++..oooo+.o.oXo++oOo.OoOOOOOo+o.+o+oX++.+ooooooo++o++.+ooo+++..oooo@@@+..oo.++oo+oO.o.oO.o+o.+oo@oooooooXXooOO.o+XX+o++.+....o++.Oo+OO+oXo.  oXo+o+@oooooOoo.++o+....+oOooOOooO.+++oo+.",
"o+oooo.oXo+.O.++++oooooo.o.+o+X+.+.o.+o+++oo@@X+.+++o+.++oXoooo+OOo+.++oXooo+++++++oX o+++..+++++...oo++oXo+++oo++oooooo.+O.oOoXoO.oXo++++++.+...oo+ooo+.Ooooo++o.XoXo+.+o.+o++++o..Xooo+oOO..+++Xoooo",
"oo+oooo+o+++oOoOO++OOOOO...oo@ooo+++.ooooooo@oo++o.+oo+o.+ooXo@oO#+X++++++o.oO OOooo+o+o+O.o+++++Xooo.+XX++o+++o+++ooooooo.oXOO++oX++++oo+O  O.oo++..oOO+ooo..+ooX+oooX+X.++.+oooooooOo+oo@oooo+++X@Xo",
"ooXXooo+oOoo....OooOOOOOo.+o+.o+++.+X++++oo++.oo+oo.+oXo.++oooo@o O++++Xo.oooOoO Oo++OoOo.o+oX+XooooX+.++o++o+.o+oXooXo@o..+.+oo.+oo+++++o+o+o.Xo+oOOO.ooo+++o++oo+o++oooo++oo++ooo+..+ooooXooXo+o.X+o",
" +XXXoo.+++++o+.O.oo.OOO.+o.OOo..+oo+.++++++oo+oo++.++++.+oooXoo++.++o+..++.oOOo++oo@o O+oo+oo..+ooXo+o+oX.++Xo.oX+++++o@ooo.oX+.++o+++++ooooo+ooo+ooo++.+o+.o.++.++o+.ooo+o++.oo+o+++oooX@o+oX+oo..oo",
" +oooo@oOo+ooo+++++.ooo+X+.+oOOo.+ooO++..oo+++ooXo++++..ooXo+oo..Xo+o+++++...+.oo.ooXo+o+.++o+oooo+Xooo++.o+.o++ooo++ooXoX+o.+o+O+X+++Ooo.++oXo.o+XXo+++O ..+..o+..O.+.oooo...+++++.+++oooX@oO.o+o.o.o",
".+ooX@ooo+.o..++oOOOo+++..+oOOoO.o++O.++..oOoXXoXoo++.+++O.oXo+.+.+.o+.o..++.+++Xoo++oo++++++++oX+o++oo+o++o+O o+oXooo+o.++..+.O.oO..o++++oooo+++++X.o.++..o+oXoo++.Oo+oo+.o++.oo+++o+++.++X@o Ooo+OOo",
"ooo@oo++X+oOOOOO.oOOoo.O.+.oOOO.o+.+o+o+++++.+oooo+o+.+o+..X@ooo.++.O++oooooooooo..oo....ooO.OO++..+ooo.+o.+oooo..oo+.O..+XoOO++...oOOO.oooooo.o..+.OO++..++o+ooo+.o+Oo+oo..++.+..oooo+++ooo@oo#O+++oO",
"OOoo+oO++++++o.  O.+X+o.+.  OO.+.o.oo.o...+++.Xo++++o.o+o++oo+.+o+OO+.o@XooooXoo.O++..o  OO++.+.o.+o+X.o.+o.++++O+o.Oo+..++o.Oo+.o.o.+Xooo+++.oOO+o++oOOo..o+XXooo++X. o+o..ooXooooo++..+++Xoo+. o+ooo",
"o#O.o o..oooXXo+o+X++ooO  O+++o.o++++.+..Oo.++oo+++o+.+++oo@++++. O.o.@o++++++oo+++..o.o.o+.o.+++..Xo+oX+o+.+o.++Xoo.o+.ooOOO+...++..+oooooo+o  +Xooo+.....+oo.+++.++oO+o+++oo+++++...++o++oooo++..+X.",
"@XO  Oooooo+oXo@oo+OOooooOo+oo.oo+ooo..oOOOoo++oo+oO+o+o++Xoo+oo ooo+XX++o++..o.+++oo+o++....+.+.Oo.+oOo.+o.+o++ooX+o+o+oo O..+ooXoo+ooo@+O..OO+oXo+oo++...++..+++++++.+X++oo++++.+++o++X.+ooXooo++oo.",
"@ooO+o+.o..+oo@@+o.ooo.++++oooo.+++o.oo+. # .o++++o.o.o+o.oooo+oo.+ooXXo+++.oo.oooooOOo+++++++..ooOoO+.oo+X.+++.Xoo.o.++o+.+++X@ooooooo@ooo.+o++oo++oo+...+OOo+X++o+o++oo.+++oo+oo+o++.++oooXo+oOOX+++",
".+.oo+...o+Xo@@o++++.oOOo+o++ooX++o+XoOoo+o  .+.++.oo.oo++oooooo+Xo+ooXoo+o+.O.+.+oOo..oo......++oO.+XooO.o+oo+ oX.+.++o.O++.+@ooo+ooo+oX.o+oo+o.++ooXo+XoX++++++o+oo.ooo+++oXo+oo+oX++++Xo+o++XX ++++",
"o+oo..+.o.ooooo++o+++oO.+oo++.Xoo.+o@+  oO+.ooO.o+o+o.oOOo+ooooX+o++ooX++.oO..+oooX++.ooo+oO.++++ O+Xoo+.O+.oooooo...++.O.++ooooo+..++ooo+++oO+.+++XooXo+++++o++++.o..+o+o+ooo+o oo+ooo+o@+o++++o+.ooo",
"ooo.++OO.ooooo.o.+ooooo+++oX++oooooo++. O....O.+oooo++.OOOO+@ooo.++oooXo+++.+o++++ooO OOOOo++o+OO+XooXo+oO.+oo@@oX+Ooo+O.o.+oooooXoX+.+X++...o.++.ooo++++.+++o+++o+o.++XXX+o++ooo o.oXXXoo+...+++o.++o",
"++.++OO++oXoo...+o+oo+++oo+++o+o+ooX++Oo  ..+++oo+.o+++.Ooo.@oo+.oXo+o+XXooo+++.oo.oXo ++o+oo+o+O ..+X+ooOOoo@oo@oo+o....Ooooooo+o+++++O+++++.++.+oXo+X+o++o++++++..O.XooooX+o+.ooOoO+ooo+oOOo.+.X.o+.",
"o++++.+++oo+oO..++++.+++++++o++o.o@+o+O.+OOo+++oX++O.+oo.+oo+oo+++oooo+Ooo++++++.+.+o+.+X..+ooo+.o.+Xo.+o+ +@o@@oX+oo+.+.oo@ooo.++.++o+.O.oO.++.++oO.Oo.++++..ooOO.oO.++++Xo+oo+oX..OOoo++.OOo+..+oo+o",
"X+o++o.++++o+o+o++...OOoo.+++++ooo+oooo+oo+..+ooo+o+..+oooo+.o++++++++++.+o++.+..+++.O+.o+.+ooXoooOO.oo++o.oo@@@ooooo+++.oooooo..o++oo+oo.++++o.++ooooo.++o...+.OoooO .++o+++o++oo+o.OooX..OO.+..+.++o",
"ooo++.O+.++oo.+o+.oO++o...o....+X++.oo. Oooo.oXooX+o.+++ oooooX+X++++.o  .+.o...+Xo...o+oo.+oo.O...ooooO++O.+@@@+O...++.+++O++X++oooXo+++o++++++oooo.OOo++o OooOo.O.oo+o+oo+oX+++@++X+XoooO...+oo.+oo+",
"oooooOO+.++o+oo..OO++++++ooooo+oo+.+++oO++o+..oXoo++o+.+O.o+++Xooo+.+..+o+..o.+++++.oo+oo@..oX++oo@@ooXOoXoo+o@@X.+.o+Xo+o++++ooo+++ooo++o+o+..ooooo+.OOO..+....oooO.+XoOOo++o+o+oXoXXoooo +.++o.+..oo",
"@ooooO.++++.ooo+oo.+oX++o+++..+o+o+X+..+o++oooooooX.+o+++.++.Oo@oo.o+oo...o OOo.+.+o.++o.o...o++.+.oooo..+XO.+o@oo+++ooooXoooXo++++..++++o o.o.Xo+.+++oooO..o.++Oo..+.++XOoooX.O@ooooooo@+O.+.+o .o+oo",
"@o+o+.o..++Oo+++.O+oo..++X+ooooooo+o+ o+.++.+oXoo@o...oo+++oo..@Xoo.+oooO.OOOO   O+++..++X+.oX+oo+.Xooo+.oo+O+.XX+.+++oo+oooX+++ooO.+++++.ooo.ooX.oooooXo++o.o+oO+.o.+o+.+o+++oXoooooooooooOO+.O# ..oo",
"o@o+o+.Oooooooo+O.Xo+o.++o.+oXo+o+.o. .+.oo..+oooooo+..@oXo++o+ooo.+oXooo+..o oo.+o++o.+ooo+o+o+.+.+XX@oOoo+ooo+ooO+++++o+ooo+o+...Oooo. OOoXo@@+.oX+o+Xooo+oo++++++o.o++++++.+oooo+oooooooOo+oO  Ooo@",
"+@ooo+O.OOoo+.+O.X...o+X+o+XXo++++.ooo.OOOO+o.+o+oooXo++oooo+oooXXo++ooooo.+o+o+++oo+o.oo+o+++++.X+o+o@o.O+o+X+O++.+o+++..oo...+.+++ooO+@++ooXoooo+o+oo++oo@@X++++++o+oo++o..++oooo+ooooooX..o. Oo.O+X",
"+oo++.o+Oooo+...oO .+O+o.++.o.o+++.+oOoooo o+++Oo+oo@@ooXooooXoooo+ooooooo.++oOooooX++ooo+.++++.o++..+@@+ooXoo+++++ooo++o++Xooo..o+++oo+ooooooX+o..O.+o+.oooX+++++o..o+O+.+.++XXooX+oo+oo@o.+o.O#o+OoX",
"o@+++O+.O.oo+oo.OO +.O++.oo.o+.+Ooo.oOO.O+oOo++.O.ooo.oooooo+.oo...oXoo@@o.+o+o.XoXooo+oo+.o++ooo++oo+o@X.+.o+o.o+ooo++oo+.Xoo+o.oo+.+o+oXooXXo+++oO.o.+..ooo++++.oo+o+ ++.oOOoo+++o..+oo@X .+.+Oo++.+",
"+oO++o..o+oooX...OO.+O+oo.o+oo+ O+OO.OO.oooo.oooO ooX+@@@X++++o++.o.+ooo@o.+o+o+++ooo++oX.oX+.+..o+o...oo++.+o+o++oo+ooO.++o@o+o+o++.+.o+oXoooX.+o+O++o+oooo@+++++oo.o+O++.OO.o..++oo++oo@o ooooo.oXXo",
"++O+..Oo.ooo@+OOooOo+.oO..Oo +..++OO+Oo.+.++++oo+ O+oo@@X++oo.oOO.++oXXXo@+o+++oo+oXX++XXo..oo++.++oo+.+@o+o+oo+o+oo+.O.+++oX+.O+++o+.o..+X+o+o++++o.+o+ooo++oX++++o++X.oo+OoX+O....O++ooo@OO.ooo+OOoO",
"o+oo++OO+o@@Xo O.Ooooo...oo. O.X++O+.Ooo++.oXo++o+o+o@@oo+..++++.+.+o+.+oo++oo++o.+ooo..o++o+.+.+O++o+.+Xo+.+Xo+..oooOo+o++o++o.o+o.oo+o +.++o++.++.o+ .+.O+.oX+.+..o.o+O .#oo.OoO+oO.+.+o@Xoo+o..o o.",
"XooooX...@o@oOO.o..+o+++.o +OOo+o+o+.o.O+o+Xoo+o.oXoo@oo+++...o++.+++.ooo@++Xoo+o++o+o.O+oX..+o.+O+o+.O.ooo.o+ooo+ooo+++O++oo+.++oX.O++o++ooO+oo+o+++oO.ooo+.+o+.++++o++O o#.ooO. +o +++..o@@O+++O.OO.",
"oo++oXXXooo@+o+.+oXo+.o++oOo.O+.oooX+o.+.+oooo+..ooXooo+.+.....oo++++++X+oo.o+X++++o+++O+o++Oo+.oO++.o+O.oXo+o.@oooo OX+o++o++.+.oo++o++X.oo.Oooo.+..+.Oooo+ +o+++++.oOoo#oOoOoOo oo +o++..o@oo++OO.OO",
"++++oooo@ooo+o+oooo++++oXo Oo.+o+ooX+o++o+X@ooX++o@oo.++.oOOOo  .oooo.+ooo@oo+oo+++++OX.++o+o+.++O+o+.ooo+@oXo.X+oOOO O.o.+oXXoX.++o.oo.o+O.+Oo+Oo.+o.+oo+..OooX+.O++. o. +oOO.oO ooO+.O+oo@@XooooOooo",
"oX+o++oXX@ooooXo+.++ooo+ooOO+o.o+Xoo.o+oooooX.+o+OOoo+oXo+...++o+oooo+OO+@o@o.oo..oo+oo.o+o...O+. o@+O+o++@oooo++....+..o+ooooooXo.o.oo+.+oo+O+.Oo.oO+OO+oo..+Xoo...++OO+O+O O.+OOo.o+.oO+oooooooo++++",
"+...O.o.X+oo++...+oo+oooXooO.X++oXo++.ooXoX++oo+.OoO@@oooo+o++.....+++o.o+@@oo.+o.o.+++++++++..ooOo@oO.Xooooooo+++..oo.o+X@oX+Xoo.+.+++oooO.+++OOOOoOOOoo.O.o+o+Xo+++.+ooo. Ooo+.o++o+o+o.oooooooXoooX",
".+XX+o+++++...+..oX.+oooo@oo++X++oXXo.ooooo..+O.+X+.ooooXooo+oXXoX.o+++ooXoo+o+.o.oOo++.o.+o++X+.o@ooOoXoooo@oooooXooo++X+o@oooo++.oo+oo.o.oOoo ooo OO.oo+o.O+@ooo+oo.o+o+.O.Oo++o+ooooO++ooooooooooXo",
"oooo.+oooo.oo.+.oo.o+ooXoooo@oooXXooo.oXo+++o++o+ooX.oo+++++o++++.O Ooo+oo+o++.+. .O++Xooo.+++o.+o@ooOooo@@oo+.++++++.o+.+oooooo++.+Xo+ooo+o +ooX+O  O+.oO.oO+@XX.o+X.oo+o+o+oX+++oooooOoooooooooooo..",
".+oO.++X.Ooo...+.+oOOo+ooo@ooo@@o@o@o@@@+O.+OOO.++o++++++ooo..o.oo.oOo++oo+XXo o.O+OO.oX+..o.+O.ooooo.ooooooo.+oo++++++oo+ooo@@@+.+ooo+o+o.oo++.o+  O+.O o..O+@o+oo++OOoo.oo++o.+ooXoo.OO+ooooo@@o++++",
".+.++.+.OoOOO.++oo.o.++.Xoo@@@oo@@@@@ooooOO++Oo++o++o++oX+.oooOO.Xo++.o+oo@oX  +. .+O++..+.++..o++X@o++oooo+oXXo++Xo++.o.ooXo@@oo+o+Xooooo+oo++++OOOo+.oo..+.+@@oooo@oooXoooXOO+ooooo@.OO+oooooo+.++++",
"+Xo.O.oO.oOOOoXXo+++Xo+ooooo@@ooo@o@X+ooo. OO@o.++oo..+.oo+++o+oXXoo+.+Xooooo  +.O.+oo++.++ooo.XXoooo+o@oXooo++..o++++oOOO++oo@@o++ooo@oooooo+Xo+O .+oX+++.+.oooo+oooXXooooooo+o+o+oo@..oo@o@@o+  o+++",
"++..+o..oOO.+oXo+++X++X@@@ooooooooX+++oo++oO oo++.+oo++.+oooooo+o+.oo  OOo..o.++o++oo++o++++oo.+.+ooooooooo+oOO+oX+..+X+OOo..ooooo+o@oooXo++oo+oo+oo+oXX+.+.+@oo@ooXXXo@ooooo+++++Xoo@++.o@oooo+.o+oO.",
"+++o+.OOOO..+oX+++++++..+ooXooXoooo+++o.o+o.O .+++.++++.OO.+Xo..oo++....o.+++.oooXoO.o+oXXoo++oooo+Xoooo+o+++oooo+.o..+oo+.+ooo+ooo.XXX..+ooooooo.oo++oo+oX.+@oooooooXoo+oooo+o++XooX@Xooo@o@o.  ++ o ",
".+X.O  Oo+ooXoOo..OO+Oo.+O.oXooo++.o.o++..+o+O Ooo..++++.o.o@Xooooo+.OO.++Xo+..++++Oo+++Xooo++o+...XoooooXooo+oo+oooooo@oX+Xoooooooo+..O.++.oooXo+o@oo.oooooo@oooooooo++ooXoo++++ooo+o@oo@o@ooooXo+OO.",
" .. OOo.+...OOoooOo++.+o++Oooooo+oO.+++.+ooo@@+ooOOO++oXooo+.+++o+ooo+....+oo..+o+o.++++oo+Xo+.+.oO.@oooo.++..+++.++++oo ooXo++++oo+..++o.o+oo+oXXoXo+O.+o+oooooo@X++++o.oXXX+.+o+o+++ooooo@@o.@o..%.%"};
