/* XPM */
static char * cubes_xpm[] = {
/* width height ncolors chars_per_pixel */
"36 60 3 1",
/* colors */
".   s selectColor   m black   c #bdbdbdbdbdbd",
"    s background   m black   c #949494949494",
"X   s bottomShadowColor   m black   c #636363636363",
/* pixels */
"                 .                  ",
"               ...XX                ",
"             .....XXXX              ",
"           .......XXXXXX            ",
"         .........XXXXXXXX          ",
"        ..........XXXXXXXXX         ",
"      ............XXXXXXXXXXX       ",
"    ..............XXXXXXXXXXXXX     ",
"  ................XXXXXXXXXXXXXXX   ",
"..................XXXXXXXXXXXXXXXXX ",
"..................XXXXXXXXXXXXXXXXXX",
"..................XXXXXXXXXXXXXXXXXX",
"..................XXXXXXXXXXXXXXXXXX",
"..................XXXXXXXXXXXXXXXXXX",
"..................XXXXXXXXXXXXXXXXXX",
"..................XXXXXXXXXXXXXXXXXX",
"..................XXXXXXXXXXXXXXXXXX",
"..................XXXXXXXXXXXXXXXXXX",
"..................XXXXXXXXXXXXXXXXXX",
"................. XXXXXXXXXXXXXXXXXX",
"...............     XXXXXXXXXXXXXXXX",
".............         XXXXXXXXXXXXXX",
"...........             XXXXXXXXXXXX",
".........                 XXXXXXXXXX",
"........                   XXXXXXXXX",
"......                       XXXXXXX",
"....                           XXXXX",
"..                               XXX",
"                                   X",
"                                   .",
"XX                               ...",
"XXXX                           .....",
"XXXXXX                       .......",
"XXXXXXXX                   .........",
"XXXXXXXXX                 ..........",
"XXXXXXXXXXX             ............",
"XXXXXXXXXXXXX         ..............",
"XXXXXXXXXXXXXXX     ................",
"XXXXXXXXXXXXXXXXX ..................",
"XXXXXXXXXXXXXXXXXX..................",
"XXXXXXXXXXXXXXXXXX..................",
"XXXXXXXXXXXXXXXXXX..................",
"XXXXXXXXXXXXXXXXXX..................",
"XXXXXXXXXXXXXXXXXX..................",
"XXXXXXXXXXXXXXXXXX..................",
"XXXXXXXXXXXXXXXXXX..................",
"XXXXXXXXXXXXXXXXXX..................",
"XXXXXXXXXXXXXXXXXX..................",
"XXXXXXXXXXXXXXXXXX..................",
"XXXXXXXXXXXXXXXXXX..................",
"XXXXXXXXXXXXXXXXXX..................",
"  XXXXXXXXXXXXXXXX...............   ",
"    XXXXXXXXXXXXXX.............     ",
"      XXXXXXXXXXXX...........       ",
"        XXXXXXXXXX.........         ",
"         XXXXXXXXX........          ",
"           XXXXXXX......            ",
"             XXXXX....              ",
"               XXX..                ",
"                 X                  "};
