/* XPM */
/*********************************************************************
*  (c) Copyright 1993, 1994, 1995 Sun Microsystems, Inc.
**********************************************************************/
static char * Dimple_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 3 1 0 0",
/* colors */
"       s background            m black c #949494949494",
".      s topShadowColor        m white c #bdbdbdbdbdbd",
"X      s bottomShadowColor     m black c #636363636363",
/* pixels */
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                   .            ",
"                                  ...           ",
"                                 ...            ",
"                                  .     X       ",
"                                        X       ",
"                                       XX       ",
"                                      XX        ",
"                                   XXXX         ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"           .                                    ",
"          ...                                   ",
"         ...                                    ",
"          .     X                               ",
"                X                               ",
"               XX                               ",
"              XX                                ",
"           XXXX                                 ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                "};
