/* XPM */
/********************************************************/
/**   (c) Copyright Hewlett-Packard Company, 1992.     **/
/********************************************************/
static char * Knit [] = {
/* width height ncolors cpp [x_hot y_hot] */
"164 180 11 1 0 0",
/* colors */
" 	s iconGray7	m black	c #4b4b4b4b4b4b",
".	s bottomShadowColor	m black	c #646464646464",
"X	s iconColor1	m black	c black",
"o	s selectColor	m white	c #7d7d7d7d7d7d",
"O	s iconGray6	m black	c #646464646464",
"+	s iconGray5	m black	c #7d7d7d7d7d7d",
"@	s background	m black	c #969696969696",
"#	s iconGray3	m white	c #afafafafafaf",
"$	s iconGray4	m white	c #969696969696",
"%	s iconGray2	m white	c #c8c8c8c8c8c8",
"&	s iconGray1	m white	c #e1e1e1e1e1e1",
/* pixels */
"   ...... .X..ooOOOOO.oo...X ++@+OO+OO .X.OOo@@#++@$$@@@OooO$@+ OOOOO$##OO+O++OoOOO+OO++O #$O@$OOOO+@+OOoXXO.o .o oooo..X$$Oo$@ OO+$+@O@+#@@$#+oOOOO@@@Oo+@OOO. oOOO",
" O+OOO ......oOOOO+@$@+@+.X..X oO+@+@o....XXX.oOOoO+OX.oOOoO@OoO@$$+$$@$@OO++OOO+++OOOOo+$+$@@+O+OOOOOOO..X.o.X O..  .. .$$+.+@ .oO$++O$$$@+@#%$O+#$O+OOOoO$+OOoOO$O",
".O++@@$@OoO.oO+++++O@#$@$$........O+@.......... o O@@X.$$+++++@$##@$@$#$+@@@@@@$@+OOOOoOO@OOOO.O@O@+@+OOOX o+$$@++o.....X+@O.oOo...@$$@O$#$@+O$$+O$#$$@++OOo+@+OO$++",
"$+O@++$###$+oo+++@@OOOO+@@+....o..Xoo....X.. ooOOo +$.. O@@OO@$$@@o  O++OO@$@$@OoOO++ooOOO++OOOOO++@@$@O O+$+O++OOO ...Xo+ o......XX@%%$+++$$@+@OO.o+##$@@+.O@@+@@@O",
"$#$O$+OO+@$$@+$@@$#@++OOO+++..oo oOoo .X.   oOOooo OO...... OOOO@.X..+##$+@@+OOOO+++OoOOO$$@@$+++@++OOo+OOOOooo.oooO..X.O$OOo Oooo...o$#$@@@###$@O. +O+++++OoO+@$+$+",
"$$$@++++O$####@+O$$%@oO#$o+O O@OOOOOOO+OoOOoOOo++OOo......XX..oO+ ...XO$@@OOOOOOOOO+@@+++OO+$$@@+@++O.OOoooO@++++++OO+++OOOO+oooo ...X.+++O@@$@Oo..o+OoO@@@OoXoO@@O$",
"@@@+$@@@$$$$$#@@+@@$#O @%#OO+o@O@$$$@+@@+o+#@+OoOO++@o.......o.oo. ....XX....o@@O O++++$@@$@@@$$$$oOOOOOO+$#@O++O+O+@$@O+O+++oOOOO ..XXOOo+o+#@$o..OoOOoO+OO ..++@@+",
"++@$+@OoO+@$#$$@@$@+$$+@#%#O$#+OO++@+O+++@Oo$$@$@OO@$@ X.o oO#@.oo............O@o..o$$$$$++$$$##$OO+@OOO@$#@o+O O$@@@+++@$@@O++OOoo.o..O+oOO. O+... . oo. oO o.o@@$+",
"++O++O.X.++@$$@++##+O@@O@$$OO$$@+OOOO+@$@@+OO$+$$++O@$@XO++OO+@OOO.X..oo..+Oo..O..... +$@++O+@+o...oO@$@+O.O++O.oO+@@$@$$@+$$@OOOoo   ....X..X..X.O+$@OOOo. o..XO@$@",
"OO+....XO+$@ooO+o$##+O++o@@+Oo+@@@OOo@$@$@$+OO$+$$+Oo+$O.O@$@+@$@ ..oOO.ooo@@OoOOX......oOOOO#OX.....o++OOOO+O@+@$+$##$$$$$@+OOOOo o o....XXXXX..OOOO@@$@+O . ..X@$@",
"+O......O+@@  oOO.$%$@+++.oOOOOOOOoO+O+O@$$$$$OOO+$+Oo$#@.O@@$$@++@@o.$$o+o O@+OO.X......Ooo+$+XXXXX..Xo++++ X@$###$$$#%%%@+OO+OO .OoOO@@$@+O .OOO@+$@$@+O+OOX..oO@%",
"+.X.XX..oOoO....o .+@@$$+OOO++++$O..+$OoO@@$$$+O+ O+@$@$#@O$$oO@+O@++OO$#+@oOO$@OO+X..XX... O+oX.X.OOOoooO++XXXO@$##$$$$@++@++O+$@+OOOO@$$$$OoO+$#++@##$OOOoOO.XoO@%",
"...XX..X++o .........OO@$$$@++OOOo..XO@@++++Oo.X.OOoOO$@@$@$#$$@++$##$OO##+@O+o@@oO+...  o.o. .X.o+OoOOO o$+X.XXXo+@@$$$++@++$@@@@@+.oO@$@+Oo+@##+@$$#@oO@OO  .X.oO+",
"o  .X..XOO..  oo..X....oO+@$@@+o....XOoO+Oo+ X....OOOO.++OO@@@$$@++++++o+@O@+OOOo@O@@O$$$++OOo..oO+@OOO+OO+.X..X.XOO$++@#+o. OOO+$$$#$OO+Oo +$@$+$#$@@@OO$#o.o ...o.",
"+++$+.X..o Ooooo Oo.XX..oO ooOO..X...o  oO.OO...XX.+O+Oo$#$+O OO@@@@+OOoO++O$O OOoOO$+@##$@OO+++ ooOO++O++o...X.X.oOOoO#$+o...ooo+$@+++@@+@O@@$$$+@$@++O+#@ OO ...oo",
"O+OoOOOOoOO+OOOO+Ooo........ o .X...X...X...o....X.@++++oO$$O.X.o+@$#$@+++OO+@OOOOooO#@++@+OOOO+@ oO+O@@OOO ........X..+OOO....ooOOOOO++OO@OOO+@@++OO@$#@OOOo O@$@Oo",
"OOOooOO@$@+@+OO+++Oo...XX...OOO .XXXO+Oo.+oo..o..X.OO@@+OOo...X..OOO+$#$@+OOo+@O+OOOO+$+O+@++$$+OOoO+@o$@.OO ....OoOOOOO.....X. .OOo@OOOOO@@++++#$+++$#$@$OoO+++@$$$",
"@OO++O@@+++++OOOOOoo...OOOOO+$$$@o..oOo+$$@@OOOOoX.#+@@OOOOoXX.XoOoOO O+O.++Oo@@OOOOO++++OO+OO@$$+OO@@@O$@+Oo .oOOOO@+OOOoX.Oo.X.. .OOOXooO+@++$@@@@@+@@$@@@@$$@OoO+",
"OOOOOOOOO@$$++@@+Oo.OO@$+OOO@$@$+o@OOOO@$@$@OOOO . $OOoo.o+..... Oo OOoOXX.+$+OOOOO@+++OOOo++++O++OO+@@$$@%+OooO+++O+@$OooXO+X. o  o.oo...OoO@$$#####@OO@##$+$$+OOOO",
"o$@O+++$$$@@#$@+OO+OOOOOO@$@@+Oo+$@OO@+@###+OOo ... o...XOo.XX.. .. oo......O$@+OOOoO+@@@O+O+++@@@OO+@@@#@@$$Oo +$$@ooO$+O..$@ o ..OoO+X... oO+O++@@$$oOoO++O@@$@O++",
"$#++$$$@@@$$$OOO+++OOOo O@$+OOO@$+@@@+++@@OOOOo .X.   .  oX..... .......oOOOOO@@@@@$@@+O+O..@$+ +OOoo@@@@$OO@$+OO@$$@+Oo++O.+#$o ooo@O+oX.......O+OOo....X..OO+@$#@@",
"++OOO+O++@@@O+@@@OO@+OO++@$+OO@$O@$$@$$$@$++OOOOO+@@+++@$$$@oo....oOoO++++OOooO+@++OO@$@OX..o@o.+$OOXO+%$$++ ##+OOOOOOOOOO$$Oo@OOO+O@+o@oX.....X ..Oo.....X...oO$$@O",
"+OOOO+++++o$OO@@$$$$$$$##$@O+@++@$$$$+O$$$@@+$+O+OOOO+@@$##$@O . O+O+++++Oo...oOoOOOo .XX... OO.o$+OX.+$%#@@++$#@OOO@$$@O+O@+O@OoOO$+OoO@.X. oOO+O++......XXXOo.OO.O",
"..X+@++@@OXo.X.O@@+@@$$++o+@$#+O+@@OOOO@@++@$$++$$+++@$#$@++++O+@OO++@@+OOOo...O.......X.... . ..oO.XXoO$##O++O+$@@OO###@@@@#%@+OoO+$OOoO+oOOoooO@@+O.o..o+ O#$+oO..",
"O..+O+$+@OXX..XX..OO+$$+XX.O##$$@O+$@+@@ooOO+@@@$#@@+$$##@O$#@OO++@@+@+ooOO.oO  oo Oo o.XX.X $.. ooO@.X.o+@$$@@@@@$$@O$$$@$+@@$+@OOo++O+O+$o+$$+OOO++OO+oO+@OO+$+ooo",
"......OO+o...XXX.XXXoOOOO..X. oOO+@$++O..ooOO+OOO+$@$#%%$@##@OO+@$+OOOO$#$+O OO@@@@@$$$$O... OO++@$OO.X.X. +$$$@$$+$@XO$@@@$$#$@++OOO+O@+O@OoO$@OOOoOo.o+OO$O.OO+OoO",
".X..... o.X.XX...oO.OOO+O....XX.oO$#$++....XO@+O+$@$#$$O$#$$@+$$@oO+O$##+..++O+++$$$$$$$@oooO+O@$$+OooO..XOOO@O OOoXX.Xo@++OO++O.++O@$$#$+$@O+O@@++@++Ooo++@@+O@OO++",
"O++OOoo.. ..X..OooO@OoO@ ..XX.....O@$+O.X...X.O+OOOOo+@++#$@o$#$+@@O$$+OOOOoOOOOOO+O+++ o+OO+@$$O++$++OoXXOOOO...XXX..XXoOOOO   ..@@O@+$$#+$@+@OO+@@@@++O++#++@OOO@O",
"OOO@@@@+OoO.o+OO++OoOooO..X.X.... o+OOo.X...X+O.o.OoXOOO##$O$##$$$++@++OO+@+OO++OOOO@$OO+Oo+@$++@$@+@++O.... .....X.o+o.o .oOo  .X.@@OOO$%OO#@OoO++O+@@OOo+#%+O@+ooo",
" +$$@+O+$+OoO+#@+@@++Oo ......  OO+OOO....  .O$. .o...O$+O+@+o++++OoOOOOOOO@+O+@OO+++O++oO@$@O@$@+++O. O+ ..X......oOOO.. ..o. ...X.++O++$$+++OO@@o+OOoOOOO##$+o@+oo",
"o @++$@OOO@@OO@#$$@@@@+++Oo.oO+O+OO+Oo.XOOOOO++O.......O+OO@+++@$+O. OOO++OoOOOO++Oo.O@O+$@++@@@+OOOOOOOOO@$+++o.. O@+@@+OOOo .  .XX.++OOO#OooOo..Xo+O+$$@o##$@++++O",
"O .O++@$@Oo#%$@@$$#@O O++@+O.+$@++OOOO  OOoO+O++Oo .....X... o@@$@O...o+@@@$$+O+OOOOOOOO$@O@+O+OO@+++O O+@@$#$$oooO+@$$$+OOOoO+ ....X+$+O ooOoX.....OOOOO+O+#$@+OO+@",
"@@OO+@@@+++O@@@@O@@@$@ooO++@@O@@+OO+OOOo.++OoOO+@+OO .........oO$@O.......o.O+O@o+Ooo$@OO.O$O+@$$@@@+O$$$$$#$$++O++O+#$@OOOoO+$OOo .XO$O++ooOoX.....@@.+oO@OO@+++.o+",
"@$@@O+@##$@+OOO+OO+OO@O o+$@@@oo@+++@@+@OO##$ OoO@@@OO......X...@Oo..........oOOO +Oo++$O@$$OO+++$@+@@##$@@+@@+o+@+O+@OOO O@$@+OOOO.XX+Oo+O.o..X...X$$O+Oooo.O@+O+OO",
"$$$@oO #%#$@O+++@+O@OOO$$o+%$@$OO++O+++@$@O@$+++o@++@+O.. ..Ooooo.... Oo...o o ...o@+OO@$$@OO+++O+$$$++@$oOOO+OO@@OOOOOOO$@+O@$$OOOo.X. .....XXX..X.+$O. .....O@++O+",
"o+O.XX.XXo$+++@+OoOO+O++@$##@+@Oo++++@++OOOo$$@@+++OO++OoO+$$@@@++...@$@oo.oOO+o...oo.OOOOOOOOO. oO@@OOOOOOO+OO+$@O+OOoO@@OO@$+++Oo.....   .O+o....Xo+OOoo ..  O+@@+",
".o ..X..X.@OOOO+Oooo +OO+$##$+OO.@#@O+$##$$@O$#@O+@OOoO+++@$@@++++O.oO$#++$oOo+@O XXX.X.oOO@@oX...oO+@@@+@+OO ++@+O+OO++OO@$$#$$+o.ooOOo  oo++O.....XO++OOO+@$+..O+@",
"Oo..X...XXoO.oOO.  .Xo+#$+@@@$+Oo.ooXo+++$$$$o@%OO$$+@OOO@O@+O+++O@+ o@$@@#+@+O+OOOX...X...OO......Xo+@$##%#OOOOOOOOOOO+++@+@#@O+@@+$$$$$@+ooOo.XX.ooOO+O++++O+... O",
"oOOOo...XXX.. o ...X.X.+@+O+O+O .XXXXO++OOOOO X@$+O$$+@O++Oo@$oOO++$O+$@+O@$+@OO+OO+X.oOo ....XXX...X.. O@$+O+OOoOOOO++@@OOOO+++@$$$$$@$@+OoOo.XoOOO$@@@@+OOoo ....O",
"OO+$$+  ..o .Oo OOOO X.$#OoOOoooXX..X++O+OoO...XO@+O$++@+O+OO#$Oo++@$@##+oO++OOOO@O$+O$$$+OO...Xo.... ooo+OooOOOOOOO+$++OOoO+OoOO++O+++++@@+OoX+$$$$@$#$O$OoOOooo O.",
"O+@+O oO+@OO++@OO++OOO.+OO      X...XOo.........X.OO++++O@@#$+#$OoOOOO$@OoOO+OOOO++O$.O@@$$@OOOO$@OoOOOOo.OOX..OOoooO+OOO.X.o+@@OoO@@@@$#@OooO@@@@@$@+OOo$$+OOOOOO o",
"$@Oo OOO+$$##$OO+OOoo...o. o.....XXX.OOo. ooo.XX.XOOoO+OO+@$$O+$$+OO@@+OO+OO+++OOO@O@Oo@+$##@OO@$$@OOO+@O.oo....  . O+OOo..X..oOOOOOOOOO@OO O@$@++@OOOO@#$@++oo$@+++",
"@$+O++@+@$$$@OOOoo. .O+OoOOOo....XO@@$@OO+OOoO...XO+@OOOOO@O+o.+$#$@+O+++++OoO@+OO$@O@O+@+O@++O@#%$OOoO$$+O X.......oooO .XX.. ..O+O+OO+O o+++O@$@OO$@$#$++Oo@##@OO@",
"$+O+@+O++OoooO+@oO.O+Oooooo.OOoo.O+@+OO+OO++ ...XX.O++O+OO@O X.XX@$$@O+@Oo@O+oo++++$$+OO+@++@O$$++OOOOO@+@@+O...... oo. .X+OX...XoOo+o. @$$$$$$$$###@O+OO@$$$@+OOO+O",
"OoOO++++OOO+@$$OOOoOOoooo  OOOo.O+OOO++++O++OOOO.X.OO$OOOoo.X..XX+$$+$+OO . O+OOOOoo+@@@OO@OO@$+@oOOOOo+@++@@o.. @o.@$@.X+$$++oo..o.OO..+$#%#$@$%#$@OOO.o@$#+$#$$@+o",
".OO@##$+O+@$#OOOOoOOOOOOoO+++O O@+OOO++@++@$$+OoOo..oOOo..X.XX.OX +..   Oo ..oOO@++@++++OO+$$OO+$$++OOOoO@+O$O. o@$+ Oo.X$#$$@+@@+o.o....O$$$@@@+++OO..XX OO@@OOOOo+",
"@$$$#$@@$#$$$+OO@$$$@@+@@@@+OOO++OOOOO@+$#$+OOOOOO.oOOOOOOoo..XO .oo... OOoo...OOO+@$@Ooo.o$###$++O+OO+Oo+o+O+OoOOO++++OO#@++@oO+$$$+O ..XX.. o.O++Oo....X.O+@@OO+++",
"##$+OO+@++OOX+$$$@O+$$@+++OOOOOOOOOO@@O$$@@@+O+OOOOOOOoO@$$$+oOoOO+@@@@@OOOOo..+oO++OOo  .X.@$####$++OOO+++@@O+o.@++OoO+$$.oOOOoOoooO+@..XX...XX O+Oo.XX.XX..  OO++O",
"#$o.o+oOoOOOXXO+O+++@@$@+O@+O+$@Oo+$+oOo@$@++OoO+$@++$$@@@@+OO+o+$+@#$$$@@+O XXoo. o.......X.O+$$$#$@OOOO+@@$OO+oO@$$OO@$++OOOOOOOOOOo$@X..........oXX.XX  .XX. oO+O",
"#oX OO OOoO X.XXX$#$OO@+o.+@$$+O+#@+O++@@OO++ ooOOOO$@+O@@%#O+O+$$$@@$#+oOOOX.oOo.ooOOo .....oooo++OOo..O++@+@OOO.@##OOO@$$$$$+++OOOO+O@o...X.$$OoOo.XXXo+++$+Oo.o+o",
".... . ooOo...X.XX...oooOXO$@@OO++@@$+@@$$$##$#OO+OOooOOO$#$+@$$$###$@+OO@OO+$$@@O++@+Oo.....oo...OooO.. O@@++@+O..@#@OOO+@$@$#++OOOOoO+@ O@Oo+%$++OOoX.OOo+$$$Oo.O ",
"X....oOooo.......XX...oOO..O$$+++OOOO++ +$$###$$@OO++@@$@O++@@@+$%#$@@$+++++$$@+++++++OoOO$..o .X.. .O..Xo@$+@+++OOo OO+O+@#$+OOO++OO+O@++O@$$@o@O+O+O+oOOOOOO+@@OoX",
".... O@@@$+XX.XXXo$Oo..  ..XX. oO++O+OO.##oO+#$@$$@@$$##+oO+@@$#@+@@$$+$OO@$+O+++OOO++O$#$@...oOOOOOO.X.X.+$+o+OOOOoO.o+@$$$$+OoO+++OO++$OOOo@$$O+$$++++OO$OOO+++@++",
".. oooo OO@O.X... +$$$O .XX...XXXoOOOOO@+$XXX..@$O$+OX$#+OO$$@$@+O$#$++%$+$@OoOoOOOOO+@@@OoOO+$$$$+++@+.@ +$OX.oooO..X$OO$$@#+@@ .OOOOO$$#@OO O++#$$@+@++O+@O@+#@+@$",
"O.O+@$$$+OO$$OoOOooOoOOOOXXXXXX.XX.o ooO#$ X.X.O+ +OO.XoO+@+o++@+++OOOO@#@@+OOOOOOOO++OOooo+@@@@+OoOOoOO@oOo .oOo.X...XO.@O+#$+....OOOO@OO#$@+OO@+$+O+@@+#@$#@@+@@++",
"O+ O@@$$$$@O@$+O@@OO.oOO+$OXXX..o+Ooo...+ooo.. o . OO...O+@@@$$@O++X..O@$$$$$$@OO++@++o.OOO+++@$$$$Ooo o..oOOOOooo . X.+OOOOOOO.....o@OO@$+@$$@+O$$@OO+++@$@$$@@O@$+",
"+OOoo+@@@@+++$+@##+O+OO+++$$+Oo+++@@+Oo.OooOOOOO+OOO..XXX..Oo .++o@.X. @$##$%$O+@@@O o++++OO+@@#$OOOO. .ooOOOo.. oOo.XXOo.O+ oo...X..o$@@++O  O+@++@@@+@+++OO##$+O+$",
"O@$$O++o+++@$##++$$O+Oo@$OO$#%O++OO++O@$+oOOOOOoOOO++XX.XXXX...o+oO.....X OOO+oo X.OoO+O++++OoooOOOoOOOOOOOOooOOOO...X.oo.O@ oo.......oO+$OoO@$$@O..oO+++OOOo+##OOoO",
"O@###@+++$$+$#$$$O$Oo+@O@++O+$+++@++OOO+@O oO++OOOOO++ XXXXXXo@$$+ ......XX..OOoo.X.O+O+O+OOOoOOOOOO+#$#$OOO++@@$$@O.OOOO@+OO . .....oO+oOOOOOOXX....OOO+@+.X.O$#$@O",
"+@+$$@OO++@#$@$$$$+@Oo@+@OO+@+O.o+$+OO+OOOoO$#$$$OO+O++ O.@$@OO+O..XX..XXX.X..o o....o$+O++O+O..$OoO++@$OoOOOO@$$@$+OOOOOOO   oOo....OOO.. ..OOX...XX$@ O+@OX..O$#@+",
"OOOo. oo++OO$$@+@@+@+OOO+$OoOO++O++++@OO+@O+@$####+++@$O..++$@OOOo  ...XoO OOO$ oX....XO+O+$+$.X+#+OO##$$@$@OOOOooo@O.OOO+OO+$$OoOo..oOo....X........@$o. O XXXXO$#+",
"oO@O ..O@O.OOO+++++O+++OO+$@OOOOO O+@O@@++@OO$$+@$$+$O@#@. +$$$@O+OOOO.o@OOOO+$$oX.o......$$+@o.X.@$@+$$$$$$$$+oO@@OO$+OO++@@++++OOoooooOOo  ......XX.O . OO+oXOX+O#",
"#Oooo.  ...Oo O++Oo.O+$+#++@$++O+OoO#+oOO+@@OO$+O+++%%$+#@.O@@@$$$@OOO+OOOO+OOO@...O .XXXOO@$+OX..X.OOO+$$#@+ ooO+O ++++@@@$$++@O.O@@OO+++$@OO....X OOoO++OOoO OXXO$",
"#oo .O.... o .oO+o...O+$+++@@+O+OOOOO@OO++OOoO+@+$@+@##$O+OOooooO++OO+#oo$@O+@+OO o. X+O. oO+OO.XXX....o.OOX.O+@OOoOO$$$$$$$$$$+O$$$ooOO++O@@O. . OOo..O+@O  OOO..XO",
"oo ..o ...X.....OoX. .oOO+$$+OO+OO..X O+OOOOO+@+o@$@@@+$$@++O OOoO+@@++O.@$@++@+OOoOoO+Oooo ooo.XX.OOO oo  ...OO+@$$@$$$#%$$$@+@$@OoOO+++++@@@OooOoOOOOo+@++++OOOXXO",
"oOOOooo...oO+O ...O O.X.O+O@+o@@.XX.XXOOOO OOo.  .O$@@@@@@+OO o+OO@$$$@+O.$@+O++OOOOO+@OOOooOOO OOoO.O+OOoo....O+@@$$$$##$+o.OOOOO++@+OO++@@@+OOOO++OOO@++@@+OOOO.Oo",
"OOoOOOo.oO+OOOo o@%+X..X +O. oOO...XX.oOo ..O... .X.@+++++$$Oo..O++$$$$@+O+$++O@@+OOO.oOOOooOOO+OO OOOO+OOoO...X..oO+@$+....X. oO@@@$@@$$$@@+OO+O@@+O+++++OOOo oO X.",
"O@+@OooOOOOoOOo$O$%.X.XXoO  ..X ....X.o .. . ....X.XO@+OOO+Oo.+ O@@++O+@+++O@++O@@+OOooOO@@OOooOoOOOOoO+O+Ooo......X. O.....X....OOO+$##$$+OO++@++O+@@+++OOOOOooOOOO",
"O$+OOO+++OO+Ooo$+#$OO.+#$@+OO++. ..X. o.O+o.o..X..XoOOO+O$@O.o%@+$##$$@+O@@+.OO++@+$@OOOO+$$+@+OOOOOO++ O@+OOO .... O+OoXX...XXXX..o  ...O##++$%#OOO@$++O+@OoOOOOOOO",
"OOoO$$@@+o@@OOo+@#OOOO$$@OOoO@+ooo O+OO@@+++O ..XXX@@#+oo@@O..#+o. OO@@@+OO..XO+OO+#$@+oOOOOOOOOOOooOO+Oo$@+OO+O...oO@$++ X.O+oo  oOo.X..+@@$@@O@+@$#+O@$$@+@++$$@++",
"@OO###@O O+OOOoo@$+O+$$+oOOOoOO+O +$$+$$OOO++o..XXX@$$$X..o .XX... Ooo  o .X..X@@Oo#@O@@+OO+++OOOoOOOO+$++$@@+o@OoO++@$$$$o  O+OO  o+O....+###+$##$+OO@$++O+@+o@$@@$",
"OO$$@+OOO++OO+$@@O+$$+OO@@+@$@++O@@O$@@+OoO+Oo.oO XoOOOoOo....XX. o o.........Xo##@OOOOoOO.O$$+$@++++O$O$O+O+$OO$+.OO+@@@++oooO+OOoooOO.XXX#%#$$@+OOOooX.oO++@@+++O@",
"oO@$@++$$+O+@@$+O+++OO+@$$$$+Ooo@@OO@@+@oO+O .@$$@.X.ooooO++Oo X OOOOoO......X.OO##$OoOoO .XoO+OO+++++O@O$++OO@@@$OO+O@#$$#$o+OO+@+OOOOO..XX.. . Oo....... OO+@$+O$#",
".oOO+$$@O+$$$OOOOOOOOOOO+++OOO$$$+O@$$++@@+oO+$@@O OOOOOOoOOOO.O$@@+oOO++++++o.OOo@$@O..X...X.$+@+@@o.XO@+@O+OO+@@@O$OO@$+++OOoO@O@O+OO+$ ..XX..oO ......X+#$.ooO+..",
".XO+OooO@$@+O .O+OOOOO+++OOOo.+++OO+O+++++OOO+O+++@++OOooOO+OoO++OooO@$@OOOOoo .O.oOO .XXX....@OO$+Oo..Xo+@+O+@OOOOOo#++OO+OOO+OO$OO+OO+$@+++++OOoOO.X..  O##$o.Ooo.",
"..XXooO$$@@ X... OOOO++OOoo++OooOO++@+$#$OOO+$$$$$$+O+@@@++oOO+OO@++++++Ooo .X.. ...o ........OO O++O...X.++++$$++OOoO@@$+oO+OO@OO@$$++@$++$+O@$@$+++O.. oO++$O. oO.",
"...XX .O$$Oo.....X.OOOO@O..oOOoO+###$$@@O+oo#%#$O+OO+$$$@+ @@OO+$$@+OOoO@O  oOoOOOOOO .....XX.X .X Oo.....o++O+++@++@.Xo@@@++$$O$++$@+OO$$+@$#OO+O@@$+O. OO$@$OOOOOo",
"X...X...OoooX...XXXX.. $O....oOO+O+++OOOOO++@+OOoO@@@OOOO.o+#@+++OOOOO@##+@@$#$+OO+O+@$O@O.XOO@+OOoO.XX...XO+@@@@@oo..X.$$@+OOOo+$@+O@@OO$$+$##OO@O+@++Oo@+O#+O+O+OO",
".X..OOOOO.o.X.. Ooo....Oo.....OoOOooOOOO..+$$@O+OOOOoOO+O +$#$Oo+$$@$$$+O+#$$$@O@+OOO+#$O+o+@@@##$@+OOo.....O+OOO++o. XX@$@O@oOoX@@$+OOO$@+@@@$#+OOO++#@O #O$$$#+O++",
"O. O@@@@$$+oX.OO+++Oooo ....o .o oooO+OO ..O+$$+++Oo+++@O+$$$@+$@++$$@OoO@@++$$$++O++O$@ O@@++@@+OOoo+OoX.  O@  O+.....X$$O +  .X.O$$@+OOO$@OOO+@$O@+@$@+OO$@@#$O@O@",
"+O.O+O+$@@$$+o +$@@++@Ooo..OO.. . . O+OOo..X....OO+$@oX+$+@#@+@@O+@@+OO+@@+@$#$$$#$@$@OOO$@O+OOOO++++OOOX@#@OO.....XX..X$#+........O++@@+OO#@oOoO  $$+#%oO@+@@$O+O+O",
"O++OO+OO+@##$@+OOOOOOO+++OO+oO@@Ooo.oOO .....XXXoo$$+$OXO$@$+@$@$$#$OOOOO+$$@@$$##$@+o@$$+O$+OOoO++@$@+@.O@+...@OXX...XXO@Oooo....XX.O@++OoO+OOO ...+$@%$+++@@$OOO++",
"OOOOoOOOOOOO+$+OOooOOoO O+@+OO+@$+oOoo .......oo .O$@$$OX..  OO++O$#@.oO+O++O+$@$@O@$##@@+O+O OO+OO$@+OOO.oo   O+  ......OOOOOO++o..X.+@++OO+Oo.   .++$$$@$O++$$+O+$",
"Oo +@@@OO+O@@+OOOOO@OO+OOo O@$@+@OOOOOO.... O+ooOooo+.X...XX.ooo@$+$O oOo ++@$$$$oo+@@OO@OOO+$@$+O@@OOOOooOOOO++OOOo...+@@+OOO+O$O.X..O@++OO$O ....XO@@O+$+oOoo$#++$",
"@++OOO+++$#+O@$#$OoO@+$oO+o##$+@OOOOOo+O.. O+$#+O+@Oo....XX.....$$$#OX.XX..O$$@$@oOO++++ +#$$$$Oo+OoO+OoO@@@$#$@@O ooO+@$+OOO+OO OOX...Oo.OooO.....X.+@OoO@...XO$$@+",
"$$$$O+$+@+##+O@$$$$+++$$oO+@$+o@$@++$$+Oo.oOooO@@+@@@oX..@...X XO$##OX..X.  $+.@$o.OO++O+$@+OOOOOO+OoO+$$$$$@@+OOOOO +@@+.O+@OO+OoOOXXXo .o.  X..X...ooo..o....X $@$",
"o+@@O@#$OoO++OOOo+@++O$%$OOo OO.o++@++@$@O.oO+OO++OoO$oX+%$O@@@O @@$.X...X..O@Oo@oX.oOooOOOOoO O+OO++OOO+$$##++OOOOoO$@+.O@@++$+OOoOOo.  ..Oo+O.XXXX. .OOooo....X.++",
"OOOOO+#$ .X.$+OOO+Ooo.O$#+@$@+@$+OO+++++@+OOO++@+O+@+O@X.%#@$###$OO+......Oo+ooOOO.XX.ooO+OOOOO XooO+@$@@@$@#$OOO+@O$@+o@#$++$+O+@@+++#$OOOOO@$@oO..oO+OOOoOOOoO.XOO",
"OOOOOOO ....@+O OO@O..XO$$O$%#@@#+O+@+@+O+@#@+@@+@O$$@O+.oOOOOO@$$+o....oo+O$O +  ...XXXXoOo+O++O O +##$#$@$$$oOO@+$+Oo@#$++@@$+@+O+@@@@@@+OOo+O++O@$$+OOOOOooo ..+@",
"+O+ OO.XXX.oOOO. o+O.$+Xo@@O+$#$$$+OO@@+OO+@@O+#@@@$O@+$O.OoO+++@$+@..oo...O oOoo.XX..X... +OOO$+oX...O+++@$$ O++O+Ooo+$@@+@$$+OO+@$####%$O+@+OO+$$#@OO$@O++@$+o.Xo$",
".oO.o....... Oo.... O#$XXO+OO+++@@OX.o@++OOO@@++@@#@@++++O$++O+OO@OOO o$$+OoOooOoo.....oOOOOO..o oo..OOo+OoOO O+OOOOOO+@@$@@OOO+@$#%%%%#$$$$$@O@+$@++$@++O@@@O  OooO",
"o  .....XXXX  Oo   .+#OX.+OoO++Oo.....OO@@OOOOO.O@$$$+oooo$$@+O+@o+@+OO$$OOOOO+O+OO X..ooOOOO.XOo..OOOOooo.X.oOOOOOOO@#$$++o.oO++@@###%#$@@+OOO+OOO.+@$@OOo+oo@@@+O.",
"$Oo oo .OoO@+++OO+OOoO.X.OO.OOo XXX..XOoOooO ...O++OO@$++Oo OOoo$#+O+++.oOOOOOO+O@@@  oOOoOOOO.O$OOO+@@@Oo.X.XX.++++@$#$Oo.X..oOOO++$###+OoOOO@$$$@$##$OoO+O$#$$@OOO",
"+$$#$@++O+$@+@OOOOOooO XX. .oo ...XX..o.. . ....XO$++++$@+O++OOoo@$+@OOOo++o@@@+@+@$$oO+OO++$#$OO+OO+OO+#@+o.O X..+O+++oO.... OOO. O+$$.OOO$$##$$@#%#@oO$$O$#$@$$$+O",
"OO@$@OO.O#++$o O@@+O+@$#$+OOooooo...X.  OOO  .X.XXoOO+++OOOOOOOOOoO@@OOOOO++O+@$@O+@@+OO$@++O@$$+@$O+O+o$$@+.O...XXX OOO.X... oOOO.OoO@XX.+O+@++@@$#$%@@+O+O+@$$$++$",
"o+@@+Ooo$@+o+@$#$+++O+@$$@@@@@$@O+O.oOOO+++O@+o...X.O+OOOOOOOo..O+OOO++O++O@@@+@@OOO@$#+o####$++++$$OO++@$++Ooo......oooX....ooO++O o.O. XO+oO$$#%%#$@O.X. oO+++$@++",
"+$$+OOOo+OO$#$#$@@+OOOOOO@$$@+Oo . OO+OOO+@++@@oO.X..OoOO  ......o@$$@@#$@oO@$$$#$+Oo$%#@@$###$OOO$$$OOO+$@OO+O O+OOooo.....OoO++O@O o....X.X..OO+@O$#+X...oOOO+@@Oo",
"o#+oOOOOO+++@@+++Oo OoOO+++++++O.O+ooOO+O++Ooo.@$...... o ....... OO+$@$$OOO$@@@#%#@$O+@@+o O+$$++$$#@+O. @O+%@ O@++++OO@OoOoOOOO+oOOOOO...ooX..X OO+O ..X.+O+$@OOO.",
"oo.ooO@++@$@O+@+OoOO@$+@@##@+Oo.O++OO@#++@$@OOOO ... ...oo .....XOOO oOOO.$$O$++++$$O+Ooo . oOO+$$@$@$$$+O +##+@OO@+@@OO+@O O$+++++OO+oOO..ooO ..X.O+X....XX.X.oOOO.",
"OOOoO+@@++++++OoOOOOO++++@@+O+O+++$+$@++@#@O+OOOoooOooOOOO ooo..X.Ooo..oo@#$oXoOO$OO@Oo. ooo.O++++OO+O$#$$o$#+O+@ o+O+$##$$@+@++$+O+OO.O@O.XO@OOo+O.o..X+$$Oo...ooOo",
"X.O$$$++@$$$O ..o+@$$$#$$@++O O@+@$@@#$++OOO++OOOOOOOO+O+O+OO  .X.oo o ...$# ...+$++@$@+O ....O##@@@++O@$$#$O@#@@@OO+@$@O++++OOO @++OOOo++O.@+++O@#@O.X..O#%#+ooooO.",
".... OOOO@++...... OO+@+OO.O@@@OO+OO##++OO+OOo+@+O+++OOO@@@OooXOO@OO+@O.o.+$oX..++OOO+$@.XX.X. O@$Oo..O$@@$%#+#%#%#$O++##$@++@++OO+@O+++oO+O oOoOOO$+@..oOo+@@+OO+O.",
"..XOo O oO+O.X.....X.Xo+oOO.@$+oOO@$@++O+@o.OOOO+@+@+O+O+Oo o O+@+OO@@Oo. $@@O.OO+o.oO.XX..XX. o++. oX.$#@+@$#OO#%#+.O+@$##@@@@@@+O+$++++OOO O+OoOoO+@$OO+oO$@@@OooX",
"....X. .  oo o.X...oo .ooOO..OO@@@$+@@O@@@+OoO+OOOO++@OOOO+OO@++++O++OoOOO@$+OOo. .X....X...X..oo .oOXXXO$@@OO+O +OX.XO##@++OOOO@@++++++O+O+@O@$@OOOOO@$++@OO#@o$$OO",
"....o  oOO Xo$.O++OOOO++OOo..XXoO+++$+$+.$$@OOO+OO++++Oo++o @+OO+@$$OOO++@$+O..X. OOoooOX.X.X.ooooO  ..XXXOO@++O+o....X.$##+OOOOo+$+++O@+OO #$O$#$O@@O+$@O@$+O$Oo$$+",
"O OOOooooOOO +OO$@OO+O+@@+..X..X..OO+$$@XXOOO+OOOOOOOOOOoO.oOO+@$++O++$+++@Oo.OO++OOO++OOo.X.ooO$OoO+O ..X.o++  ooX....XX+$+++o.. O$++OO@@@OO+o+###O$%$$#$+$@@OOOOO+",
"+OOo$$$$$@+++OOO##+@+OoO++O ...... . $$@X.XX. OOOOO+OOoOooo++@$+OOO++++@$@OO+$$$@@@@@OOoO..OOO@@O+Oo.OO..X........XXX.X.XO+O@O.X...O$+++++@+@+O.@#%#++$@@@@+$O@+oOO+",
"@@$$O+@@$$$$$@@+$%@o$$OOoOOo... ooo .O$+X...X.... oO$+. OO+@@@O+@@$++$$@O+O+++OoO@$+OOOOooOO+++@$@O@#$+o.X oO+oOo   XXXXXOooOO.X.X.XoOOO++OOOo...O$##$@@+@@+$$.$O+OO",
"++@#$.+@$$$$@@@++@$@O$#$+OOo .oO+$+OOOOO.X... o . oo@O...o+OO+$#$@+OOo+OO+O+++OOOOoX+$@oO+O+++O++O$%%$OoO@$$$$+OOO++O ..X....o.X....X.+OOOoO O#$OX.o+@$#$+OOO$+O+O+O",
"O$$$#+oO@@$$$@+++O@$#O+$$$$OOooO@OO++O O.X...oO$@OOOOo..XX.O+@@@$$$@o oooOO+@@$@$@+#$@O@@++OO+OOO+$$@OO+@+@$###$@+O+oooo++@OOO+++O....O++OOO.#%@ .. ++OO$$OOO+@O$@@+",
"@O#$#$OO++@@$#$+OOO$#$OOoO#$OO..$$@OOOOOOO.o O+@$$@OO+..X.X.O++$@@@$O.OOOOO++@@$+O$$+O$#$@OO$O+O+@+@OO++@@@$$@@@$OoOOO+@@+O+@@$$$$OX..+++.o..+#XX.XoOOo.oOoOO O@+#$o",
"@+O+$#@OOoO+@@++@@$+@@O+@O$%#$@+O@$@++++++OOOOO+OOO+@++X..X.X..OO+.XX...OO++$#@OOOO++#%#+$$#@O+O@@@$o++O+@$$@$+++OOOO++OooO$#@++o.X..X o..o .XX....o .o.oO  OoX+++#o",
"oOOO+@$OXXXO+O@$$$$@ +@+@#++$$$#$.O+++OO+$$OOO+OoOO+oO+..o++Ooo.oO XXXX.X..X Ooo@O.oO@$$$##$O$@$$$$OOO++@@@++@+OOO+$O+@O+@@@$@@@O.o ....OOOOo. o....Ooo   o.o.. O++$",
"O@+@$+O...XO@O@+++Oo..o@++#$oO@$#$o+@$$$++$#OoO@OOOO@o OX ooOO+O o ..X.XX.OO o .O+.. OO+$$@$#O@@OO+$#O$$+O+$$$O+O@@+@$+@$@+OOOOoO++OO+$@$+oO+O  oooOOoOO oO .....OOO",
"O o..XXX.XXOOO+.oOo....o@+O##+O@$$Oo++@$$O+OO+O@@oO@O+OOoO@+ooO@@@...... OO+@@#+ O... O@$##$$@+$oo@+++@$$+@@@+@@@$$@+O++++++Oo.o++O+@#$+OooOOOo Oo+OoOOOO+Oo.......O",
"...XXX.X.XX.ooo..X.....X++Oo@$+O$$Oo $#@+$$#$+@+@@OO@O++O+++OOOO@@$O .  O@@ o@$#+....X.OO+@$$@o$OX.++++++@$@OO@$#$+OO++$+$$OOOOO+@$@+OOOOOO+@+Ooo@+OOOOOooooO@@+..oo",
"o     ..XX.oO$O ......X.@OO+oO@+O ..XX@##$$@+OO$+$@+OOO+O+O$$+OO+$O$O OO.o$$OoO$$ ..X..X.. O+$+@....oo.O@$$o.oOO+OO+$#%$$%@++$####+OoOOOoO+@@OOoO+OOOOOOOOO++@@@O.oo",
"oOOOOo.X.+@+$$ooOOOo... O.oOoO.......XX+@@@OO .O$++#+$@O+OOO$##+OO+OOoo@@OO$@Oo$OOo.X.. oo .O@+oX....  .o$@O+..+++@##%#$$O.$$++@@+O+++O O@$#+O+$$oOO+OOOOOOoO+OOO..O",
"OOOooooO++o++++++Oo  ..ooO .o ..XX.....@O.Oo....O$OO$$$#$$@OO$##@O+@OOOO@OOO+@OO@  X.. O++o oOoXX OO . O.oO#$XX  o+O@@++O.o.OO +O++$$+o+@$@OO@@@+++++@+OOOO+OOooOOO+",
"+@+Oo++@+O++@+Oo.$+...oOOO+@$$+...XX.XXO........X@$O.@+@@++OO+$@++OOOOOooOO+o+@oO+ooOOo+@$$$Oo..+OoOOO oOOO@....XXXX.o@OO....OOOOOOOO@$+O+Oo++OO+@++O+$@+@OOOOOOOOOo",
"%#$O+++@++$$OoooO@@o O+++@@+@@+OOO .XXX  .......O. @O++OOOOOOo$$@++OOO+OO+.OOo#@OOOOoo+$++$##+o.O+OO oOO+@O.Xo.... ...OO ......oO..oo$#OX+@oOO+O@@$@+@+++Oo OO+OO@$O",
"+OO++$#@@#$OOoOOOoo+++@@@@$@@@OOOoo.O$$OOOO OOo+$o..oO$+oo.O$O. @$$$$$@@+O+OOOO$@OOO+OooOoO@$$@oO$$+$#oO++OO ...o+@Ooo o.X.X...... ..O$@XXXo..OOOOOO+X++@++++++$$$$@",
"O$++@$++$@o++O+O ++$$$$$++++O++O+OoO++OO+OO+++$@@o.X.O.o  ..#O..X.O+@#$$$@O+@+o$@@#+O+O$O++OO+$@+OO#%$OO@@@$@o. oO+OO@+OO ...  ..oO+Oo+$OXXX...oOO@OO.+$@O$$O+@$$$$@",
"OOO+++@+OO@OO@+OO$++@O+@$@+O+$+Oo oOOOO+@$$@O+Oo.Oo.........$+...XXo+$$$$@O.@@O+@+@$@O@@O+@$OO@##$+#+OOOO@@@$@OoO++o.O@+oOOo oOOoOoO@oo++X........+$O.. .XXO+@@@$#@O",
"+O@@@+O+++OO@O.+$###%@$$$@++@OOOOOOOOO$+@@$##$oo@@$@+OoOOOoOOO..X.X  oO+o..X.+$oO@Oo$$$$$O+$$+OO@@+ooOOOO+@+++@+O+##@oOOOOOO O+$$O+oo+OOO.. .. oOOoOO..X...Xo O++$Oo",
"o+@$+OO++OO@o..o+$#$+$#$+OO@@+O+$O+O$%#OO@@@O.O@$$$+OoOOOoOOooO$.X. ooo.o.X.XXO+OO+O+#$$$$+#%#@$+@+O+OOOOO+O@+O++OO@$$@+OO.Oo.OO++++oO+O+.O. OOoo++OO ........OoO+OO",
"X.O+OOO+@++OXo$..O$##$@@+O++ O@+$@@$#$OO$@++o+$$@@OOO@$@$#++OoO$+O+@O+@@@@Oo...OOoOOO+$+O+o.O@@$#@+O++O+@@@+O$$++OO.O@++OOOO .O@@@++O OO@+O.oOOO OOOOo... .  oo. +O.",
"X.X...o.o@ o.X ....oOO+++Oo@OO++$+++O$#@@@+OOOOOOO+@$$$@#$+OOO+@+O++++++$++Oo .O.oOOOOO XX..XO@.   oooO+$#@$OO$#$+o@OO@@@++@$OoO+$$O@+OoO+@.OOOO+O$$oo .OOoOoooOo$#.",
"XXXX.XX.oOO.XX.O......OO++Xo++++%$O.$$@#$$OOO++++@@+O@++@Ooo+++o+$@@$o@+O+#$O..o oO .Oo.....XOO......XOO$#$@+OOO@$+%@Xo$%$OooO OOO$@O@+@@+++.oOOOO+++O+Oooo  oooOO@O",
"+$+o+$O. O..X.O+@OOOOooOO..XX.. +@++O+++oXo$@@$@+++O@++$Oo.oOo+$$@o@oO++O##@O.....oo..o.XX..X. .X..o.X.X.@$@+oo+ooO$+o X@$@++OOO+++$$+O##@O++O+OoOO@Oo+O.OOO+O++oOOX",
"OO@+O+++OO XX oo+$$@O+O+@oX.X.XXX.@@@@OXXX..OOOoOO++@@@+O$$@OO+@+OO@##@@@+Ooo+$@++O+Oo+o++......o@@+ ...XO++@OO@@+OOXO%@.++@+Oo.o@$$++O+$#$+O@@OOOooOoO$oO$@+OO@$@OO",
"OOOO++OOOoOOO.O@@+$$@O+@+OXX..X...OOO+O.....X..+$$$@+oOOO@$$$@$@++@$$@@@++Oo+@@$$$OO$+OOoo  oOo+$@O.. ..X.Oo..oO o ...#$O+oo++OOOo$%$oOoo@#$@+Oo+OOoO+O$#$O$+@Oo@#$O",
"$++O+$$+O++@$$+O+$O+@@@+@@.X.OOO..o  oO..X.XX.X.oOo OooO+@$@$$@+@@@@OOOO+$OOO+$#$@@+OO+O.OOOO+$@O..O$$+o O@@+Oo.. .XX..O@OoX. OoOOo$#$O+OO+@@+O O@+OO+@O@@OO@++OO+@@",
"$$@@Oo+$++@$$$$@++$+OO+@+$+...oO$$@$+oo.X.o+Oo.... OO...X.O+$##@@$$.@@o+@@$++#%%###$@+@+O@O+O+OOO+$$@$o+$$+$@OOO++++o.X.+OOOOo.o Oo.O@$$$+oOOoooo.o@+OOOOOO.O$@+OOoo",
"oo$++O++@@OO$$+@+++@@Oo+@$$..oO.o@$$$$@O.OO++O@@oO.ooX..XXX.o+Ooo$$. $$$$$$@+++@+$$@Oo+O+@OOO++O+@+OOOO#$OOOO+O+++OOO.X +@+OooOo ....o$$$@@+OOo...X+$#$+O+OOo+O@++Oo",
"$o@@OO$$#+$$@++OO+O+#$O+O+@@+$$$O +@@@@@+O+O+$%@oOoO+X..XXXX.o..o+$.XX @@$@+O@++@+@@OOO++OO@@+OO+@@OOoOOOOO$$@$+o.+O OO+@+O+O++O......o+@#$$O.....Xo+$##$@++oOOO+@+O",
"##$OOO#@@o.@$$@+@@OO+$@+++OO$+###++$$$@$#$ ++$#@+ .O+.X..XO$@++.. O...XXXXXoOOO$OOO+@O+OO+@+OOOO$$@+.O+@+@@$$@+OoO +@O+@+O+OOo.O$@+....o .ooo$X...X.O@+OO+O..X++OO@+",
"+$#$$+$$+O.o+@@#+OO+OO@@@@O+O+.@@+O$##@O+$+@$O+$$$Ooo .. ++$%#$@O ....X..XX...o#$.O@@@O+@@O+OO+##$@O@$$$@+Oo++++OoO$+O+++OOO+@$@+OO.... oo.+#$XX .X.OO+O..oo.XO@@Oo+",
"@+OOO@$O o.OoOOo.o X.OOOO@@O$OoO@+OOO+$+oOO$#@O@+$$+OoOOO$#@@##$$@ XX  ooOOoo. +$OooOOOOOOoO+$#$@o.O@$$@+O+++OOOOO+OO+@OOO@$$$@O+%$  @$++OO#$oo.X.XX.ooO+O oOO..@@Oo",
"oOOOo.XX..XO ..oo....OOOOO+++@@+O@$@+OOOO+++#+++O@$O+OooO+@$+++$##@O.O+OOOO@OOoO+O.OOO+O+@++$#@oXX.oOO+OOO@$@#$o OO@#@OOO@$#$O+#%#$#@OO++O+OoO+OO.. oo+@+OOOoOOXXO$@",
"oo o...XX.Oo.O+@@O..XO+OO+O@@$+OOO$$$@+@+OO@$@++Oo O@##$ooO@@@+O+@$@+.OoO+++OoOOo...O+@$$@@@@OXX...X..Oo++++%%OoOO+$@OO+$###$$$@oO$++@$@OOOOO+OOo oO oOO+@OOOOOo.X.O",
".o..XX.+$+O@$$@+O+Oo..OOOO+++@+OO Oo+##$#$+O+OO++OOoO+%%$O +@$$+O.O++o.O OoOOooO+O.XX.oOooOOOoX.X..X....o+ . .++O ooOoO$$@$$@@o .O++@@+OOOOOO+O..OOOo+@@$OoOO....XOO",
"#@++oX$$#+@#$$$+OO++OXOO.OOo  .....X.O@@#%%#+OOO+++OOOO###++$$$##$O+oOOO+Oo.OOo O$OoX....o O ..X.OOo....OO .X.o$$$@++@+++@$@o+$++@OoOOOOOoOO+O+OO+oO+@$+OOOoO+@+.. O",
"#$OOOO+@@O@$+ooOOo.OOXX. .  o .o.....OOo.O$@o  ..OO@+OOO$#$+$#$#%%$$@+@$+OOoOOOO@$$O .oOOOOoo X. ooo.  oO@OX... $#$O+++$@##.X O+@$$+@+++OOOooOoOOo$$#@O@@OO@$#$O  oo",
"OO+oO@+%$OOooO@OOOOo.O .O+$##O   ...X  ..X..XX..XXoo+@OOOO@O+%#%####$$$+OO$@+OOO@$$@Oo@+OO+OoOo.. OOOoo+OO+XX..XX.OOOO+$##.X..X.OO+@+@$$@OO oO@@++@#@++OOO+O@$@@@OO+",
"++Oo@$$%$oo+@@OO@+O O#oX@%#@Oo oooXXo ooO++@O.X....oO+++@$OOo+##$+@@++OOOO@+$@+O###$@+++@+O+OOOo..o.oOO+@o++.X.o+...X.o#$.X.....X.OOO+++OoooOO+@++OOOO@$$@OO$$$$++$@",
"Oo$+$$##+$$$+OO$$+OOOO++@@+OO++OO .O+O+$$++OO .X..Xo#+oO@#$@ .Xo.OO+@@@+OO$+$$@$O+$$+$OO+@@O+@@@OooOOOO$$++##$X+#....X.$@....XX.....X.O@o.oOOOO+$@@++@@+O+@++$$#$$+O",
"Oo%$$$$O@$+@$O@O+@@$$$#$$@OO+@++oO++OO$@o+++++OoX.X O.o ..  .XXX.O+O@#$+Oo@@O@+#@OO#$O@.+++OOO+@#$O@OO+@$%#O$%O##oO+@+oo X. .oOoOOoO..OO.. OooOO+@@+o..X.oO++$#$@+OO",
"OO#@@@+++$$$@+o@OO@$$@+Oo oOOOO  +@OOOOO@@+++OoO .. .   O.... .X. O .oO oX.$$O+O$$@@#+@+O@++++O++@+O$O+$@$$#+O+$@O++$#$O++oO+$$@OOOO+.o+ ..O@oo..$$+oXXX.X..ooo oOO+",
"oOOO+@@$##$$+ .+@+oOOOO+@$@@+OO@$$@O++@$@++@@$$O. OO+++@+O ..+#...  ..o.o.XO##+++$@@@@O@OO@$@O++@$+o@@O@$@$@@@+@++$$o+$@@++..$$#$@@O@@ooX. .o..XXo@O ..XX.XXXXoooooO",
"Oo++$#&%#@+OXX...O+$@+$##$@O.O+$$+O+$@@++$$$@$#+oO+++@@+OOo . ooOO++OOOOoo.Xo##+OOOO#$@.OoX$#$OoO+$+O$O+@@O++@+++.$#$O+$O@$+o.oOOO @o@@ ..........Oo.XX OOO o    oO.",
"O+@$$#$#$@oX....X.+$$###+O@O.oO$+OO+OO++$@$##@+@OOOOOO+++OOooo.O@@+OO@@+ooo.XO$@$@OOO+OO+.XX+@##@+OOO@$O++@OO+@$+OO++@+@OOO@@OOOo+++$o++o. oooOOo  o.XXoO@@+Oooo oO.",
"X.. .oO+++.....X....o+@+..o$$+OOO+@$@@+++++OOO@$@OOOO+OO@@$+O+++@oOOOOOOOO+oXo$@$#++++$@oXXXO+++$$$++o+@O++@O+$$$$@@$+++$@@++@+OOO$$+$@+OOOO++OOOoo ....O@+@+$+OOOo.",
".XXX..ooO$O....o...X.OO@O..o@@+O+@@++OOO++.O$++OO++++@+++@O@@++OO+O+++@@@@O+o.+OO.X o..XX..X OOooO..XX.+++O++o@#$##$+$@++++OOOoO+++$O@$OOOOO$@OOOOOOO  O o+OO@@OO++X",
"X.++$O.O.Oo...++@OOOoOO@OX.. O++OOOOO@+o.++$$++@@$$$#%#+$#$$@@OO$+$$@+OOOo . X .. ....XX...X.+Oo o..X...O$$@OOo+##$$$@@@+OOOOOOO@O$#@O@+OO+O oO+@@+OOOo.. +$O.@$++@O",
"O$$$$@@@OOo..o@##OoO++$@OX.X.O@@@$$o+O.XXXO@O+@$$$@$##$###$$O+++@$@+$$OOOOO.oooOoOOooo..X.X.$@oOOoO+O..XX.+$@OO+#$@$$OX.+OOOOO$@O+oO+o@$+OOOOoO+@$$+@#$+Ooo$$+o@@@@+",
"$@O$$$$$@OO+o.O@@@@+OO++.X..XOoo+O.O$@OX..X OOO+@$$###$%%$$+O++@$O@##++$$$@+OOoOOOOOOOo..XO++O@+O++o..XX.X+@OO+++@$O.XXo@O..oOOOOO@+OOo+$$+OOooO+$#$@$#%$OO+#$O$$@$@",
"#$@+@$+OOOO++O.OoOO@@+O++@...X... .o+$OX.XXX.... @@+O.#%$$+oO@$$@+$$++O@@$+OOOOOoO@+@+++ $@+O$$ooO++OOO...O+..........X.Oo..X O$$XO+++OoO$$+OOOo@+$##$@@%$+O$#@@##@@",
"@$$+OOOOOOO$##$+OO@$$$+O+$+.X..... . o .X.. o++o #%OXXOOOO.OOO+oO+++@++OoOO+++++$####$+o++ +$#oO+@$$+oooX.+OO+Oo .X.XXX....+@o$#@...O+$@OO+@+@@OO++@$##@$@+OO#$$@##$",
"OO++O+$$@+OO#%%%$O+$@$$@O$$.OO+++OOoo @.OOoOOO+@$+$O..XX O+O+OoO+OO O$##$$$@+@$$####++$@+O+$$O+$#++$@O...@#$$$@@O ...o@.oo@@@O++o .. $#$+@$$$#$OoXO++++@++@$$@#$@@#%",
"OOO+@@@$@@@+o$#%%$ @$@+$$O@$o O+$$+OoOo.OOO++OO+$$+.X...X.OOO@##+$OXoOO@$+@$@@$$$+OO+$@@@O@+O$$$+@$$@oo.+$$@@$##@oOO.#$++@+OoOOOoo ..O+$$$$@$@@O.X.@#+OOOO+OO.$$$#$$",
"$$@O+$#+.O$#$@$$$OoO$$@+@@+@@.O@O+++OOOooOO oO$+O@@O.X.X.X...o+OO#OX.oOO$@OOOO@@+O+O+o@$OO@+++@@$$$O..oOO+@+O+@@+OOOO+O+@@Oo+@@Ooooo..oOoO+O+++....++o.OOoo.XXX.O@%@",
"O@$@OO.X.oO@$$@+OOO.+@$++$#@@@OOOoO+@+OO .OOOOo$+oOOOO...XX... oo+....X.oOOOO++Oo+++$$@OO$$@@@O+@O.OOOOOO++O+@+OOOOOOOO++oO@$+OoO+OO.X XX...o.X....o... o...X..X O@$",
"O++OO...XOOoOOO.....oO+O@$$##+OOO++O@#$$@@++$++O+OO@@@O.oOO. oOOOO.X.X+@.XoOOOOO..O$#@OoOO@++O+++ooO+++OOoO+$$OoOOoOOOOO++@OoOO++O OOOOOOo.+##........ OO ..XXXXo+O+",
"+OOOo...XOOo....XXX..o++O$##%#+OO+@$@$$$$$#$+$+@@+O++$#+OOoO@@+++O@OXO#@+o...o@O.X.O+OOOOO+OOO@@oOOO++@+@$$$@+@@+.+OOo@$@+O$@O+O. O++++++O+@$#O OOooO+++++ .+$OX.O+ ",
".  ....XX o o ooOO.XX..@$+O#%%#@O.o+$$@+O@@$O@@O@$+OO@$#@@+oo+@@@$$#.$%.oOo.  OOXX.X.oOO+@++@+o..o@$@+O+$@+++@O$$O++O$@OOO#@O@@O+++@OOOOO+@++O+@+OO+@$@+OO+OO+@..OOO",
"oo......XoOO@@+OOOO ....+$Oo@$%#oo..O+@$+O@$++@OoO@OO@$@+O$$+oOO+@$#@$#$OoO@+Oo XX.XX... O+O@OXX..O$#@ooOOO  @@@@+Oo@@O++@+O@@O$$+++@+O+@+@+o+@@+$$@+O@+OooOOo...o @",
"Oo ....XO++@+OO++OOO ..XOO+OOO@@Oo. .OO$#%%$@OO@+OOO+OoO+$@$$OO+O+@++o+OOO@$$+o@OX..X...X..O@@X...XXoo.oo.OX. O@@OOoO+++@#$@++oOO++@@$$$@$$$$$$@$$+O$@@$$+++OO..oOOO",
"OOo ...O++++++OOo.oOo...oooOo ......O$@OO$#$$o @O@OO$$+O+OOo++OOOoo@$$OoOO+OOOOO@+.+O oOO+OooO........ o++oXXX.OO@@++@@@@@++oo++@$$$#$@+$#@#%$@$+@O##$++++o. oOO$$@@",
"OOO ooO++O OO+$O+$##@.X$@+o ...X.....++.oO  X.X..O@+@##+O+$@@OOO$$$oO$+o+oO$#+@@OOO@@ OO+$$@Oo..OOO+@$Ooo++O.XXO$@$@@@@+$@O .oO+@$@@@@@$$O+$@O+O++@+OO+@$++++$+O+@+@",
"O++@+O+++OO++@$##%#@Ooo+$@  ....XXX..o...o .XX..XX+@OO$$@OOOO .O+#%$OOOoO@O@$@$$$$O++$$@Oo++@+Oo.+$+O@@+O+@@@O.XX.o. O@$$$ ...X oOO+@####$+OooO+@@++@@@$#%#+@+O+OOO+",
"$@@$++@@OOO+@$$$@OO@$+++##$$$$$@OXo@+OO+$#O. .X.X..O@+++@OOO....OoO++++Oo++++$O@++$+OO@OoooO++O+@o+#@+oOO+O+@$+.XXX.XXO@$+X....XX O++$.XO$+OO+@@+++++OOO@@OO+OOO@@@+",
"$@+@@@$+O@@+$$@@$@+++OO+@$$$$$$$+@@++++$+OOoOo.....OOo@++OO...+$@..oOOOOOo+@O@$$@++O+o OoOOo.O@$#$OO#@+o+O++O##OX.O+@O .@OX.X......oO+OXXO+OOO+@@++$OX+OOO+++@+$$$%O",
"++@@@+@++++$$$+@$$$@@@++O+@+++++@$Oo@+O$OO++OO ...X oOOX.O...o$#$..ooooo ..@@O$$$@O$OO oOOO++OO$$$$O++$$O++@+%%$o OOOO@O+.X. O+++OOooooXXX O.oO++OO#OX. O++O+@$$$.O%",
"#@@O+++$#$#$@+$$@$@$##$@$$O@$@$$@+OOOoO+O+O$$Oo...OOooo#+..... OO .  ++++...+@+@$%+@@$@OO+OOOOOOoOOo++O@@O@++#%#$o+OOO+$$$ XO$$##$$@+O XXX.X... $o @O.XXXX.OOO@++O.%",
"%OO+++$%#+o..oO+OO@$$##%#+oO$$$$+@OOO+@++O++OOOo+@+OOO##o++..X+$@OoOO++$+....O$$#$$O+$$$@++@OO+++o oo++O++++++$$#+$+OO+++$$.oO+O@$$$@$$oX..XX .oOo.oo.XXX..o.OO++O. ",
"@+OO+@+@OOX.. ..oOO+@@$$+oo$#$#$+O+$$$+@$$@OooO@@OOO@#$OO$$..oOOOO++++oo....XX+@$$@O@%$@+O.O@+OO@+OoO+O$OOO+O+O@%#o+OoOO@$$Oo+$@O#$OO+$+ X..o OOO ...XXXXXXXo+O@@o..",
"O OOOOO++o.........OOO@+.X+##@$@O$$$$@$$$@O@@oOOOO++@@OO@@ ..OO++OOOo   O .X.XO@oO$@O+O....XOO+OO++oO@OO$OOo++$$@+O$@+O@OO@@o$$OO@$@@@@@+.XoOO+O++O ...$$$+OOoO@+...",
"O....oO@+o..X..XXX. X.O@O. $OOOO@$$$$$$@OOO+OOOOO$$@@@@$@+OoO++OOOOoOOO++Oo..X.ooooO+o.X..X.@O+@$$@@O+oX$$$+ooO+OoOo@@++#+O@O@$$OO+O++@$$@OOoo+OO++@O.O$$+@+ooOoo.. ",
"  .....ooo.....oo O$$+o+O.XX.OO+O+O+@$$oO++O+O++$#$$+++OoOO++@OoO@O@+OOOOOo X.X.....o ......++O@$@+Oo+OXX@$$@@@+++ .$$oO+#@.OOO$$+O@OOo@@@@ooOOOOO+$$+ . +$+O.@+oX  "};
