/* XPM */
/********************************************************/
/**   (c) Copyright Hewlett-Packard Company, 1992.     **/
/********************************************************/
static char * Lichen [] = {
/* width height ncolors cpp [x_hot y_hot] */
"142 153 8 1 0 0",
/* colors */
" 	s selectColor	m white	c #7d7d7d7d7d7d",
".	s background	m black	c #969696969696",
"X	s bottomShadowColor	m black	c #646464646464",
"o	s topShadowColor	m white	c #c8c8c8c8c8c8",
"O	s iconGray6	m black	c #646464646464",
"+	s iconColor2	m white	c white",
"@	s iconColor1	m black	c black",
"#	s iconGray1	m white	c #e1e1e1e1e1e1",
/* pixels */
"       ..      XXXooO  +                  .++O+++o   o oXXXoo XXXXXXXX    XXXX.+ +o    o+++++......    o+Oo o+        o+   o  o o      oo     ",
"          .. XXXXX.XXX +o             o o. +++++o o o   XXX    XXXXXXX     XX...+o ooo  +  +  ..     +o.+oo   o    o   O       oooo  o +o    +",
"   +   + ...XXXXXXoXXX       +  +       .. O O+.o    o XXXX @o XXXXXX++     ......   .o +  ...     +++....oo+o@@X        ...   o ++ooo o     +",
"     +++ ...XXXooooXXXoo       O   ooo  oO+ o.+..o o o XX     XX++XXX     X ......  .... ...X..    O++oo..+oo+        .. ....OO++ooo oo o    O",
"   ...+.  ..XXXXXoooo+      +      ooo  +XX o++ o   o   +oo oXXXXXXXX XXX  ............. ..X..   X+++X+.o.o @@O   XX. .. ....Ooo  +ooo   o  ++",
"  . .  +    ooXXX oo  o                 XXXXo+O ..o     oo  oXXXXXXXX XXX XX.XXX ......    .X .X  O o+oo++o  o+ o@XX....  o..@o oooo   +  ++++",
"++    ..    ooXXX o.XXXo           o    XXXX++++..oo      @XXXXXXXXX@OXXX XX.XXX ....     o. ...    ++oOo@o@.     ...      oo @   oo   O++   +",
"++    ..   o oo o oXXXXX   +      oo..   XXO  ++..oo+o     XXX @XX+o +  @... XXX o.X    OX.X ...O  ..o+o+@ @o    .  +     o@ @oo+o+o+@+oo+   +",
"      +O.XXXX  oo oXXXXX   +       ...o    o   ..+..o @+ o XXX@@@ o @    .XXXoXX      Xooo ..X...   ..oX@           +   + +@  +++oo+O+ O+o    ",
" +      .XXXX   o .oXXXX   + oXXo+ .o.    .XX....+...@o+  @  o++Oo+ @  +..XXXXXXXXX  o ..XX.o....O  X+Oo@      .        XoXo+o   o.o+  ++++   ",
"   +    .XXXX.ooo ooXXXXo ooXXXXX  .      .XX... .... @++o@@@ o+@@ @  XXX.XXXXXXXXXo   ..X...X...   X+XX.   o  .         oXo@@  o +++ o@      ",
"            ...o X +oo++++OOXXX#X         ....#.....    @    @@  @    XXX.. XXXXXXX o   ..ooo.+@   @ OXX.                oO  o@o   @O++      +",
"     oo oo oo... +o ++   +X+XXX#X o       .#X.   ...  @       @    ++OXXX.   XXo   oOo     ooO      +++++          X      +  oo @ oo+O+       ",
"          o oo.X  +ooO   o+O+++#X o@o. X   XXX#   ..++@   @  o    +OoXX  ..  o oo  +o           o o +@o +          # XXXXo    .@o    ++   O+  ",
"     o+         O   ++       #o    oo+      X#    ..+O     @      o  XXo+.. o    ooo+++Xo o         o  X      #  X   XX  ..       o  X     +  ",
"      +       +O+    o     X o XX          X  X  ..+     ooo  O    o .o.oo oXXooX o Oo+o  ... o    +@     X      X   O.X     X     @@     ++  ",
"     o + ooo .+        XXX   X           X X    ..... ...  oo+O      o....oXXXX     ooo  o..o   o  @o            XX   +      X XX XX  X  @+   ",
"         oooXo+          o +           XX #  X  X .o.....++ o        o .XXXXXXXX o   +  o o..o o o@+ooX   +   X    X  @o        X X.o XO@++   ",
"   +    +++ ...         X  XX  @XX     X  .X #    o.. ..o .       o  o  XXX XXXX  o X oo++oo   ..ooo+oo.@o             .   X   XXXX.X  + @    ",
". O +   XX  ...+         X   XX+o     X       XXX.oX. ..o o   XXo  XXX  XXX .o.  OXoX  ++O  o @o@+.o.o@..+.             @ XX X  XXXX. +O    ++",
".++    XXXX ... +     X    X  X++      #        .oXo# .o     XXXXXoXXX   XXX.oo  XXX X X++    ooo+o.ooo.@ o   .o                 X..   X    ++",
".+   o XXXX o   o  # X   X X XO+O      + X X    X.   oo#...o.XXXX@ XXX@  XXX... XXXX X XX o  o+..@@o..oXX .   .     @o  @X oo X   +  @  @   O+",
"++o oo XXXX   oo ooo #     XXX  X  X@   +o..o    X # o o#oooooXXXo@    ..XXXo+  XXXX XX+  o    ...ooo..XXoo   @.o   +  . X oX      X   XX   + ",
"+..oXXX XXXX        o# X..       +++    O#.oOX X .o# @o##.. o@  XX     X.. o X  X++X XXX     o XXXo+...oo+o.@o.@@ O++.              X  @    O ",
" ...XXX oXXX XXXX#XX X .X    X  Xo@Oo  +O oo+OX  ... # #oO#oXXoXXXX   oXXX@  +oXXXX++XXXooo    XXXooo..oo @..X..oo@ @    X        XXX@ ooo Oo ",
" o..XXX .XXX XXXXXX#Xo#.X         +++ooO     o oo...     o oXXoXXXXXXX XXXXXXXoXXX+XoXXXoXX    XXXXXo.o    +.@o@    +o  X     X      Oo  ++++o",
".oooo XXXXXXoX#XXXXXXo      oo    +oOoo+ oo  +o .o..o ..oO@@o...XX@XXX XXXXXXXXXXX+o+XXXXXXX  oo..XXO++o+Oo.@@o @@  +  o         +   oOo+o++o+",
"..  oXXXXXXX XXXXXXX oo      X Xo++oo+@o@    +   @.@.+@oOO+@@     XXXX @+  XXXo+oooXoXX XXXXX oo  .. ++..o.o.@o@ .++O.@.   o X        ++  ++oo",
"o.oo XXXX    XXX#Xo    o     X o OoOo+oo@       +  @@.oO+O+@XX   @XXX  @@+@+OO+OXXXXoX  oXXXX X      +XXXo.o@o  @+ @@ o@   ..XX     o +oo ++  ",
".   oXXX  XXXXXX##   o    .  o o @@ @@o+      @ ..O+..O+@+++XX++X@XXX.  ++..XXXXoO+XX    oXXX+XXX  XX XXX+o @ O++   @ ..   ..      o  oo+O++oo",
"...  oooXXXXXX#XXXo@o       ooo  O+oOO   @ o+   ..@o++@o+o++XX@OoXXX++@@+@.XXXXXXXXXXX  XX    XXX+ XX XXXX    ++o   ++o o.X   X ++    oo+++++O",
"...  ..XXXX XXXXX  oo...  ...+ o @ +o+  @@+O O    OO++OXo+O++o..XXXXoX.XXo.XXXXoXXXXXooXXXXX  XXX    ++XXXX   oo         ooX o ooo@+  o oooo  ",
"...o ..XXXX.XXXXX@o..o..  ...     oo+@ @ ++  @ @  @Oo@O@ @+o ..o@XXXoO XXo .XXX.XXXXXo XXXXX     XXXX OXXXX o+ XX + o   o XooXoo  @O   o++    ",
" ++  .o.XX..o @X#X+..o.. o..X...@ +   @++O...     o   .@  +  ..XXX...XXXo    ..oO+XXX+  XXXXO+   XXXX + XX ooX X  X..ooo. XXXXX + @ ++@  +    ",
" +   o    X#oXXXXXXo..   XX o... ooo oo @ ...   ++o.o @   Oo  .XXXXXXXXX..   o..+  o oOo+++     XXXXXXX  X@X@   X..... o..XXXXXoXXX XXX @oO+ +",
"++      o XXXXXXXX++O   .... ..oo    o  .@...O+OO@   @.  ++O o.XXXXXXXXX...    oo ..     +XXXX.XXXXXXXXX  +@@ X....... XXXXXXXX+XXX XXXo  ++  ",
"XXX         XX#X+o#@+ XXX...XX+..XX  @  ... ...O+Xoo....++O+ O+  XXXX...... .@o  o...      XXX.XXXX+XXXX XO    XX....XXXXXoXXXo+XXXoXXX    +  ",
"XXX   o   X..XXXXXX++ XXX..    o XX o o ... ...   @oo.o.+o...    ..o..........@@o@.o. o   .XXX.++XX  XX  +X  ..... . XXXXX XX++@++O@O      +  ",
"XXX       o.oXXXXXXXX XXX..oX  X       o.  +.@.      ..++ ..oo    +.o....  X.@.@  o.oo ++ X.+OO++XXX @   +oX ... X   XXXXX+Ooo@+oXXX+      ++O",
"++X       ..o XXXXXXX@  ...o+  ...  o  .. O+..o     OO... ...o  .o +.X.     .@ @  ..XX@ +XX.++OO+XXX +o++Ooo .X.+       XX++o+XXXXXX@+     +  ",
"  XX          oXXXXX..@ X..  o ... o+      ...o     O......+. oo o oXo. X       o o XX.X XX.++.. XXX +oo @oXo Xo..   ..O o+ooXXXXXXXXXO@      ",
"  XX++oo    X@oXXXXXXXXX...   o@o.+@       ..       +......o+oo   +oOoX      # #o @@XX..@...+....    O+O @  o o.X.+  ...+oo oXXXXXXXXX   O    ",
" XXX++ oooooo+oXXXXXXXXX.      OoOoO      .          .......++  oo   +oX X @ XXo .  XX o...@ ....       +oo X  .X.O ...XXXoo  XXXXXXXX @++    ",
"+XXX   XX +oo oo  XXXXXX.    @ +o@@+++    .          ...XX. o    o    +    @@XX @ @XXX@.....@...     ooo+o oX@ o     ..XXXoo oXXX+XXXo@  +@  O",
" XXX   XX o+ XXXO+oXX+@...o   o@O+O+@@+                .XX  o o  o    X   @#    #.+XX    XX@.@.XXX    o o o  o Oo ..  oXXXo++oo@o@+oo   @@   +",
"         oo XXXXo@.XX o... @@  +++++O+o@      o...o.   ..   o  o     o      @ +#..@+ @ @XXXX...XXX         oo@  oo@.++... o+ooooooooo @X     +",
"X        oo XXXX o.  XXX.o o o o @+@@+       .XXX O    .. o  o o                ...+o++XXXXX ..XXX         O@ooo oooo+o..O @Oo@ @ o X X  @    ",
"XX         @XXX Xo   XXX.oX  o @@+@+ @    + oXXXX.+    ..       o         #     ..@    XXXX    @XX        o+o+ @  @  oo     +o ooo X.X.       ",
"XX  @    o  XXXoo oo XXXX   X +   O  @    .O XXXXXX.            .          #       XXX  XXXXX X XX  @XX  o+o+     @oo@@  @ +Oo@  o .@.XX     .",
"XX     o @@o.o  X         X Xo+  @o  @      .. XXXX.                  X  #      o  XXXooXXXX. X  ##@ +  XOo+o  @+   @  o  o@@o   @ .@..     O+",
"o +    @@ o o oX  @      X   o @o @@        ..oXXXX.   ++         X XX X@  #  @o oOXXXooXXX..X  X   @@OOXo oXX @O         +@oo  ..@...   XXX  ",
"XXX   ++    oo   o      X X o o @   @@@   +++..XXX.    O..o +            X #   X+o o o+oXXX.X   XX  X  ++ ooXX +o o   oo o+@o   oo@.X    XXX  ",
"XXX     XXX    X o  @        X@o@@o @@@ O++O..XXX +    +....OO  oX    X .X  X        ...o o@@  XX     o oo  XX o o o    oO@+++ @XXX..X.  XXX  ",
"XXX@XXX XXX @o X         X  O+@OO@o@ @@@ o o.oXXX O.   +.... o      XX# XXX X        oo.       X   @X o +     +@oo oo  o oo@+@ @ XX..XX     ..",
" +  XXXXXXX+  @o            +O@O@@     @   o.oXXXo+oo o++.. o  +      X#X X XX  X    @o.       OO++O+  OOoo+X o oo@o   ooo@@+O@  Xo......  ...",
"o   XXXX   @@     @  +      @O+O@+@@  @ @  o  +O+...Oo  Oo         X    X     X oXo@   X       OX.X++OOoOXo   o @        o ++@o    X.....  ...",
"     XXX  @@@       .X.         @+ @ XXXoo+  ooo+o..O@ o + oo      X     #    X XXoO     X X X O.X+O  O oXo   oOoX         o+O     ...@..O+.  ",
"   @ XXXX@@ @      X.X....       oO @XXXX XXXX++o...@ o o o.o          XX    X    +   X   XXO@ +OOO+  OoX o    ++O+       oo @+     oX.    .  ",
"++o@+XXXX@  @       .o....    XX  +++XXXXXXXXXO@o@o+O++@  o..             XXXX  XX o     X X+X +X  X    oooX   +oo+        o  O      ... ...  ",
" @  +@XX +XX       X+  .o.    XX @@ ++XX+XXXXX@O@@@+Oo@@o  oooo  .         XXX XX  o     X.XXX+o.o  ...oXXo   X     X        o.o@+     . @    ",
"    O@XXX@XX    XO  OX XXX          + XXX XX@oo@o@@o@o@+o oo OoO+              X XX XX  X#XXXX@ooo  ..o          XX       X   .o O            ",
"    +@XXXXXX @    O+O+oXXX   O+   @@  XXX oo O+@@@@@ooOoo@ooO+oO            XXXX  oo##Xo.XoXXXO...  ...  o  X   X  X XX      O oX.@           ",
"   @XXXXXXXX@     XXX .XXX XXX+++     XXX  oo+oO+o+o@++@+OOo+oOo   ..     X+         XX#XX##@OO.@.  O++o              X      O   .@    X X    ",
"@+  XXXXXXXX o     X+o... oXXXOo   @   +++ o ++Oo+o @OO+O+  o+   Oo.. #    XXX      X# X    @  oo@      o  . ooo.   X  X     OO  XX .     X   ",
"      XXX@        o+o X..OXXXXoXXX       XXO++++OOO o+++@   o XXXXXXXo.o    # #      .. X     .  @o     o oooooo.   X+  X X      X XX  X X.   ",
"  @o @XXX++       oXoX XX.XXX  XXX   XX  XX@+@+OOOO@o     o oXXXXXXXXo o      #  X   X         .  @      +.  o...        X     XX  X       X  ",
"  @    +@@oo     oo+  oX..XXX.oXXX  +       Oo++Oo@ @      o XXXXXX oo      ooo                ..      oo+oo   X o   @ @.   X ..XX  X X       ",
"       o@    o@++ooO+  .XXo....o+o +..+     @++++ @   @ X   XXXXXXXo    o  oo@#      X  +  o  @..o   @  oooXXXXo     @@..O  @ ..++O X     XX  ",
"   @o @O@@ oo+oXo++oo..XXXX.@..+@o o...     @@  + @ @@     .XXXoXXXo        @oo@ X X.@ +o@.@...@@.. OOo oo+XXXX  o   @   + @ @ ..+ X   X ..   ",
" @  . .+oo   ooX.o XXX.XXXX o   +@++...     @  @ O         oXXX XXX o         @@oX  .o.+ XXo@...o@.  +OOooooXX  o o  @     +@ ....... XX X..  ",
"       @+oo ++oo.. XXXXXXXO  o +o@  ....     o  +O+            o+oo  +       o@.o XX..X@XXXXo @....   +XXXoXXXX o+O@  @   @@ @.......    XX.  ",
"   +    O  o+o X ooXXXXX   @  o+o@    .. +      ...   O   XXXXXO+O XXX+o       @    X..oX#XX.      XXX XXXoXXXX o++@o  o    @ O......O +  ...O",
"   +..      o  +o   XXXX  o+o@+      o   + o  o .o.   +   XXXXX +oOXXXoo       XXX@o   #XXXX.     +XXX XXXOOXX o ++XX .. @@  .@. ....XX+  ... ",
"   ....  o    o   +       oOO@@o.o.@@  +oo o  o oo.  @+   +OXXX ++OXXX X      @XXX@oo OXXXXX o@  .+XXXXXX Oooo +O XXXXo.@@   .@@ ...... ..... ",
"....o..      @+ o +XXX      +O@+...@ oo oo   oO++o+OOO+   ++   oOOO    o       XXXX#OO#XX#XX   o  O   XXXX+oOoO++oXXXXo   @ .... ....XX ...   ",
"......    @  @...XXXXX      @OOo@@.o   oo oo oo+o.@@++O+O++  o   o+o     o     +XXXX##X#X #XX@ oo    XXXXX+oo XXXXXXXo   o o    .....XXX...  O",
"oo..o     o   ... @XXXX      @+@+@  oo@  oo +O+++XX. ..@      o ooo  o+  +     +XXXXXXXXXXXXXo @@ o  XXXXX   oXXXXXXoO oo+ @@   .....XXXXX   +",
"  ....   .. .....X  XX@  O    @@+@   OOo    +o+oXXXXXX.XXX  ooo o+ o+O   + .   +XXXXXXXXXXXXXo   oo   XXXX     XXXXXXo oo@@o@o.@ X.  XXXXXXOO ",
"  ....   ..oX..@OX@  +X+     @  @@ o +o@oo oooo+XXXX## XXX o+O++O++  +o  +o    oXXXXX..ooXXXo  o o @   XX    XXXXXXXXo  o +ooo.@  +  XXXXXXXO ",
"   ..... ....X@ XX @  X      @@ +    +++ @+oooo@XXXXXX+XXX@O  +o +o  oo o+Oo  o oXXXXX.oooo#ooo o  oo X+    XXXXXXXXX o  oOX.@..   o   XXXXX+ ",
"     ... ... @...  X          ++    ++@@Oo+o++o XXX###@+  o o o  oo oooo++Oo o.@..XXXXO #    o@@o     @OO@  XXXXXXX     ooo XX.XXX.@. XXXXX   ",
"   X ....... X..@      X      +    o@o+++oOoo  .XXO.++   XXX  o ooo   o ooooooOo...o  o@#o    oo  oo o ++@  XXXXXXXooo Xo+XXXXXXXX.@.oXX...   ",
" X  XX oXX   O@..      XX o X       O@++oo oo  @XXo@@X#X XXX oo ooO o  oo++oOooo....   ++O  X # oo@+ @+O@Oo  XXXXXOoo.  +oXXXXXXXX@@XXXXXo. XX",
"XXXXXX  .X.O++OXXX   X   X  o   o   o      oo  o@ XXXXXX XXXX o  +O oo o+o@ o@ooXo      +++OO o oo  @o   +O  XXX  o..X  +oXoXX X+   XXXXXXo XX",
" X X..XXX...+++XXXX @ X  X  XX  o     @@    o o XXXXXXXX@oXXXo XXX+oo oooooooo @        #+#oo+o oo @ O   +++oo@...oo..+o+..XX XXXX@oXXXXXXX   ",
"    XX ..@X.+ +XXXX@  X      OOo  @ @ @      oOXXXXXXXXXXXXXX XXXXo o  oooX XX@oX     o  #+oo++o    o   @+o   o..oo..+ oo.XXX+XXXX @  @ XXX   ",
"    XX XX.X.+O  XXX  X  Xo X+oO  @@.@       XXXXXXXX.XXXXXXX  XXXX o o  XXoXXX@X @       oXooo+o++oo    +o+@@o ..XXX.+++O.oXX@XXX @XXX@oXXX  +",
"  X+X+ XX          @  X oo ooo+  .@@   ..X.. XXXXX @...XXXXXX  XX ooo ooXXoXXXooo+      o o +o+o           O+    XXXo++OooXo+XX@o  XXXXXXXX  +",
"X ++@XXXXXX.   O+       X  XX   ..@.   ......XXX    ... oXXXX  XXo  + ooX XXXX o           @o@ +   o       @ ..  XXX+o..  XXXXXX@o XXXXXXXXXX+",
"++XXX oXX@oo+++O+    XXX    Xo  .@     .........   O++   .XX         ++X XXXo@o+     o    @Xo  o  o          ..ooo    .o  XXXXXX  OO+XXX  XXXX",
"+XXXXX  Xo  XXX.       XXXo .o         . .......XX   o  o...   XXX o oOoOXXX@XXo          o o  oo       +  o o  XXXXX     XXXXX.oOooOO+   XXXX",
"+XX.o.X.@.XoXXX.       X oX  +  o    ... .......XXoooo XXX..o oXXX  OXX oXXX +oo        .@  ooo+ XX+    ... ..oXXXXXX     o o ..oo + @    OXX ",
"++.o.X X.@  XXX. XX    X    XX# +# ......o.. o XXX @@O XXXo   XXXX OooX  o               o ..oO+ XX +   ...X...XXXXXX oo..o.o ......    o+++O+",
"+++o..+...   ... XX     X X ++ # ......ooo.o+  XXX@@@OoXXXXOoooXXX  o+oo  o     @@@o       ..XX+o   +  XX.....XXXXXXXX o.... oo.oo.XXX  + ++++",
"oXOX  XXXX ...XXX     X  X X#XX  ..#.....  oo  XXXXOo   XXXXXO XXX  ++o  o      @XXo       .oXXoo   o XXX   ..XXXXXXXX  o...    +..XXX  ++O++ ",
"+X++  oooo...oXXX  ++XX X  XXXX. .....o...o . @o  O+Xo  XXXXX+XXXX  +o+OOoo      Oo+      O   o++XXXXXXX    X XXX oXXXooo +o o  O  XXX   OOO  ",
".Xo+X ..o.....XXX  +++X X XXX#XXXX...o..ooo.o o..o+O@o @oXX O+XXX+Oo+++  oo        +      @    oXXXXXXX  ..         XXo oo ooo      ..@      @",
".X   XX......+ XXX ++   XXXX#XXX#X...ooo..ooo..oo++o+@ @    +XXXXXoO+o+ o o        @  @         XXXXXXX ..XXXX XX    XXXooooo   .   ..@     @ ",
"X.o.o  +...o.+ XXXO++XXXXX XXXXXXXX .oo.oo.ooo.oo@O+@ o    oOo+++oooOO    o           .@        oXXXX ++..XXXX XX    XXXooooo..XXX  ...    +X ",
"+..XX Xo.o.....XXX   XXXXXXXXXXX#XX  ..o.o.o..ooo@ o  o     ooo+o+oooo oo  @        .o.. @o     ooXXXXXO+.XXXX XX. XXXXXooo  X.XXX         +@ ",
"+@...XXX... ....XXX  XXXXXXXXXXXX#XXO .ooooooO@ooo @+o    oo+oooo+ooXoo    @+       ..@...@. ++   XXXXX+O.XXX+ XX..XX o o.o oo XXX .     @    ",
"o..X   +o   ....XXXo oXXXXXXXXXXXXXX  oo.o..oo           o oo ooo++Oo       +     +o.@.....oo+   XXXXX+O+.XXX+ .... oO+ o XX o        .. X @X ",
" ... X    o. .. XXXXXoo +XXXXXX #XX  +...o...o oo@           o ooo ... +o  @ @ ...++.......+  oXXXXXXX.o...XX   ..   oo.O+XX   o +++  .. X    ",
" .X. XXX  ...o   +XXXX o XXXXX##XX#X +o.oo+++o@  o @        o o O+o.Xo.o  @.@ @...++...+.  ...XXXXXXXXXo..XXX   +++. ...Ooo   XX ++      @    ",
"    oXXX .o.oo   +XXXXo o XXXXXXX#XX Oo++ooo@o@@@ o@  @      o o..X..........  .....@++... ...XXXXXXXXX..OXXX   .+#XX...O oO XXXX+OO ...      ",
"    .XXXo...o.  +o XXXo  oXXXXXXXXX   + @oo+o@@oooo@      +o    XXo..o....... .. ...  O...+...+XXXXXXXX++XXXX.. O+#XX#. .oo oXXXX    ...      ",
" o +.o.o  ...XXX+oooooo o XXXXXX          @o+ooo o@       +     +.oX......... .@ ...  +...O ...o@XXXooo@oXX. XX o.XX#.#oo..  oXX     ...      ",
"   +o.. +  o.XXX++o oXXXXX XXXXXX    @ oo oO@++o        .o o    +.o+.........     ..  +     ..oo o@ o+XXX  XXX#XX.XXXX. ...  Oooo o  +.       ",
" ++     ++o+oXXXOo+o+XXXXXoO   o@o ooo@ o +++++@O    +O...o    +oXoo....@.....     ....     .o.Oo@  o.XXXOXX #XXXXXXXXX# + o   oo  ++O       X",
" +  o +o  o+   ++++@o++XXXo      o     oO @@+o @@o@ .......    Xo+ ............@  ....   +  XXo@.o..o.XXX+XX  XXXX X#XX#Xo..o oo ooo+O     X  ",
"++oo      o+o    O+ooo +Oo      o   +++XXX oo  o @  ... ....    ..+XX.@.++.....+@@ ...   +  XXo+o..o..@@XooO   XX#XXXX#XX..oo    oooO+    X X ",
"    ++o  ooo     +O+@  o++         ++XXXXX    o  o @... .....  ..X+....+  ....     ....  oo.ooo+...ooO+O+++#XXX XXXXX#XXXo..ooooo..o++       X",
"    @ +o+ oo    @  Oo@  @@   + XXX.. XXXXXXXX   .o@    ...o.o     +    O  @#@@    +.@o@o o ooO+ooooo+@+o  ..XXXX#XXXXoXXXo..ooooo..@ooo      X",
"XXXX @o   oo o +    + @  @   +XXXXX.  X++oXXX @ ..   . .o.. ..        X   .#.. .oo+ ..    o OOoooooo..   .o#XX#XXXXXXoo+.+ o   oo   o+X X     ",
"XXXX++   o     O    @  @ o..X XXXXX... O +XXX  @ O..  +....o..        O @#......X.  o @    o++oXo.....   .... X XX .ooo ++ oo ooo   @+  ..   X",
"XXXX+o@o    o  +o X @..  .....  XX...oX++X+@   @@...XXX..o.....oO   XO+..@X..O..@. @   @  ++ooOo.......  +XXX+oXXXoo..oooooooo      O+        ",
"   + @         o+++@@.@++..... oXXX.o.XXX++.@.@  @..XXXo.o..   .X      ...#@.@... @ o+o ooooo+ooo.oo...   XXX oXXXooXXooooo+o      XX  X      ",
"   o      O+   XXX+o+.@ @  ... XXXX.ooXXXOo..XX..o..XXX... .   o   #X X       o+ @ O @@oooo  +oo   ...o   XXXo+XXXXXXXX  o o      X     XX    ",
"    o @  O+o OXXXX.+O@.   @.XXXXXXXo +XXX  X.XXo   ..O .XXX.   +    #X  X      ++ o o ooooXo ooo   .  +    o + XXXXXXXXO o  o        +    o   ",
"     XXX X.. .XXXX.+oo  @ @.XXXXXXX o+O+ o oo..o   +XX..XXoo      #  # @#      @@@@o   oooo o o    .     . ooXXXXXXXXXX+XXooooo o  o+o@   o   ",
"X   @XX........XXXo ..   .@.XXX XX+.o Ooo    ....  oXX...           X         @+    @o        o X    .       XXXXXXXXXXXXXoXXXo oo+o@@.X  .   ",
"X @ XXX........XXX.    +O.@...++XX+ oXX++o   .o..  o+.X  ..        #  #       OOo@ @++      Xo       .     ooooXXXXXXXXXX  XXXoo oo.@.@   @   ",
"X   XXX........XXX. @.XXXXX ..+OXXXXXXXXo+  o.X+..  ++.X  X       X     X     Xo OO o@      X X X X  ..    ++..XXXXo+XXXXX XXX o ooo......    ",
"   oXXXXXo..  .... ...XXXXX@...XXXXXXXXX.+o  o.oo.     X             #X#     o+X   @o++O+         X X...   o+o.XXXo++XXXXXoo+o o o ....XX    o",
"  ++X XXX... ..... @..XXXXX o.oXXXXXXXX.oo    o.oo..X X       X X         X XXoo  @o+ ...   X X     oX..    o.oXXX.ooXXXXX  oooooXXX..XXXX @oo",
"  ++o++     oo. .. @X.@  XXo.XXoXXXXX....o     o. o. X      X   XX#X  @       oo @++@ .X.    X XX  ..o.o o oXXoXXX....XXo.o   ooXXXX..XXXXXo  ",
" XXXO+o o     o+.XX@++    .@XXXXOOXXXO+o..o     o     XX  X  X  XX##     ..XX OX  X.  .X.    X    Xooooo   XXXXoXX...o..+oooo   XXXX XXXXXX   ",
" XXX  ..   +o o+ XX+++ o  @oXXXXoOOO+++ o      o.          XX X  #X     oo  oXXX .XO @ ..   @..X    o.o   oXXXXXXXX.@XX. ++XXXoXXXXX XXXXXXo O",
" XXX .oo.o..o   + @ O@o@+ oooXXooo+  .... o           #X XXX            ..X   X+++..oOoo.    X.o+       XXXXXX+XXXX.XXXX o+XXXXXX+    XXXX+ @+",
"     .....oo   .oo  ++O o @oo..Xoo   ..o..  o     O   #XXXX  XX  X..    ... XO+X++..@o o@@@  ..oo    XX XXXX..XOXXooXXXXo+ XXXXo+  @.@.XXX.o o",
"   oo ..+O+    ...@ O@+#O   ...ooXXX .o..o   o    #     ..       X .    ... X  oo...o.@oo@ @@o +O    X XX XoXXoXXo o.XX.   oXXX @....@.  .@.  ",
"  o o    o              ##  .o.ooXXX+   o+ooo         .X.o    X         ..o     .. ...@  XXX XXo    X      XXX.oooo o o XX X XX ....@o@@ .o.  ",
"+@++   ooo                   .oO+XXX+ oo o     .o.@#  ..X  X X  X   ...+       o..@... +.XXX XX+       XX  Xoo  Xoo.oo XXXXXXXX  ..o.@.     o ",
" + @+.o o     o        #o   oo oo o  +oo     o o..o+  #o  Xo  o..  ....   oo oo ..oo@. O.XXX   o      X X  ooX  oo.XoXXXXXXXX +O   ..o@ + o oo",
" + o o  ++oo ooo    #    o    o Xo   + o oo+ .o..o.+#+++@ ooXO  ++ ....oO++  .oooo.... +... @  O         X      o ....ooXXXXX +@   ..@. oo   o",
" +@@o   ++  oo o     #        @ +X   O    + o.oo +.  O+o++@++++++  ... ++oOo .o..oo.@. O .@@  @o+O   X          +XXX@oX.o.XXX..XX   o..++     ",
" @   oo@++  oo           #    o O+O+O++ ooooo.o. o o O+@+++ o      +   o +   .ooo.o. @o@@...   oo+o   Xo     XXooXXXXX.@..XXX..XX   o XXX     ",
"    @o o ooo             +     o +X..+o..o+ooXX  @oOO@ +@+        @  ..o  o+++X..o.    XXX.@   O+ oX X       ++oXXXXOoo +......X XXXo XXXo.oo ",
"      @+@ooo     @    ++@o+        ..++..+XXoXX  o Ooo+++O  o@+@     ...o  ..    ooXX@@XXXOO   @O   X+X+       o+o+ooXX..O oO... XXX++XXXooo. ",
"@@   oo++++ooo        ++o@ X      X ++ ..XXXX  ..++oo O oo@ o  ++    .....@oo  o ++XX  XXXXX ooo+X o X++   X  X+oXXOOXX..    .XXXXXXo+XX.o.o.o",
"@o    @+o+oo            +O   X      XXXo XXXX XXX+Oo+@@ o @ o  O@ @ +  @o....+  +++X+++ XXXXX @    +oooo        XXXXoo...XX XXXXXXXX+o..oo  o ",
"     @ oooo        ++    +    XXO@+OXXX  XXXooXXX  oo o  o @@@+XX   O  ..@..o++XXX+   @ XXXXX  ooo o oX  o   o  XXXX+o  XXXXXXXXXXXXo+XXoo+@++",
" @  @ @oo+                      O+++XXX  XXX  XXX X o    oo   XXXX@  + ....o@O+XXX+XX   XXXX+o oooo  o     o oXXXXX.o+XXXXXXXXXX.XXXXXXXX o@@@",
"   @ @@o@O    o. X  X X +@@         XXX+o   oXXOooo  o  XOo   XXXX@@@@.@.....+.XXXXXX       oo   oo oo oX     XXXo+o.oXXXXXXXXXX.XXXXXXXX o oO",
"     X  o      o.        .@          ++     +XXoooooo o XXXX XXXX  XX... @++@+@XXXX..    .@ ++   oo+oo  o Xo  XXXoo  oXXXXXX XXX  XXX.XX.XXo @",
"     ++o@.      X .X.@  X@.  .       +o  XXooXXX XXXXXo XXXX XXXX. XX...@ ++ ...XX...    o....+o  o++o ooo      +oooo+OoXXoo XXX  XXX....XXo  ",
"     O+ @.oo      ..@XX   X...X...    + XXXX XXX XXXXXXXXXXXXXXXX++++@.X@.+ ....  ...    +.....oo   ooo  o     o   ++..o.....XXXX XXX.  o o@  ",
"     ++@@XX++ .    X X    X..oX...+   O XXXX XXX XXXXXXXXXXXXXXXO@+.+O...@+...XX.   .. @++@o.o.O+o oooo oo oo o oo  oo.......XXXX XXX    oo o ",
"XXX +O   XXO ..@. X.X  X  @.X....++  o+o XXX Xo oXXXXXXXXXXXXXXXXXXXXX@...@..XXXX   ..+O++O+..++o+ooo ooo+OOo ooooooooo...oo. XXo XXX.. O  o  ",
"XXX+++ ...   .@@@ ..    .X.XXX.oo     XX XXX +  o+  +XXXXXXXXXX XXXXXX+@@O+@.XXXX   +  ++O++o@+OOo  o oo Oo+ o ooo oo oooo..o o ..XXX.. +     ",
"XXX   .... @@XX@  @...X ++.XXX.o.... XXX XX+Xo  o  o XXXXXXX XXXXXXXXX++@@ ...XX.   O@ ++OOo.@o@+o       + oo oOooo   o  oo.  @ ..XXX..       ",
"   o   o.@o XXX. ..... ++ .XXXXXXXo.  o oO       oo @XXXXXXo+XXXoo++XX++   .@...    + @..o..@..++oo@o o O  oooo  oo o oooo  @@ oo             ",
"  XX    oO.@XXX.  ..@  XXX oXXXXXXXooXXX++   o   o@@XXX XXXXoXXXoo+XXo   @@.@...  .......o..o..       o +oOooo   o Ooo+o++o   o               "};
