/* XPM */
static char *suncurve_small_blue[] = {
/* width height num_colors chars_per_pixel */
"    16    40       12            1",
/* colors */
". c #567c9a",
"# c #678eac",
"a c #5c83a1",
"b c #5f87a4",
"c c #638ba8",
"d c #6890ad",
"e c #6189a6",
"f c #658daa",
"g c #5e86a4",
"h c #5a819f",
"i c #658daa",
"j c #6a92ae",
/* pixels */
"jjjjjjjjagghajjj",
"jjjjjjjjhagghjjj",
"jjjjjjjjhhgbajjj",
"jjjjjjjjhhhcbfjj",
"jjjjjjjjhha#cijj",
"jjjjjjjjhheifejj",
"jjjjjjjjhgiicbjj",
"jjjjjjjegiiieejj",
"jjjjjjf.iiiibcjj",
"jjjjj#.hiiiihcjj",
"jjjjj..hiiii.fjj",
"jjjjg.hhiiibhidj",
"jjjd.hhhiii.cidj",
"jjja.hhhiiahiidj",
"jjd.hhhhie.iii#j",
"jjc.hhhhc.ciii#j",
"jjaahhhh.eiiii#j",
"jdhghhhhbiiiiidj",
"j#hghhhhiiiiiidj",
"j#.ghhhhiiiiiijj",
"j#.bhhhhiiiiifjj",
"ji.bhhhhiiiiidjj",
"ji.chhhhiiiifjjj",
"jihiahhhiiiidjjj",
"jihcbhhhiii#jjjj",
"jiabiahhiifjjjjj",
"jfchibhhiidjjjjj",
"j#i.cighidjjjjjj",
"j#igaiiadjjjjjjj",
"jdii.cicfjjjjjjj",
"jdiibhiigdjjjjjj",
"jjfiiaaigbdjjjjj",
"jjdiii.eggcjjjjj",
"jjjfiic.aggdjjjj",
"jjjdiiie.agijjjj",
"jjjj#iiih.gejjjj",
"jjjjjfiig..gjjjj",
"jjjjjdiigg.adjjj",
"jjjjjjdiggh.fjjj",
"jjjjjjj#ggg.ejjj"
};
