/* XPM */
static char *suncurve_big_blue[] = {
/* width height num_colors chars_per_pixel */
"    32    80       12            1",
/* colors */
". c #567c9a",
"# c #5b82a0",
"a c #5f87a4",
"b c #678eab",
"c c #6990ad",
"d c #628ba7",
"e c #4e7593",
"f c #517997",
"g c #5e86a4",
"h c #5a819f",
"i c #658daa",
"j c #6a92ae",
/* pixels */
"jjjjjjjjjjjjjjjjj#gggggg.#jjjjjj",
"jjjjjjjjjjjjjjjjjh#gggggh.jjjjjj",
"jjjjjjjjjjjjjjjjjhhgggggg.djjjjj",
"jjjjjjjjjjjjjjjjjhhhgggggggjjjjj",
"jjjjjjjjjjjjjjjjjhhh#gggddhjjjjj",
"jjjjjjjjjjjjjjjjjhhhh#ggib.jjjjj",
"jjjjjjjjjjjjjjjjjhhhhhggcjhijjjj",
"jjjjjjjjjjjjjjjjjhhhhh#djj#djjjj",
"jjjjjjjjjjjjjjjjjhhhhhhbjjgajjjj",
"jjjjjjjjjjjjjjjjjhhhhhaicjagjjjj",
"jjjjjjjjjjjjjjjjjhhhh#iibjd#jjjj",
"jjjjjjjjjjjjjjjjjhhh#diiici#jjjj",
"jjjjjjjjjjjjjjjjjhhhdiiiibi#jjjj",
"jjjjjjjjjjjjjjjjjhhaiiiiiii#jjjj",
"jjjjjjjjjjjjjjjjchgiiiiiiid#jjjj",
"jjjjjjjjjjjjjjjc.giiiiiiiighjjjj",
"jjjjjjjjjjjjjjj.fiiiiiiiii#hjjjj",
"jjjjjjjjjjjjjj#fhiiiiiiiiih#jjjj",
"jjjjjjjjjjjjjgfhhiiiiiiiii.gcjjj",
"jjjjjjjjjjjjdf.hhiiiiiiiiifdcjjj",
"jjjjjjjjjjjcf.hhhiiiiiiiia.ibjjj",
"jjjjjjjjjjjhfhhhhiiiiiiiihhiijjj",
"jjjjjjjjjjafhhhhhiiiiiiiifdiijjj",
"jjjjjjjjjbf.hhhhhiiiiiii#.iiicjj",
"jjjjjjjjj#.hhhhhhiiiiiiifgiiicjj",
"jjjjjjjjifhhhhhhhiiiiiih.iiiibjj",
"jjjjjjjjh.hhhhhhhiiiiiafaiiiibjj",
"jjjjjjjbfhhhhhhhhiiiii.hiiiiibjj",
"jjjjjjjg.#hhhhhhhiiiih.iiiiiibjj",
"jjjjjjc.#hhhhhhhhiiigfdiiiiiibjj",
"jjjjjjdfahhhhhhhhiiafaiiiiiiiijj",
"jjjjjcg.ghhhhhhhhidfgiiiiiiiiijj",
"jjjjjbh#ghhhhhhhhdfhiiiiiiiiiijj",
"jjjjji.a#hhhhhhhh.hiiiiiiiiiiijj",
"jjjjcifihhhhhhhhhhiiiiiiiiiiibjj",
"jjjjba.ihhhhhhhhhiiiiiiiiiiiibjj",
"jjjjbahihhhhhhhhhiiiiiiiiiiiibjj",
"jjjjih#ihhhhhhhhhiiiiiiiiiiiicjj",
"jjjcihgihhhhhhhhhiiiiiiiiiiiicjj",
"jjjci.aihhhhhhhhhiiiiiiiiiiiijjj",
"jjjbi.aihhhhhhhhhiiiiiiiiiiibjjj",
"jjjbi.ai#hhhhhhhhiiiiiiiiiiicjjj",
"jjjbi.aighhhhhhhhiiiiiiiiiiijjjj",
"jjjbi.aighhhhhhhhiiiiiiiiiibjjjj",
"jjjii.gidhhhhhhhhiiiiiiiiiijjjjj",
"jjjiih#idhhhhhhhhiiiiiiiiibjjjjj",
"jjjii#hii#hhhhhhhiiiiiiiiijjjjjj",
"jjjiia.iiahhhhhhhiiiiiiiicjjjjjj",
"jjjiiafiidhhhhhhhiiiiiiibjjjjjjj",
"jjjiiifdiighhhhhhiiiiiiijjjjjjjj",
"jjjiii.aiidhhhhhhiiiiiicjjjjjjjj",
"jjjbiihhiiiahhhhhiiiiicjjjjjjjjj",
"jjjbiia.iiii#hhhhiiiibjjjjjjjjjj",
"jjjbiiifdiiidhhhhiiibjjjjjjjjjjj",
"jjjbiiihhiiiiahhhiibjjjjjjjjjjjj",
"jjjciiidfiiiiighhibjjjjjjjjjjjjj",
"jjjciiii.#iiiii#hicjjjjjjjjjjjjj",
"jjjjiiiiafiiiiid#cjjjjjjjjjjjjjj",
"jjjjbiiii.hiiiiidcjjjjjjjjjjjjjj",
"jjjjbiiiidfdiiiiiacjjjjjjjjjjjjj",
"jjjjciiiiih.iiiiigdjjjjjjjjjjjjj",
"jjjjjiiiiii.#iiiiggdjjjjjjjjjjjj",
"jjjjjbiiiiidfaiiigggbjjjjjjjjjjj",
"jjjjjciiiiiigfiiigggacjjjjjjjjjj",
"jjjjjjbiiiiiih.iiggggdjjjjjjjjjj",
"jjjjjjciiiiiii.higggggcjjjjjjjjj",
"jjjjjjjiiiiiiidfggggggdjjjjjjjjj",
"jjjjjjjciiiiiiiafhgggggcjjjjjjjj",
"jjjjjjjjbiiiiiiige#ggggdjjjjjjjj",
"jjjjjjjjciiiiiiii.egggggjjjjjjjj",
"jjjjjjjjjbiiiiiiigffggggbjjjjjjj",
"jjjjjjjjjjiiiiiiigge.gggijjjjjjj",
"jjjjjjjjjjciiiiiigghehggdjjjjjjj",
"jjjjjjjjjjjbiiiiiggg.egggjjjjjjj",
"jjjjjjjjjjjjbiiiiggggf.ggcjjjjjj",
"jjjjjjjjjjjjjiiiigggg#e#gbjjjjjj",
"jjjjjjjjjjjjjciiiggggg.fgbjjjjjj",
"jjjjjjjjjjjjjjciiggggggehbjjjjjj",
"jjjjjjjjjjjjjjjbigggggg.fijjjjjj",
"jjjjjjjjjjjjjjjjbgggggggedjjjjjj"
};
