/* XPM */
static char * Weave_pm[] = {
"16 16 4 1",
"    s bottomShadowColor   m black   c #636363636363",
".   s selectColor   m black   c #737373737373",
"+   s background   m white   c #949494949494",
"@   s topShadowColor   m white   c #bdbdbdbdbdbd",
"             .+.",
"     ...     .+.",
"     .+.     .+.",
"     .+.     ...",
"     .+.        ",
".... .@. .......",
"+++. .@. .+++@@@",
".... .@. .......",
"     .+.        ",
"     .+.     ...",
"     .+.     .+.",
"     ...     .+.",
"             .+.",
" ........... .@.",
" .+++@@@+++. .@.",
" ........... .@."};
