/* XPM */
/* $XConsortium: DtABtmp.pm /main/3 1995/07/18 16:16:04 drk $ */
static char * DtABtmp_x_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 32 10 1 0 0",
/* colors */
"     s iconGray3     m white c #adadadadadad",
".	s iconColor1	m black	c black",
"X    s iconGray2     m white c #bdbdbdbdbdbd",
"o	s iconColor2	m white	c white",
"O    s iconGray2     m white c #bdbdbdbdbdbd",
"+    s iconGray5     m black c #737373737373",
"@    s iconGray1     m white c #dededededede",
"#    s iconGray4     m white c #949494949494",
"$    s iconGray4     m white c #949494949494",
"%    s iconGray3     m white c #adadadadadad",
/* pixels */
"                                                ",
"              ....................              ",
"             .XXXXXXXXXXXXXXXXXXXX.             ",
"            .oooooooooooooooooooooo.            ",
"            .oOOOOOOOOOOOOOOOOOOOOO.            ",
"            .oO+++++++++++++++++++O.            ",
"            .oO+.................oO.            ",
"            .oO+.................oO.            ",
"            .oO+..@@@@@@@@.......oO.            ",
"            .oO+.................oO.            ",
"            .oO+.................oO.            ",
"            .oO+..@@@@@..........oO.            ",
"            .oO+.................oO.            ",
"            .oO+.................oO.            ",
"            .oO+..@@@@@@@@@@@@...oO.            ",
"            .oO+.................oO.            ",
"            .oO+.................oO.            ",
"            .oO+ooooooooooooooooooO.            ",
"            .oOOOOOOOOOOOOOOOOOOOOO.            ",
"             ......................             ",
"                .++++++++++++++.                ",
"                 ..##########..                 ",
"         ..............................         ",
"         .$$$$$$$$$$$$$$$$$$$$$$$$$$$$.         ",
"         .XXX$XX$XX$XX$X$XXX$X$X$XXXXX.         ",
"        .XXX$XX$XX$XX$XX$XXX$XX$X$XXXXX.        ",
"        .XX$XX$XXXXXXXXXXXXX$X$X$X$XXXX.        ",
"       .%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%.       ",
"       .%$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$%.       ",
"       ..................................       ",
"        ................................        ",
"                                                "};
