/* XPM */
/* $XConsortium: Dtainfo.l.pm /main/3 1995/07/18 16:27:53 drk $ */
static char * Dtainfo_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 12 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X	s iconColor1	m black	c black",
"o	s iconGray5	m black	c #737373737373",
"O	s iconColor5	m black	c blue",
"+	s iconGray3	m white	c #adadadadadad",
"@	s iconGray4	m white	c #949494949494",
"#	s iconGray6	m black	c #636363636363",
"$	s iconGray1	m white	c #dededededede",
"%	s iconGray2	m white	c #bdbdbdbdbdbd",
"&	s iconGray7	m black	c #424242424242",
"*	s iconGray8	m black	c #212121212121",
/* pixels */
"  ...........................................XX ",
"  .ooOooOooOooOooOooOooOooOooOooOooOooOooOooOXX ",
"  .OOoOOoOOoOOoOOoOOoOOoOOoOOoOOoOOoOOoOOoOOoXX ",
"  .OOoOOoOOoOOoOOoOOoOOoOOoOOoOOoOOoOOoOOoOOoXX ",
"  .ooOooOooOooOooOooOooOooOooOooOooOooOooOooOoX ",
".........OOoOOoOOoOOOOOoOOoOOoOOoOOoOOo........X",
".+@@@@@@@.OoOOoOOoOOoOOoOOoOOoOOoOOoOO.@@@@@@@#X",
".+@@@@@@@@.OooOooOooOooOooOooOooOooOo.@@@@@@@@#X",
".+@@@@@@@@@.OOoOOoOOoOOoOOoOOoOOoOOo.@@@@@@@@@#X",
".+@@@@@@@@@@........................@@@@@@@@@@#X",
".+@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#X",
".+@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#X",
".+@@@@@@@@@@@@@@@@@@$$$....$##o@@@@@@@@@@@@@@@#X",
".+@@@@@@@@@@@@@@@@$%$O+O+O+O+O+##@@@@@@@@@@@@@#X",
".+@@@@@@@@@@@@@@@.%%O+OOOOO+O+O+##@@@@@@@@@@@@#X",
".+@@@@@@@@@@@@...O+O+OO...OO+O+O+###@@@@@@@@@@#X",
".+@@@@@@@@@@@@.+O+O+OO.....OO+O+O+&#@@@@@@@@@@#X",
".+@@@@@@@@@@..+O+O+OO.......OO+O+O+##@@@@@@@@@#X",
".+@@@@@@@@@..+O+O+O+O.......OOO+O+O+##@@@@@@@@#X",
".+@@@@@@@@@.+O+O+O+OO.......OO+O+O+O+#o@@@@@@@#X",
".+@@@@@@@$$.O+O+O+O+O.......OOO+O+O+O+&o@@@@@@#X",
".+@@@@@@@..O+O+O+O+O+O.....OOO+O+O+O+O@&@@@@@@#X",
".+@@@@@@@.O+O+O+O+O+O+O...OOO+O+O+O+O+O&@@@@@@#X",
".+@@@@@@$.+O+O+O+O+OOOOOOOOO+O+O+O+O+O+&o@@@@@#X",
".+@@@@@@.$O+O+O+O+O+O.....OOO+O+O+O+O+Ooo@@@@@#X",
".+@@@@@@.O+O+O+O+O+OO.....OOOO+O+O+O+O%Oo@@@@@#X",
".+@@@@@@.+O+O+O+OOOO.......OO+O+O+O+O+Oo&@@@@@#X",
".+@@@@@@.O+O+O+O+O.........OOO+O+O+O+O%O&@@@@@#X",
".+@@@@@@.+O+O+O+OO.........OO+O+O+O+O+Oo&@@@@@#X",
".+@@@@@@.O+O+O+O+OOOO......OOO+O+O+O+O+O&@@@@@#X",
".+@@@@@@.+O+O+O+O+O+O......OO+O+O+O+O+Oo&@@@@@#X",
".+@@@@@@.O+O+O+O+O+OO......OOO+O+O+O+O%O&@@@@@#X",
".+@@@@@@.+O+O+O+O+O+O......OO+O+O+O+O+Oo&@@@@@#X",
".+@@@@@@$$+O+O+O+O+OO......OOO+O+O+O+O@O&@@@@@#X",
".+@@@@@@o$O+O+O+O+O+O......OOOOOO+O+O+O*#@@@@@#X",
".+@@@@@@@$+O+O+O+O+OO.........OOOO+O+Oo&@@@@@@#X",
".+@@@@@@@o$+O+O+O+O+O........OOOO+O+O+&&@@@@@@#X",
".+@@@@@@@@$$+O+O+O+OO........OOO+O+O+&#@@@@@@@#X",
".+@@@@@@@@o$O+O+O+O+OOO....OOOO+O+O+O&#@@@@@@@#X",
".+@@@@@@@@@@$O+O+O+O+OOOOOOOOO+O+O+&&#@@@@@@@@#X",
".+@@@@@@@@@o@$O+O+O+O+O+O+O+O+O+O+O&#@@@@@@@@@#X",
".+@@@@@@@@@@o$%O+O+O+O+O+O+O+O+O+&##@@@@@@@@@@#X",
".+@@@@@@@@@@@@++O+O+O+O+O+O+O+O+&##@@@@@@@@@@@#X",
".+@@@@@@@@@@@@@++O+O+O+O+O+O+&###@@@@@@@@@@@@@#X",
".+@@@@@@@@@@@@@@@@++&&&&&&&&&&#@@@@@@@@@@@@@@@#X",
".+@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#X",
".+#############################################X",
".+XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"};
