/* XPM */
/* $XConsortium: Dtasys.l.pm /main/3 1995/07/18 16:29:14 drk $ */
static char * Dtasys_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 13 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X	s iconColor1	m black	c black",
"o	s iconGray5	m black	c #737373737373",
"O	s iconColor5	m black	c blue",
"+	s iconGray3	m white	c #adadadadadad",
"@	s iconGray4	m white	c #949494949494",
"#	s iconGray6	m black	c #636363636363",
"$	s iconGray1	m white	c #dededededede",
"%	s iconGray7	m black	c #424242424242",
"&	s iconColor7	m white	c cyan",
"*	s iconGray8	m black	c #212121212121",
"=	s iconGray2	m white	c #bdbdbdbdbdbd",
/* pixels */
"  ...........................................XX ",
"  .ooOooOooOooOooOooOooOooOooOooOooOooOooOooOXX ",
"  .OOoOOoOOoOOoOOoOOoOOoOOoOOoOOoOOoOOoOOoOOoXX ",
"  .OOoOOoOOoOOoOOoOOoOOoOOoOOoOOoOOoOOoOOoOOoXX ",
"  .ooOooOooOooOooOooOooOooOooOooOooOooOooOooOXX ",
".........OOoOOoOOoOOoOOoOOoOOoOOoOOoOOo........X",
".+@@@@@@@.OoOOoOOoOOoOOoOOoOOoOOoOOoOo.@@@@@@@#X",
".+@@@@@@@@.OooOooOooOooOooOooOooOooOo.@@@@@@@@#X",
".+@@@@@@@@@.OOoOOoOOoOOoOOoOOoOOoOOo.@@@@@@@@@#X",
".+@@@@@@@@@@........................@@@@@@@@@@#X",
".+@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#X",
".+@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#X",
".+@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#X",
".+@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#X",
".+@@@@@@@@@@........................$$@@@@@@@@#X",
".+@@@@@@@@@.@@@@@@@@@@@@@@@@@@@@@@@@o#%@@@@@@@#X",
".+@@@@@@@@@.@+++++++++++++++++++++++@#%@@@@@@@#X",
".+@@@@@@@@@.@+%%%%%%%%%%%%%%%%%%%%%+@#%@@@@@@@#X",
".+@@@@@@@@@.@+%O&O&O&O&O&O&O&O&O&.@+@#%@@@@@@@#X",
".+@@@@@@@@@.@+%&O&O&O&O&O&O&O&O&O.@+@#%@@@@@@@#X",
".+@@@@@@@@@.@+%O&...&O&O&O&O&O&O&.@+@#%@@@@@@@#X",
".+@@@@@@@@@.@+%&O..&O&O&O&O&O&O&O.@+@#%@@@@@@@#X",
".+@@@@@@@@@.@+%O&.&O&O&O&O&O&O&O&.@+@#%@@@@@@@#X",
".+@@@@@@@@@.@+%&O&O&O&O&O&O&O&O&O.@+@#%@@@@@@@#X",
".+@@@@@@@@@.@+%O&O&O&O&O&O&O&O&O&.@+@#%@@@@@@@#X",
".+@@@@@@@@@.@+%&O&O&O&O&O&O&O&O&O.@+@#%@@@@@@@#X",
".+@@@@@@@@@.@+%O&O&O&O&O&O&O&O.O&.@+@#%@@@@@@@#X",
".+@@@@@@@@@.@+%&O&O&O&O&O&O&O..&O.@+@#%@@@@@@@#X",
".+@@@@@@@@@.@+%O&O&O&O&O&O&O&O&O&.@+@#%@@@@@@@#X",
".+@@@@@@@@@.@+%&O&O&O&O&O&O&O&O&O.@+@#%@@@@@@@#X",
".+@@@@@@@@@.@+#...................@+@#%@@@@@@@#X",
".+@@@@@@@@@.@+#@@@@@@@@@@@@@@@@@@@@+@#%@@@@@@@#X",
".+@@@@@@@@@.@+++++++++++++++++++++++@#%@@@@@@@#X",
".+@@@@@@@@@@XXXXXXXXXXXXXXXXXXXXXXXX%%@@@@@@@@#X",
".+@@@@@@@@@@XXXXXXXXXXXXXXXXXXXXXXXX%%@@@@@@@@#X",
".+@@@@@@@@@@@@**@@@@@@@@@@@@@@@@+*%@@@@@@@@@@@#X",
".+@@@@@@@@@@@@@XXooooooooooooooo*%@@@@@@@@@@@@#X",
".+@@@@@@@@@@@@@@XX#############%*@@@@@@@@@@@@@#X",
".+@@@@@@.%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%**o@@@@#X",
".+@@@@@.$*@%..%..*..*..*..*..*..*..*..@*$Xo@@@#X",
".+@@@@..*@.%.*%.**.**.***.**.**.**.**.%.*$%o@@#X",
".+@@@=.#%%%.%%.%%.%%.%%.%%.%%.%%.%%.%%.%.*$Xo@#X",
".+@@@$$###################################$=%@#X",
".+@@@$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$=%@#X",
".+@@@XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX%@#X",
".+@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#X",
".+#############################################X",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"};
