/* XPM */
/*********************************************************************
*  (c) Copyright 1999 Sun Microsystems, Inc.
**********************************************************************/
static char * dtaudio_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 10 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray6	m black	c #636363636363",
"X	s iconColor2	m white	c white",
"o	s iconGray3	m white	c #adadadadadad",
"O	s iconGray2	m white	c #bdbdbdbdbdbd",
"+	s iconGray5	m black	c #737373737373",
"@	s iconGray7	m black	c #424242424242",
"#	s iconGray1	m white	c #dededededede",
"$	s iconGray4	m white	c #949494949494",
"%	s iconGray8	m black	c #212121212121",
/* pixels */
"                                                ",
"                                                ",
"                                                ",
"                    .....                       ",
"                    .XXXX.                      ",
"                    .XooOO.                     ",
"                    .X+@XOO.                    ",
"                    .X+@#XOO.                   ",
"                    .X+@X#XOO.                  ",
"                    .#+@#X#XOO.                 ",
"                    .#+@X#X#XOO.                ",
"            o.      .#+@#X###XOO.               ",
"           @.       .#+@######XOO.........      ",
"          @.        .#+@OO#####XOOOOOOOOO.O     ",
"         @.         .#.@oOOO####XXXXXXX##.O     ",
"        @.          .o.@#ooOOO###########.O     ",
"       o@o      @   .o.@###ooOOO#########.O     ",
"      #@.      @    .o.@o$###oooooOoOoOoO.O     ",
"      o@o     @o    .o.@$$o$#############.O     ",
"      +@     o@    .#o.@o$$$ooooooo#o#o#o@O     ",
"     #@.     @.    ..o.@$$o$$$o$o$o$oo$oo@O     ",
"     o@+    #@.    .#o.@o$$$o$$$$$$$$$$$$@O     ",
"     o@+    o@+    ..o.@$$$$$$$$$$$$$$$$$%O     ",
"     o@+    o@+    .#o.@$$$$$$$$$$$$$$$$$@O     ",
"     o@+    o@+    ..o.@$$$$$$$$$$$$+$$$+%O     ",
"     o@+    o@+    .#o.@$$$+$$$$$$$$$$+$$%O     ",
"     o@+    #@.    ..o.@$$+$$+$$$+$+$+$+$%O     ",
"     #@.     @.    .#o.@+$$+$$+$+$+++++++%O     ",
"      +@     o@    ..o.@$+++++++.+.+.....%O     ",
"      o@o     @o    .o.@++.....@.@.@.@.@.%O     ",
"      #@.      @    @o.@....@@@@@@@@@@@@@%O     ",
"       o@o      @   .o@@..@@@@@@@@@@@@@@@%O     ",
"        @.          @o@@@@@@@@@@@@@@@@@@@%O     ",
"         @.         @o@%@@@@@@@@@@@@@@@@%%O     ",
"          @.        @o@@@@@@@@@@@%%%%%%%%OO     ",
"           @.       .o@%@@@@@@@@%OOOOOOOOO      ",
"            o.      @o@%@@@@@@@%O               ",
"                    @o%%@@@@@@%O                ",
"                    %o@%@@@@@%O                 ",
"                    @o%%@@@@%O                  ",
"                    %o%%@@@%O                   ",
"                    %o%%@@%O                    ",
"                    %o%%@%O                     ",
"                    %%%%%O                      ",
"                    OOOOO                       ",
"                                                ",
"                                                ",
"                                                "};
