/* XPM */
/* $XConsortium: Dtcore.m.pm /main/3 1995/07/18 17:10:19 drk $ */
static char * Dtcore_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 12 1 0 0",
/* colors */
" 	s iconColor2	m white	c white",
".    s iconGray2     m white c #bdbdbdbdbdbd",
"X	s none	m none	c none",
"o	s iconColor1	m black	c black",
"O	s iconColor3	m black	c red",
"+    s iconGray6     m black c #636363636363",
"@    s iconGray3     m white c #adadadadadad",
"#    s iconGray1     m white c #dededededede",
"$    s iconGray7     m black c #424242424242",
"%    s bottomShadowColor m black c #636363636363",
"&    s iconGray4     m white c #949494949494",
"*    s iconGray8     m black c #212121212121",
/* pixels */
"                   .     XXXXXXX",
" .......................oXXXXXXX",
" .......... .......O ...oXXXXXXX",
" ..........+......O@  ..oXXXXXXX",
" .......... .....O@ OO#.oXXXXXXX",
" .. ....... ....O@ OOOO#oXXXXXXX",
" ..+.......+...O@ OOOO+++XXXXXXX",
" .... ..... ..o  OOOO+O$+XXXXXXX",
" ....+..... ..... OO+O$ooXXXXXXX",
" ..... ....+.....oO+O$o.oXXXXXXX",
" .....+..........  O$o..oXXXXXXX",
" .........  ......%oo...oXXXXXXX",
" .........   ...........oXXXXXXX",
" ........  + ++ . ......oXXXXXXX",
" .  .  ..    +  .  .....oXXXXXXX",
" .++.++..+ +      ......oXXXXXXX",
" .........+ +   + +.....oXXXXXXX",
" ..........      &+.....oXXXXXXX",
" ......  ... + +  +.....oXXXXXXX",
" .....OOo....+   +......oXXXXXXX",
" ....O@ o.....+++...  . oXXXXXXX",
" ...O@ Oo   ........++.+oXXXXXXX",
" ..O@ OOO+O%...... .....oXXXXXXX",
" .O@ OOO+O$o.. ... .....oXXXXXXX",
" o@ OOO+O$o... ...+ ....oXXXXXXX",
"*o OOO+O$o....+.... ....oXXXXXXX",
" ooOO+O$o..... ....+....oXXXXXXX",
" .oo+O$o...... ..... ...oXXXXXXX",
" ..oooo.......+.....+...oXXXXXXX",
" ...+o........ .........oXXXXXXX",
" .............+.........oXXXXXXX",
" ooooooooooooooooooooooooXXXXXXX"};
