/* XPM */
/* $XConsortium: Dtdgclk.m.pm /main/3 1995/07/18 16:34:08 drk $ */
static char * Dtdgclk_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 5 1 0 0",
/* colors */
"     s iconGray1     m white c #dededededede",
".    s iconGray3     m white c #adadadadadad",
"X	s iconColor1	m black	c black",
"o    s iconGray7     m black c #424242424242",
"O	s iconColor6	m white	c yellow",
/* pixels */
"                                ",
" ..............................X",
" ..............................X",
" ..............................X",
" ..............................X",
" ..............................X",
" ..............................X",
" ..............................X",
" ....XXXXXXXXXXXXXXXXXXXXXX....X",
" ...XXooooooooooooooooooooXX...X",
" ..XXooooooooooooooooooooooXX..X",
" .XXooooooooooooooooooooooooXX.X",
" .Xoooooooooooooooooooooooooo .X",
" .Xoooooooooooooooooooooooooo .X",
" .XoOoOOoooOOOoOOoooooOoooOoo .X",
" .XoOooOoOoOoOooOoOooOOooOOoo .X",
" .XoOoOooooOoOoOooooOOOoOOOoo .X",
" .XoOoOOoOoOOOoOOoOoooOoooOoo .X",
" .Xoooooooooooooooooooooooooo .X",
" .Xoooooooooooooooooooooooooo .X",
" .XXoooooooooooooooooooooooo  .X",
" ..XXoooooooooooooooooooooo  ..X",
" ...XXoooooooooooooooooooo  ...X",
" ....X                     ....X",
" ..............................X",
" ..............................X",
" ..............................X",
" ..............................X",
" ..............................X",
" ..............................X",
" ..............................X",
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"};
