/* XPM */
/* $XConsortium: Dtdirnw.m.pm /main/3 1995/07/18 16:35:45 drk $ */
static char * Dtdirnw_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 11 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X	s iconColor5	m black	c blue",
"o	s iconGray8	m black	c #212121212121",
"O	s iconGray5	m black	c #737373737373",
"+	s iconGray2	m white	c #bdbdbdbdbdbd",
"@	s iconGray6	m black	c #636363636363",
"#	s iconGray7	m black	c #424242424242",
"$	s iconGray4	m white	c #949494949494",
"%	s iconColor6	m white	c yellow",
"&	s iconColor8	m black	c magenta",
/* pixels */
"                                ",
"                                ",
"                                ",
"                  ...........   ",
"                 ..XXXXXXXXXoo  ",
"  ................XXXXXXXXXXXoo ",
"  .OOOOOOOOOOOOOOOOOOOOOOOOOOOOo",
".............................oOo",
".+++++++++++++++++++++++++++OoOo",
".+++++++++++++++++++++++++++OoOo",
".+++++++++++++++++++++++++++OoOo",
".+++++++++++++++++++++++++++OoOo",
".+++++++++++++o@++++++++++++OoOo",
".+++++++++++++@oo#++++++##++OoOo",
".++++++++++++++o..o++++###++OoOo",
".++++++++++++++#.o$#++###+++OoOo",
".+++++++++++++++oO%%####++++OoOo",
".++++++++++++++++oO%###+++++OoOo",
".+++++++++++++++++@####+++++OoOo",
".+++++++++++++++++###%%#++++OoOo",
".++++++++++++++++###OO%%#+++OoOo",
".+++++++++++++++###++oO%@#++OoOo",
".++++++++++++++###++++oO&&#+OoOo",
".++++++++++++++##++++++o@&@+OoOo",
".+++++++++++++++++++++++o@++OoOo",
".+++++++++++++++++++++++++++OoOo",
".OOOOOOOOOOOOOOOOOOOOOOOOOOOOooo",
" oooooooooooooooooooooooooooooo ",
"                                ",
"                                ",
"                                ",
"                                "};
