/* XPM */
/* $XConsortium: Dtdirlk.m.pm /main/3 1995/07/18 16:35:19 drk $ */
static char * Dtdirlk_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 7 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X	s iconColor5	m black	c blue",
"o    s iconGray8     m black c #212121212121",
"O    s iconGray5     m black c #737373737373",
"+    s iconGray2     m white c #bdbdbdbdbdbd",
"@    s iconGray7     m black c #424242424242",
/* pixels */
"                                ",
"                                ",
"                                ",
"                  ...........   ",
"                 ..XXXXXXXXXoo  ",
"  ................XXXXXXXXXXXoo ",
"  .OOOOOOOOOOOOOOOOOOOOOOOOOOOOo",
".............................oOo",
".+++++++++++++++++++++++++++OoOo",
".+++++++++++++++++++++++++++OoOo",
".+++++++++++++++++++++++++++OoOo",
".+++++++++++++++++++++++++++OoOo",
".+++++++++++++++++++++++++++OoOo",
".++++++++++++++++++++@@@@+++OoOo",
".+++++++++++++++++++@@++@@++OoOo",
".+++++++++++++++++++@@++@@++OoOo",
".+++++++++++++++++++@@++@@++OoOo",
".+++++++++++++++++++@@++@@++OoOo",
".++++++++++++++++++@@@@@@@@+OoOo",
".++++++++++++++++++@@@@@@@@+OoOo",
".++++++++++++++++++@@@@@@@@+OoOo",
".++++++++++++++++++@@@@@@@@+OoOo",
".++++++++++++++++++@@@@@@@@+OoOo",
".++++++++++++++++++@@@@@@@@+OoOo",
".+++++++++++++++++++++++++++OoOo",
".+++++++++++++++++++++++++++OoOo",
".OOOOOOOOOOOOOOOOOOOOOOOOOOOOooo",
" oooooooooooooooooooooooooooooo ",
"                                ",
"                                ",
"                                ",
"                                "};
