/* XPM */
/*********************************************************************
*  (c) Copyright 1999 Sun Microsystems, Inc.
**********************************************************************/
static char * Font_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 4 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X	s iconGray8	m black	c #212121212121",
"o	s iconGray5	m black	c #737373737373",
/* pixels */
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"   ..........................                   ",
"   ...XXXXXXX......XXXXXXX...X                  ",
"   ..XXXXXXXXX....XXXXXXXXX..XX                 ",
"   .XXXoooooXX....XXXooooXXX.XXo                ",
"   .XXoo     X....XXoo    XX.XXo                ",
"   .Xoo       ....XXo      X.XXo                ",
"   .Xo        ....XXo       XXXo                ",
"     o        ....XXo        XXo                ",
"              ....XXo    .................X     ",
"              ....XXo    ..XXXX.....XXXX..XX    ",
"              ....XXo    .XXXXXX...XXXXXX.XX    ",
"              ....XXo    .XXoooX...XXXooX.XXo   ",
"              ....XXo    .Xoo   ...XXoo  XXXo   ",
"              ....XXo      o    ...XXo    XXo   ",
"              ....XXo           ...XXo          ",
"              ....XXo           ...XXo          ",
"              ....XXo           ...XXo          ",
"              ....XXo           ...XXo          ",
"              ....XXo           ...XXo          ",
"              ....XXo           ...XXo          ",
"              ....XXo           ...XXo          ",
"              ....XXo           ...XXo          ",
"              ....XXo           ...XXo          ",
"              ....XXo           ...XXo          ",
"              ....XXo           ...XXo          ",
"             ......Xo           ...XXo          ",
"            ........o          .....Xo          ",
"          ............X      .........X         ",
"           XXXXXXXXXXXXX      XXXXXXXXXX        ",
"            XXXXXXXXXXXXX      XXXXXXXXXX       "};
