/* XPM */
/* $XConsortium: Dthistprev.m.pm /main/2 1996/07/23 12:12:06 drk $ */
static char * Dthistprev1_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 8 1 0 0",
/* colors */
" 	s background	m black	c #949494949494",
".	s iconGray8	m black	c #212121212121",
"X	s iconGray6	m black	c #636363636363",
"o	s iconGray2	m white	c #bdbdbdbdbdbd",
"O	s iconGray5	m black	c #737373737373",
"+	s iconColor2	m white	c white",
"@	s iconGray1	m white	c #dededededede",
"#	s iconGray4	m white	c #949494949494",
/* pixels */
"                                ",
"                                ",
"                ..              ",
"               .XXX             ",
"              .XXXo             ",
"             .XXXO+             ",
"            .XXXX+              ",
"           .@.XO+               ",
"          .X.@++                ",
"          +XX+                  ",
"           ++                   ",
"                 ..             ",
"       ...      .XXX            ",
"      .XXX+    .XXXo            ",
"     .XXXX+   .XXXO+       +.   ",
"    ..XXX+   .XXXX+       +#.   ",
"    .XXX+   .@.XO+       +##.   ",
"   .@.X+   .X.@++       +###.   ",
"  .X.@+    +XX+        +####.   ",
"  .XX+      ++        +#####.   ",
"   ++   ..           +######.   ",
"       .XXX         +#######.   ",
"      .XXXo        +########.   ",
"     .XXXO+         .#######.   ",
"    .XXXX+           .######.   ",
"   .@.XO+             .#####.   ",
"  .X.@++               .####.   ",
"  +XX+                  .###.   ",
"   ++                    .##.   ",
"                          .#.   ",
"                           ..   ",
"                                "};
