/* XPM */
/* $XConsortium: Dthist.l.pm /main/2 1996/10/29 15:52:15 drk $ */
static char * Dthist_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 6 1 0 0",
/* colors */
" 	s background	m black	c #949494949494",
".	s iconGray8	m black	c #212121212121",
"X	s iconGray6	m black	c #636363636363",
"o	s iconGray1	m white	c #dededededede",
"O	s iconColor2	m white	c white",
"+	s iconGray4	m white	c #949494949494",
/* pixels */
"                                                ",
"                     ...                        ",
"                    .XXX.                       ",
"                   .XXXXXo                      ",
"                  .XXXXXXO                      ",
"                 .XXXXXXXO                      ",
"                .XXXXXXXO                       ",
"                .XXXXXXO                        ",
"                .XXXXXO                         ",
"              ..oXXXXO                          ",
"             .XX.ooOO                           ",
"             .XXX.O                             ",
"             .XXXXO                             ",
"              .XXO                              ",
"               OO                               ",
"                        ...                     ",
"         ...           .XXX.                    ",
"        .XXX.         .XXXXXo                   ",
"       .XXXXXo       .XXXXXXO                   ",
"      .XXXXXXO      .XXXXXXXO                   ",
"     .XXXXXXXO     .XXXXXXXO                    ",
"    .XXXXXXXO      .XXXXXXO                     ",
"    .XXXXXXO       .XXXXXO                      ",
"    .XXXXXO      ..oXXXXO                       ",
"  ..oXXXXO      .XX.ooOO                        ",
" .XX.ooOO       .XXX.O                          ",
" .XXX.O         .XXXXO                          ",
" .XXXXO          .XXO         OO   OO           ",
"  .XXO            OO         O+.   .+O          ",
"   OO                       O++.   .++O         ",
"          ...              O+++.   .+++O        ",
"         .XXX.            O++++.   .++++O       ",
"        .XXXXXo          O+++++.   .+++++O      ",
"       .XXXXXXO         O++++++.   .++++++O     ",
"      .XXXXXXXO        O+++++++.   .+++++++O    ",
"     .XXXXXXXO        O++++++++.   .++++++++O   ",
"     .XXXXXXO        O+++++++++.   .+++++++++O  ",
"     .XXXXXO         O+++++++++.   .+++++++++O  ",
"   ..oXXXXO           .++++++++.   .++++++++.   ",
"  .XX.ooOO             .+++++++.   .+++++++.    ",
"  .XXX.O                .++++++.   .++++++.     ",
"  .XXXXO                 .+++++.   .+++++.      ",
"   .XXO                   .++++.   .++++.       ",
"    OO                     .+++.   .+++.        ",
"                            .++.   .++.         ",
"                             .+.   .+.          ",
"                              ..   ..           ",
"                                                "};
