/* XPM */
/* $XConsortium: Dtinfoadd.m.pm /main/2 1996/07/23 12:14:58 drk $ */
static char * Dtinfoadd1_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 15 1 0 0",
/* colors */
" 	s background	m black	c #949494949494",
".	s iconGray1	m white	c #dededededede",
"X	s bottomShadowColor	m black	c #636363636363",
"o	s iconGray7	m black	c #424242424242",
"O	s iconGray8	m black	c #212121212121",
"+	s iconGray5	m black	c #737373737373",
"@	s iconGray4	m white	c #949494949494",
"#	s iconGray6	m black	c #636363636363",
"$	s iconColor8	m black	c magenta",
"%	s iconColor3	m black	c red",
"&	s iconGray2	m white	c #bdbdbdbdbdbd",
"*	s iconGray3	m white	c #adadadadadad",
"=	s iconColor5	m black	c blue",
"-	s iconColor2	m white	c white",
";	s iconColor1	m black	c black",
/* pixels */
"                                ",
"                                ",
"                                ",
"        ....X .....o   ....O    ",
"        .+@#O@+++++o...+@@#O    ",
"   ....O$@+%O@+#o+O+o#O+@+oO    ",
"   .&*+O@+@#O@+++oOo+=O@#++O    ",
"   .&&+O$@+%O@+#++O+o#O+@+oO    ",
"   .&*+O@+@#O@+++oOo+=O@#++O    ",
"   .&@+O@++%O@-----+o#O@#++O    ",
"   .&*+O@+@#O@-&&&;o+=O@@++O    ",
"   .&@+O$@+%#@-&&&;+o#O@o++O    ",
"   .&*+O@+@#O@-&&&;=+=O@@@+O    ",
"   .&*+O$@+%o@-&&&;oo#O@o++O    ",
"   .&@+O@------&&&------+++O    ",
"   .&*+O$-&&&&&&&&&&&&&;#++O    ",
"   .&@+O@-&&&&&&&&&&&&&;@++O    ",
"   .&@+O$-&&&&&&&&&&&&&;#++O    ",
"   .&@+O@;;;;;-&&&;;;;;;+++O    ",
"   .&*+O$@+%O@-&&&;oo#O+@@+O    ",
"   .&*+O@+@#O@-&&&;X+=O+@++O    ",
"   .&*+O$@+%O@-&&&;Xo#O+@++O    ",
"   .&*+O@+@#O@-&&&;=+=O+o++O    ",
"   .&*+O$@+%O@;;;;;oo#O+@++O    ",
"   .&*+O@+@#O@+++#O=+=O+@++O    ",
"   .&*+O$@+%O@+++#Ooo#O+@++O    ",
"   .&*+O@+@#O@+++#O=+=O+@++O    ",
"   .&*+O$@+%O@+++#Ooo#O+@++O    ",
"   ;;OOOOOOOOOOOOOOOOOOOOOOO    ",
"                                ",
"                                ",
"                                "};
