/* XPM */
/* $XConsortium: Dtinfo.l.pm /main/3 1996/07/23 12:13:53 drk $ */
static char * Dtinfo_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 10 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X	s iconColor5	m black	c blue",
"o	s iconGray6	m black	c #636363636363",
"O	s iconGray7	m black	c #424242424242",
"+	s iconGray1	m white	c #dededededede",
"@	s iconGray4	m white	c #949494949494",
"#	s iconGray5	m black	c #737373737373",
"$	s iconGray8	m black	c #212121212121",
"%	s iconGray2	m white	c #bdbdbdbdbdbd",
/* pixels */
"                                                ",
"                                                ",
"                    .......                     ",
"                 ...XXoXoXo...                  ",
"               ..XXoXoXoXoXoXo..                ",
"              .XoXoXoX...XoXoXoX.               ",
"             .XoXoXoX.....XoXoXoXO              ",
"            .XoXoXoXo.....oXoXoXoXO             ",
"            .oXoXoXoX.....XoXoXoXoO             ",
"   .......+.XXoXoXoXoX...XoXoXoXoXoO@......#    ",
"  ..++++++@.XoXoXoXoXoX#XoXoXoXoXoXO@++++++OO   ",
" ...++++++@.oXoXoXoXoX#XoXoXoXoXoXoO@++++++O#$  ",
"%++.+++++@.oXoXoXoXoXX...oXoXoXoXoXoO@+++++O#$$ ",
"%+..++oo+@.XoXoXoXoX......oXoXoXoXoXO@+oo++O#O$ ",
"%++.+++++@.oXoXoXoX.......XoXoXoXoXoO@+++++O#O$ ",
"%+..+++++@.XoXoXoXoXo.....oXoXoXoXoXO@+++++O#O$ ",
"%++.++oo+@.oXoXoXoXoX.....XoXoXoXoXoO@+oo++O#O$ ",
"%+..+++++@.XoXoXoXoXo.....oXoXoXoXoXO@+++++O#O$ ",
"%++.+++++@.oXoXoXoXoX.....XoXoXoXoXoO@+++++O#O$ ",
"%+..++ooo+@.oXoXoXoXo.....oXoXoXoXoO@+ooo++O#O$ ",
"%++.++++++@.XoXoXoXoX.....XoXoXoXoXO@++++++O#O$ ",
"%+..++++++@.oXoXoXoXo.....oXoXoXoXoO@++++++O#O$ ",
"%++.++ooo++@.oXoXoXoX.......XoXoXoO@+oooo++O#O$ ",
"%+..+++++++@.XoXoXoXo......XoXoXoXO@+++++++O#O$ ",
"%++.++++++++@.XoXoXoXo...oXoXoXoXO@++++++++O#O$ ",
"%+..++ooo+oo+@OXoXoXoXoXoXoXoXoXO@+oooooo++O#O$ ",
"%++.++++++++++@OOoXoXoXoXoXoXoOO@++++++++++O#O$ ",
"%+..+++++++++++@@OOOoXoXoXoOOO@@+++++++++++O#O$ ",
"%++.++ooo+ooooo++@@@OOOOOOO@@@+++oooooooo++O#O$ ",
"%+..++++++++++++++++@@@@@@@++++++++++++++++O#O$ ",
"%++.++++++++++++++++++%@%++++++++++++++++++O#O$ ",
"%+..++ooo+oooooooo++++%@%++++ooo++ooooooo++O#O$ ",
"%++.++++++++++++++++++%@%++++++++++++++++++O#O$ ",
"%+..++++++++++++++++++%@%++++++++++++++++++O#O$ ",
"%++.++ooo+oooooooo++++%@%++++ooo++ooooooo++O#O$ ",
"%+..++++++++++++++++++%@%++++++++++++++++++O#O$ ",
"%++.++++++++++++++++++%@%++++++++++++++++++O#O$ ",
"%+..++++++++++++++++++%@%++++++++++++++++++O#O$ ",
"%++.++++++++++++++++++%@%++++++++++++++++++O#O$ ",
"%+.##$$$$$$$$$$$$$$$$%%@%%OOOOOOOOOOOOOOOOOO#O$ ",
"%+###################$$@$$###################O$ ",
"%oOOOOOOOOOOOOOOOOOOO##$##OOOOOOOOOOOOOOOOOOOO$ ",
"##$$$$$$$$$$$$$$$$$$$O#$#O$$$$$$$$$$$$$$$$$$$$$ ",
"                     $$$$$                      ",
"                                                ",
"                                                ",
"                                                ",
"                                                "};
