/* XPM */
/* $XConsortium: Dtinfosubi.m.pm /main/2 1996/07/23 12:17:00 drk $ */
static char * Dtinfosubi_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 12 1 0 0",
/* colors */
" 	s background	m black	c #949494949494",
".	s iconGray2	m white	c #bdbdbdbdbdbd",
"X	s bottomShadowColor	m black	c #636363636363",
"o	s iconGray7	m black	c #424242424242",
"O	s iconGray6	m black	c #636363636363",
"+	s iconGray5	m black	c #737373737373",
"@	s iconGray4	m white	c #949494949494",
"#	s iconGray3	m white	c #adadadadadad",
"$	s iconColor8	m black	c magenta",
"%	s iconColor3	m black	c red",
"&	s iconColor5	m black	c blue",
"*	s iconGray8	m black	c #212121212121",
/* pixels */
"                                ",
"                                ",
"                                ",
"        ....X .....o   ....O    ",
"        .+@OO@+++++o...@@@OO    ",
"   ####O$@+%O@+Oo+O+oOO@@+oO    ",
"   ###+O@+@OO@+++oOo+&O@O++O    ",
"   ##@+O@++%O@+++Oo+oOO@O++O    ",
"   ###+O@+@OO@++ooOo+&O@O++O    ",
"   ##@+O@++%O@+++OO+oOO@O++O    ",
"   #@#+O@+@OO@+++OOO+&O@@++O    ",
"   ##@+O$@+%O@++++O+oOO@o++O    ",
"   #@#+O@+@O*@++++O&+&O@@@+O    ",
"   #@#+O$@..............o++O    ",
"   ##@+O@+.O#O#O#O#O#O#O+++O    ",
"   ###+O$@.#O#O#O#O#O#OOO++O    ",
"   ##@+O@+.O#O#O#O#O#O#O@++O    ",
"   #@@+O$@.#O#O#O#O#O#OOO++O    ",
"   ##@+O@+.O#O#O#O#O#O#O+++O    ",
"   ###+O$@OOOOOOOOOOOOOO@@+O    ",
"   ###+O@+@OO@+++OoO+&O+@++O    ",
"   ###+O$@+%O@++OOoOoOO+@++O    ",
"   ###+O@+@OO@++OOo&+&O+O++O    ",
"   ###+O$@+%O@+oOOOooOO+@++O    ",
"   ###+O@+@OO@++OOo&+&O+@++O    ",
"   ###+O$@+%O@++OOOooOO+@++O    ",
"   ###+O@+@OO@++OOo&+&O+@++O    ",
"   ###+O$@+%O@++OOoooOO+@++O    ",
"   OOOOOOOOOOOOOOOOOOOOOOOOO    ",
"                                ",
"                                ",
"                                "};
