/* XPM */
/*********************************************************************
*  (c) Copyright 1999 Sun Microsystems, Inc.
**********************************************************************/
static char * Keyboard_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 8 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray6	m black	c #636363636363",
"X	s iconColor2	m white	c white",
"o	s iconGray2	m white	c #bdbdbdbdbdbd",
"O	s iconGray1	m white	c #dededededede",
"+	s iconGray8	m black	c #212121212121",
"@	s iconGray7	m black	c #424242424242",
"#	s iconGray5	m black	c #737373737373",
/* pixels */
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"................................................",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo",
" .OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+o",
"  .OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+o",
"  .OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+o",
"   .OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+o",
"   .+++++++++++++++++++++++++++++++++++++++++++o",
"   .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX+o",
"   .OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+o",
"    .OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+o",
"    .@@@@@@@@@@@@@@@@@@@@@@OO@@@@@@@@@@@@@@OOO+o",
"    .#OOO#OOO#OOO#OOOOOOO#XOO@OOO#OOO#OOO#XOOO+o",
"    .#O###O###O###O#######XOO@O###O###O###XOOO+o",
"    .#O###O###O###O#######XOO@O###O###O###XOOO+o",
"    .#####################XOO@############XOOO+o",
"    .##OOO#OOO#OOOO#OOOOO#XOO@OOO#OOO#OOO#XOOO+o",
"     .#O###O###O####O#####XOO@O###O###O###XOOO+o",
"     .#O###O###O####O#####XOO@O###O###O###XOOO+o",
"     .####################XOO@############XOOO+o",
"     .##OOO#OOO#OOOOOOOOO#XOO@OOO#OOO#####XOOO+o",
"     ..#O###O###O#########XOO@O###O#######XOOO+o",
"      .#O###O###O#########XOO@O###O#######XOOO+o",
"      .###################XOO@############XOOO+o",
"      .#OOOOO#OOO#########XOO@OOO#########XOOO+o",
"      .#O#####O###########XOO@O###########XOOO+o",
"      .#O#####O###########XOO@O###########XOOO+o",
"       .##################XOO@############XOOO+o",
"       .XXXXXXXXXXXXXXXXXXXOO@XXXXXXXXXXXXXOOO+o",
"       .OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+o",
"       .OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+o",
"       .+++++++++++++++++++++++++++++++++++++++o",
"       .+++++++++++++++++++++++++++++++++++++++o",
"       .oooooooooooooooooooooooooooooooooooooooo"};
