/* XPM */
/* $XConsortium: DtMnone.l.pm /main/3 1995/07/18 17:09:29 drk $ */
static char * DtMnone_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 11 1 0 0",
/* colors */
" 	s none	m none	c none",
".    s bottomShadowColor m black c #636363636363",
"X	s iconColor2	m white	c white",
"o    s iconGray1     m white c #dededededede",
"O    s iconGray4     m white c #949494949494",
"+    s iconGray3     m white c #adadadadadad",
"@    s iconGray2     m white c #bdbdbdbdbdbd",
"#    s iconGray5     m black c #737373737373",
"$    s topShadowColor m white c #bdbdbdbdbdbd",
"%    s iconGray7     m black c #424242424242",
"&    s iconGray6     m black c #636363636363",
/* pixels */
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"        ................................        ",
"       .XXXXXXXXXXoXoXoXoXoXoooooooooooo.       ",
"      .XO++++++++++++++++++++++++++++++++.      ",
"     .X@OOO+++++++++++++++++++++++++++++@+.     ",
"    .X@#OOOO++++++++++++++++++++++++++++O@+.    ",
"   .X@##OOOOOO++++++++++++++++++++++++++OO@+.   ",
"  .X@###OOOOOOOO++++++++++++++++++++++++OOO@+.  ",
" .X+####OOOOOOOOO+++++++++++++++++++++++OOOO@+. ",
".Xo++++++++OOOOOOOO++++++++++++++++++#########O$",
".Xo+@@@@@@@#OOOOOOOO++++++++++++++++#@@@@@@@@@%$",
".Xoo+OOOOOOO#@@@@@@@ooooooooooooooo#@OOOOOO#&&%$",
".Xo+++OOOOOO#@@@@@@@ooooooooooooooo#@OOOOO###&%$",
".Xoo+OOOOOOO#@@@@@@oooooooooooooooo#@OOOOOO#&&%$",
".Xo+++OOOOOO#@@@@@@oooooooooooooooo#@OOOOO###&%$",
".Xoo+OOOOOOOO#@@@@oooooooooooooooo#@OOOOOOO#&&%$",
".Xo+++OOOOOOOO####################@OOOOOOO###&%$",
".Xoo+OOOOOOOOOO@@@@@@@@@@@@@@@@@@@OOOOOOOOO#&&%$",
".Xo+++OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO###&%$",
".Xoo+OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO#&&%$",
".Xo+++OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO###&%$",
".@++########################################&&%$",
".+&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$",
" $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                "};
