/* XPM */
/*********************************************************************
*  (c) Copyright 1999 Sun Microsystems, Inc.
**********************************************************************/
static char * Mouse_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 10 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray6	m black	c #636363636363",
"X	s iconColor2	m white	c white",
"o	s iconGray2	m white	c #bdbdbdbdbdbd",
"O	s iconGray3	m white	c #adadadadadad",
"+	s iconGray1	m white	c #dededededede",
"@	s iconGray4	m white	c #949494949494",
"#	s iconGray7	m black	c #424242424242",
"$	s iconGray5	m black	c #737373737373",
"%	s iconGray8	m black	c #212121212121",
/* pixels */
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"         ...................    ",
"       ..XXXXXXXXXXXXXXXXXX...  ",
"       .X........ooooOoOOO+XXo. ",
"      .Xo.+++++++oooooOoO@O@@Xo ",
"      .X.+OOOOOO.XoooooOOO@O@@+o",
"      .X.+OOOOOO.XooooOoOOO@@@#o",
"      .X.+OOOOOO.XoooOoOOO@O@@#o",
"   ....Xo.......XoooooOoO@O@O@#o",
"  ..o$OXo.+++++++ooooooOOO@O@@#o",
"...@o$OX.+OOOOOO.XooooOoOOO@@@#o",
"+++@o$OX.+OOOOOO.XoooOoOOO@O@@#o",
"...@o$OX.+OOOOOO.XooooOoO@O@O@#o",
"ooo.o$OXo.......XooooooOOO@O@@#o",
"   oo.OXo.+++++++oooooOoOOO@@@#o",
"    oo.X.+OOOOOO.XoooOoOOO@O@@#o",
"      .X.+OOOOOO.XooooOoO@O@O@#o",
"      .X.+OOOOOO.XoooooOOO@O@@#o",
"      .Xo.......XoooooOoOOO@@##o",
"      ..XoXXXXXXoooooOoOOO@###oo",
"       .%%%%%%%%%%%%%%%%%%##ooo ",
"        ooooooooooooooooooooo   ",
"                                ",
"                                ",
"                                ",
"                                "};
