/* XPM */
/* $XConsortium: DtPrtun.l.pm /main/3 1995/07/18 16:25:13 drk $ */
static char * DtPrtun_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 13 1 0 0",
/* colors */
" 	s none	m none	c none",
".    s iconGray6     m black c #636363636363",
"X	s iconColor6	m white	c yellow",
"o    s iconGray7     m black c #424242424242",
"O    s iconGray8     m black c #212121212121",
"+    s iconGray4     m white c #949494949494",
"@    s iconGray1     m white c #dededededede",
"#	s iconColor2	m white	c white",
"$    s iconGray2     m white c #bdbdbdbdbdbd",
"%    s bottomShadowColor m black c #636363636363",
"&    s iconGray3     m white c #adadadadadad",
"*    s iconGray5     m black c #737373737373",
"=    s topShadowColor m white c #bdbdbdbdbdbd",
/* pixels */
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                     ......                     ",
"                    .XXXXXXo                    ",
"                   .XXXXXXXXo                   ",
"                   .XXOOOOXXXO                  ",
"                   .XXO   .XXO                  ",
"                    OOO   .XXO                  ",
"                         .XXXO                  ",
"           +++++++++++++.XXXOO++                ",
"           +@##########.XXXOO#@+                ",
"           +@#########.XXXOO##@+                ",
"           +##$$$$$#$$.XXOO$##@+                ",
"        %%%+####$#$##$.XXO#####+%%%%%%%%%       ",
"       %#$$+##$$$$#$$$.XXO$$$##+@$$$$$$$$o      ",
"      %#$$$+###########OOO#####+&#$$$$$$$$o     ",
"     %#$$$*+@@@@@@@@@@....@@@@@++$@$$$$$$$$o    ",
"    %#$$$o.***********.XXO********#$$$$$$$$$o   ",
"    %#################.XXO##################O   ",
"    %#@@@@@@@@@@@@@@@@@OOO@@@@@@@@@@@@@@@@@@O   ",
"    %#$$@@@@@@@@@@@@@@@@@@@@@@@@@@.........$O   ",
"    %#$$@$$+$$+++$$+++$$+++$$+++@@.XXXXX**.$O   ",
"    %#$$@@@@@@@@@@@@@@@@@@@@@@@@@@.XXXXX**.$O   ",
"    %#$$$*************************.........$O   ",
"    %#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$O   ",
"    %#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$O   ",
"    %#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$O   ",
"    %#$$$***************************$$$$$$$$O   ",
"    %#$$$*OOOOOOOOOOOOOOOOOOOOOOOOO$$$$$$$$$O   ",
"    %#$$$*O+**********************OO$$$$$$$$O   ",
"    %#OOOO&#***********************OOOOOOOOOO   ",
"    %=@&oO&&&&&&&&&&&&&&&&&&&&&&&&&OooooooO     ",
"      @&oO+************************OooooooO     ",
"      @&OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO     ",
"      @==O+************************O%           ",
"         OOOOOOOOOOOOOOOOOOOOOOOOOOO%           ",
"          %%%%%%%%%%%%%%%%%%%%%%%%%%%           ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                "};
