/* XPM */
/* $XConsortium: DtPrtun.m.pm /main/3 1995/07/18 16:25:29 drk $ */
static char * DtPrtun_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 13 1 0 0",
/* colors */
" 	s none	m none	c none",
".    s iconGray6     m black c #636363636363",
"X	s iconColor6	m white	c yellow",
"o    s iconGray8     m black c #212121212121",
"O    s iconGray7     m black c #424242424242",
"+    s iconGray4     m white c #949494949494",
"@	s iconColor2	m white	c white",
"#    s iconGray1     m white c #dededededede",
"$    s iconGray2     m white c #bdbdbdbdbdbd",
"%    s bottomShadowColor m black c #636363636363",
"&    s iconGray5     m black c #737373737373",
"*    s topShadowColor m white c #bdbdbdbdbdbd",
"=    s iconGray3     m white c #adadadadadad",
/* pixels */
"                                ",
"             .....              ",
"            .XXXXX.             ",
"           .XXXXXXX.            ",
"           .XXoooXXXO           ",
"           .XXo  .XXO           ",
"            .oo  .XXO           ",
"      ++++++++++OXXo++          ",
"      +@@@@@@@@OXXo##+          ",
"      +@@@@@@@OXXo#@#+          ",
"      +@$$$$@OXXo##@#+          ",
"    %%+@@@@$@OXXo@@@@+%%%%%%%   ",
"   %$$+@$$$@$OXXo$$$@+#$$$$$$&  ",
" %@$$&+#######..#####++#$$$$$$O ",
"%@$$O.&&&&&&&.XXo&&&&&&@$$$$$$$O",
"%@@@@@@@@@@@@.XXo@@@@@@@@@@@@@@o",
"%@############.oo##############o",
"%@$$###################.......$o",
"%@$$+++$++$$++$$++$$++#.XXXX&.$o",
"%@$$###################.&&&&&.$o",
"%@$$$$$$$$$$$$$$$$$$$$$$$$$$$$$o",
"%@$$$$$$$$$$$$$$$$$$$$$$$$$$$$$o",
"%@$$$$$$$$$$$$$$$$$$$$$$$$$$$$$o",
"%@$$&&&&&&&&&&&&&&&&&&&&&$$$$$$o",
"%@$$&ooooooooooooooooooo$$$$$$$o",
"%@$$&o+&&&&&&&&&&&&&&&&oo$$$$$$o",
"%*%=o===================oOOOOo&&",
"  %=o+&&&&&&&&&&&&&&&&&&oOOOOo  ",
"  %=oooooooooooooooooooooooooo  ",
"  %*o+&&&&&&&&&&&&&&&&&&o%      ",
"    ooooooooooooooooooooo%      ",
"     %%%%%%%%%%%%%%%%%%%..      "};
