/* XPM */
/* $XConsortium: DtPrtmg.m.pm /main/3 1995/07/18 16:24:23 drk $ */
static char * DtPrtmg_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 12 1 0 0",
/* colors */
" 	s none	m none	c none",
".    s iconGray8     m black c #212121212121",
"X    s iconGray7     m black c #424242424242",
"o	s iconColor2	m white	c white",
"O    s iconGray2     m white c #bdbdbdbdbdbd",
"+    s iconGray1     m white c #dededededede",
"@    s iconGray3     m white c #adadadadadad",
"#    s iconGray5     m black c #737373737373",
"$    s iconGray6     m black c #636363636363",
"%	s iconColor1	m black	c black",
"&    s iconGray4     m white c #949494949494",
"*	s iconColor4	m white	c green",
/* pixels */
"                                ",
"         .XXXXXXXXXXXXX         ",
"         XooooooooooooX         ",
"         XoOOoooooOOOoX         ",
"         XooooooooooooX         ",
"         XoOOOOOoOOOOoX         ",
"       XXXooooooooooooXXXXXXX   ",
"      X++XoOOOooOOOoOoXo@@@@@X  ",
"     XoO##oooooooooooo$+OOOOO@X ",
"    X#OO...............%OOOOOOX ",
"    X#++oooooooooo++++++++++++X ",
"   X$##$$$$$$$$$$$OOOO+$$$$$$+X ",
"   X&oOOoooooOOOoX+++++$****$+X ",
"   X&ooooooooooooX+####$$$$$$+X ",
"   X&oOOOOOoOOOOoX++++++++++++X ",
"   X&ooooooooooooX++++++++++++X ",
"  Xo&oOOOooOOOoOoX#####XOO++++X ",
" XO#&oooooooooooo$+&&&&&XO++++X ",
"XOO...............XOOOOOO.....X ",
"X++++++++++++++++++++++++.XX.X. ",
"X+OOOOOOOOOOOOOOO+$$$$$$+....X  ",
"X+++++++++++++++++$****$+.      ",
"X++###############$$$$$$+.      ",
"X++++++++++++++++++++++++.      ",
"X++++++++++++++++++++++++.      ",
"X++................++++++.      ",
"X++.+#############.++++++.      ",
"XXX+@@@@@@@@@@@@@@@.......      ",
"  X&###############XXXX.XX      ",
"  X$$$$$$$$$$$$$$$$.....X       ",
"   ................             ",
"                                "};
