/* XPM */
/* $XConsortium: Dttrsh.m.pm /main/3 1995/07/18 16:49:56 drk $ */
static char * Fptrsh_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 9 1 0 0",
/* colors */
" 	s none	m none	c none",
".    s iconGray4     m white c #949494949494",
"X    s iconGray1     m white c #dededededede",
"o    s iconGray3     m white c #adadadadadad",
"O    s bottomShadowColor m black c #636363636363",
"+    s iconGray2     m white c #bdbdbdbdbdbd",
"@    s iconGray7     m black c #424242424242",
"#	s iconColor1	m black	c black",
"$    s iconGray5     m black c #737373737373",
/* pixels */
"      .XXXXXXXXXXXXXXXo.OO      ",
"      X.XXXXXXXXXXXXXXXXX.O     ",
"      X+X++++++++++++++++X@     ",
"      X+X++++++++++++++++X@     ",
"      @+X++++++++++++++++X@     ",
"      X@@@@@@@@@@@@@@@@@@@@     ",
"      oX++++++++++++++++++@     ",
"      .o+.................@     ",
"      .o+.................@     ",
"      oo+.................@     ",
"      .o+.................@     ",
"      oo+.................@     ",
"      .o+.................@     ",
"      oo+.................@     ",
"      .o+.................@     ",
"      oo+.................@     ",
"      .o+.................@     ",
"      oo+.................@     ",
"      .o+.................@     ",
"      oo+.................@     ",
"      .o+.................@     ",
"      oo+.................@     ",
"      .o+.................@     ",
"      oo+.................@     ",
"      .o+.................@     ",
"      oo+.................@     ",
"      .o+.................@     ",
"      oo+.................@     ",
"      .o+.....######......@     ",
"      #o+.....#XXXXXX$....@     ",
"       #+.....######$$....@     ",
"        ###################     "};
