/* XPM */
/* $XConsortium: FpPrtmg.m.pm /main/3 1995/07/18 16:54:38 drk $ */
static char * FpPrtmg_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 14 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X    s iconGray4     m white c #949494949494",
"o    s iconGray2     m white c #bdbdbdbdbdbd",
"O    s bottomShadowColor m black c #636363636363",
"+    s iconGray6     m black c #636363636363",
"@    s topShadowColor m white c #bdbdbdbdbdbd",
"#    s iconGray3     m white c #adadadadadad",
"$    s iconGray7     m black c #424242424242",
"%    s iconGray5     m black c #737373737373",
"&    s iconGray8     m black c #212121212121",
"*    s iconGray1     m white c #dededededede",
"=	s iconColor4	m white	c green",
"-    s selectColor m white c #737373737373",
/* pixels */
"                                ",
"          ............          ",
"          ............X         ",
"          .oo.....ooo.X         ",
"          ............X         ",
"          .ooooo.oooo.X         ",
"       OOO............+OOOOOO@  ",
"      O###.ooo..ooo.o.+XXX###$@ ",
"     O.o%%............+Xooooo#&@",
"    O#oo++++++++++++++++oooooo&@",
"    O*************************+@",
"    +............Xoooo*++++++*+@",
"    X.oo.....ooo.Xooo**+====+o+@",
"    X............X*%%%%++++++o+@",
"    X.ooooo.oooo.%oooooooooooo+@",
"   O*............%%%%%%ooooooo+@",
"  Oo*.ooo..ooo.o.$#####$oooooo+@",
" O*%X............+##oooo$ooooo+@",
"O*o%+++++++++++++++oooooo&&&&&&@",
"O........................+$$&$&@",
"O.ooooooooooooooo*++++++*+&&&$@ ",
"O.****************+====+*+@@@@  ",
"O.*%%%%%%%%%%%%%%%++++++*+@     ",
"O.***********************+@     ",
"O.***********************+@     ",
"O.*&&&&&&&&&&&&&&&&******+@     ",
"O**&*%%%%%%%%%%%%%&******+@     ",
"O&&*###############&&&&&&&@     ",
"@$$X%%%%%%%%%%%%%%%$$$$&$$@     ",
" $&++++++++++++++++&&&&&$@      ",
" @@$&&&&&&&&&&&&&&&-@@@@@       ",
"   -----------------            "};
