/* XPM */
/* $XConsortium: FpPrtmg.l.pm /main/3 1995/07/18 16:54:29 drk $ */
static char * FpPrtmg_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 14 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X    s iconGray4     m white c #949494949494",
"o    s iconGray2     m white c #bdbdbdbdbdbd",
"O    s iconGray5     m black c #737373737373",
"+    s bottomShadowColor m black c #636363636363",
"@    s iconGray6     m black c #636363636363",
"#    s topShadowColor m white c #bdbdbdbdbdbd",
"$    s iconGray3     m white c #adadadadadad",
"%    s iconGray1     m white c #dededededede",
"&    s iconGray7     m black c #424242424242",
"*	s iconColor4	m white	c green",
"=    s iconGray8     m black c #212121212121",
"-    s selectColor m white c #737373737373",
/* pixels */
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                ..................              ",
"                ..................X             ",
"                ..ooo.......ooooo.X             ",
"                ..ooo.......ooooo.X             ",
"                ..................O             ",
"                ..ooooooo..oooooo.O             ",
"                ..................O             ",
"             +++..................O@+++++++#    ",
"            +$$O..oooo...ooooo.oo.@$$$$$$$$+#   ",
"           +%$$O..................@$$$$$$$$$&#  ",
"          +%oOOOOOOOOOOOOOOOOOOOOOOOOoooooooo&# ",
"         +%ooooooooooooooooooooooooooooooooooo&#",
"         +.%.%.%.%.%.%.%.%.%.%.%.%.%.%%%%%%%%%&#",
"         +%ooooooooooooooooooooooo%%@@@@@@@@@%&#",
"        ...................X%%%%%%%%@*****$O@%&#",
"        ..o.o........oooo..&%%%%%%%%@OOOOOOO@%&#",
"        ...o.o.o...........&%%OOOOOO@@@@@@@@@%&#",
"        ..o.o.o.o..oooooo..&o%%%%%%%%%%%%%%%%%&#",
"        ...o.o.o.o.........&oo%o%o%%%%%%%%%%%%&#",
"     +++..o.o.o............&OOOOOOOOo%o%%%%%%%&#",
"    +%$$...o.o.o.o.o.o..o..&$$$$$$$$&o%o%o%%%%&#",
"   +%o$X..o.o.o.o.o.o......@$$$o$o$o$&ooo%o%%%&#",
"  +%ooo@...................@$ooooooooo&oooooo%&#",
" +%oooOOOOOOOOOOOOOOOOOOOOOOO&ooooooooo=======&#",
" +.....................................=&&&==###",
" +.%ooooooooooooooooooooooo%@@@@@@@@@%%======#  ",
" +.%ooXXXooXXXooXXXooXXXooo%@*****$O@%%======#  ",
" +.%%%%%%%%%%%%%%%%%%%%%%%%%@OOOOOOO@%%=######  ",
" +.%%%OOOOOOOOOOOOOOOOOOOOOO@@@@@@@@@%%=#       ",
" +.%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%=#       ",
" +.%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%=#       ",
" +.%%%XXXXXXXXXXXXXXXXXXXXXXXXX%%%%%%%%=#       ",
" +.%%%========================%%%%%%%%%=#       ",
" +.%%%=ooOOOOOOOOOOOOOOOOOOO==%%%%%%%%%=#       ",
" +.$$$=%oOOOOOOOOOOOOOOOOOOO==$$$$$$$$$=#       ",
" +.===%$$$$$$$$$$$$$$$$$$$$$$$==========#       ",
" ###&&XOOOOOOOOOOOOOOOOOOOOOOO&&&&&&=&&&#       ",
"    ==@@@@@@@@@@@@@@@@@@@@@@@@=======&&##       ",
"    ==@@@@@@@@@@@@@@@@@@@@@@@@=======&&#        ",
"    ##========================- ########        ",
"      &&&&&&&&&&&&&&&&&&&&&&&&-                 ",
"       ------------------------                 "};
