/* XPM */
static char *impress.l[] = {
/* columns rows colors chars-per-pixel */
"48 48 6 1",
"  c #800000",
". c red",
"X c #808080",
"o c #C0C0C0",
"O c gray100",
"+ c None",
/* pixels */
"......................XXXXXXX...............o+++",
"...................XXXoOOOOoo ...............o++",
"..........XXXXXXXXXoOOOOo    .................++",
".O.O...XXXOOOOOOooOOOO   o.o.O.O.O.O.O.O.O.O.o++",
"O.O..XXOOOOOOOOOOOOO  X.o.......O.O.O.O.O.O.O.o+",
".O..XOOOOO     oOOo Xo...XXXXXXXXo.O.O.O.O.O.O.+",
"O..XOOo   o.o.o    .o.XXXoOOOOOoo o.O.O.O.O.O.o+",
".O.o   o.O.O.O.O.O..XXoOOOOOo    X.O.O.O.O.O.O.o",
"o.o.o.o.o.o.o.o.o..XoOOOOOo  .o.o.o.o.o.o.o.o.oX",
".O.O.O.O.O........XOOOOOo  X.O.O.O.O.O.O.O.O.O.X",
"o.o.o.o.o.XXooooXXOOOOOo .o.o.o.o.o.o.o.o.o.o.oX",
".O.O.O.XXoOOOOOOOOOOOO  .O.O.O.O.O.O.O.O.O.O.O.X",
"o.o.oXXoOOOOOOOOOOOOO X.o.o.o.o.o.o.o.o.o.o.o.oX",
".o.XXoOOOOOOooOOOOOO X.o.o.o.o.o.o.o.o.o.o.o.o.X",
"o.XoOOOoo        OOo .o.o.o.o.o.o.o.o.o.o.o.o.oX",
".XOOOo   X.X.X.X.   .o.o.o.o.o.o.o.o.o.o.o.o.o.+",
"XOOo  X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X+",
"XOX .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.oX+",
"X  .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.++",
".o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o++",
"X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.++",
".o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o++",
"X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X+++",
".X.X.X.X.X.X.X.oOOOOOOOOOOOOOOoX.X.X.X.X.X.X.+++",
"X.X.X.X.X.X.XoOOOOOOOOOOOOOOOOOOo.X.X.X.X.X.X+++",
".X.X.X.X.X.X.OOOOOOOOOOOOOOOOOOOOX.X.X.X.X.X++++",
" . . . . . .oOOOOOOOOOOOOOOOOOOOOo . . . . .++++",
".X.X.X.X.X.XOOOOOX.X.X.X.X.X.OOOOO.X.X.X.X. ++++",
" . . . . . .OOOO . . . . . . .OOOO . . . . X++++",
".X.X.X.X.X.XOOOO.X.X.X.X.X.X.XOOOO.X.X.X.X.+++++",
" . . . . . .OOOO . . . . . . .OOOO . . . . +++++",
". . . . . . OOOO. . . . . . . OOOO. . . . .+++++",
" . . . . . .OOOO . . . . . . .OOOO . . . . +++++",
". . . . . . OOOO. . . . . . . OOOO. . . . .+++++",
" . . . . . .OOOO . . . . . . .OOOO . . . . +++++",
". . . . . . OOOO. . . . . . . OOOO. . . . .+++++",
" . . . . . .OOOO . . . . . . .OOOO . . . . +++++",
". . . . . . OOOOO . . . . . .OOOOO. . . . .+++++",
" . . . . . .oOOOOOOOOOOOOOOOOOOOOo . . . . +++++",
". . . . . . .OOOOOOOOOOOOOOOOOOOO . . . . .+++++",
" . . . . . . oOOOOOOOOOOOOOOOOOOo. . . . . +++++",
". . . . . . . .oOOOOOOOOOOOOOOo . . . . . .+++++",
" . . . . . . . . . . . . . . . . . . . . . +++++",
". . . . . . . . . . . . . . . . . . . . . . ++++",
" . . . . . . . . . . . . . . . . . . . . . .++++",
"............................................++++",
"............................................o+++",
".............................................+++"
};
