/* XPM */
static char *impress.m[] = {
/* columns rows colors chars-per-pixel */
"32 32 6 1",
"  c #800000",
". c red",
"X c #808080",
"o c #C0C0C0",
"O c gray100",
"+ c None",
/* pixels */
"..............................o+",
"............XXoX...............+",
"O.O.O..ooo.XOOOO .O.O.O.O.O.O.OX",
".O.O.oOOOOOOOO  .O.O.O.O.O.O.O.o",
"O.OoOOO   OO  .XXXXXO.O.O.O.O.O.",
".O.O   o.o  .XXOOOOo O.O.O.O.O.o",
"o.o.o.o.o.o.XOOOO   o.o.o.o.o.o.",
".O.O.......XOOO  X.O.O.O.O.O.O.o",
"o.o.ooOOOOOOOO .o.o.o.o.o.o.o.o.",
".oXoOOOOOOOOO .o.o.o.o.o.o.o.o.o",
"oXOOo     oO .o.o.o.o.o.o.o.o.o.",
"XO   X.X.X  .X.X.X.X.X.X.X.X.X.X",
"o X.o.o.o.o.o.o.o.o.o.o.o.o.o.o+",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.+",
"X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X+",
".X.X.X.X.oOOOOOOOOOo.X.X.X.X.X++",
" . . . .OOOOOOOOOOOOO. . . . .++",
".X.X.X.oOOOOOOOOOOOOOo.X.X.X.o++",
" . . . OOOO. . . .OOOO . . . +++",
".X.X.X.OOO.X.X.X.X.OOO.X.X.X.+++",
" . . . OOO . . . . OOO . . . +++",
". . . .OOO. . . . .OOO. . . .+++",
" . . . OOO . . . . OOO . . .X+++",
". . . .OOO. . . . .OOO. . . X+++",
" . . . OOOO. . . .OOOO . . .X+++",
". . . .oOOOOOOOOOOOOOo. . . X+++",
" . . . .OOOOOOOOOOOOO. . . .X+++",
". . . . .oOOOOOOOOOo. . . . .+++",
" . . . . . . . . . . . . . . +++",
".............................+++",
".............................o++",
"..............................++"
};
