/* XPM */
static char *draw.l[] = {
/* columns rows colors chars-per-pixel */
"48 48 6 1",
"  c #808000",
". c yellow",
"X c #808080",
"o c #C0C0C0",
"O c gray100",
"+ c None",
/* pixels */
" . . . . . . . . . ....ooooo.. . . . . . . . +++",
"....................oooOOOOoo ...............o++",
"..........oooooo..ooOOOOo    o................++",
".......oooOOOOOOooOOOO   o....................++",
".....ooOOOOOOOOOOOOO  o.......................o+",
".O..oOOOOO     oOOo o.....oooooo...O.O.O.O.O.O.+",
"O..oOOo   o....    ....oooOOOOOoo ..O.O.O.O.O..+",
".O.o   o...O.O.O.O...ooOOOOOo    o.O.O.O.O.O.O.o",
"O.O.....O.O.O.O.O..ooOOOOOo  o....O.O.O.O.O.O.O.",
".O.O.O.O.O........oOOOOOo  o.O.O.O.O.O.O.O.O.O.o",
"O.O.O.O...ooooooooOOOOOo ...O.O.O.O.O.O.O.O.O.O.",
".O.O....ooOOOOOOOOOOOO  .O.O.O.O.O.O.O.O.O.O.O.o",
"......ooOOOOOOOOOOOOO X.........................",
"....ooOOOOOOooOOOOOO X.........................o",
"..ooOOOo         OOo ..........................o",
".oOOOo  o........   ...........................+",
"oOOo  o........................................+",
"XO  o.........................................o+",
". o...........................................++",
"..............................................++",
"o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.++",
".............................................o++",
"o.o.o.o.o.o.o.o.oOOOOOO.o.o.o.o.o.o.o.o.o.o.o+++",
"...............OOOOOOOOOO....................+++",
"o.o.o.o.o.o.o.OOOOOOOOOOOOo.o.o.o.o.o.o.o.o.o+++",
".............OOOOOOOOOOOOOO.................++++",
"o.o.o.o.o.o.oOOOOOOOOOOOOOO.o.o.o.o.o.o.o.o.++++",
".o.o.o.o.o.oOOOOOOOOOOOOOOOO.o.o.o.o.o.o.o.o++++",
"o.o.o.o.o.o.OOOOOOo.o.OOOOOOo.o.o.o.o.o.o.oo++++",
".o.o.o.o.o.oOOOOOo.o.oOOOOOO.o.o.o.o.o.o.o.+++++",
"o.o.o.o.o.o.oOOOo.o.oOOOOOO.o.o.o.o.o.o.o.o+++++",
".o.o.o.o.o.o.o.o.o.oOOOOOOOo.o.o.o.o.o.o.o.+++++",
" . . . . . . . . . OOOOOOO . . . . . . . . +++++",
".o.o.o.o.o.o.o.o.oOOOOOOOo.o.o.o.o.o.o.o.o.+++++",
" . . . . . . . . OOOOOOO . . . . . . . . . +++++",
".o.o.o.o.o.o.o.o.OOOOOOo.o.o.o.o.o.o.o.o.o.+++++",
" . . . . . . . . OOOOO . . . . . . . . . . +++++",
".o.o.o.o.o.o.o.o.OOOOOOo.o.o.o.o.OOOOo.o.o.+++++",
" . . . . . . . . OOOOOOO . . . .OOOOOO . . +++++",
".o.o.o.o.o.o.o.o.OOOOOOOOOOOOOOOOOOOOO.o.o.+++++",
" . . . . . . . . .OOOOOOOOOOOOOOOOOOOO . . +++++",
".o.o.o.o.o.o.o.o.oOOOOOOOOOOOOOOOOOOOO.o.o.+++++",
" . . . . . . . . . OOOOOOOOOOOOOOOOOO. . . +++++",
". . . . . . . . . . .OOOOOOOOOOOOOOO. . . .o++++",
" . . . . . . . . . . . .OOOOOOOOOO . . . . .++++",
". . . . . . . . . . . . . . . . . . . . . . ++++",
" . . . . . . . . . . . . . . . . . . . . . .o+++",
". . . . . . . . . . . . . . . . . . . . . . .+++"
};
