/* XPM */
static char *math.m[] = {
/* columns rows colors chars-per-pixel */
"32 32 6 1",
"  c #008080",
". c cyan",
"X c #808080",
"o c #C0C0C0",
"O c gray100",
"+ c None",
/* pixels */
". . . . . . . . . . . . . . . o+",
" . . . . . .oXoXo. . . . . . . +",
".o.o.ooooooXOOOO o.o.o.o.o.o.o.o",
"....ooOOOOOOOO  ................",
"...oOOO   OO  .oXXXX............",
"...    ...  .oXOOOOo ...........",
"............XOOOO   ............",
"o.o.o.oooooXOOO  .o.o.o.o.o.o.o.",
"....ooOOOOOOOO .................",
"o.XoOOOOOOOOO o.o.o.o.o.o.o.o.o.",
".XOOo     oO ...................",
"XO   .X.X.  X.X.X.X.X.X.X.X.X.Xo",
"o X............................+",
"X.X.X.X.XOOOOOOOOOOOOOX.X.X.X.X+",
".........OOOOOOOOOOOOO........o+",
"X.X.X.X.XOOOOOOOOOOOOOX.X.X.X.++",
"..........OOOO................++",
" . . . . . OOOO. . . . . . . o++",
".o.o.o.o.o.oOOOO.o.o.o.o.o.o.+++",
" . . . . . . OOOO. . . . . . +++",
".o.o.o.o.o.o.oOOOO.o.o.o.o.o.+++",
" . . . . . . .OOOO . . . . . +++",
".o.o.o.o.o.o.OOOOo.o.o.o.o.oo+++",
" . . . . . .OOOO . . . . . .o+++",
". . . . . .OOOO . . . . . . o+++",
" . . . . .OOOO . . . . . . .o+++",
". . . . .OOOOOOOOOOOOO. . . o+++",
" . . . . OOOOOOOOOOOOO . . . +++",
". . . . .OOOOOOOOOOOOO. . . .+++",
" . . . . . . . . . . . . . . +++",
". . . . . . . . . . . . . . .o++",
" . . . . . . . . . . . . . . .++"
};
