/* XPM */
static char *calc.m[] = {
/* columns rows colors chars-per-pixel */
"32 32 7 1",
"  c black",
". c #008000",
"X c green",
"o c #808080",
"O c #C0C0C0",
"+ c gray100",
"@ c None",
/* pixels */
"..............................o@",
".O.O.O.O.O..oo.o.O.O.O.O.O.O.O.@",
"X.X.X......o++++o.X.X.X.X.X.X.Xo",
".X...O++++++++ o.X.X.X.X.X.X.X.O",
"X..O+++   ++ o.oooooX.X.X.X.X.X.",
".X..  .X.X o.oo++++OoX.X.X.X.X.O",
"X.X.X.X.X.X.o++++  oX.X.X.X.X.X.",
".X.X........+++ oX.X.X.X.X.X.X.O",
"X.X..O++++++++ .X.X.X.X.X.X.X.X.",
".XoO+++++++++ .X.X.X.X.X.X.X.X.O",
"Oo++O     O+ .O.O.O.O.O.O.O.O.O.",
"o+  .X.X.X. .X.X.X.X.X.X.X.X.X.o",
"Ooo.O.O.O.O.O.O.O.O.O.O.O.O.O.O@",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.@",
"O.O.O.O++++++++++++++++.O.O.O.o@",
".X.X.X.++++++++++++++++X.X.X.O@@",
"O.O.O.O++.O.O.++O.O.O++.O.O.O.@@",
".O.O.O.++O.O.O++.O.O.++O.O.O.o@@",
"O.O.O.O++.O.O.++O.O.O++.O.O.O@@@",
".O.O.O.++O.O.O++.O.O.++O.O.O.@@@",
"O.O.O.O++++++++++++++++.O.O.O@@@",
".o.o.o.++++++++++++++++o.o.o.@@@",
"O.O.O.O++.O.O.++O.O.O++.O.O.o@@@",
".o.o.o.++o.o.o++.o.o.++o.o.oo@@@",
".......++.....++.....++.....o@@@",
".o.o.o.++o.o.o++.o.o.++o.o.oo@@@",
".......++++++++++++++++.....o@@@",
".o.o.o.++++++++++++++++o.o.o.@@@",
".............................@@@",
".............................@@@",
".............................o@@",
"..............................@@"
};
