/* XPM */
/*********************************************************************
*  (c) Copyright 1999 Sun Microsystems, Inc.
**********************************************************************/
static char * audiomixer_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 11 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray6	m black	c #636363636363",
"X	s iconColor2	m white	c white",
"o	s iconGray8	m black	c #212121212121",
"O	s iconGray3	m white	c #adadadadadad",
"+	s iconGray2	m white	c #bdbdbdbdbdbd",
"@	s iconGray1	m white	c #dededededede",
"#	s iconGray5	m black	c #737373737373",
"$	s iconGray7	m black	c #424242424242",
"%	s iconGray4	m white	c #949494949494",
"&	s iconColor5	m black	c blue",
/* pixels */
"                                                ",
"                                                ",
"                                                ",
"                    .....                       ",
"                    .XXXX.     ooooo            ",
"                    .XOO++.    o@@@o            ",
"                    .X#$X++.   o@@+o            ",
"                    .X#$@X++.  o@@+o            ",
"                    .X#$@@X++. o@@+o            ",
"                    .@#$@@@X++.o@@+o            ",
"                    .@#$@@@@@+$$$$$oo           ",
"            O.      .@#$@@@@@$%&%&%&%o          ",
"           $.       .@#$@@@@@$&%&%&%&o....      ",
"          $.        .@#$++@@@$ooooooooX++.+     ",
"         $.         .@.$O+++@@$&%&%&oXX@@.+     ",
"        $.          .O.$@OO+++@oooooXX@@@.+     ",
"       O$O      $   .O.$@@@OO++o...o@@@@@.+     ",
"      @$.      $    .O.$O%@@@OOo..+o+O+O+.+     ",
"      O$O     $O    .O.$%%O%@@@o.@+o@@@@@.+     ",
"      #$     O$    .@O.$O%%%OOOo@@+oO@O@O$+     ",
"     @$.     $.    ..O.$%%O%%%Oo@@+oOO%OO$+     ",
"     O$#    @$.    .@O.$O%%%O%%o@@+o%%%%%$+     ",
"     O$#    O$#    ..O.$%%%%%%%o@@+o%%%%%o+     ",
"     O$#    O$#    .@O.$%%%%%%%o@@+o%%%%%$+     ",
"     O$#    O$#    ..O.$%%%%%%%o@@+o#%%%#o+     ",
"     O$#    O$#    .@O.$%%%#%%%o@@+o%%#%%o+     ",
"     O$#    @$.    ..O.$%%#%%#%o@@+o%#%#%o+     ",
"     @$.     $.    .@O.$#%%#%%#o@@+o#####o+     ",
"      #$     O$    ..O.$%######o@@+o.....o+     ",
"      O$O     $O    .O.$##.....o@@+o.$.$.o+     ",
"      @$.      $    $O.$....$$$o@@+o$$$$$o+     ",
"       O$O      $   .O$$..$$$$$o@@+o$$$$$o+     ",
"        $.          $O$$$$$$$$$o@@+o$$$$$o+     ",
"         $.         $O$o$$$$$$$o@@+o$$$$oo+     ",
"          $.        $O$$$$$$$$$o@@+oooooo++     ",
"           $.       .O$o$$$$$$$o@@+o++++++      ",
"            O.      $O$o$$$$$$$o@@+o            ",
"                    $Ooo$$$$$$oo@@+o            ",
"                    oO$o$$$$$o+o@@+o            ",
"                    $Ooo$$$$o+ o@@+o            ",
"                    oOoo$$$o+  o@@+o            ",
"                    oOoo$$o+   ooooo            ",
"                    oOoo$o+                     ",
"                    ooooo+                      ",
"                    +++++                       ",
"                                                ",
"                                                ",
"                                                "};
