/* XPM */
/*********************************************************************
*  (c) Copyright 1997 Sun Microsystems, Inc.
**********************************************************************/
static char * error_log_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 9 1 0 0",
/* colors */
" 	s iconColor2	m white	c white",
".	s none	m none	c none",
"X	s iconGray2	m white	c #bdbdbdbdbdbd",
"o	s iconColor1	m black	c black",
"O	s iconGray8	m black	c #212121212121",
"+	s iconGray5	m black	c #737373737373",
"@	s iconGray7	m black	c #424242424242",
"#	s iconGray1	m white	c #dededededede",
"$	s iconColor3	m black	c red",
/* pixels */
"                         .......",
" XXXXXXXXXXXXXXXXXXXXXXXo.......",
" XXXXXXXXXXXXXXXXXXXXXXXo.......",
" XXXXXXXXXXXXXXXXXXXXXXXo.......",
" XXOo+@X@@X@@XXXXXXXXXXXo.......",
" XXXXXXXXXXXXXXXXXXXXXXXo.......",
" XXXXXXXXXXXXXXXXXXXXXXXo.......",
" XXXo@X@oo@X@XXXXXXXXXXXO.......",
" XXXXXXXXXXXXXXXXXXXXXXXO.......",
" XXXo@X@@XoX@@XXXXXXXXXXO.......",
" XXXXXXXXXXXXXXXX##############.",
" XXXo@Xoo@X@@XXX#$$$$$$$$$$$$$$O",
" XXXXXXXXXXXXXXX#$$$$$   O$$$$$O",
" XXX@@X@ooX@@@XX#$$$$$   O$$$$$O",
" XXXXXXXXXXXXXXX#$$$$$   O$$$$$O",
" XXX@@XoXo@X@@XX#$$$$$   O$$$$$O",
" XXXXXXXXXXXXXXX#$$$$$# #O$$$$$O",
" XXXo@X@X@@@XXXX#$$$$$# #O$$$$$O",
" XXXXXXXXXXXXXXX#$$$$$$ O$$$$$$O",
" XXXXXXXXXXXXXXX#$$$$$$$$$$$$$$O",
" XX@oX@@@Xo@@XXX#$$$$$# #O$$$$$O",
" XXXXXXXXXXXXXXX#$$$$$   O$$$$$O",
" XXXXXXXXXXXXXXX#$$$$$# #O$$$$$O",
" XXX@@X@X@@X@@XX#$$$$$OOOO$$$$$O",
" XXXXXXXXXXXXXXX#$$$$$$$$$$$$$$O",
" XXX@@Xo@@X@@XXXXOOOOOOOOOOOOOO.",
" XXXXXXXXXXXXXXXXXXXXXXXO.......",
" XXXo@XoXooX@XXXXXXXXXXXO.......",
" XXXXXXXXXXXXXXXXXXXXXXXo.......",
" XXXXXXXXXXXXXXXXXXXXXXXo.......",
" XXXXXXXXXXXXXXXXXXXXXXXo.......",
" oooooooooooooooooooooooo......."};
