/* XPM */
/*********************************************************************
*  (c) Copyright 1997 Sun Microsystems, Inc.
*  All Rights Reserved
**********************************************************************/
static char * error_log_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 12 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X	s iconGray2	m white	c #bdbdbdbdbdbd",
"o	s iconGray8	m black	c #212121212121",
"O	s iconColor1	m black	c black",
"+	s iconGray5	m black	c #737373737373",
"@	s iconGray7	m black	c #424242424242",
"#	s iconGray1	m white	c #dededededede",
"$	s iconColor3	m black	c red",
"%	s iconGray6	m black	c #636363636363",
"&	s iconGray4	m white	c #949494949494",
"*	s iconGray3	m white	c #adadadadadad",
/* pixels */
"                                                ",
" ....................................           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXooO++@X@@@XX@@@XXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXXo@@X@oo+@@X@@XXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXXo@@X@@@XooX@@@XXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXX####################### ",
" .XXXXXXXXXXXXXXXXXXXXXX#$$$$$$$$$$$$$$$$$$$$$o ",
" .XXXXXo@@Xooo@X+@@@XXXX#$$$$$$$$$$$$$$$$$$$$$o ",
" .XXXXXXXXXXXXXXXXXXXXXX#$$$$$$$$....%$$$$$$$$o ",
" .XXXXXXXXXXXXXXXXXXXXXX#$$$$$$$$....o$$$$$$$$o ",
" .XXXXX@@@X@oooXX@@@@XXX#$$$$$$$$....o$$$$$$$$o ",
" .XXXXXXXXXXXXXXXXXXXXXX#$$$$$$$$....o$$$$$$$$o ",
" .XXXXXXXXXXXXXXXXXXXXXX#$$$$$$$$....o$$$$$$$$o ",
" .XXXXX@@@X@XXO@@X@@@XXX#$$$$$$$$....o$$$$$$$$o ",
" .XXXXXXXXXXXXXXXXXXXXXX#$$$$$$$$#..#o$$$$$$$$o ",
" .XXXXXXXXXXXXXXXXXXXXXX#$$$$$$$$#..#o$$$$$$$$o ",
" .XXXXXo@@X@+X@@@@XXXXXX#$$$$$$$$X..Xo$$$$$$$$o ",
" .XXXXXXXXXXXXXXXXXXXXXX#$$$$$$$$$..o$$$$$$$$$o ",
" .XXXXXXXXXXXXXXXXXXXXXX#$$$$$$$$$oo$$$$$$$$$$o ",
" .XXXXXXXXXXXXXXXXXXXXXX#$$$$$$$$$$$$$$$$$$$$$o ",
" .XXX@@oXX@@@@Xo+@@@XXXX#$$$$$$$$$..%$$$$$$$$$o ",
" .XXXXXXXXXXXXXXXXXXXXXX#$$$$$$$$....o$$$$$$$$o ",
" .XXXXXXXXXXXXXXXXXXXXXX#$$$$$$$$....o$$$$$$$$o ",
" .XXXXXXXXXXXXXXXXXXXXXX#$$$$$$$$$..o$$$$$$$$$o ",
" .XXXXXoooXo+X@@@X@@@XXX#$$$$$$$$$oo$$$$$$$$$$o ",
" .XXXXXXXXXXXXXXXXXXXXXX#$$$$$$$$$$$$$$$$$$$$$o ",
" .XXXXXXXXXXXXXXXXXXXXXX#$$$$$$$$$$$$$$$$$$$$$o ",
" .XXXXX@@@Xo@@@XX@@@XXXX#oooooooooooooooooooooo ",
" .XXXXXXXXXXXXXXXXXXXXXXX&&&&&&&&&&&o           ",
" .XXXXXXXXXXXXXXXXXXXXXXX***********o           ",
" .XXXXXo@@Xo+XoooX@@XXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .ooooooooooooooooooooooooooooooooooo           ",
"                                                "};
