/* XPM */
/*********************************************************************
*  Copyright (c) 1996 Sun Microsystems, Inc.
*  All Rights Reserved
**********************************************************************/
static char * estar_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 5 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray2	m white	c #bdbdbdbdbdbd",
"X	s iconColor6	m white	c yellow",
"o	s iconGray8	m black	c #212121212121",
"O	s iconGray4	m white	c #949494949494",
/* pixels */
"                   .........                    ",
"               ....XXXXXXXXX....                ",
"             ..XXXXXXXXXXXXXXXXX..              ",
"           ..XXXXXXXXXXXXXXXXXXXXX..            ",
"          .XXXXXXXXXXXXXXXXXXXXXXXXX.           ",
"         .XXXXXXXXXXXXXXXXXXXXXXXXXXX.          ",
"        .XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.         ",
"       .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.        ",
"      .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.       ",
"     .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.      ",
"    .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.     ",
"   .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.    ",
"   .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.    ",
"  .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXoooXXXXXXXXX.   ",
"  .XXXXXXXXXXXXXXXXXXXXXXXXXXXXOoooXXXXXXXXX.   ",
" .XXXXXXXXXXXXXXXXXXXXoooooooooooooXXXXXXXXXX.  ",
" .XXXXXXXXXXXXXXXXXXXooooooooooooooXXXXXXXXXX.  ",
" .XXXXXXXXXXXXXXXXXXoooooooooooooooooooooooXX.  ",
" .XXXXXXXXXXXXXXXXXOoooooooooooooooooooooooXX.  ",
".XXXXXXXXXXXXX.OoooooooooooooooooooXXXXXXXXXXX. ",
".XXXXXXXXXXX.ooooooooooooooooooooooXXXXXXXXXXX. ",
".XXXXXXXXXX.oooooooooooooooooooooooXXXXXXXXXXX. ",
".XXXXXXXXX.ooooooooooooooooooooooooXXXXXXXXXXX. ",
".XXXXXXXX.oooooooooooooooooooooooooXXXXXXXXXXX. ",
".XXXXXXXXOoooooooooooooooooooooooooXXXXXXXXXXX. ",
".XXXXXXX.oooooooo..OoooooooooooooooooooooooXXX. ",
".XXXXXX.ooooooo.XXXXoooooooooooooooooooooooXXX. ",
".XXXXXOooooooo.XXXXXXooooooooooooooXXXXXXXXXXX. ",
" .XXXooooooooOXXXXXXXXoooooooooooooXXXXXXXXXX.  ",
" .XXXooooooooXXXXXXXXXXXXXXXXXXOoooXXXXXXXXXX.  ",
" .XXXooooooo.XXXXXXXXXXXXXXXXXXXoooXXXXXXXXXX.  ",
" .XXXoooooo.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.  ",
"  .XXXooooOXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.   ",
"  .XXXXoooXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.   ",
"   .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.    ",
"   .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.    ",
"    .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.     ",
"     .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.      ",
"      .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.       ",
"       .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.        ",
"        .XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.         ",
"         .XXXXXXXXXXXXXXXXXXXXXXXXXXX.          ",
"          .XXXXXXXXXXXXXXXXXXXXXXXXX.           ",
"            .XXXXXXXXXXXXXXXXXXXXX.             ",
"              .XXXXXXXXXXXXXXXXX.               ",
"                  .XXXXXXXXX.                   ",
"                                                ",
"                                                "};
