/* XPM */
/*********************************************************************
*  (c) Copyright 1997 Sun Microsystems, Inc.
*  All Rights Reserved
**********************************************************************/
static char * sys_info_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 11 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray1	m white	c #dededededede",
"X	s iconColor2	m white	c white",
"o	s iconGray2	m white	c #bdbdbdbdbdbd",
"O	s iconGray8	m black	c #212121212121",
"+	s iconGray6	m black	c #636363636363",
"@	s iconColor5	m black	c blue",
"#	s iconGray7	m black	c #424242424242",
"$	s iconColor1	m black	c black",
"%	s iconGray4	m white	c #949494949494",
"&	s iconGray5	m black	c #737373737373",
/* pixels */
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"              ....................              ",
"          XXXXXXXXXXXXXXXXXXXXXXXXXXXo          ",
"         XooooooooooooooooooooooooooooO         ",
"        XooooooooooooooooooooooooooooooO        ",
"        Xoo++++++++++++++++++++++++++ooO        ",
"        Xoo+OOOOOOOOOOOOOOOOOOOOOOOO+ooO        ",
"        Xoo+O@O@O@#@@@@@@@@@@#@O@O@OXooO        ",
"        Xoo+OO@O@O@@@@@@@@@@@@O@O@OOXooO        ",
"        Xoo+O@O@O@@@@@XXXX$@@@@O@O@OXooO        ",
"        Xoo+OO@O@@@@@XXXXXX$@@@@O@OOXooO        ",
"        Xoo+O@O@O@@@@XX$$XX$@@@O@O@OXooO        ",
"        Xoo+OO@O@@@@@@$$@XX$@@@@O@OOXooO        ",
"        Xoo+O@O@@@@@@@@@@XX$@@@@@O@OXooO        ",
"        Xoo+OO@O@@@@@@@@XX$@@@@@O@OOXooO        ",
"        Xoo+O@O@@@@@@@@XX$@@@@@@@O@OXooO        ",
"        Xoo+OO@O@@@@@@@XX$@@@@@@O@OOXooO        ",
"        Xoo+O@O@O@@@@@@@$$@@@@@O@O@OXooO        ",
"        Xoo+OO@O@@@@@@@XX@@@@@@@O@OOXooO        ",
"        Xoo+O@O@O@@@@@@XX$@@@@@O@O@OXooO        ",
"        Xoo+OO@O@O@@@@@@$$@@@@O@O@OOXooO        ",
"        Xoo+O@O@O@#@@@@@@@@@@#@O@O@OXooO        ",
"        Xoo+OOOOOOOOOOOOOOOOOOOOOOOOXooO        ",
"        Xoo+XXXXXXXXXXXXXXXXXXXXXXXXXooO        ",
"        XooooooooooooooooooooooooooooooO        ",
"         %ooooooooooooooooooooooooooooO         ",
"          OOOOOOOOOOOOOOOOOOOOOOOOOOOO          ",
"              ####################O             ",
"               OO+++++++++++++++OO              ",
"                OO&&&&&&&&&&&&OOO               ",
"                OO&&&&&&&&&&&&OOO               ",
"      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%O     ",
"     XXXXX&XX&XX&XX&XX&XX&XX&XX&XXX&X&X&XXXO    ",
"    XXXXX&XX&XX&XX&XX&XX&XX&XX&XXXX&XX&X&XXXO   ",
"   XXXXX&XX&XXXXXXXXXXXXXXXXX&XX&XX&X&X&X&XXXO  ",
"  X...........................................O ",
" XX............................................O",
" X%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%O",
" X#############################################O",
"  OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                "};
