/* XPM */
/*********************************************************************
*  (c) Copyright 1997 Sun Microsystems, Inc.
**********************************************************************/
static char * sys_info_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 10 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray1	m white	c #dededededede",
"X	s iconColor2	m white	c white",
"o	s iconGray8	m black	c #212121212121",
"O	s iconGray2	m white	c #bdbdbdbdbdbd",
"+	s iconGray6	m black	c #636363636363",
"@	s iconColor5	m black	c blue",
"#	s iconColor1	m black	c black",
"$	s iconGray5	m black	c #737373737373",
"%	s iconGray4	m white	c #949494949494",
/* pixels */
"                                ",
"                                ",
"                                ",
"       .................        ",
"      XXXXXXXXXXXXXXXXXXXo      ",
"     XOOOOOOOOOOOOOOOOOOOOo     ",
"     XO++++++++++++++++++Oo     ",
"     XO+o@o@o@@@@@@o@o@o.Oo     ",
"     XO+@o@o@@XXXX#@o@o@.Oo     ",
"     XO+o@o@@.X#@XX#@o@o.Oo     ",
"     XO+@o@@@XX#@XX#@@o@.Oo     ",
"     XO+o@o@@###@X.#@o@o.Oo     ",
"     XO+@o@@@@@@XX#@@@o@.Oo     ",
"     XO+o@@@@@@.X#@@@o@o.Oo     ",
"     XO+@o@@@@@###@@@@o@.Oo     ",
"     XO+o@o@@@@XX#@@@o@o.Oo     ",
"     XO+@o@o@@@XX#@@o@o@.Oo     ",
"     XO+o@o@o@@###@o@o@o.Oo     ",
"     XO+.................Oo     ",
"     XOOOOOOOOOOOOOOOOOOOOo     ",
"      oooooooooooooooooooo      ",
"         oo++++++++++oo         ",
"         ooo$$$$$$$$ooo         ",
"    $$$$$$$$$$$$$$$$$$$$$$$$o   ",
"   XXX$X$X$X$X$X$X$X$XX$X$X$Xo  ",
"  XXX$X$X$X$X$X$X$X$X$XX$X$XXXo ",
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo",
" %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%o",
" ooooooooooooooooooooooooooooooo",
"                                ",
"                                ",
"                                "};
