/* XPM */
static char * SDtwebbr_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 12 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor5	m black	c blue",
"X	s iconGray2	m white	c #bdbdbdbdbdbd",
"o	s iconColor4	m white	c green",
"O	s iconGray3	m white	c #adadadadadad",
"+	s iconColor2	m white	c white",
"@	s iconGray5	m black	c #737373737373",
"#	s iconGray1	m white	c #dededededede",
"$	s iconGray8	m black	c #212121212121",
"%	s iconGray4	m white	c #949494949494",
"&	s iconGray6	m black	c #636363636363",
"*	s iconGray7	m black	c #424242424242",
/* pixels */
"             .....X             ",
"          ..oXoXoXoOoO  ++@     ",
"         .OoXoXoXoOoOoO   +@    ",
"        oOo#o#oXo..O.Ooo   +$   ",
"       oOo#o#oXoOoO.Oo.Oo  +$   ",
"      .Oo#o#o#oOoOoOoo.ooo++@   ",
"   ++..oXo#o#oOoOoOooOo.++$$    ",
"  +@$..Xo#o#oOoOoOoo++++$$o     ",
" +@$ ..oXoXoOoO+++++$$$$..o     ",
"  +++++++++++++$$$$$........    ",
"  @$$$$$$$$$$$$..O..........    ",
"    ......oo......oO........    ",
"    ......oo.....oOoO.......    ",
"    .....o.o.....o..o%......    ",
"    @+++++++++++++&.........    ",
"    +OOOOOOOOOOOOO$%.@o....$++  ",
"    +O**********%O$..o&.... @$+ ",
"    +O*@@@@@@@@@+O$@o&o...$   +$",
"    +O*@+%@@@@@@+O$o..*...    +$",
"    +O*@+@@@@@@@+O$&o*o..     +$",
"    +O*@@@@@@@@@+O$o*o..     +$@",
"    +O*@@@@@@@@@+O$*..$    ++$@ ",
"    +O*@@@@@@@@@+O$o..   ++$$@  ",
"    +O%++++++++++O$    ++$$@    ",
"    +OOOOOOOOOOOOO$   +$$@      ",
"    @$$$$$$$$$$$$$@  +$@        ",
"       $*&&&&&*$    +$@         ",
"   @@@@@@@@@@@@@@@@@$$          ",
"  ++@+@+@+@+@+@++@+@+$          ",
" ++@+@+@+@+@+@+@++@+++$         ",
"#######################$        ",
"$$$$$$$$$$$$$$$$$$$$$$$$        "};
