/* XPM */
static char * SDtwebbr_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 12 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor5	m black	c blue",
"X	s iconGray2	m white	c #bdbdbdbdbdbd",
"o	s iconColor4	m white	c green",
"O	s iconGray3	m white	c #adadadadadad",
"+	s iconColor2	m white	c white",
"@	s iconGray4	m white	c #949494949494",
"#	s iconGray5	m black	c #737373737373",
"$	s iconGray1	m white	c #dededededede",
"%	s iconGray8	m black	c #212121212121",
"&	s iconGray7	m black	c #424242424242",
"*	s iconGray6	m black	c #636363636363",
/* pixels */
"                     .....X                     ",
"                  oX....oXoX.O                  ",
"                .oXoXoXoXoXoO.Oo++++++++        ",
"              ..oXoXoXoXo.oOoOo@o@#####X+       ",
"             .ooXo$oXoXoX.OoOo.o@o@%%%%#+#      ",
"            oXoXo$o$oXoXoOoO.....@o#    +@%     ",
"           ..oXo$o$o$oXoOoOo@o@o.o#o#   +@%     ",
"           .oXo$o$o$oXoOoOo@o@o@.#o#o  +X%#     ",
"          ..Xo$o$o$oXoOoOo@o@o@o#.#o#++X%#      ",
"   ++++++...oXo$o$oXoOoOo@.@o..#o#o++X%%        ",
"  +X#####....oXo$oXoOoOo..@o@o.++++X&%&         ",
" +##%%%%%...oXoXoXoOoO.....++++X@&%%%.*         ",
" +#%%   ...o.oXoXoOoOo+++++X@@&%%%&....         ",
" ++++++++++++++++++++++X@@&%%%%.........        ",
"  @@@@@@@@@@@@@@@@@@@&%%%%%...o.........        ",
"   #%%%%%%%%%%%%%%%%%%....#o#o..........        ",
"        ........@o@.......o#o*..........        ",
"        ......o@.@o......o#o*o*o........        ",
"         .......@o@......#..............        ",
"         .........o......o.o*o.........         ",
"         ...........o.....o*.*.&o&.....         ",
"       ++++++++++++++++++++*.o&o......$+++      ",
"      +OOOOOOOOOOOOOOOOOOOO%..o.o.....##%#++    ",
"      +OOOOOOOOOOOOOOOOOOOO%&o&o&.....%%%%%@+   ",
"      +OO&&&&&&&&&&&&&&&@OO%o&o&o....     #%++  ",
"      +OO&##############+OO%&o&o%..%o       #+# ",
"      +OO&##@+##########+OO%o&o%o.%o         +@%",
"      +OO&##+###########+OO%&o%....          +@%",
"      +OO&##+###########+OO%o%....           +@%",
"      +OO&##+###########+OO%%oo.            ++%#",
"      +OO&##############+OO%..              +@% ",
"      +OO&##############+OO%              ++@%# ",
"      +OO&##############+OO%            ++@%%#  ",
"      +OO&##############+OO%          ++@%%#    ",
"      +OO@+++++++++++++++OO%        ++@%%#      ",
"      +OOOOOOOOOOOOOOOOOOOO%      ++@%%#        ",
"      +OOOOOOOOOOOOOOOOOOOO%     ++%%#          ",
"       %%%%%%%%%%%%%%%%%%%%     +@%#            ",
"         %%&&&&&&&&&&&&%%      +@%#             ",
"          %%**********%%      +@%#              ",
"    ##########################%##               ",
"   #@@@@@@@@@@@@@@@@@@@@@@@@@@@%#               ",
"  #+++#++#++#++#++#++#++++#+#+#+%               ",
" #+++#++#++#++#++#++#++#+++#+#+++%              ",
"#+++++++++++++++++++++++++++++++++%             ",
"+$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$%            ",
"+@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%            ",
" %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%             "};
