/* XPM */
/*********************************************************************
*  (c) Copyright 1997 Sun Microsystems, Inc.
*  All Rights Reserved
**********************************************************************/
static char * ws_choosr_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 9 1 0 0",
/* colors */
" 	s iconGray1	m white	c #dededededede",
".	s iconGray2	m white	c #bdbdbdbdbdbd",
"X	s iconGray6	m black	c #636363636363",
"o	s iconColor2	m white	c white",
"O	s iconGray3	m white	c #adadadadadad",
"+	s iconGray5	m black	c #737373737373",
"@	s iconColor5	m black	c blue",
"#	s iconGray8	m black	c #212121212121",
"$	s iconGray4	m white	c #949494949494",
/* pixels */
"                                                ",
" ..............................................X",
" ..............................................X",
" ..............................................X",
" ..............................................X",
" ooooooooooooooooooooooooooooooooooooooooooooooX",
"                                               X",
" OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOX",
" OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOX",
" OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOX",
" OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOX",
" OXXXXXXXXXXXXXXXXXXXXXOOXXXXXXXXXXXXXXXXXXXXXOX",
" OX                   .OOX                   .OX",
" OX +@+@+@+@+@+@+@+@+#.OOX +@+@+@+@+@+@+@+@+#.OX",
" OX @+@+@+@+@+@+@+@+@#.OOX @+@+@+@+@+@+@+@+@#.OX",
" OX +@+@+@+@+@+@+@+@+#.OOX +@+@+@+@+@+@+@+@+#.OX",
" OX @+. @ @.@+@+@+@+@#.OOX @+ . +@ @$@+@+@+@#.OX",
" OX +@ .  .  @+@+@+@+#.OOX +@+ + . .@+@+@+@+#.OX",
" OX @+@+@+@+@+@+@+@+@#.OOX @+@+@+@+@+@+@+@+@#.OX",
" OX +@+@+@+@+@+@+@+@+#.OOX +@+@+@+@+@+@+@+@+#.OX",
" OX @+@+@+@+@+@+@+@+@#.OOX @+@+@+@+@+@+@+@+@#.OX",
" OX ##################.OOX ##################.OX",
" OX....................OOX....................OX",
" OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOX",
" OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOX",
" OXXXXXXXXXXXXXXXXXXXXXOOXXXXXXXXXXXXXXXXXXXXXOX",
" OX                   .OOX                   .OX",
" OX +@+@+@+@+@+@+@+@+#.OOX +@+@+@+@+@+@+@+@+#.OX",
" OX @+@+@+@+@+@+@+@+@#.OOX @+@+@+@+@+@+@+@+@#.OX",
" OX +@+@+@+@+@+@+@+@+#.OOX +@+@+@+@+@+@+@+@+#.OX",
" OX @+ . + +@ @ @+@+@#.OOX @+  @ @+ +@+@+@+@#.OX",
" OX +@+ + .  @ .+@+@+#.OOX +@ @ @. . +@+@+@+#.OX",
" OX @+@+@+@+@+@+@+@+@#.OOX @+@+@+@+@+@+@+@+@#.OX",
" OX +@+@+@+@+@+@+@+@+#.OOX +@+@+@+@+@+@+@+@+#.OX",
" OX @+@+@+@+@+@+@+@+@#.OOX @+@+@+@+@+@+@+@+@#.OX",
" OX ##################.OOX ##################.OX",
" OX....................OOX....................OX",
" OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOX",
" OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOX",
" OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOX",
" OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOX",
" ##############################################X",
" ++++++++++++++++++++++++++++++++++++++++++++++X",
" ..............................................X",
" ..............................................X",
" ..............................................X",
" ..............................................X",
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"};
