/* XPM */
/* $XConsortium: Dtainfo.m.pm /main/3 1995/07/18 16:28:01 drk $ */
static char * Dtainfo [] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 11 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X	s iconColor1	m black	c black",
"o	s iconColor5	m black	c blue",
"O    s iconGray5     m black c #737373737373",
"+    s iconGray4     m white c #949494949494",
"@    s iconGray2     m white c #bdbdbdbdbdbd",
"#    s iconGray3     m white c #adadadadadad",
"$    s iconGray6     m black c #636363636363",
"%    s iconGray7     m black c #424242424242",
"&    s iconGray8     m black c #212121212121",
/* pixels */
" .............................X ",
" .oOoOoOoOoOoOoOoOoOoOoOoOoOoOX ",
" .OoOoOoOoOoOoOoOoOoOoOoOoOoOoX ",
"......oOoOoOoOoOoOoOoOoOoO.....X",
".+++++.oOoOoOoOoOoOoOoOoO.+++++X",
".++++++.oOoOoOoOoOoOoOoO.++++++X",
".+++++++................+++++++X",
".++++++++++++++++++++++++++++++X",
".++++++++++++......@+++++++++++X",
".++++++++++..o+o+o++@++++++++++X",
".++++++++..+o+o..+o+oO@++++++++X",
".+++++++..+o+o....+o+oO++++++++X",
".++++++..+o+o+....o+o+oO+++++++X",
".+++++@.+o+o+o....oo+o+oO++++++X",
".+++++.#o+o+o+o..oo+o+o+oO+++++X",
".++++@.o+o+o+o+o+o+o+o+o+$+++++X",
".++++.@+o+o+o+...+o+o+o+o+O++++X",
".++++.+o+o+o+.....+o+o+o+%O++++X",
".++++.++o+o+......o+o+o+o%O++++X",
".++++.+o+o+o+o....oo+o+o+%O++++X",
".++++.++o+o+o+....o+o+o+o%O++++X",
".++++.@o+o+o+o....oo+o+o+%O++++X",
".+++++@+o+o+o+....o+o+o+o%O++++X",
".+++++@o+o+o+o......+o+oO%+++++X",
".++++++@o+o+o+.....oo+o+&O+++++X",
".++++++@+o+o+o+...oo+o+o&++++++X",
".+++++++@+o+o+o+ooo+o+o&+++++++X",
".++++++++$+o+o+o+o+oOo&++++++++X",
".++++++++++%o+o+o+oOo%+++++++++X",
".++++++++++++&&&&&&%O++++++++++X",
".++++++++++++++++++++++++++++++X",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"};
