/* XPM */
/*********************************************************************
*  (c) Copyright 1999 Sun Microsystems, Inc.
**********************************************************************/
static char * Color_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 15 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray6	m black	c #636363636363",
"X	s iconColor2	m white	c white",
"o	s iconGray2	m white	c #bdbdbdbdbdbd",
"O	s iconGray3	m white	c #adadadadadad",
"+	s iconColor8	m black	c magenta",
"@	s iconColor6	m white	c yellow",
"#	s iconGray8	m black	c #212121212121",
"$	s iconColor3	m black	c red",
"%	s iconGray5	m black	c #737373737373",
"&	s iconGray1	m white	c #dededededede",
"*	s iconColor5	m black	c blue",
"=	s iconColor4	m white	c green",
"-	s iconGray4	m white	c #949494949494",
";	s iconColor1	m black	c black",
/* pixels */
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                      ..........                ",
"                  ....XXXXXXXXXX...             ",
"                ..XXXXoOOOOOOOOoXXX..           ",
"              ..XXoOOOOOOOOOOOOOOOoXX..         ",
"            ..XXoOOOOOOOOOOO+++++OOOoXX.        ",
"           .XXoOOO@O@OOOOOO+++++++OOOOOX.       ",
"          .XooOOO@O@O@OOOO++++++++.OOOOO.       ",
"         .XOOOO@@@@@@OOOOO++++++++.OOOOO.o      ",
"        .XOOOO@@@@@@O@OOOOO+++++..OOOOOO#o      ",
"       .XOOOO@@@@@@@@$OOOOOOO...OOOOOOO%#o      ",
"      .XoOOOOO@@@@@@$OOOOOOOOOOOOOOOOO##o       ",
"     .XoOOO$OOOO@@@$OOOOOOOOOOOOOOOO%##o        ",
"     .XOO$$O$OOOOOOOOOOOOOOOOOOOOOO##oo         ",
"    .XoOO$$$O$OOOOOOOOOO#####%OOOO#oo           ",
"    .XOO$$$$$$$$OOOOOOO##    &OOO#o    ....     ",
"    .XOO$$$$$$$$OOOOOOO#     &OOO#o  ..&&oo     ",
"    .XO$O$$$$$$.OOOOOOO#     &OOO&...o&oOOo     ",
"    .XOO$$$$$$.OOOOOOOO%&&&&&OOOOo&&&&OOO#o     ",
"    .XOOOO$$$.OOOO*O*O*OOOOOOOOOOOOOOOOO#o      ",
"    .XoOOO...OOOO*O*O*OOOOOOOOOOO===OOOO#o      ",
"     .XOOOOOOOOO********OOOOOOO*=*===OO#o       ",
"     .XoOOOOOOO*O********OOOOO*=*=*==OO#o       ",
"      .-%OOOOOOO*********OOOOO=*=*==OO#o        ",
"       Oo##OOOOOO*******;OOOOO***OOOO#oo        ",
"         oo##OOOOOO***;OOOOOOOOOOOOO#oo         ",
"          ooo###OOOOOOOOOOOOOOOOOO##oo          ",
"            oooo###OOOOOOOOOOOOO##ooo           ",
"               oooo#############ooo             ",
"                  ooooooooooooooo               ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                "};
