/* XPM */
/* $XConsortium: Dtdirup.m.pm /main/3 1995/07/18 16:36:00 drk $ */
static char * Dtdirup_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 10 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X	s iconColor5	m black	c blue",
"o    s iconGray8     m black c #212121212121",
"O    s iconGray5     m black c #737373737373",
"+	s iconColor1	m black	c black",
"@    s iconGray3     m white c #adadadadadad",
"#    s bottomShadowColor m black c #636363636363",
"$    s iconGray6     m black c #636363636363",
"%    s iconGray2     m white c #bdbdbdbdbdbd",
/* pixels */
"                                ",
"                                ",
"                                ",
"                                ",
"            .......             ",
"   .........XXXXXXo             ",
"  .XXXXXXXXXXXXXXXXo            ",
"...................O+           ",
".@@@@@@@@@@@@@@@@@OO+#          ",
".@@@@@@@@@@@@@@@@@OO+#          ",
".@@@@@@@@@@@@@@@@@OO+#          ",
".@@@@@@@@@@@@@@@@@OO+#          ",
".@@@@@@@@@@@@@@@@@OO+#          ",
".@@@@@@@@@@@@@@@@@OO+.......    ",
".@@@@@@@@@@@.........XXXXXXo$   ",
".@@@@@@@@@@.XXXXXXXXXXXXXXXXo$  ",
".@@@@@@@@...................O+  ",
".@@@@@@@@.%%%%%%%%%%%%%%%%%OO+# ",
".@@@@@@@@.%++++++%%%%%%%%%%OO+# ",
".OOOOOOOO.%+++++%%%%%%%%%%%OO+# ",
" ++++++++.%++++%%%%%%%%%%%%OO+# ",
"  #######.%+++++%%%%%%%%%%%OO+# ",
"         .%++%+++%%%%%%%%%%OO+# ",
"         .%+%%%+++%%%%%%%%%OO+# ",
"         .%%%%%%+++%%%%%%%%OO+# ",
"         .%%%%%%%++%%%%%%%%OO+# ",
"         .%%%%%%%%%%%%%%%%%OO+# ",
"         .%%%%%%%%%%%%%%%%%OO+# ",
"         .OOOOOOOOOOOOOOOOOOo+# ",
"          +++++++++++++++++++$  ",
"           ##################   ",
"                                "};
