/* XPM */
/* $XConsortium: Dtdirlk.l.pm /main/3 1995/07/18 16:35:12 drk $ */
static char * Dtdirlk_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 9 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X	s iconColor5	m black	c blue",
"o    s iconGray8     m black c #212121212121",
"O    s iconGray5     m black c #737373737373",
"+    s iconGray2     m white c #bdbdbdbdbdbd",
"@    s iconGray7     m black c #424242424242",
"#    s iconGray6     m black c #636363636363",
"$    s iconGray4     m white c #949494949494",
/* pixels */
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                           .................    ",
"                           .................    ",
"                          ...XXXXXXXXXXXXXooo   ",
"   ........................XXXXXXXXXXXXXXXXXooo ",
"   ........................XXXXXXXXXXXXXXXXXooo ",
"   ..OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo",
"............................................oOOo",
"..++++++++++++++++++++++++++++++++++++++++OOoOOo",
"..++++++++++++++++++++++++++++++++++++++++OOoOOo",
"..++++++++++++++++++++++++++++++++++++++++OOoOOo",
"..++++++++++++++++++++++++++++++++++++++++OOoOOo",
"..++++++++++++++++++++++++++++++++++++++++OOoOOo",
"..++++++++++++++++++++++++++++++++++++++++OOoOOo",
"..++++++++++++++++++++++++++++++++++++++++OOoOOo",
"..+++++++++++++++++++++++++++OO@@@@OO+++++OOoOOo",
"..++++++++++++++++++++++++++O#@@@@@@#O++++OOoOOo",
"..++++++++++++++++++++++++++O@@@@@@@@O++++OOoOOo",
"..++++++++++++++++++++++++++O@@$++$O@o++++OOoOOo",
"..++++++++++++++++++++++++++O@o++++O@o++++OOoOOo",
"..++++++++++++++++++++++++++O@o++++O@o++++OOoOOo",
"..++++++++++++++++++++++++++O@o++++O@o++++OOoOOo",
"..+++++++++++++++++++++++++OOOOOOOOOOOO+++OOoOOo",
"..+++++++++++++++++++++++++O@@@@@@@@@@o+++OOoOOo",
"..+++++++++++++++++++++++++O$$$$$$$$$@o+++OOoOOo",
"..+++++++++++++++++++++++++O@@@@@@@@@@o+++OOoOOo",
"..+++++++++++++++++++++++++O$$$$$$$$$@o+++OOoOOo",
"..+++++++++++++++++++++++++O@@@@@@@@@@o+++OOoOOo",
"..+++++++++++++++++++++++++O$$$$$$$$$@o+++OOoOOo",
"..+++++++++++++++++++++++++O@@@@@@@@@@o+++OOoOOo",
"..+++++++++++++++++++++++++Oooooooooooo+++OOoOOo",
"..++++++++++++++++++++++++++++++++++++++++OOoOOo",
"..++++++++++++++++++++++++++++++++++++++++OOoOOo",
"..++++++++++++++++++++++++++++++++++++++++OOoOOo",
"..OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOoooo",
"  ooooooooooooooooooooooooooooooooooooooooooooo "};
