/* XPM */
/* $XConsortium: DtMnew.l.pm /main/3 1995/07/18 17:09:04 drk $ */
static char * DtMnew_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 15 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X    s bottomShadowColor m black c #636363636363",
"o    s iconGray1     m white c #dededededede",
"O	s iconColor4	m white	c green",
"+    s iconGray3     m white c #adadadadadad",
"@    s iconGray4     m white c #949494949494",
"#	s iconColor3	m black	c red",
"$    s iconGray2     m white c #bdbdbdbdbdbd",
"%    s iconGray6     m black c #636363636363",
"&    s iconGray5     m black c #737373737373",
"*	s iconColor1	m black	c black",
"=    s topShadowColor m white c #bdbdbdbdbdbd",
"-    s iconGray7     m black c #424242424242",
";    s iconGray8     m black c #212121212121",
/* pixels */
"                              .X                ",
"                             .ooX               ",
"                            .oOooX              ",
"                           .o+@+ooX             ",
"                          .oO@O@OooX            ",
"                         .o#o+@+ooooX           ",
"                        .o#oo@OooooooX          ",
"                       .o#oo#oooooooooX         ",
"                      .oooo#oooooooooooX        ",
"                     .oooo#oooooooooooooX       ",
"                    .ooooooooooooooooooooX      ",
"       oooooooooooo.ooooooooooooooooooooooX     ",
"       o@@@@@@@@@@.ooooooooooooooooooooooooX    ",
"      ooooooooooo.ooooooooooooooooooooooooooX   ",
"      o+++++++++.oooooooooooooooooooooooooo$XX  ",
"     .ooooooooo.oooooooooooooooooooooooooo$+X   ",
"     .$$$$$$$$.oooooooooooooooooooooooooo$+X    ",
"     .$@$@@@$.oooooooooooooooo+ooooooooo$+%X    ",
"     .$$$$$$.oooooooooooooooo+&oooooooo$+%&X    ",
"     .$@@$$.oooooooooooooooo+&oo+ooooo$+%&@X    ",
"     .$$$$.oooooooooooooooo+&oo+&oooo$+%&$@X    ",
"     .$$$.ooooooooooooooooo&oo+&oooo$+%&$+@X    ",
"     .$$.oo&o&ooooooooooo+ooo+&oooo$+%&$+$@X    ",
"     .o.oo&ooooooooooooo+&ooo&oooo$+%&$+$+@X    ",
"    Xo@oo&o&ooooooooooo+&oooooooo$+%&$+$+$@X    ",
"   X@o+@oo&oooooooooooo&oo+ooooo$+%&$+$+$+%&X   ",
"  X.&o$+@oooooooooooooooo+&oooo$+%&$+$+$+$%@$X  ",
" X.&%o$$+@ooooooooooooooo&oooo$+%&$+$+$+$+%*@$X ",
"X.$@++@@@@@@$$ooooooooooooooo$+%&$+$+&&&&&&&&&$=",
"X.$oooooooooo+$ooooooooooooo$+%&$+$+oooooooooo-=",
"X.$$+@@@@@@@@%$$ooooooooooo$+%&$+$+$o@@@@@@&%%-=",
"X.$+++@@@@@@@%$$$ooooooooo$+%&$+$+$+o@@@@@&&&%-=",
"X.$$+@@@@@@@@%@$$oooooooo$+%&$+$+$++o@@@@@@&%%-=",
"X.$+++@@@@@@@%;@$$$$$$$$$+%&$+$+$+$+o@@@@@&&&%-=",
"X.$$+@@@@@@@@@%;@++++++$+%%%%%&&&&&o@@@@@@@&%%-=",
"X.$+++@@@@@@@@@%%%%%%%%%%%%%%%%%%%o@@@@@@@&&&%-=",
"X.$$+@@@@@@@@@@ooooooooooooooooooo@@@@@@@@@&%%-=",
"X.$+++@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@&&&%-=",
"X.$$+@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@&%%-=",
"X.$+++@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@&&&%-=",
"X$$$@&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&%%-=",
"X%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%=",
" ============================================== ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                "};
