/* XPM */
/* $XConsortium: DtMnone.m.pm /main/3 1995/07/18 16:22:50 drk $ */
static char * DtMnone_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 9 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X    s iconGray1     m white c #dededededede",
"o    s iconGray7     m black c #424242424242",
"O    s iconGray3     m white c #adadadadadad",
"+    s iconGray2     m white c #bdbdbdbdbdbd",
"@    s iconGray4     m white c #949494949494",
"#    s iconGray5     m black c #737373737373",
"$    s iconGray6     m black c #636363636363",
/* pixels */
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"   ...............X.X.X.X.o     ",
"   .OXXXXXXXXXXXXXXXXXXXXXo     ",
"  .OOOXXXXXXXXXXXXXXXXXXXX+o    ",
"  .OOOOXXXXXXXXXXXXXXXXXXX+o    ",
" .@OOOOXXXXXXXXXXXXXXXXXXX++o   ",
" .@OOOOOXXXXXXXXXXXXXXXXXX++o   ",
".@@@OOOOOXXXXXXXXXXXXXXXXX+++o  ",
".......#OOOOOOOOOOOOOOO......o  ",
"..++OO@@#+++++++++++++.@@@@$$o  ",
".++OO@@@#O++++++++++++.@@@@@$o  ",
"..++OO@@#OO+++++++++++.@@@@$$o  ",
".++OO@@@@.............@@@@@@$o  ",
"..++OO@@@@@@@@@@@@@@@@@@@@@$$o  ",
".++OO@@@@@@@@@@@@@@@@@@@@@@@$o  ",
"..++OO@@@@@@@@@@@@@@@@@@@@@$$o  ",
" $$$$$$$$$$$$$$$$$$$$$$$$$$$o   "};
