/* XPM */
/* $XConsortium: DtMrfc.m.pm /main/3 1995/07/18 16:23:25 drk $ */
static char * DtMrfc_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 10 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X	s iconColor5	m black	c blue",
"o    s iconGray8     m black c #212121212121",
"O    s iconGray5     m black c #737373737373",
"+    s iconGray2     m white c #bdbdbdbdbdbd",
"@    s iconGray3     m white c #adadadadadad",
"#    s iconGray1     m white c #dededededede",
"$    s iconGray6     m black c #636363636363",
"%	s iconColor4	m white	c green",
/* pixels */
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                  ...........   ",
"                 ..XXXXXXXXXoo  ",
"  ................XXXXXXXXXXXoo ",
"  .OOOOOOOOOOOOOOOOOOOOOOOOOOOOo",
".............................oOo",
".+++++++++++++++++++++++++++OoOo",
".+++++++++++++++++++++++++++OoOo",
".+++++++++++++++++++++++++++OoOo",
".+........................@+OoOo",
".+.###################+@+#$+OoOo",
".+.#OO#O##############+%%#$+OoOo",
".+.###################%%+#$+OoOo",
".+.#O#OO##############+@+#$+OoOo",
".+.#######################$+OoOo",
".+.#######################$+OoOo",
".+.#####OO#OO#O###########$+OoOo",
".+.#######################$+OoOo",
".+.#####OOO#O#OO#O########$+OoOo",
".+.#######################$+OoOo",
".+@$$$$$$$$$$$$$$$$$$$$$$$$+OoOo",
".+++++++++++++++++++++++++++OoOo",
".+++++++++++++++++++++++++++OoOo",
".+++++++++++++++++++++++++++OoOo",
".OOOOOOOOOOOOOOOOOOOOOOOOOOOOooo",
" oooooooooooooooooooooooooooooo "};
