/* XPM */
/*********************************************************************
*  (c) Copyright 1999 Sun Microsystems, Inc.
**********************************************************************/
static char * Screen_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 10 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray6	m black	c #636363636363",
"X	s iconColor2	m white	c white",
"o	s iconGray2	m white	c #bdbdbdbdbdbd",
"O	s iconGray1	m white	c #dededededede",
"+	s iconGray7	m black	c #424242424242",
"@	s iconColor5	m black	c blue",
"#	s iconGray8	m black	c #212121212121",
"$	s iconGray3	m white	c #adadadadadad",
"%	s iconGray4	m white	c #949494949494",
/* pixels */
"                                ",
"                                ",
"                                ",
"                                ",
"................................",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo",
".XOoOoOoOoOooOooOooooooooooooo+o",
".XoOoOoOoOooOooOoooooooooooooo+o",
".XOo++++++++++++++++++++++++oo+o",
".XoO+@#@#@#@#@#@#@#@#@#@#@#Xoo+o",
".XOo+$$$$$$$$$$$$$$$$$$$%%%Xoo+o",
".XoO+@@XX@XX@@@@@@@@@@@@@@@Xoo+o",
".XOo+$OXXXXXOOOOOOOOOOOOO$%Xoo+o",
".Xoo+@@X@$@X@@@@@@@@@@@@@@@Xoo+o",
".XoO+$OXXXXXXXXXXXXXXXXXO$%Xo$+o",
".XOo+@@XX@XX@@@@@@@@@@@@@@@X$o+o",
".Xoo+$OXXXXXXXXXXXXXXXXXO$%Xoo+o",
".XoO+@@XX@XX@@@@@@@@@@@@@@@Xo$+o",
".XOo+$OXXXXXXXXXXXXXXOO$%$%X$o+o",
".Xoo+@@@@@@@@@@@@@@@@@@@@@@Xoo+o",
".Xoo+$$OoOoOoOoOoOooooooo$%Xo$+o",
".Xoo+@+@+@+@+@+@+@+@+@+@+@+X$o+o",
".Xoo+$$$$o$o$o$o$o$o$o$o$$%Xo$+o",
".Xoo++@+@+@+@+@+@+@+@+@+@+@X$o+o",
".Xoo+XXXXXXXXXXXXXXXXXXXXXXXo$+o",
".Xoooooooooooooo$oo$oo$o$o$o$o+o",
".Xooooooooooooo$oo$oo$o$o$o$o$+o",
".X+++++++++++++++++++++++++++++o",
".ooooooooooooooooooooooooooooooo",
"                                ",
"                                ",
"                                "};
