/* XPM */
static char *draw.m[] = {
/* columns rows colors chars-per-pixel */
"32 32 7 1",
"  c black",
". c #808000",
"X c yellow",
"o c #808080",
"O c #C0C0C0",
"+ c gray100",
"@ c None",
/* pixels */
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.Xo@",
"XXXXXXXXXXXXOOOoXXXXXXXXXXXXXXX@",
"XXXXXXXXXXXO++++.XXXXXXXXXXXXXXO",
"X+XXXO++++++++..X+X+X+X+X+X+X+XX",
"+X+O+++...++..XOoooo+X+X+X+X+X+X",
"X+X.. .OXO..XOo++++O.+X+X+X+X+XX",
"+X+X+X+X+X+XO++++...+X+X+X+X+X+X",
"X+X+XXXXXXXO+++..OX+X+X+X+X+X+XX",
"XXXXXO++++++++.OXXXXXXXXXXXXXXXX",
"XXoO+++++++++.OXXXXXXXXXXXXXXXXX",
"Xo++O.....O+.OXXXXXXXXXXXXXXXXXX",
"o+...OXXXO..OXXXXXXXXXXXXXXXXXXO",
"X.oXXXXXXXX+++++XXXXXXXXXXXXXXX@",
"XXXXXXXXXX+++++++XXXXXXXXXXXXXX@",
"OXOXOXOXO+++++++++OXOXOXOXOXOXO@",
"XXXXXXXXX+++++++++XXXXXXXXXXXX@@",
"OXOXOXOXO+++O+++++OXOXOXOXOXOX@@",
"XXXXXXXXX++XXX++++XXXXXXXXXXXO@@",
"OXOXOXOXOXOXO++++XOXOXOXOXOXO@@@",
"XOXOXOXOXOXO+++++OXOXOXOXOXOX@@@",
"OXOXOXOXOXO+++++OXOXOXOXOXOXO@@@",
"XOXOXOXOXO+++++OXOXOXOXOXOXOX@@@",
".X.X.X.X.+++++.X.X.X.X.X.X.XO@@@",
"XOXOXOXOX++++OXOXOXOXO+OXOXOO@@@",
".X.X.X.X.+++++.X.X.X.+++.X.XO@@@",
"XOXOXOXOX+++++++XOXO+++++OXOO@@@",
".X.X.X.X.X+++++++++++++++X.XO@@@",
"XOXOXOXOXOX+++++++++++++XOXOX@@@",
".X.X.X.X.X.X+++++++++++X.X.X.@@@",
"X.X.X.X.X.X.X.+++++++.X.X.X.X@@@",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.O@@",
"X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.@@"
};
