/* XPM */
static char *math.l[] = {
/* columns rows colors chars-per-pixel */
"48 48 6 1",
"  c #008080",
". c cyan",
"X c #808080",
"o c #C0C0C0",
"O c gray100",
"+ c None",
/* pixels */
". . . . . . . . . . . XXXXXXX . . . . . . . .+++",
" . . . . . . . . . XXXoOOOOooX . . . . . . . o++",
". . . . . XXXXXXXXXoOOOOo     . . . . . . . . ++",
" . . . XXXOOOOOOooOOOO   . . . . . . . . . . .++",
".o.o.XXOOOOOOOOOOOOO  Xo.o.o.o.o.o.o.o.o.o.o.oo+",
"....XOOOO      oOOo X....ooXXXXXo..............+",
"... OOo  o.....   X...ooXoOOOOOoo .............+",
"...o  Xo............oooOOOOOo    ..............o",
"...................XoOOOOOo  o..................",
"..................XOOOOOo  o...................o",
".o.o.o.o.oooooooooOOOOOo o.o.o.o.o.o.o.o.o.o.o..",
".......oooOOOOOOOOOOOO  o......................o",
".o.o.oooOOOOOOOOOOOOO Xo.o.o.o.o.o.o.o.o.o.o.o..",
"...oooOOOOOOooOOOOOO X.........................o",
".oooOOOo         OOo o.o.o.o.o.o.o.o.o.o.o.o.o.o",
".oOOOo  o.......o   ...........................+",
"oOOo  oo.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.+",
" O  o.........................................o+",
". oo.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X++",
"..............................................++",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.o++",
"..............................................++",
".X.X.X.X.X.X.X.OOOOOOOOOOOOOOOOOOX.X.X.X.X.X.+++",
"...............OOOOOOOOOOOOOOOOOOo...........+++",
".X.X.X.X.X.X.X.OOOOOOOOOOOOOOOOOOo.X.X.X.X.Xo+++",
"...............oOOOOOOOOOOOOOOOOO...........++++",
".X.X.X.X.X.X.X.XOOOOOO.X.X.X.X.X.X.X.X.X.X.X++++",
"o.o.o.o.o.o.o.o.oOOOOOO.o.o.o.o.o.o.o.o.o.o.++++",
". . . . . . . . . OOOOOO. . . . . . . . . .o++++",
"o.o.o.o.o.o.o.o.o.oOOOOOO.o.o.o.o.o.o.o.o.o+++++",
". . . . . . . . . . OOOOOO. . . . . . . . .+++++",
"o.o.o.o.o.o.o.o.o.o.oOOOOOO.o.o.o.o.o.o.o.o+++++",
". . . . . . . . . . . OOOOOO. . . . . . . .+++++",
"o.o.o.o.o.o.o.o.o.o.o.OOOOOOo.o.o.o.o.o.o.o+++++",
". . . . . . . . . . .OOOOOO . . . . . . . .+++++",
" . . . . . . . . . .OOOOOO . . . . . . . . +++++",
". . . . . . . . . .OOOOOO . . . . . . . . .+++++",
" . . . . . . . . .OOOOOO . . . . . . . . . +++++",
". . . . . . . . .OOOOOO . . . . . . . . . .+++++",
" . . . . . . . .OOOOOO . . . . . . . . . . +++++",
". . . . . . . .oOOOOOOOOOOOOOOOOO . . . . .+++++",
" . . . . . . . OOOOOOOOOOOOOOOOOOo . . . . +++++",
". . . . . . . .OOOOOOOOOOOOOOOOOOo. . . . .+++++",
" . . . . . . . OOOOOOOOOOOOOOOOOO. . . . . o++++",
". . . . . . . . . . . . . . . . . . . . . . ++++",
" . . . . . . . . . . . . . . . . . . . . . .++++",
". . . . . . . . . . . . . . . . . . . . . . o+++",
" . . . . . . . . . . . . . . . . . . . . . . +++"
};
