/* XPM */
/*********************************************************************
*  Copyright (c) 2000 Sun Microsystems, Inc.
*  All Rights Reserved
**********************************************************************/
static char * wsctrl_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 7 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray6	m black	c #636363636363",
"X	s iconGray1	m white	c #dededededede",
"o	s iconGray8	m black	c #212121212121",
"O	s iconGray3	m white	c #adadadadadad",
"+	s iconColor5	m black	c blue",
"@	s iconColor2	m white	c white",
/* pixels */
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"................................................",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"oooooooooooooooooooooooooooooooooooooooooooooooo",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOXXXXXXXXXXXXXXXXXXXXXOOXXXXXXXXXXXXXXXXXXXXXOO",
"OOX+++++++++++++++++++oOOX+++++++++++++++++++oOO",
"OOX+++@+++++++++++++++oOOX+@@@+++++++++++++++oOO",
"OOX++@+@++++++++++++++oOOX++@++++++++++++++++oOO",
"OOX++@+@+@@@+@@+++++++oOOX++@+@+@+@+@@+++++++oOO",
"OOX+++@++@+@+@@+++++++oOOX++@++@+@++@@+++++++oOO",
"OOXooooooooooooooooooooOOXooooooooooooooooooooOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOXXXXXXXXXXXXXXXXXXXXXOOXXXXXXXXXXXXXXXXXXXXXOO",
"OOX+++++++++++++++++++oOOX+++++++++++++++++++oOO",
"OOX+@@@+++++++++++++++oOOX+@@++++++++++++++++oOO",
"OOX++@+@++++++++++++++oOOX+@+++++++++++++++++oOO",
"OOX++@+@@+@@+@@+@@++++oOOX+@@+@@+@++@@+++++++oOO",
"OOX++@+@@+@++@@+@@++++oOOX+@++@@+@@+@++++++++oOO",
"OOXooooooooooooooooooooOOXooooooooooooooooooooOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"................................................",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"oooooooooooooooooooooooooooooooooooooooooooooooo",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                "};
