#!/usr/bin/env python3

#
# This file is a part of the NsCDE - Not so Common Desktop Environment
# Author: Hegel3DReloaded
# Licence: GPLv3
#

import time
import sys

usleep = lambda x: time.sleep(x/1000000.0)

try:
   usleep(int(sys.argv[1]))
except:
    print("Usage: usleep <microseconds>")

