# Generated by go2rpm 1.9.0
%bcond_without check

# https://github.com/nwg-piotr/nwg-look
%global goipath         github.com/nwg-piotr/nwg-look
Version:                1.0.6

%gometa -f


%global common_description %{expand:
GTK3 settings editor adapted to work in the wlroots environment.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           nwg-look
Release:        1%{?dist}
Summary:        GTK3 settings editor adapted to work in the wlroots environment

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

BuildRequires: golang(github.com/gotk3/gotk3/gdk)
BuildRequires: golang(github.com/gotk3/gotk3/gtk)
BuildRequires: golang(github.com/sirupsen/logrus)

Recommends:     xcur2png

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%build
%gobuild -o %{gobuilddir}/bin/nwg-look %{goipath}

%install
%gopkginstall
install -m 0755 -vd                         %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/*     %{buildroot}%{_bindir}/
install -m 0755 -vd                         %{buildroot}%{_datadir}/pixmaps
install -m 0755 -vd                         %{buildroot}%{_datadir}/applications
install -m 0755 -vd                         %{buildroot}%{_datadir}/%{name}
install -m 0755 -vd                         %{buildroot}%{_datadir}/%{name}/langs
install -m 0644 -vp stuff/main.glade        %{buildroot}%{_datadir}/%{name}/
install -m 0644 -vp stuff/nwg-look.svg      %{buildroot}%{_datadir}/pixmaps/
install -m 0644 -vp stuff/nwg-look.desktop  %{buildroot}%{_datadir}/applications/
install -m 0644 -vp langs/*                 %{buildroot}%{_datadir}/%{name}/langs/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc README.md
%{_bindir}/*
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/pixmaps/%{name}.svg
%gopkgfiles

%changelog
* Tue Jul 01 2025 Jerzy Drożdż <jerzy.drozdz@jdsieci.pl> - 1.0.6-1
- Update to 1.0.6

* Tue May 06 2025 Jerzy Drożdż <jerzy.drozdz@jdsieci.pl> - 1.0.5-1
- Update to 1.0.5

* Tue Mar 18 2025 Jerzy Drożdż <jerzy.drozdz@jdsieci.pl> - 1.0.4-1
- Update to 1.0.4

* Sun Mar 09 2025 Jerzy Drożdż <jerzy.drozdz@jdsieci.pl> - 1.0.3-1
- Update to 1.0.3

* Tue Jan 21 2025 Jerzy Drożdż <jerzy.drozdz@jdsieci.pl> - 1.0.2-1
- Update to 1.0.2

* Sat Jan 18 2025 Jerzy Drożdż <jerzy.drozdz@jdsieci.pl> - 1.0.1-1
- Update to 1.0.1

* Fri Jan 17 2025 Jerzy Drożdż <jerzy.drozdz@jdsieci.pl> - 1.0.0-1
- Update to 1.0.0

* Mon Feb 12 2024 Jerzy Drożdż <jerzy.drozdz@jdsieci.pl> - 0.2.7-1
- Update to 0.2.7

* Mon Jan 29 2024 Jerzy Drożdż <jerzy.drozdz@jdsieci.pl> - 0.2.6-1
- Update to 0.2.6

* Thu Dec 14 2023 Jerzy Drożdż <jerzy.drozdz@jdsieci.pl> - 0.2.5-2
- Added distribution to to version

* Tue Nov 21 2023 Jerzy Drożdż <jerzy.drozdz@jdsieci.pl> - 0.2.5-1
- Update to 0.2.5

* Mon Jul 31 2023 Jerzy Drożdż <jerzy.drozdz@jdsieci.pl> - 0.2.4-2
- Golang packaging guidelines spec file

* Wed Jul 26 2023 Jerzy Drożdż <jerzy.drozdz@jdsieci.pl> - 0.2.4-1
- Update to 0.2.4

* Fri Jul 14 2023 Jerzy Drożdż <jerzy.drozdz@jdsieci.pl> - 0.2.3-1
- Update to 0.2.3

* Sun Jun 04 2023 Jerzy Drożdż <jerzy.drozdz@jdsieci.pl> - 0.2.2-1
- Update to 0.2.2
* Fri Dec 30 2022 Jerzy Drożdż <jerzy.drozdz@jdsieci.pl> - 0.1.4-3
- Changed build process

* Thu Dec 29 2022 Jerzy Drożdż <jerzy.drozdz@jdsieci.pl> - 0.1.4-2
- Added missing LICENSE

* Thu Dec 29 2022 Jerzy Drożdż <jerzy.drozdz@jdsieci.pl> - 0.1.4-1
- Initial build
