/* XPM */
/********************************************************/
/**   (c) Copyright Hewlett-Packard Company, 1992.     **/
/********************************************************/
static char * K2 [] = {
/* width height ncolors cpp [x_hot y_hot] */
"128 140 10 1 0 0",
/* colors */
" 	s iconGray5	m black	c #7d7d7d7d7d7d",
".	s iconGray7	m black	c #4b4b4b4b4b4b",
"X	s iconGray6	m black	c #646464646464",
"o	s background	m black	c #969696969696",
"O	s selectColor	m white	c #7d7d7d7d7d7d",
"+	s iconGray4	m white	c #969696969696",
"@	s bottomShadowColor	m black	c #646464646464",
"#	s topShadowColor	m white	c #c8c8c8c8c8c8",
"$	s iconGray3	m white	c #afafafafafaf",
"%	s iconGray2	m white	c #c8c8c8c8c8c8",
/* pixels */
" .XooOoo XooooO.OXooOooX  oX o ooooXooXXOXXO... XXoOO.oXooXXO.XXXXoooXXXo XOOXoo+oo.o  ooX+oXooOOooXOo Ooooooo+ooooo+oooO +ooo.+",
".oooooXXXXX ooO.OXoOoo  Xo XOXoXXooXoooOOooOO.@XXXoXOX ooXoOOO.XXOXXOo oXXoOOOoooo X    ooooooooOoXooXoOOooooo+oooooooo+Oo+oooo.",
"ooooo oXo O O+OXooXXOX  XXoXOX ooooX oooOXXoOX@XOOXXXooXoXOOXX O oOXoXXoXXXOOoo+ooooXooXooXooooooooXooXO.oooooo+ooooooooooXX+o+O",
"oooooooXoX   XXooOooO.o XOoXo.o +ooOooXXOOooXOOXOOXXOooooOXXO. OO XOo OXooOOooOOOoooOXoo Xo+.oXXXXXXooOXXOoo+oXo+oooooo+Xooo+ooo",
"ooooOoooX XOo.oXooo  XOooXXoXXoOOoOooXXoO.XX XXoXXOXOooXoXOOOo.XOOoXOOooXXXXoooOoOOoOXo  ooooXoXoXoOoooooO.+oooooooo+oooo ooo+XO",
"oooooXo XooXoXoooo O  oooo ooooOOXOOXoXOX.oOoOoooXXoXoXoXOOOOoXXOooOOOXXOoXOoOooooooOX  oXXoooooOooXoOXoo Oooooo+#oooooooo ooooo",
"o+O+oooXoXXXXXoooooo+ooooXX+Xoo OX XoOXoOOoOOoXXooXooXXoooXOOoOOOO XXOOooOOOOOooooOoXoo  oXoooooooOooOXooooOooooooooooooXXooOOoo",
"ooOo#+oOoooooXoooooooooXoXOX o oXX XoXXXoOOOOX oooOXooXoXooOOXOOXOOooOoXOOXOooooooOoo+o+  oooo. OOOooooo oooOoooX.ooooo+oooooOOo",
"oO OooXo+++o oOoooOOoooOXXXX XXXo O ooXXXO.XOOXooXooXooooX+XOOXoOOXXoOo OooXooooXXo oXoooXo oO.oo.XOooXo oooXOooooOoooO+oooo+ . ",
"oOoooo#+o+XXX OoooOOoXoXXXXO  o XXXOXXXOXoOOOOoXXoooXoXXXooOXOO .O.ooXOoXoXXXOXoo oooOOo ooo.@  XooOooX.+oo+ O oo+XooXoooooooXO+",
"ooO++oooXo OXoOooOo oX OOOXXXoo XoXXooX OXOXOoOXoooooX XoooOOXooXXXOXOooXOOooo oO oOoooooooX.oo ooOOOoooXooX ooooo o+ooooooooOXo",
"ooooo+Oooooo.Oo o +XOoX XOOXooooXo oXoXXXXoOOX.oXooo oXoooOoXOXXoOOoX.o oXooO+oooooOOooOXoXO. Xoo OO@X+oooo   ooooXoo+ooooooo. X",
"o+ooooooooXoOo XOO+ooXXOXXOOoo+o o oOXooXoXOOoOXXXXXooXooo. XXOXOOXoXXo XXOoo ooo+oooOooXoo. oOXoXX.OXo oo oo+ooooo+ooooooo+OO+o",
"oo#ooooo+oXOoo  ..+ooooO OOooooo Xo XXoXXXXOXXOX.XoXXXooooOXXOoXOX. XoO  oooO+#ooooOooXoXoOXoXooX X.oXX ooooooooo.oooooooOXooo+o",
"oooooooooooX XooOOX+oooXo.+oOoooooo  oXXXoOoooOOOXXXXoooooXXXOOo OOoXOoXXXooOo+ oooooXoXoO@X oOXo XoX OooOooooooooooo#ooooooO +o",
" oooooooooXXXo oOOO XoooXXXoXOoooooXoXXoXXOooXXOO XOXoXooXoooo.OXOOXooOXoooooOooooOoXoooO.OXXXXXXXXoX XOoooooooooooooooo ooXO+++",
"oooooX+oo+OX.XooXXXoooo+oXooOo+O   +OXoooXo XOo.OoXXooXoXXXX ooOXoOXXoOOooOoX+ooo o  ooooOXooOX XXXX OXOooO ooo+o+ooooOoOoooO +o",
"oooO+oooooO+ XOXX+oooooooXXOo+oX  XoXXoOOO XoooXO ooXXoXooXXooooOOooOXOXoOooX+oo oo oXoOOOXoooXX oX  Ooooo oooX +#ooooOXO+oOXo +",
"oooooooooooooO.X  oXoo oXoXXooooooO ooX O.XooXoXoXo ooOXooXXooooo.OXoOoOoXoo  o+o oooooO.oo ooooXXoXoXOXXO XoXO.X oooooO oo o+o+",
"ooooooooooXX oXX o  oooOX ooXo+X XOoX XXOOXoXXO.ooXOoOOooXO oo oX XO XX.XXooo oo oooooXO@O+ XoX o oXo OX X X o oOooOoo Xo oooo+ ",
"ooo+oooooooo.XX.   o oXOoooXOooo OO  oXoOO.+oXOX Ooo.oOXoOXXooooOXXoO OO. X+oooooXooooOXO.XX+oOX oXXX XX XX  ooo . oOX.+oXooo oo",
"ooooooooooXXXO.oXXoXXooOoooOOoo   .  X O XO.XXOOXoXXOoXXXXoXo+ooo@oXooXX.oO  ooooooo XoXOX@. XOo  XooXoXXo X X+o$XoooO.oo oo++++",
"o+ooo+oo#oXO O@ooo oooXOoXoXXXXoX  OXOX  XO@.+OXooOooOXXX.XoXoooXooXo oXOOoO ooX  ooooooXoo.  .o   oXoooooXo o X oX+ooOoo O+ ooo",
"ooOooo+o oXXOX.oXoXX oXX X X XXo XXoXXOOOX@XX  OXXXXXXOXOOoooX oOooooOXooXOXoooo +o ooooooOO@X      oX+oXooooX+ X+oooO. o   +o++",
"ooooO+++oo X.XooXooX  XX oo X  o Xo XXOOXO. X  XoXX XXooXO oXXooXo+XOX+XXOo.oooXooo ooooooXO.@.X  oo Xo+o oXOoo+ XooooOO oo o+o+",
"o+ oo ooooXoO.X OOX XoXOX    X XXooXOOXX  OXO  X   XXXooXX.oOooXoOooXo oXOooooooX+ooooooo O O..Oo  XooX o oXooX$+oXXOO @O o+o +o",
"ooooo o+ooXoO.  OOOXoooOOXX OoXXoX.X  O.  OOOoX. oOOo XooOXOOoooooooOoooOooXoooooooo+oo o   @XX@ oXX  oo+ooo+o+ooooooXXO@+o.+o++",
"ooo   #+ooXoXOoX O.O X XX.ooXX  XOXOXXX X  .X X  XXX XOO XXoo oooOoXo ooooOoooo  oXooo ooo X.XX.  oX  Xoo Xooo.  oooXOXX.X%OO$o$",
"ooOo   +ooOoXoOoXOXXOOOXOXo OoX  .OOXXXX#O oXO.  X o oXOX O XOo ooooooooOooooooooo o  X ooOXXXOX  X +XXoo +ooXX +oOXOXXO.oOX. + ",
"oooOo# oooooOOo XOOXXX.oXXXXXXoO  .X X .+OXoOOXo+  oO XOX .X XOooOXXOooOooXoo+ooo    Xo oX.  X.. X  X ooo.oo ooo oO.Xo XO XOXo+ ",
"oooooo+oOoooooXXXOOOOOOOooXX   OOOXOOX+XOOoOXXOooo XXO OooOXooooo@XoXooooXoooooooXXoXoXXXXXOXXXo  X  o o .o XXoOoXX.$XXOOooXo o ",
"oooooooooooooOoXoOOX.OOX X   XXX..XO.X OOX OXOoo+oXXo.XoX OO.o+o+.oXO  XooooooooooX XXo oXXOo+O X  X +o ooX# oXXOX O X.oX  ooX  ",
"+oooo+ooOoooOooXXOX XO.ooXo XX  X . X oO. O O.+ooXoooOO Xo XOO ooXXXXo XoXoo+ooooo oXXXoXO.Xo XooX oo  XooOooOO ++  O .+ oo   oO",
"+ooooooooooOOOo oOooOO XXO   XX   OX X X.OXX Xo  ooooOXOOoXOOOOo OoOOOoOXoooooXo  +Oo.OXXOo  oo   Xo OXoooOooo OX OOXO o++ +X   ",
"oooooO++oooOXO.ooOOOoOO XO.X@$O o O.X  .XO X. X XXX oXO XoXOXoOXXOo.ooXXoXXoooooo  +OOO.OOoX  X X  oX+ ooooOOXOXX XOX.O o  + XXX",
"ooo+ooOooooXooXoXOoo OooX XoOX.   @Xo OX.XXX  X  OXX OXo ooo  OXoX.XOXoOoXXoooooo+XX.XOX XXX  X#    +o oooXO.X+  X XO@o     OOX ",
"ooo#oooX+oOoOooOXXoooOX+oXOX...X@X. oXOX . .X     OXXXXoooooOoXOX. OX.oXooooooooo#XXO.XX OX    Xooooo+ ooXoXoo  X XXO. o   X X  ",
"oooooXXOooXoooOOOoo oOOooOOOO OX.XXo OOO.XX OX  XXOO XooXooooooooXOXoOXo oo+O+oo+.XO XOOXX  XXoXXoXoXo O+oX.XX XX  XX.X Xo. OOoo",
"oooooOoXooooOoooo XXO OO OOXXOOX. XXXOXX. X. X  oXXOooooo+ooooo  .OX oXooOOooooo ooXOOO X+  XXXXXX oo+ ooooXoOX XXXOX O  O      ",
"oooooOXoO o OOOooOOo   X  XXOOOOXO X.  O@X . XXoX XOXoooooooXooooOoo  .+XXo  o+  . O.XX     X o oXoXXooooXoXoXXX O X OO X  X  XX",
"ooooooXooXOoooOooXXooXO XX +X. X XOXX X X@X.@ O+ooXXXXooooooo oooO   .oooO oX oo  XOOO+X  +X XXoXOOoooooooXooo.O. XX   . o    OO",
"o+oooooooOOoXooooOooOOXX  oOXOX    O  OX X@.. . oXOXooXoooooXo+ OXo X.XOX  Xo oX  XX@@$    XXoXoXXoX .oXXoooO oOOX  X +OXX X+ XX",
"o+ooXooooXXOOoooOo oOX XXO XOXXXX O+o  OOXX... OooXXooooooooooo OO  .@o.oo Ooo    oOXX ++   XX.  ooXXoooooOooOXOXOX+   + X+oX OO",
"ooooXoooXOOo+oooo   X O  .O X OXX X+O.  O O  .Oo+ooXXoooX   oooooOXoo. X oOXXX.   XX@O.+X   X XX XooO+ooooOOoOOoXXOX  o Xo   .O.",
"o o+oOXOXOOooooooo    X   X  XXOXX  XX.X  OOX XO oXooo+oXoXoo+oooXoO.  OX .  @  oXoXXOX X+  XooOX.XooooooooXOoXOoX X o o+ o   X.",
"o  o++oXOooooooOooO    XX O O  .OX  XO.OX X OXO XoXoo oXooo+oXXXOooO@  XX OX .X O  X@O@  X  OXXOXOXXooooXXoXOOoOO    ooo +    X@",
"O   oooo+oooooooX    O  X XXO    XXX OXXO @OO. Oooooo+oXXXoooXXooOoo.XOXX  XOXXX.XXX @X   X XXXXOOOOoooooXXoOOOX    + oO +  XOX ",
".OoXXooooo+ooOXoooX    XXoXX XX  X Xo+XX X O O ooooo+ooOOo +XXoOOo XOOXXX X X X+.X@XXOX     oOoXXOXoX+oXOoOoOXoOo X o X   o OOO ",
" XX@Xo+ooooo+oO oo o+    o o  OX XXOXO XX  XoX.+o+XoooOOOoooOXO.OXoXXOX@   X oO XX.@.XX  XXoXOXXoOXXo+o. oOooXOoX O X+    XX@XO.",
"  @.OoO+OoooooXXX X+  O+ OXX OXXXXOX OXoO OO+XXoXoooooX.OoooXOOOXOXXooX.X     .o  X..O  XXXoXooO XoO.oO+ XXoXoX O   ooXXOO OXXOO",
"o OX.OXooooooXX o X   X  OOO XOXXOX.X X  OOXOXoooo+ooOO . +oXO.OX.X XooO.XXo +XoXXXOXX  XXXXXXXX OX OXOO ooooooXOX  o O OOXXo.X ",
" OX.O   ++OoooX+oo oo  O   XOXOX O. X  XXXXO o XoooXoO.oXoo .OOOXOOO+OoO@XoXX X OO. XOX XX XXOO XO.ooOOXoo ooo  OXXX  o .O X O o",
". OXX@+ oooXO oo+oXX+o OX X  OO OX   XXXXoXXXXo+ooooXXXOX+XOOOOX. O. oXXXOOOXX.. O XXOXXX  XXOOoXo.X ooXXo ooooOOX X   OXOX   X ",
"OO. O. O $+ooOo#oo O o X  o X.oOX  X OOXXXoXXX ooooo oXO oo.OOXXOOXXX oo o.XO.X. X  X.oXX    XXOO XXO  X.oooXoXXO XXX XOO OX oX ",
"O.@X  .  o++. oOoo Oo OX   oO.XOO  XXoXOOX oOOooooooXooo +OOOOX XXX.O ooXOOoX. .O.+X XXXO+o  XXXXXO XXoXOX+ OoXXO   O  OXOXX XX+",
" ..@O +   O+XX #OXO oX @X    O.XO   XXXoX ooO oooo ooo o+ooOOOO OXXXXOX XXOo X .XX OXXXOXX X  XXXoO+XXoo ooooXoO oXX XO X oXXXX ",
"oO .OX  o   ooXO OOX+ XXO X  OXXXO   OX X o Ooo o oXoooX+oo.OX. Oo X OXXo.X. oX X+XX. oXO   X XXOoOoXXXX  ooooXXoo XXXO X  O O+X",
" OX   .OX  ooOO oXO +XX OXOOXO X XO  oo oooXXXXoooooXXXo ooOO o OOXX Xoo.O .XOOXo+XX ooXXX      oOXooXooX+ooooXooX OXXOo oO +X  ",
" XO  X ..O oo X  oO++XX  X   XO. OX  XX oXXoXXXo oXoooXoX+OOoooXXOOoXOX XoOO.OX XoX oO  XXXX X X o.o OOXXX o o X O O.  O   X+ o ",
"O  X  OO   X o Oo. X+XXXX XX XO.X   X+oooXoXooX oooXooXoo+oooooOooO X XXOoXoOOX oo X XOoXXXO  OXXoXXo .o OXoX  X   OXXO  OO++O X",
"   XX+O OX o+O ooX O+O. ooo  XX  X  ooooooXXoOX ooooooooo+oooXXooOXO XO X OOX. oX  Xooo+   XX XOOooo+OXo oO OXoO   OXXOO O + OO.",
" XX o X XXo oO#o OXXoX  oooXo O  XO+oo o+OXXXXXooooo+oooooooooOooOOXXO.X XXOO. XXo XooX+  XXXXXo.XooXX oX+o OX o. X XX XX      X",
"  X      XX  +oXo oo+XXOXo+ooXOX  Ooo+ O OXoXXoooXXoo+X+o+OOoOoooOoOXOX. OooX oOoooooX. + o X X .XoXXo XOoOX  Oo XO XOO X   XX  ",
"   X  XOXOX ooooOooX+  Xo o+o .XX oo+oOXoXX  XX+oooo+o+o+OooOOoooOoOooOXXXOoOo oooooooooo+o   X .XoX X ooX XO o X o. O.  o+X  oo",
"OXX + XOX  o O Xoo O  XOoOX X Xooooo ooOOooO+ooooooooo+oo#ooOoOOOOOoo OOXoXo@ o oXooXo  oXXXo   X oOXXooXXXX OOXOX XO O +  o    ",
" OX X XXoX  X oooo  + XooXo Xoo   oXo OOo  Xoo+Xoo+ooooooo#oOoooOOOOoXOoOXoOOooooo X oooo  XO XXX  XOOX oooo  XOXX O. X ++ +  XX",
" OO   XX   XXX ooX  ++ ooXoo XXXoo ooOooXoXO o ooXoooooo+ooo+oooOXoooOOOXoo. ooOo+ooXooooo  XX X ooO. X OX oo OOOXO OX  +$+     ",
" OOoO     o   XO X ++o  XXXooooOooo  o oX XoXOOoooXooooooooooOoOOoXoXOoO.XXo ooX o  oooooo X XX  oXX oooo.o XOX X . OOXX ++o   o",
"  O  X X X oO Xo   o+  OoXo+oOXOOo ooo oO oooOOoooo+#oo+ooo++OOOOOOoo XX.X.oXoXo+oo. oo++o XOXoXOXXXOXooOXo  OoXX  Xo O   +++X  ",
" XX  ooX  O O.XoXXX$o XXooo+o+oOX o ooO+OoooooOoOOo++#+ooo#oOoOXo.OOXX .O. X ooX+oooX+ooooooo+ oooooooXOOo  OX X XO  XX+   X XoX",
"O OOX  o  X+XXO ooO#+XOXooo+Xoo+OXooo+Xoooo#o+Oooooooo+o###+oooo+oXOOOO..XOX o+oXX oXoooXo++oo+oooo o   o    oX   O .  +oXX  o  ",
"X OO   oOO o XXX oo+ XXOo+ +o+ XX ooo oooo###ooooo+oo#o+#oo+#ooo+oXO.O.O @O oXXooooooooO.OX+ +X ooX +    Xoo oX  X  XXX+ OX oOX ",
"  XXO  o XO o . Xooo+ooXX X +ooXo  o+oooooo+ooooooooo###ooOo+ooooooOO@.OOXOo X oooo XooX.o + +  oo      o X X   OX    X+   X  OX",
"   O. X     oXO.o++o+ ooXXXo o+oXo+   ooO++#oooooooooooo+oooo+oooooX.X XOOooOXO  oooooooX@ + ++o +X    .+Xo o   X X   o+XX XO X ",
"ooOX OOX+ Ooo XOoooX   oXOXO o  +oooooooo++#ooooooooooooOoOOoo+oXoO.XOXOXo oo.X.+XoO+oooo.X    $      XXXO o oo oX +o    X O.OX ",
" oXX XO X  XoXX.. oo+X XOXooo+oooooooooooooo#+ooo#oooo+oOooO.ooo   OOOX +X  X Xoo.XXX ooXO+o+  $ X+   O XXX++o X   $+ +X    X O ",
"O oXX   OXooo OOX.  $XX+oo oooooooXO oXo+Ooo#o+OoooooooOO.O ooOOOooO.ooo + .XXXXXXXOo +oX.    .+$+X X    X.X +o++  ++   +o+  X X",
"  O X+X XOXoXXXXO OX#++oo  ooooXOOooo oO+oooo+o#+ooooooOOOXXXXO. OOOXXoOOo   XXX. .OXXooO.+Xo$ X++X        OOOX+++ ++o+ooo  o XX",
"XXX +  X XXXXO.XOXXo+$ oo X++oXoXOOoOX oooooo+oo+oooooooOO.+oOO.XO@.Oo+oO oO XXOOOOXoXOX@+OoX+ Xoo  X +    XXXX.OOX$$$++ooX  OO ",
"XOXo oX X O OXOOOO +  +ooooooXOOOO.ooOoo ooooooooooooooOOO oXOO.XX.O+XoooX XXOoX..XXXO ..XO. $+o               X X.@XO  +oX   .+",
"X O + X X X XOOXOXX+$o+   oo+ XXOO.o ooo.#oOooooooooOXoOOOXXXoo.OXOOXoooooXoX. o .XX o .XXXO +o     oX+   X XX XX   XXo  +    OX",
"  O +X  XX oXoXXOXXo##o+ooo+X XOXXXoo+OOoooOOoooooooOooXXXXOX XXXOOX.+Xooo X ..  OOOOOX@.  OX$   XooO   . +X O X X XX   O  XX XX",
"XXXOXXXXXoo XX OOooO#+XXX #o  X  OXoo+oooooOXooooooOoooXOOOXO. XOXXoOO oXoXo oOX  XXOO.. OXOX$  X    O   @+  O. X  OX XXXX    X ",
"XXO.OO oo oooXX . XX+  oooo    XXooo  ooXooooooo+OoooOOO .XOXXXXXO.XO.O XOX  XOo XX OX.XOOX.o  o OXO X  XOX  O @     X   .XX  XX",
"OO X.O  Xoo oOX  OOo+oXoo+o+   OXO. ooooooooooooOooO oOOXoXoXOO X OOOOXXOOOO.  XoXoXO.OOOO.XO  X  XX. X    X XO.. +  +X  XXO   X",
"oXX.OXO ooo  XOoo Xooo.oo+o   X+  o  o+oo+oooo ooXXXoOOOXOX XXXX OoXXXOOO.XXXXOoXXXX. @XOOOO X   X  XO       O @ X+o      .XXXO ",
"XXO. XO O+ o. OO oo+oooO+o+   +oX Ooooo+ooooO ooooXoOO.OXO  oXoOXOXO XXOXX o  OXXoXOO OXO Oo  O+XXooO@   X     X@     O  O  X XX",
"X.. o.oXX Xoo.XXooXXooOOo+oXX o+ooooooooo#oX.oooooo OXX.OoOXXOXooXXXXX .X  oX X.  XXOOOO OX  XX OX oOX X +    XO.X .$ XoXX X X X",
"  . XXX  XoXo .Xoooo#OXoX#o  +XX+oooo+ooooooooo+oo o+oXOOO. XOX X oXoo  XXXXO  . XoXO@o OOo   O X    O Xo        @X X    X      ",
"OOO O.OoXX XX OOX #oo OXooXX+     Xoo+oo #o oOXoo+ooooXoXXOXO@   X ooXoXXOXXOXoXX oXX.+XOOO   X OOX OX    X       ..  X +   .  O",
"XOXXXX.+ XoXXoXX.o ooo o++OooOX    oo+oo++oooooooooooo XoXOO.@+ +    XoXXoXoOOXXo oO. XOooO     OX  X X  +  XXX O  . +     XX   ",
"    OXX o  XXXOXXoooo  o+#oo+ ++  + +XXoooXXooXooXoooooXXXXO.@X+     o XXoooOOOOXoXo.  . XXo  X  X+ XX XX+X+X  O  XXX O +    XOO",
"Xoo X. OX+XXoXX  o +OXoX###o+ooooXXo XooXooXXOXo oXoooooXOX.O.@     X XoooXXOOoooXOXooXOoo.O XXO  oo   XXX OX  XXXX XO. +oX+ . .",
"O  XX.  o XXOO o  o  X Xooo+ooooO.OXXO. OooXoXOXXoooXooooX.OX.@    X     ooooX.ooX.X+oo.ooOo+O OX o    OoOX XX X XXX XXO OOX    ",
"XoX  OOo    OOXo oX  XXXOOXoXXX XOO.OO XXoXXXXooooXXXX XoXOOX.@ +  X  + oo  oX.  Xooo +OOOXXOXOXOOXXXo   XX  XX XXX Xo+ X@ OOO  ",
" XX XX. oXX XXOoX+    + XOO XXoXOXOo .OXXXOoOXOXOXXooXXOXOXX.X.@+ oXOOX    XX OOXoXoOoooOOOXXXXXX@XXO    .   X XX XX    X@OX X O",
" X oXO X XXoXXoo+ +  #o OOO+OXoXOXOXXO.  XXXoXOXOOXoO X .XXX...@X ooX.X     XXXXooOXo oooXXXXXoO.XXO@  X XX XX  X XXO o .@X XX X",
"XX  XXoX  Xo Xo+o+ + oX XOO OXXo XX O.O OXXXXOXOooXooX o OOX  ..@  oO.oO     O XooOoooooX XXoO. @X X.X  XX     X X.X  +  .+  oXo",
"  X XX XX X Xo o  ++X XXOXXO OooooO .XOXoOXOXXX XooOoOoXOOXX...@  ooOXXX. oo   +XoOooOoXXX XXX. .@  XO  X  X XX O  XX   @. +  XX",
"XX X OXXX oooXo+  +oOXX  XXXOXOOooX OOX.X OXOOXOOX oXX XXXO   @.  o o.ooXo+oOOOOOooX XoXXXo X . OXOXO.  O  X O X  XOOo  .XX+   X",
"X XXOX.XXX ooXo++o oOXo  O XOOOOXOO  OXO   XOXOXOOOX@ oooOO..O.X   X oOXXooXXXXX.@oo. oOoXX XOXOOXXXXXO X.X XX OOO OX   XX+@  XX",
" XOX XOXOX  ooX o       O   OOoXO OOXX .XXooXXOOOOXO@ OXoO.. ++ o +ooooooXXOXO. ..ooo+XOXX oXXXOXXXX XXX XX XX oXXO  oO XX O   X",
"XXO XXO  O X   O     XX   XX OOO.  OXOOOOXXo+o OOOOO.XOoOOXo  oX o+Xo   X+oXO@. X oOooOOXX  XoXOXXXXX  XX X X . oX X o+O.O+XX   ",
"XXOo OXX X           XX    O XOXO O+OXOXXXoooo OX XXXX.OOXO   XXoXOX+ XoooO.XOX XoXOXo.O.X  XXXX. XX  X XXX XXOO+  + $+XX+  OX  ",
"O X  X    +X          X  +O oO Xoo oOOO.Oooo +ooXXXOO.X..XO XXXOXo O +X + Oo OXOoooOX+OoOXO O  O.XXXX XX.X XXXXO. OX +  + X+. X ",
"OOO  X X  oX XO o   X OX oX  XX .O  XoOOO+O.oo+ooOO OXO @ X Xo OX o XooX+OXooXOOoOoooXooo@ XXo  .@ X +   XX OO XX OXO+  O .+X X ",
"OXOXXX   o  O ooX o  X   Xo +OOXOXXoX XOX.XXoOOX+oXX OOX.XO ooo Xooo  X +XooooXooOOoXoooXXXXX.oXXOXX     ++   XXX XX.    .O+ X X",
"X X OX     XOX  X   OO  o.X+oXooOooXooX oOoOX.O.O+ooX XX..  +ooXoX oooO oXOX oooOOooooo o.XXoXX.X XOX     X+ XX  X .  X  .XX+X  ",
".   XXX+o  XoXOXX  XOooooO   O.oo Xo+oXX XXOOOOO..OoO OXXOX +o XOX X oo  oOXoXo.XoOOoX+.XXXX. X. XX XX      + .  X .@ $ OOX+    ",
"X   O    + .     X XoXXo O  Xoo+ooO+#+XXXXXXOOXOOO.X OXO.oXXooXOXoXOX o  oXooXXO.. o.oXXXXXOXOXXXXXXXXX      + X X ..OXX+ X++   ",
"  + OO +O +O X   XX.   oo XOO o#oXoXoXXoXX XXXOXO.XX OOO.oOoo+OOXXXOXXXooXooO  XXXOXOX.OOOX@.X.O XXXX   XXX      X   X.X+  +    ",
"X  X    oooo o+o OOX Xooo  OX X#ooXXoooO oOOXXOOOXo OXOXX ooooOOXOO X Xo  oXXo O O X  XOXOXXOOX.XXX XX X X O    +    X X  O +   ",
"X XXX. X oo oXoooo.oX +XOX OX  @@  OXOo OOXooOXoXX XXooO@ X+X  X XXO   X  X OX.XOXoXX   .OXXXO.OX XXXX  XXXXX+++ +  O.XX   XX   ",
" O OXO   ooo +o#oo oo OX  XX    X.  XOO  ..oOXOXoOOXoooOOoooo Xo XXX     oo OXoXXXoo  X OXXOXO@XXX@OXXX XXX  +   +        X    o",
" XO.Xo   +oooooo OXo  XX  X X  XXOXO+ OOXOOXOoOO oX.oo OoooO XXOXXXX   oo XXOo oXoXX    OXoOXO@@  XXXXX XXO       X+    X  X ++ ",
"XoOOOOX+ o Xo++oO  o O    X  o  XOXXXO.OO.XOOoXO o OOooOXoXOXXo O  XX  XXXXoOooooooo   X .X.XXX... XXXXXXXOXX    X + ++ XX + +  ",
".X  XOO X oXXoooXo     XXoX X   XXX   X.. OO.X OOoooOOOO. XoOooXXO X.O  ooooOXoXo oX o O OOX.XX.@OXXXo.O OO    X XX++    X + o+ ",
".OXOXo   Xo Ooo OX o  XOX         OoX+O.XooOO  OOOoooXOOOooXOOooXOoOO.o+oXoOOOo oo  o    X@O OOXX@XXOXXXOX@ X  X+   +  ++   o + ",
"X oOOX XoOX+  oO oooX   X  XO oX  OX  .O@OOXXoOXXXXoXOOOO  ooooXoOO XOOX OOooX.ooX.ooXX XO.XX@XX@@X OXXXXXXOXX  X     o     o $ ",
"OO  .X ooXXo+X OXooO X X  X O     X   .X.OXXO XOOXOOOoOOOO XOX O X.OoOO.O OX oXOoX XX XX XX.@XXXXOX X X. OXOXO +  + +oo+  .  o  ",
"OOXOXXX  OXXooOXX oO X X  XXo          O X.OX XOOOOO.XOO OOXO oX  OXXXOOOOOOOXoOoo oX  X X...XXX.@@XX XXX.XXOX.      +oo+ooOX X ",
"XO.X XX    OX+X  o   X    OX X  X    X.O O.O.OOXOOOOOO#.oO. OooXX OX OOOOOXXXXXoXo  XX o O. .XXOX @ . .X .X X.XX  +ooo+ +ooOOO. ",
"OO XOXOX+  XX O. ooXX     X  XO   X  .   X O .XX O oXX OXOOOX ooOX XXOOOOOXoX  ooX   Xo   O@ . ..X@ XX .. XX XOX+++ooXXoXooXXOo ",
"XOXXXOX +  Ooo+.Ooo O Xo    X XX oo O.   OXX OOO..X   oXOOOOOXXoXX  oO.XOXooO  ooO oXXX  X @. X. @XOXXX.X .XX XXX +oX+ooXX    oo",
"XX.OOX    oX O+ O +  OX X +  OX   X   OXOOXXOXX  ..O. XoOX OOXo XoOoXXOXooOoX XoooXo oOX X   O@ @XoOXX. .. XXXXXO++O.#$+XoXXoOo+",
"  OOXX XOOo  Xo+OXOXoX XOOX o Xo  .    X O.XXOXOXOX. XO o.XO OXXX  O OOXXooXoXXooooX  oX    .X@.X .XX .@  .X Xo+o+oXXooXooooo OO",
"O  . XXXOoo O o  XX XXXX X X OX o     X X XOOOXXXXX  OOO OO@XX OoX+ X OoOXXXXoX oooo  OXooooXX@ XO..XX...X.XX +++oOoOo+o X    . ",
". O   X X  oOXo  XX  oXooo XX oXoX XXX  OXX XOXOOOXX O.XO@OO OX X   X XXOoo+XXo oo+o    oo oO@. .X .. XX.O.X   +o ++oooooOXo Xo+",
"  OXXOOXO XOOOooOoooooXXXoo oX OOOOXOXXXXoooOO@X XXoXOXXXXOoX XXXOXoOOXoXoXooO  oXXooOOoO+oooooooO ooOooooOoooXooOXOooXo+o+ooooo",
"O XooXXXoXXOoOooooooo  ooXXX   O.XXXOOXXX o OX.OXXXoXXX oXO O X oXXXXOXoXoXooOXoXoooooOOoooooooooOXooOooooOooooX+oXOOOXo+ooooooo",
"OOOo oXX XOOXoooOO o ooooXXX    XOOXoOOoOoXX+oO.oooX.XoXX oX oXXXOoooOoooXXXXoooXoooOoOooooooooooOX.XooOoooooooooooOOooXo+o+o+oo",
"+o.Xo oX XooooooOXoXo##o oX  X oOXXooOoOXXoOO ooooXX.oXoXXOXXXooOoX OOo ooXooOO.oXooOOOOo+oooOooooOOoooOooooooooooOoooOXooooXo+o",
"oo.O XoX  ooooooooOXo+oooXooXXoXoOOX oOXoOOOXXXO o oXXoXXXXX oooOOoX.oOXoXoXoO.OOXoooOOoo+oooOoooO.OXooOoOooo+oo+oOOOXoO o ooooo",
"ooOX XXoooo+oooOoOoOooo+XXooo XXXOOOXooXXOO OX.o  XooXXXX oXo OOOOOOOoooo OooOOXoXo+oooo+ooXooooooOoOooo.oooooo++  +oX+ooooo+ooo",
"+#O@X  +X ooOOooOXooooooooooX X OXXXXO XOX.OXX.X X X XOXXXXXOOOO.oXOoOOo ooOOO.OoooooooooOooooo.oO.oXooooO+oooooo+oooo+OooXo++oo",
"o+OOXoXooXX OoooOOooooooo+ooXo XXXXXo ooXOXOXOOXXOoo.XoOoXooOO.OOooOOXoXOXXoX.XooooooooOoX+XXooOOoOoOoooOOoo+o+ooo+oooooooOo  +o",
"o+o+oOXXoXooOXXoXXoOoXoo oXoooXXX XX OX O.XXO.OXoOXOoo OXooOoO.XOOoOXoXXO.XOOOOOOoXoXoX.oOoo ooOOOoOooooOoooooooooo+oOXooooo+X+o",
"ooooOoO oOoXo.XO ooooOoOo Oo+Xo   oX OOXO. X.X.XoXoOOoXooooOXOOOOOoXOoOXOXOOOOOoOooX. oXoOooooOOoOOoXoooooooo#oooooooooooooooo o",
" oOOooOoooOo oOOO ooooO ooOOoo o   XooXo OOO... XXo.OoOo XXOOO.OXO oooO+ oooOooOO. o o XX@ ooOOoooOooooOoo#ooo+oo+ooOoooooo++ o ",
"  oOoOo  X o XO.O.oooo+oXOOoooo o oXO oX.ooOO@OoO oOOXoXooXOXOOOOOX OXXO oOOOooXoooX. oX o+ooooOXXXooooOooooo ooooooooo +oo+oo +"};
