/* XPM */
/* $XConsortium: WaterDrops.pm /main/3 1995/07/18 17:20:24 drk $ */
/*************************************************************************/
/**  (c) Copyright 1993, 1994 Hewlett-Packard Company			**/
/**  (c) Copyright 1993, 1994 International Business Machines Corp.	**/
/**  (c) Copyright 1993, 1994 Sun Microsystems, Inc.			**/
/**  (c) Copyright 1993, 1994 Unix System Labs, Inc., a subsidiary of	**/
/**      Novell, Inc.							**/
/*************************************************************************/
static char * waterdrops [] = {
/* width height ncolors cpp [x_hot y_hot] */
"158 163 8 1 0 0",
/* colors */
"     s iconGray4     m white c #949494949494",
".    s selectColor m white c #737373737373",
"X    s iconGray3     m white c #adadadadadad",
"o    s background    m black c #949494949494",
"O    s bottomShadowColor m black c #636363636363",
"+    s iconGray8     m black c #212121212121",
"@    s iconGray2     m white c #bdbdbdbdbdbd",
"#    s iconGray1     m white c #dededededede",
/* pixels */
"   .   X......o ..........o o .OO...oX.....O...oo..... ...o..o....o. .OOO.OOOOO..o...oo..o.O.oo.o ...o... .........O.o.OO+OOOOO.o.....ooo.OOOOOO+........o....",
" .....o.o.....o.. .........o  OOOOO.......oo.................o.o.o...O+O+.OOOOO.......o...ooo................o.....O.O+OOO+OOOO.. o.OOOOOO++OO+OO.........o...",
"  .......... .... .......   X.OO.OO..... ...o..o.o........ . ..o... ...OOO.OO...........oo.  .OO....o...... .o.o .....o....O....oo...OO+OOOOOOOO..........O...",
"... o....... ...o.o......o XXO.OOOOO. .oo.oo... ..o.....................O.oo ..............o ...Ooo............o.................o........OOOOOO..............",
" o  .......O.o.....o.O......OOOO.OOO.....o. .o..........ooo..............o................o...o.OO.....................oo.....o..o.O........o..o..............",
"  @ ...o.oo.O.o..o.. ..OOO+OOOOOOOOO.. .o........o..o... o ooo...........o.o..o......o....o.o.OOOO.o......o.. ....ooo..........o...o........o...o..... O......",
"o # .....oo.OOO .o...o.o.OOOOO.O.OO..ooo....o.... o ....OO.............................oo..o...........o........o..O..............oO......o....o..............",
"..#@Xo..o  o.OOo.o...o..oo..........o............ @@...o.O...ooo....o....oo...oo........ o...O..ooo.o...o.....o .O..O.O............o............oo.......oo...",
"..@ Xoooo   .OOO....OO..o.. .....o............ .o #@.o.oo.OO. o.......... .....o..o.ooo.. ..........o.o......o.oo.........o.o.......oo.....o......o.o..o......",
".. ....ooo o.OOOO..O+.o.o..o...o ..........o.o. o Xo...ooo.+O.o..o ......X ...OO.....o..  .....O..............  .......O+O...o.o............o..o..............",
".oo....oo   oOO.O..o..............o.o..o..... .oo......oo  OOO.o.oo.......o..o.+O..oo...X ..o. O+..o...o...o.o@XX....oo.OO..o..o............o...o....o o....oo",
". .....oo   o..OO...........o...............oo..oo.....o   O.O.o.........o..oo..O..oo.oo....oo OOO. .oo......o   ...ooooOO................o....o....o.  ...O..",
".o.....oo   .OOOOO.o.........o.....O....o..o.o.. ......   .OO.O...o.........o.OOO..........o.  OOOOo..o..O...........oooOO+O.....o..............oo....O.. oOO.",
".oo....oo   .OOOO... ... ...........O............o....o  o.OOOOO. .oo......O.OOOO..oo...o......OO.O.....o.oooo......   .OOOO......oooo.....o......o.O ... .O.o",
"..o....oo  .OOOOOO.ooo..o..o......OO....  o.o.O..oo..O..OOOOOOO.............OOOOO...........OOO+OO..o..O.O..........o .OOOO+O......oo.O...oo.O.o..O..o...OOOO.",
".o ...oooo ....OO......... ..O... ... ..  o........oo.O+.OO.O+O...o.....oo..oo.o. ....o.........o.o X....O...o.....oo.+OOOOO....oo..o.O....o.o..oo............",
"o.o.....oo.O.OOOO..... ......O.....o.....oo....o ..oo....OOO............o.o......@..o.......o.o..o.....o O.oo..o.O..OOOOOOOO..oo...ooO.O.......o..............",
"..........OOOOOO.o..........O..o...o.....o......o............o...o........o.........o.OO......o..........OO.......O.OO+OOOOO...o..o.o.............o...........",
"........OO.OO.O.......... oo.o .oo....o  o.....O... ........o.o..oo..o..o .....oo..  .OO.o.oo..o  .o......Oo.o...... ..o..oo.....o.....o...oo.......o...o.....",
".......OOOOOO...........oo.o.. ....o.o o....O....oo...o..o.......o.......o...........OO+.........o.........ooo.o.....o......OO................................",
"....o.o. o..oo..o.................o ............oo.oo...o..........oX ...o...o......OOOO....OO.................o..o..o...o...OO......O.....O.OOOO.............",
".......o.....o............o...oo.oo  @@o...o......o o..OO..o.+.o..ooooo..o.. ....o....oo o....O.o..o..oooo......o. ...oo.  ....O.o.o.O.oo.O....OO....o........",
".............oo...o......o..o...o.oo @o.o.o..o...o @ .....O.OO....o....OO.o. .o..o..... X .....+...........O.........O..oXX.....+................OOO....oo....",
"....o...o...............o .......o....o..OOO..... X@X...ooO....o....o...............o ooo....o O+O......o......o.oo...........ooOO.oo @ ..O.......OOOO........",
".......o...  ...............oo..o.  oo ....OO. oo......oo OOO.. .........oo........oooo..... o OOO.oo.oo............o..o.....oo OO+..o@ ..O........OOOO.......",
"..... oo.o..........o...o........o.o @o....O.OO.......o  XOO.o.o.......O....o..............o  .OOOOooo.......................  .+OOO.o  ........o...++OO...o..",
".o.. .........................o...ooX@ .....o.+O.o....o .OOOO......o .....O.........oo.....o..OOOOOo.......o....o. o..O. ....o.OOOO+ooX X.......o.o o+OO+O....",
".... ...oo..o o..o ............o..o @@@ ....o O+  o......OOOO...... @ ...o.OO.o..o........OOO+O++O...oo... ..oOO......O.o....+++OOOOo. ..........oo  OOOOO+...",
"o........o..X ... .........ooo o .ooo.......o +.O..o.OO+OO+O....o..o.o.oo  OOO.o.o.o.. .....o............oo.o .+..o..O.o..o.....O..o ...........ooo XOOOOO+O..",
".......o.o...o...... .o..... o..o..........o  +OO..o.....O.............oo XOOOo..o................... .......oOO+.o.....o...o.......o..........oooo XOOOOOO+O.",
"o........... . ...o......o....o...o.......oo XOOOO..  .o . .oo.o..o....o  .OOOO....o....o..........O......o...+OO..o......o......o.............ooo  XOOOOOOOOO",
".o......o...o......o .o...o..oo.o..o......    O.O.....O ....oooo..o....oo.O..OOooo....ooooo. ..oo.O.O..... o.o..o..oo...oooo.oo....o.........o     X@OOOOOOOOO",
".o.....oo.o....oo.o......oo..o........O...o  .O.OOO...oX...O.....o...OOO+OO+OO.........o...o... ....OOO.....oo..o.o....OO....o.......O........ ooo XX+OOOOOO+O",
"O..............o.o..X...Oo..o..o oo.o.O....OOOOOOOO.o.oo..ooOO.ooo..oooo......o...o..... ....oXX......+O  ooOo.o..o .....OO.... ......OOO.....oo  XX.OOOOO+O+O",
"O. . o.....o.......  ooo...o..... o.oo...OOOOOOOOO+.oo...oo OO.o.o .... o..oo..o..o ....o .o..@@ ....o.O.o  O.oo o  ......O..o.o....o.O......o   XXo.OOOOOOOOO",
"O.o.o.o.O.........o...ooOO......o.o.o o..O+OOOOOOO..oOO..oo.OOO.. .O.OO.o................o......o...o .OO..O+.....@ ......O+O..........OO.....o   OOOOOO+OO+OO",
"O....oX....O.o.... .....OO.oo..oo......o......OOoo..o..o.O.OO+O.o@ .o.+O...o.oo....o...............o  .OO+o....... o....oooOO+......o...OOO......O+O+OOOOO+++O",
"........oooOOoo... oo.OOOO.o.o .....oo.oo .o.oo ......o.o..OOO.oo  .o .O.o........o ..o..o..o...... oX.OOO.   ..ooo....oo  OOOO...o.o....OO....OOOOOOOOOOO+OOO",
".O.oo.O.o .OO......oo....oo...o...OO..ooo ...o oo.o....o.o.....o...o  OOO..........................  .OOOO.............oo  +OOO.o.........O+OOOOOOOOOOO+OOO++.",
".........+OOO.......oo o.oo. @o.....O.o.oo.o......o o..o....o...o..o oOOO..oo.o..  .........o.o.O..o..+OOOO............o  .OOO+.oo..o.oo.o..o..+OOOOOOOO+OO++O",
"....o....O..O.........o.....   ...ooOO..........o......o.oo....O....O+OOO.....oo. .... OO.......O.OO+OO+OO.o.o.o...O.....++OOO+O....o.............OOOOOOOOO...",
" .........o...ooo.o.ooo o.. o....oo OOO. oo. .ooo....o...o....O.oo ...O....oo.......o XOOO.oo......O+O.OO...o o......OOOOOOOOOOO....o.........................",
"..................o...  ...  ...ooo OOOOoo.........o.o....o.....oo.....oo.....o...O.o  OOO.oo..............o.o....o...O+OO+OO+O.....o................ ..o.....",
"....o..o........ ...o..oo.......o   .OOO.o... .o..ooo........o.o....... ...........OO++OOO.oo........o.........OOOO..o.....O.....o............................",
".......o....  o....... .o ......o  ....O...o.. ...   o..o..o oooX. o o..o o..ooo.......OO..o o..o.......ooooo.....OO.ooo...........O......O.O.o......o........",
"............ ......O.........oO...OOOOOOo.....o.......OO..o.....o. .oo..ooo...o.........o..................X.......+O....o...OO.........O.OOOOOO..............",
" .......... ...oo.o......o..o....O+OO+.....o.o.... ....O+O...o...o..o..o.oo......o.oo...oooo.....oooo.....X@X..... ++O.oooo.oo+..O.... ...OO..O+..............",
"...o...... ....o..........o  .  oo..... ...oo o.. o......OO..o  oo.ooo......oo.o..ooo  .o .ooo........o...X  ..ooo +OOOo....  O+....ooXo.O....oO+.............",
"...oo............ o..o....o.o.. .....o..ooO....o  .....o .OO..o.......O.O........o...oo....oo..o.o..O.....o.....oo OOOO.......OOO.... X ......o+O+O.........o.",
"...oo.o.. o.. OO.oo... .o...oo oo..oo...........@ .......O.OO....o  .....O............o.o.....o.@@............. ooXOOOOO...OO+OOO.... oo....oo .OOO......... .",
"..O.........  .OO.o...o.. o........oo... .....oo@o.........OOOO..o   ...o.OO.............o....oo....o.OO....O..oo oOOOOOO....................o .OOOOO......oX.",
".ooOO.... o...O..oo. ... o...oo..........  ooo  @X@o...oooo..OOO.oo....o  OOO.....  .O...o..o...o..o ..O.o ....o .OOOOO...................o o X.OOOO.O.....oo.",
"oo OO....  ...O..o....oo...............o..o.ooo  .o....ooooo.OO+Oo.....   .O+O...oo ....OO....o.o....OOO.........OOOOOOOo...o........O.O...o  XOOO+OO+........",
"oo.OOO.O...o.ooo......oo..O....oo.o...oo.....oo.o.......oo  .OOOO..O..o  .OOOO...o Xo....OO.......O.OOOO......OOOOOOOOOO.............O.....oo .OOOO+O+........",
"O.OO+O.....oo ..o.... Xo.......o o.oo....ooo oo........o o  oOOOOOo....o.....O...ooo..oo .O.o.....o......... o..o.......o........o..o.O...o  .OOOO+OOOO.....o.",
"..OOO.........oo...o.@Xo.....OO. .oo..... ...o.........oo   .OOOOOO.....OOOOOOo.oo....ooX.OOOoo..o......................o........oo....OO....++OOOOOO+O.......",
"......o... o...o.....   ...ooOOO..o..o..o...o.o.......o  o  OOOOO+OO..O+OOOOOOoo......oo.OOOO.........O..O..............................O+O+O+++OOOO+OO.......",
"o..o  o... ..oo...oooo.o..o  .OO...o.ooo  o...o......ooo   .OOO.OOOO.ooo.... oo ......o.OOOO....... .....O......................OOO.....o.....OOOOOO.O.o...o..",
" ..oo.....o......oo........o OOOO..oo....oo...o......oooo .OO.OOOO++............o....O+OOOOOO......X......+O.O.............oo....OOO..o.......................",
".. .o.... .o..oo...o.....oo  OOOO..o.......o..o...O....ooOOOOOOOO..O.o..o........oo...........o... @ ......O+............. @X....ooO+...........o........o...o",
"..... ..O+........   ....o  .OOOO..@......o ....o........OOOOOOOOO...oo. oo....o.....oo.oo. o.....   ....o OO.......o...o. XXo...  +OO...o.......o..o.........",
"..   @....O......oooo.....OOOOOOO.oo.....O......oo...OOOOOOOOOOOOOOO.....................o..............o. .OOO....O........O....  O+OO..o.........o..oo....o.",
"...o......OO...o..o.o.o...OOO++O......o  OO.o.o.o.. .o...OO+OOOOO...oo.oo. o.............o.............o  X.OO+................  .XO+OO..........o.....o...o..",
"...o... o .OO....................o.... .OOOOo.o.o.........oOO.... o...oo.....................o...o.....oo .OOOOO.... .O....O... o  +OO...OO... ..X..oO.o......",
".......oo.O+OO... o........ oooo.ooo...OOOO...o...o.....o.oo......o......o..... ...oo.o.....oo .oo....oo .OOOOOO..o.  .........oo.OOOOOOOO......o..o .O..o..O.",
".ooo.....OOOOO........o..o.. o..o..o..OOO.O. ......o....oo..OO..o o........o.....o......o....o .. o.O....OOOOOOO.oo....O.....O..O+OOOOOOO... .. ...  ..Oo@....",
"O.oo....OOOOO...........oo......oooooo...o.oo...ooo..o.....O........oo...o..............oooo..o......OOO+OOOOOOO..o...........OOOOOO+OOO......o..o...OOO. ..oO",
"OO............o....oo........... o...o.o o....o ....o...oooo o.oo.o..o...o.o.o.o o....oo.o............oo.O.OO.o........o.................o..........OO...O.o .",
"OO...oo.........oo..o.....o.....X ... o.oo...oo..o.o.o.......o.o..o.o...o.oo.oo.  ...O...............o.......o ...o......................o............o....oo.",
"oO...........o.  ..........o O+.....O.o..o.oo...o..o...o.........o............o.O.. oOO.............o...........OO..........................................OO",
".......o.. .. oX@o..o..o.o...OO....O.o ...oo.oo...o...o  o..o..o.oo....o......o ... .O.o........o..o.o .........o......o.....o.........o oo.o....o......o.....",
"..o..........o. oo..o.O..o..OOO.o....oo.....o o..OO..oooo........oo.o..........o...OOOO.......oo.....o..........o.....OO.OOO........................OOOO......",
"...o.......o..oo..oo .O+Oo.oo.o oo.oo o....o @ .....O.oo..o......o..o.......o.......oo........ o.o...o..... ...o.... o.....OO....................o.OOOOOOO.O..",
"o...o....oo......o.o .OOOo   .o....o.oo.o.. X@X...ooO...o.  o...o..oo...o....o.o....o.oo ... ...o..oo...oo. .o..o.. X ......OO......o...OOO.....  ...O...OO...",
"....o.. ...o...o..oooO.OO.o.....o......o oo......oo OOO...o....oo......o..........o....o.o....o..............oOOo..X@X......O+O.....o ..O..OO...@@..OO....+OO.",
" ooo..........o.....OO.OOo.........ooooooo......o  XOO.o....oo.........o.o o........o.oo.O+O....  o.o........OOO...o.o....oooOOO.o.. @o......+. @X.......o.++O",
".....O.oooo... ..o.O..OOOoo o.o..o.o....oo.o....o .OOOO..oOO .....o.......o....o............. ..  o......o..........O.....oo.+OOO...   ....o.++O o......oo.O+O",
"........o o ....o...o.....  o. ..o. .....oo o......OOOO. oOO ..... ooo...o.o...o.....oo..o.o..OO.......o .o.............o   .OOOO..oo.....o  +O+.......o o .Oo",
"........O .....o.....  .....oo..o. @....O.oo.o.OO+OO+O...OOO.o.OO......o..o ..o.OOOO..o....o..OO.o.oo...o.....o.o..O....oo .OO.OOO...O...oo  OOO.O.....oo  O o",
"........OO.ooo...... ..o..Oo..o.o.o...oo.OO..o.....O...o...oo..O...+.o.......o......OOO.oo...OO+.........o  .......O......O+O++OOOO......o  .+OO.O.....oo  . .",
".........OOo o.....o.....O.o.........   oOOoo.  .. o  oo... o......O+...o.. @ .......OO....oOOOO....OO.....ooo..o.....O.+OOOOOOOO........o .OOOOO..... o X.  .",
".........OO+....o......oo..oo........o ...O.....o.o..o..o. X ......O++O...o.@Xo.......+O..o ..oo o....O.o..o.o.....O.....OO+OO++O....OO.O+OOOOO+OO....oo oO@ .",
"....o..oo.OOO... ....o. ...............OOOOO....oo.o...o.oXoo....oooOO+O..oo o ....ooooo..o ... X .....+.....o....o.......O.......o.....OO+OO+++OO....  ...@o.",
"..o..oooooOO.O..X...o.o.......o...oo..OO.OO..oo......... o ....o.o  OOOO..........o o ....o.o ooo....o O+OOOO...OOo..............................OO....OO. @X@",
"....o.ooooOOO+........o............o....O..........o....o...O....oo OOOOO..........o  O..o oooo..... o OOO.oo.. .O..oo..OOOO..O...........O.......+OO.O++O  .o",
".o.ooooo  OOOOOO....................o. .oo.....oo..o..o........oo  ..OOOO........   X.O.o o........o  .OOOOooo+..Oo.. o....OOO..........................Oo o..",
".o.ooo    .OOOO.............. .....o..o...........ooo.o. o.....oo XOO.OO.oo......o XXO....o.oo.....o..OOOOOo......oo @o......OO..........................o o..",
".o.o o    OOOO.OOo...o................o..o.........o...........o.O.OOOOO+Ooo.O......OOo...o.......OOO+O++O...ooOO... X .......OO.............O............ ...",
".o.oo    oOOOOOO..o........o.........o...o.o....o. o.OO..o....OOOOO...OOO..o ..OOO+OOOOo.ooo.. .....o..........OOO...  ....   +OO............+............oo..",
".....o  o.OOOOOO....o.o......o..................o  ....OOOo.....OO..O.OO.... o.o.OOOOO o .................... OOO+ ...O...X o..OO+O.........OO.............o..",
"...oo   ..OO.OO.O.o...........o...o.........o.o. X@ .....O..o.o........o..o..o...o......o.oo....o..........O...O.O........ o...OOOO......o..................O.",
"...oooooOOO.OOOOO.....o....o o...o.....o.o.o..o.o @X...ooO...oo..o....o.......o..o....o.o.....ooooo. ..oo.O.O............. ...OOOOO+...O.o..................OO",
"......OOOOOOOOOO...........ooo.........o..OOO..........  +OOOo .....o.....o........oo...o..o...o...o... ....OOO...o...O...o  .OOOOOO..........OO...........O.O",
"OO..OOOOOOOOOOO.O...o...o.. o. ....  oo ....OO..o....   @OOO...o.O........o....o....o.o....o.... ....oXX......+O  oo..O...oo.OOOOOOO.......o.O.OO...o...o.....",
"o..OOO+OOOOOOOO.........oo........o.o @o....O.OO.....o  oOOOOO..OO...................... o......o .o..@@ ....o.O.o  .....OO+O+OOOOO+..O... o..O..OOO.........O",
".o.o o..OOO...o...o..O..........o..ooX@ .....o.+O.O.....+OOOOO..oo........o...........o.o.o..oO+.o......o...o .OO..Oo......+OO+OO+OO.....oX@X.....OOOO........",
"o......oo.o......o.o O.oo...o...o..o @@@ ....o O+...O.OOOOOOO. o..o............... o..oooo....O............o  .OO+o............oO..OO....o   ...ooo+OO.......o",
"..........oo.....o...OOo...........ooo.......o +OO....OOOOO+O..oo.........o......o..o.o.o..oo....o..o...... oX.OOO. ..........o ....O+..........oooO+.O.......",
"o.o.....o...o..o...OOO.o....................o  +OOO.o.... @...O..... ..... ...o...OO.......o..o............  .OOOO....O...........oo.+.........oo oOO.O+...o..",
"...o..oo.......oo.....o......oo....o.......oo XOOOO.oo..ooo.ooO.o...ooo...oo   o..O.OO.o.oo.o..O....o.o.O..o..+OOOO.......o..o.O.oo .+O..oO....o @.OOOOO.....o",
"..oo.........o....o............o....o......    O.OO+.o......ooOO..........o.o X......OOO.o.oo...OOO.....O.OO+OO+OO...............ooOOOO+OO.OO..o..+OOOOOo....o",
".o... ...o.....o......o...oXo...o......O...o  .O.OOO...o..o..O+O.o........o..X@ .......O...@ ......+.......O+O.OO................OOO+OOOO....OO+OO+O.OO.......",
"..... o..........o...........o.O...o.o.O....OOOOOOOO.o.......OO..........oo. X@o........OO. X.......OO............................OOO+OOO......OOOOOOOo.......",
"....  ooo.o.o ... ..o.. o .....O.o.o.oo...OOOOOOOOO+.ooo ..o.........o...o.oooX@o.....ooOOO.....oo oOOO......o....o..........o......o..o...o.......o......o.O.",
".O..o o...O.oo .......o .o....OO...o.o o..O+OOOOOOO..o....o......oo. o.o.....o  .......o.OOOO...o oo+O+O.........o ...OO................OO.........oo....oX...",
"oOO.  o....OO.o...o.....................o......OO....o.o............oo................ooo+OOO..o.o .+OOO....O..........O+O...............OOOOO..o.o..o......oo",
".OOo@@ o..o.....o Xo....o..ooooo o.oooo.oo....oo ...o .oo.o.o.......oo..........O..o.o   .OO.O.o   OOOO+O....o.......o .+O...o..........Xo..O.......o.....O.o ",
"OO.. o.o.ooo..O.oo...o.OO...o.....o...o ..OO..OO....oo..o.o.o....o..........oOOO.....oo X.OOOOO..OO+OO+OOO...o...O...  .O+.......OOO.O.....oO+.....o.........+",
".........oo  .OO....oo......ooo..o.o.oX ..OO...O....oo.o.. o.o.........o.......OO...oo  X.+OOOOO+OOOOOOOOO.o.....OO.o .O.OO.. Xo....O...O..OOO...............O",
"........o    .OO.....OO.Oo.o..... ..o@@@X.....o.+.... o...o.oo....o......o.oo......ooo  @.OOOOOO.OOOOOOO..o ....o.O...OOOOOO.   ...o.O....OOOO......oo.o......",
"...o.....o  .OOOO. o.....o...........o.......o.OOO.o..................o.......OOO...oo   OOOOOOO...OO................O+OO+O.......oo.+O.............o...o...o.",
"...oo.O.o o.OOOOO.o.............o.  .........o oOOO...ooo..........o......o....O....o.oX.+OOO+O++.....o.............O.......o....   o+O+O........OOOO.....o.o.",
"....oo.....OOOOOO... o.oo..o..ooo.o .......   XoOOOO.o.o o.. .o o.o......oo.o....O..oo  OOOOOOOO....o.......................o.O.o   .OOOO..o..o .....O........",
".....o..OOOOOOOOOO....o.......o....o.......oo X.OOOOO.........oo...oo..........OO....o..OOOOOOOOO.............................OO...O+OO++....Oo .O...+OO......",
"........o .oo.. o.....oo..o.o......o.oo...... .OOOOOO..o...o...oo.O.............O.....OOOOOOOOOOO..........o....................OOOOOOOOO.....o o...o.OO......",
".........oo....  ...o.O............o..oO...O.O+OO+OOO.......oo. ....OOO..........OOOOOOOOOOOOO++O..................O..........O.O....OO.o..oo.oO....ooO+OO....",
"....o.....o.oo.....o oOO.....o..........o..O.OOOOOOO.......oo.o@......O.....o..oo....OOOOOOOOOOO.OO............ ....OO....o.oo..............o.o....o .+OOO....",
".....o...o.. ......o oOOO....... ........o....O+O+O.........o. @......OOO..... o....o..O.OOO...OO.OO.......... @.....O...................o.oo..o...  OOOOOO...",
"o.....o .o........oo OOOO....................oo....o....o....o....... OO+.o..............O.. ..O....OOO.......  o...o.OO.........Oo....OO..OooO..O+O+OOOOOOO..",
"...o..o o.o..o....oo.OO.OO....o......................o......o.....oo  .OO............oo.... @ o......+OO....o.......  OO...o.o.....o.o..O.....oo...+ooOOOO.o..",
"o.o.o.+....O.O.o...O+OOOOO................. .... ..O....o.o...O....o XOOOOO...........o....oo.........+OO.........oo  OOOO....+O.o.....o..o.o........o.OO....o",
"..oo .O....O..Oo..o......o....oo......o...........oO+o.........O.o.  o+OOOOO....................o.Oo o+OOO.o......o  .OOO+O...O......o..o.+...OO....o.o.o..o..",
"....OOOO. ....OOO...oo... ....oo.oo..  ....... o...O.o..........O.oo.O+OOOOO...o................o..o o.OO.oo...O..oooOO.OO........oo..oo .O ......O...o.......",
"...O....o....ooO+Oo.....oX...O.......o...O.oo.o...........o.....OOO+OOOO+OOO...............O.O...ooo .OOOOO.......OO+OOOOOOO......oo.o..OOO.. X.........o....o",
".o....oooO..oo O+OO.....oo..ooOO...o ...O.OO.o....o.......o..........OOOOO.....o............O....oo .OO+OOO.O...o....O++OO...........o.O.....o ....OO.o....o..",
"......oo....o .OOO..o......oo OO...  ......OO.ooo................oo.................o........OO....O+OOOOOOO.......o..O............o......O.OO..............o.",
"... o.O.oo..oo+OO+.........oo.OOO..X@o....o.OOoo....ooo....o ...o......o.o....................OOOOOOOOOOOOOO...o.....ooo................. .o.+O...o.oo....o...",
"..o.....oo.OO++OOO.......o.O.OO+O.o  ....oooOOO......o..............o.o............o.O.OO...o.....+OOOOOOOO...o.o...o..................o  .o .O.o........o ..o",
"... ........o................OOO........o .XOOOO. ...O.o..o....o.....oooo.............OO..........O.O+OOOO.........o......................o  OOO..............",
"....o.oo...o.o.oo...o............o.....o oo@OOOO..o .O...........o..oo.ooo.... o..O...OO....o.o..o....o...o ...................O.......o..o oOOO..oo.o..  ....",
"OO...o. O......o .............o........oo   OOOOOO. .OO.......O..o.oooo...o..........O+O.....o............ X..O.....o...o .O..OOOO....O....O+OOO.....oo. .... ",
"OOO..o  OOO.o..... ......o.oo....o.....o  .OOOOOO...O...o............o..........OO...O.O..O.....oo...........oO..o...... X......OOO....oo ...O....oo.......o X",
"OOO.ooo..OOOoooo...O.......o..oo.o........OOOOOOO....o  o.o...O.....o..o.oo...............o........o.........oOO...o..ooX@ .......O....oo.....oo.....o...O.o  ",
"OOO...OO+OO..o.............o....o.oo..OO++OOOOOOO.o.o o....O....O.o...ooO.O............O.....................OOO.o..o.o    .......OOOO........ ...........OO++",
"OO... ...... ..o.. ... ............o..o.....OOOO.o ooXo.O+......OO.... oOO.O....................................o.o.....o........ .+O+.X. o o..o o..ooo.......",
".o...............o .o.oo.o.o..oo.....o..oo....o..o  @@o...O......OO.o.@ ....O...O..............o.................o.............ooX OOOO.. .oo..ooo...o........",
".oooo..o.........oo...O..o....o....o.....o...o...oo @ ....OO.....OOO........+OO.........o..........O...O.........oo..oo.O......oo .+OOO.O..o..o.oo......o.oo..",
".o .ooo..o...o...oo o........... ..X..oO.o......o oX@@@ ......ooo.O+O. ..oo OOOO...OOO.........O. .+oo...........o..o.........oo  .+OOOOO.ooo......oo.o..ooo  ",
"....oo..OOO.o.oo.o..o..o.O....o...o..o .O..o..O. ooXX @ ....ooooo.OOO+O.O  .O+O+..OOOOOO........O.++O.....OOO.......oo...O....o .OOOOOOO.....O.O........o...oo",
".o...........o........o oO...o... ...  ..Oo@.....oo o.......ooooo..OOO.....OOOO...O.....O..o.........o. o...O....O.......O...ooo+OOOOOOO+  .....O............o",
"..o........O...o......  .OO.ooo.o..o...OOO. ..oO.ooo........ooo   .OOOOO..O+OOOO X......OOO....O.......  ....OO...........OO...O+OOOOOO+O   ...o.OO...........",
"..o..o....o.OO....o...o.OOO...........OO...O.o .ooo........ooo   oOOOOOOO.OOOOO..o.....o.+OOO...o.....o.....o.OO...........OOO+OO+OO+OOO .....o  OOO.....  .O.",
".OO......o o..O..ooo.OOOOOO...oo........o....oo O. ......... X  X.OOOOOO+ ............oo OOOOO.. oo...o...oo  OO................OOOOOOO.......   .O+O...oo ...",
"..OO..... o .OO...o.....OOO.o.o...............Ooooo........o     OOOOOOOO.............o XOOOOO............oo oOOO...  .....o..O....O....O.O..o  .OOOO...o Xo..",
"o .O.o..o  ...OO............o...o....o....................oooo  OOOOOOOOO....O..O...ooo  +OOOOO........O..oo.OOO+O....Ooo..X.O..OO.....OO.....o.....O...ooo..o",
"oX.OOO.oo  .O.OO.o..oo..oo.oo..O.........o........o......oooo  ...O..OOOOo..oO.......   OOOOOOO............OOOOOOO........oo...o.OO...o........OOOOOOo.oo....o",
"o.OOOO....OOOOOOO...oo...o.oX.OOOOO..o ..........oo..OO.......OOOOOOOOOOO...OO..OO.....O++OOOOO.........oOOOOO..+O..o.oo..o....ooOO+....O.O..O+OOOOOOoo......o",
".OOOO.......OOO..oo.o...ooo@@...o.O........o .OO.....o.OOOOOOOOOOOOOOOOO.o...o.O..OOO++OOOOOOOOO.....o..o...o......o...o.ooO......o.o....o......... oo ......o",
"OOOOOOo..o ooo...o..o.. o..  ...o O..o...O. o....O..oO+O O.OOOOOOOOOOOO..oo...o.....O+OOOOOOOOO.............o........o...... .o..ooo........o..........o....O+",
"......o..o.. X......oo...o......  +OO......X......OO......OOO+OOOOO+OOO........o.....OO+OOOOOO.......................o..o.o.. ...   o..o..o oo.X........oo....",
".o..........o ....OO.....o.....o XO.O. ....  .....oO+........o.ooo...O.o..o.........oo.................oo...o..........oo....o.......OO..o.....oO ....o.....oo",
"....O..........o  OO...........o .+.OO..........oo .O+O......o...o.o.o.o....o...O.ooo.......O...........o..o..............o.o.... ....O+O...o...o..o..........",
"..........o....  o.O......oo.....OOOOOO.o......o  @.OOO..o..o.. ..o.o.................o.oX..............o ................oo o.. o......OO..o  oo.ooo.........",
".O........o.o....O.OO..........OOOOOOO...o.O...oo  .+OO......o.o..o....................ooo.o.O...o...........o.......o..oO....o  .....o .OO..o.......O.O......",
"...o...o..o....OOOOO..........o.O.OOO.......O..o .OOOOOOO..............OOO....O..o.o.oo...OO+O.........O.OO...........OO.......@ .......O.OO....o  .....O.....",
"..........o..oo..o. o........o..o.O+..o.o........OOO.OOO...........o .....O.........o............... o.....Oo.......oo.......oo@o.........OOOO..o   ...o.OO...",
"......... ..o..o..oo....o.............oo.......+OOOOOOO+....ooo...X .oX...O.........O...............XX....OOO..o....X ..  ooo  @X@o...oooo..OOO.oo....o  OOO..",
".o...............oo....oo.....o..........o.......O.OOOO....oo....oXXooo...OOO.......oo..........O..........OO......o.X...o.ooo  .o....ooooo.OO+Oo.....   .O+O.",
".......o.....o.oo......o.OOOO..o..............o..o.........oo. .. oo.......OO.oo.oo.....................oo.OO...............oo.o.......oo  .OOOO..O..o  .OOOO.",
"................. ....o......OOO.....oO...............................o.OO.OOOO.....O..............O.... .OOOO..........ooo oo........o o  oOOOOOo....o.....O.",
".................... @ .......OO..oo.oOO.oX...O.o.o ..... ...... .O...oo X.OOOO.....O.........o..........OOOO.......O... ...o..........oo  .O+OO.......OOOOOOo",
"o..o ..o.oo......ooo.@Xo.......+OO.oo..O..X ......oo  .o.o.o..o.o.....o  @OOOOOO.......................O+O.OO........O....oo.o.........oo oOO+OO.....O+OOOOOO.",
".O..o............o.oo o ....oooOOO..ooOOOO....oOO....o................   .OOOOOOO..................o...OOOO...........O..o...o.........o o.OOOOOO...ooo.... .."};
