.TH NSCDE_FVWMCLNT 1 "May 2026" "NsCDE 2.3" "User Commands"
.SH NAME
nscde_fvwmclnt \- send commands to the NsCDE FVWM instance
.SH SYNOPSIS
.B nscde_fvwmclnt
.RI [ command ...]
.SH DESCRIPTION
.B nscde_fvwmclnt
is a helper command used by NsCDE desktop launchers and tools to communicate
with the running FVWM-based NsCDE session.
.PP
It is primarily intended for internal use by NsCDE.
.SH SEE ALSO
.BR nscde (1),
.BR fvwm (1)
.SH AUTHOR
NsCDE was written by Hegel3DReloaded and contributors.
