.TH NSCDE 1 "May 2026" "NsCDE 2.3" "User Commands"
.SH NAME
nscde \- start the NsCDE desktop environment
.SH SYNOPSIS
.B nscde
.SH DESCRIPTION
.B nscde
starts the NsCDE desktop environment, a CDE-like desktop environment based
on FVWM.
.PP
It is normally launched by a display manager through the NsCDE X session
desktop entry.
.SH SEE ALSO
.BR fvwm (1),
.BR xsession (5)
.SH AUTHOR
NsCDE was written by Hegel3DReloaded and contributors.
