XOverrideFontCursor.so:
	gcc -I/usr/include/X11 -I/usr/local/include/X11 -I/usr/local/include -I/usr/X11R6/include -I/usr/X11R7/include -I/usr/X11R6/include/X11 -I/usr/X11R7/include/X11 -L/usr/X11R6/lib -L/usr/X11R7/lib -L/usr/local/lib -lX11 -fPIC -shared XOverrideFontCursor.c -o XOverrideFontCursor.so

clean:
	rm XOverrideFontCursor.so

